OneIsland_PokemonCenter_1F_Text_BillHeyThereCelio::
    .string "正辉：哟，这边这边！\n"
    .string "阿锦！$"

OneIsland_PokemonCenter_1F_Text_CelioCantBelieveYouCameOut::
    .string "阿锦：正辉！\n"
    .string "你还真的来这儿了。$"

OneIsland_PokemonCenter_1F_Text_BillHowsYourResearchComing::
    .string "正辉：嗯，当然了！\n"
    .string "你的研究进行的怎么样了？\p"
    .string "……噢，等一下。$"

OneIsland_PokemonCenter_1F_Text_ThisIsMyBuddyCelio::
    .string "{PLAYER}，这是我的好友阿锦。\n"
    .string "他是个专业的电脑狂！$"

OneIsland_PokemonCenter_1F_Text_PlayerIsRisingPokemonChamp::
    .string "阿锦，这是{PLAYER}，一个向着\n"
    .string "宝可梦联盟发起冲击的新星！$"

OneIsland_PokemonCenter_1F_Text_PlayerIsReigningPokemonChamp::
    .string "阿锦，这是{PLAYER}，\n"
    .string "本届的宝可梦冠军！$"

OneIsland_PokemonCenter_1F_Text_CelioThatsReallyImpressive::
    .string "阿锦：这真让人印象深刻。\p"
    .string "我不喜欢这样说，不过\n"
    .string "我对战斗没有兴趣。\p"
    .string "怎样都好，幸会幸会。$"

OneIsland_PokemonCenter_1F_Text_BillBringMeUpToSpeed::
    .string "正辉：所以，回到正题吧。\n"
    .string "你的机器运行得怎样了？$"

OneIsland_PokemonCenter_1F_Text_CelioPCsCantLinkWithYours::
    .string "阿锦：它们工作正常，不过\n"
    .string "我们这边比较偏僻。\p"
    .string "岛上的电脑跟你的电脑 \n"
    .string "连接不上。$"

OneIsland_PokemonCenter_1F_Text_BillLetMeHelpYou::
    .string "正辉：喔，这样？\n"
    .string "好吧，让我看看吧。\p"
    .string "……等下……\n"
    .string "我想我们能把它弄好。\l"
    .string "让我来帮忙，好吗？$"

OneIsland_PokemonCenter_1F_Text_CanYouDeliverThisMeteoritePlayer::
    .string "{PLAYER}，你可以在这里\n"
    .string "等我一会吗？\p"
    .string "……事实上我想请你\n"
    .string "帮我一个忙。\p"
    .string "这个岛旁边的另一个岛\n"
    .string "叫做二之岛。\p"
    .string "那里有个经营\n"
    .string "游戏城的男人。\p"
    .string "他有很多珍贵的石头\n"
    .string "和宝石。\p"
    .string "作为共同的研究狂，\n"
    .string "我们一直保持着联系，哈哈。\p"
    .string "所以，能请你帮我\n"
    .string "把这陨石交给他吗？$"

OneIsland_PokemonCenter_1F_Text_AcceptedMeteoriteFromBill::
    .string "{PLAYER}从正辉手上\n"
    .string "接过陨石。$"

OneIsland_PokemonCenter_1F_Text_CelioPleaseTakeThis::
    .string "阿锦：{PLAYER}，如果你要去\n"
    .string "二之岛，带上这个吧。$"

OneIsland_PokemonCenter_1F_Text_PassLetsYouTravelBetweenIslands::
    .string "这是这边的群岛的\n"
    .string "渡轮准乘证。\p"
    .string "拿着它你就可以去\n"
    .string "一之岛、二之岛和三之岛了。\p"
    .string "噢，把这也拿着吧。$"

OneIsland_PokemonCenter_1F_Text_ReceivedExtraPageForTownMap::
    .string "{PLAYER}城镇地图得到了\n"
    .string "新的一页。$"

OneIsland_PokemonCenter_1F_Text_ReceivedTownMap::
    .string "{PLAYER}得到了\n"
    .string "一张城镇地图！$"

OneIsland_PokemonCenter_1F_Text_BillCatchYouLater::
    .string "正辉：我等会会追上你的！\n"
    .string "代我向他问好！$"

OneIsland_PokemonCenter_1F_Text_HmmHowAboutLikeThis::
    .string "嗯……\p"
    .string "我们不如试试这样做吧……$"

OneIsland_PokemonCenter_1F_Text_GotPCWorkingStrollAWhileMore::
    .string "噢，这边，{PLAYER}！\p"
    .string "看到了吗？\n"
    .string "我们把电脑弄好了！\p"
    .string "我有点东西 \n"
    .string "想给阿锦看看。\p"
    .string "你可以先到外面\n"
    .string "等等我吗？$"

OneIsland_PokemonCenter_1F_Text_SorryForBeingPoorHost::
    .string "很抱歉占用了\n"
    .string "正辉这么多时间。\p"
    .string "同时我也为没能尽\n"
    .string "地主之谊而道歉。$"

OneIsland_PokemonCenter_1F_Text_UsualPCServicesUnavailable::
    .string "电脑服务\n"
    .string "现在不能使用……$"

OneIsland_PokemonCenter_1F_Text_BillOhHeyPlayer::
    .string "正辉：噢，这边！\n"
    .string "{PLAYER}！$"

OneIsland_PokemonCenter_1F_Text_BillWeGotItDone::
    .string "正辉：这儿有什么使你陶醉的东西吗？\n"
    .string "还是已经感觉腻了吗？\p"
    .string "这边的事都处理好了。\n"
    .string "这些电脑都能正常运作了！$"

OneIsland_PokemonCenter_1F_Text_CelioJobWentQuick::
    .string "阿锦：这事处理得真快。\p"
    .string "正辉真是个了不起的家伙……$"

OneIsland_PokemonCenter_1F_Text_BillYouveLearnedALot::
    .string "正辉：不，不！这没剩下\n"
    .string "什么我可以做的事了。\p"
    .string "阿锦，这边交给你了。\n"
    .string "相信你也学到了不少吧。$"

OneIsland_PokemonCenter_1F_Text_CelioOhReallyEhehe::
    .string "阿锦：噢，真的？\n"
    .string "嘿嘿……$"

OneIsland_PokemonCenter_1F_Text_BillWeShouldHeadBackToKanto::
    .string "正辉：好了，就这么简单。\n"
    .string "我已经完成了我的工作了。\l"
    .string "我们回关都去吧。\p"
    .string "阿锦，下次再见了。$"

OneIsland_PokemonCenter_1F_Text_CelioPromiseIllShowYouAroundSometime::
    .string "阿锦：{PLAYER}，今天没能\n"
    .string "让你享受一下，真的很抱歉。\p"
    .string "我保证，下次你来的时候\n"
    .string "我会带你在这些岛上逛逛。$"

OneIsland_PokemonCenter_1F_Text_CelioImModifyingMyNetworkMachine::
    .string "阿锦：你好！\n"
    .string "你看来跟平时一样的忙。\p"
    .string "我？\p"
    .string "嗯，我最近在调整\n"
    .string "我的网络服务器。\p"
    .string "我弄好了之后，\n"
    .string "我希望你是第一个试用的，\l"
    .string "{PLAYER}。$"

OneIsland_PokemonCenter_1F_Text_CelioCaughtMoreMonMaybeICanBeUseful::
    .string "阿锦：{PLAYER}，\n"
    .string "你最近过的怎样？\p"
    .string "噢，这样？\n"
    .string "你最近抓到很多宝可梦。\p"
    .string "知道不？\n"
    .string "也许我能帮上你的忙。$"

OneIsland_PokemonCenter_1F_Text_YoullBeTradingFromTrainersFarAway::
    .string "我正在调整 \n"
    .string "我的网络服务器。\p"
    .string "我正在把它设定成\n"
    .string "可以远距离的传送。\p"
    .string "我完成后，你可以\n"
    .string "跟远方的训练家 \l"
    .string "交换宝可梦。$"

OneIsland_PokemonCenter_1F_Text_NeedsSpecialGemstone::
    .string "不过，现在有点小问题。\p"
    .string "要让这运行，它要\n"
    .string "装上一个特别的宝石。\p"
    .string "听说有一个在一之岛上，\n"
    .string "不过我一直找不到。\p"
    .string "天晓得它在哪儿。$"

OneIsland_PokemonCenter_1F_Text_TryingToFindGem::
    .string "我甚至在读书的时候 \n"
    .string "也一直试着找到它。\p"
    .string "结果，我不能兼顾好\n"
    .string "研究和读书的事……\p"
    .string "如果我找正辉的话，我相信\n"
    .string "研究一定会很顺利。\p"
    .string "不过，这次我想靠\n"
    .string "自己来完成。$"

OneIsland_PokemonCenter_1F_Text_OhThats::
    .string "噢！\n"
    .string "这……这是……$"

OneIsland_PokemonCenter_1F_Text_HandedRubyToCelio::
    .string "{PLAYER}把红宝石\n"
    .string "交给了阿锦。$"

OneIsland_PokemonCenter_1F_Text_MayIAskOneMoreFavor::
    .string "谢谢你！\n"
    .string "{PLAYER}，你真的是太棒了。\p"
    .string "…… …… ……\p"
    .string "嗯……我可以请你\n"
    .string "帮我另一个忙吗？$"

OneIsland_PokemonCenter_1F_Text_PleaseINeedYourHelp::
    .string "这……这不是什么奇怪的事，\n"
    .string "请你一定要帮我，拜托了。$"

OneIsland_PokemonCenter_1F_Text_AnotherGemstoneInSeviiIslands::
    .string "当我研究宝石时，\n"
    .string "我发现了很重要的事。\p"
    .string "世上还存在着\n"
    .string "跟红宝石凑成一对的宝石。\p"
    .string "我认为宝石\n"
    .string "会在七岛上。\p"
    .string "{PLAYER}，拜托了，请你\n"
    .string "帮我去找出它们吧。\p"
    .string "{PLAYER}，我可以看看你的\n"
    .string "通行证跟城镇地图吗？$"

OneIsland_PokemonCenter_1F_Text_ReturnedTriPassForRainbowPass::
    .string "{PLAYER}归还了三岛通行证，\n"
    .string "并得到了彩虹通行证。$"

OneIsland_PokemonCenter_1F_Text_ObtainedExtraMapPage::
    .string "得到了城镇地图\n"
    .string "的补充页！$"

OneIsland_PokemonCenter_1F_Text_PassLetYouGetToAllIslands::
    .string "这是我的通行证。\p"
    .string "这能让你在\n"
    .string "七岛间穿梭。\p"
    .string "{PLAYER}，拜托了，我没了你\n"
    .string "我什么都做不到。$"

OneIsland_PokemonCenter_1F_Text_HandedSapphireToCelio::
    .string "{PLAYER}把蓝宝石\n"
    .string "交给阿锦。$"

OneIsland_PokemonCenter_1F_Text_ThankYouGiveMeTime::
    .string "阿锦：那么这就是能跟\n"
    .string "红宝石凑成一对的宝石……\p"
    .string "{PLAYER}，你为此付出了\n"
    .string "很多努力，对吧？\p"
    .string "你不用告诉我。我知道\n"
    .string "这一定不简单。\p"
    .string "非常的感谢你！\p"
    .string "现在是我回报你的时候了！\n"
    .string "请给我一点时间。$"

OneIsland_PokemonCenter_1F_Text_OkayThisIsGood::
    .string "行了，这就好了……$"

OneIsland_PokemonCenter_1F_Text_LinkedUpWithLanette::
    .string "我做到了！\n"
    .string "我跟真弓连接上了！$"

OneIsland_PokemonCenter_1F_Text_ManagedToLinkWithHoennThankYou::
    .string "{PLAYER}……\n"
    .string "{PLAYER}，我做到了！\p"
    .string "我成功跟丰缘\n"
    .string "的训练家联系上了！\p"
    .string "终于，这个服务器\n"
    .string "可以正常运作了！\p"
    .string "{PLAYER}，这都是因为有你！\p"
    .string "感谢你，我的梦想\n"
    .string "终于成真了……$"

OneIsland_PokemonCenter_1F_Text_WishYouBestOfLuck::
    .string "我……\n"
    .string "我才没有哭。\p"
    .string "我已经很满足了！\p"
    .string "{PLAYER}，你会继续\n"
    .string "寻找珍稀的宝可梦的，对吧？\p"
    .string "我祝你好运！$"

OneIsland_PokemonCenter_1F_Text_CelioHearingRumorsAboutYou::
    .string "阿锦：你好！\p"
    .string "{PLAYER}，最近我常常听到\n"
    .string "有关你的传闻。$"

OneIsland_PokemonCenter_1F_Text_BillsFirstMonWasAbra::
    .string "{PLAYER}，你最喜欢\n"
    .string "哪一种宝可梦？\p"
    .string "正辉是个宝可梦狂，\n"
    .string "所以他每一种都喜欢。\p"
    .string "不过，听说他的第一只\n"
    .string "宝可梦是凯西。$"

OneIsland_PokemonCenter_1F_Text_BillsHometownInGoldenrod::
    .string "说起来，{PLAYER}，你是从\n"
    .string "真新镇来的，对吧？\p"
    .string "我听说那里是一个\n"
    .string "很宁静跟和平的地方。\p"
    .string "正辉是从满金市过来的，\n"
    .string "他的家人还在那边住着。\p"
    .string "听说那边是个\n"
    .string "很热闹，很有活力的城市。\p"
    .string "我很想去见识一下。$"

OneIsland_PokemonCenter_1F_Text_BillCantStomachMilk::
    .string "{PLAYER}，你有没有什么\n"
    .string "忍受不了的事？\p"
    .string "听说，正辉的胃\n"
    .string "对牛奶过敏。$"

OneIsland_PokemonCenter_1F_Text_CameFromPalletDontKnowIt::
    .string "哦哦，陌生人啊！\n"
    .string "你好！你从哪儿来的？\p"
    .string "……真新镇？\n"
    .string "我听都没听过！$"

OneIsland_PokemonCenter_1F_Text_EnormousVolcanoOnIsland::
    .string "在这岛上，有个\n"
    .string "巨大的火山。\p"
    .string "最近都没爆发，\n"
    .string "去试试爬山怎么样？$"

OneIsland_PokemonCenter_1F_Text_WishICouldTradeWithBoyfriend::
    .string "我希望可以跟我那\n"
    .string "住很远的男朋友交换宝可梦……$"

OneIsland_PokemonCenter_1F_Text_TradedWithFarAwayBoyfriend::
    .string "我跟我住很远的男朋友\n"
    .string "交换到宝可梦了！\p"
    .string "每个人都说我们\n"
    .string "要感谢你跟阿锦。\p"
    .string "所以，谢谢你！$"

OneIsland_PokemonCenter_1F_Text_MachineUnderAdjustment::
    .string "网络服务器\n"
    .string "信号强度：0\p"
    .string "……宝可梦储存系统\n"
    .string "正在维护中……$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKanto::
    .string "网络服务器\n"
    .string "信号强度：1\p"
    .string "跟关都地区\n"
    .string "连接上。$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKantoAndHoenn::
    .string "网络服务器\n"
    .string "信号强度：2\p"
    .string "跟关都和丰缘地区\n"
    .string "连接上。$"

OneIsland_PokemonCenter_1F_Text_ObtainedTriPass::
    .string "得到了三岛通行证！$"

