SilphCo_4F_Text_CantYouSeeImHiding::
    .string "嘘！\n"
    .string "你看不见我在躲人吗？$"

SilphCo_4F_Text_TeamRocketIsGone::
    .string "什么……\n"
    .string "火箭队已经不在这里了？$"

SilphCo_4F_Text_Grunt1Intro::
    .string "火箭队已经控制了\n"
    .string "整个西尔佛公司！$"

SilphCo_4F_Text_Grunt1Defeat::
    .string "啊！$"

SilphCo_4F_Text_Grunt1PostBattle::
    .string "哇哈哈哈！\n"
    .string "我的老大一直都想占领这地方！$"

SilphCo_4F_Text_RodneyIntro::
    .string "我的宝可梦是我忠实的仆人。$"

SilphCo_4F_Text_RodneyDefeat::
    .string "可恶啊！\n"
    .string "你这虚弱的宝可梦！$"

SilphCo_4F_Text_RodneyPostBattle::
    .string "这些门都是用电子锁\n"
    .string "来锁定的。\p"
    .string "看来需要一张钥匙卡来打开\n"
    .string "这些门。$"

SilphCo_4F_Text_Grunt2Intro::
    .string "发现可疑人员！$"

SilphCo_4F_Text_Grunt2Defeat::
    .string "你是谁？$"

SilphCo_4F_Text_Grunt2PostBattle::
    .string "我最好去报告在11楼的老大！$"

SilphCo_4F_Text_FloorSign::
    .string "西尔佛公司总部\n"
    .string "4F$"

