PokemonMansion_1F_Text_TedIntro::
    .string "你是谁？\n"
    .string "这里不应该有任何人。$"

PokemonMansion_1F_Text_TedDefeat::
    .string "我输了。$"

PokemonMansion_1F_Text_TedPostBattle::
    .string "一把钥匙？我不知道\n"
    .string "你在说什么。$"

PokemonMansion_1F_Text_JohnsonIntro::
    .string "哇哇哇！你把我吓了一跳！\n"
    .string "我以为你是鬼呢。$"

PokemonMansion_1F_Text_JohnsonDefeat::
    .string "啊！\n"
    .string "我怎么也赢不了。$"

PokemonMansion_1F_Text_JohnsonPostBattle::
    .string "我一个人到这里来探索，\n"
    .string "但我觉得很害怕。\p"
    .string "我还是尽快离开这里吧。$"

