FuchsiaCity_WardensHouse_Text_HifFuffHefifoo::
    .string "园长：哇伊嘿咻乎嘿\p"
    .string "乎哈希嘻嘿哇！\n"
    .string "哈希嘻呼！$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo::
    .string "啊活货嚯惑伙！\n"
    .string "诶夫咦嘿嗨活！$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo::
    .string "哈？\n"
    .string "他呵哈呵呵呵呵呵哈哈哈！$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden::
    .string "{PLAYER}将金假牙\n"
    .string "交给了园长。$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth::
    .string "园长急忙把假牙\n"
    .string "装进了嘴里！$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething::
    .string "园长：谢谢你，小朋友！\n"
    .string "你真是我的救命恩人！\p"
    .string "所有人都听不懂我说的话，\n"
    .string "一个都没有！\p"
    .string "我甚至都没脸去\n"
    .string "见我的那些员工了。\p"
    .string "让我给你点东西\n"
    .string "做为感谢吧。$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething::
    .string "园长：谢谢你，小姑娘！\n"
    .string "你真是我的救命恩人！\p"
    .string "没有任何人听得懂我说的话，\n"
    .string "我是说，一个也没有！\p"
    .string "我甚至都没脸去\n"
    .string "见我的那些员工了。\p"
    .string "让我给你点东西\n"
    .string "做为感谢吧。$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden::
    .string "{PLAYER}从园长那里\n"
    .string "得到了秘传学习器04。$"

FuchsiaCity_WardensHouse_Text_ExplainStrength::
    .string "园长：通过秘传学习器04可以\n"
    .string "学会怪力。\p"
    .string "能让你在战斗以外的时候\n"
    .string "用宝可梦推动大石头。\p"
    .string "喔，对了你找到狩猎地带\n"
    .string "里的神秘小屋了吗？$"

@ Unused
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff::
    .string "なんや　にもつ\n"
    .string "いっぱいやんけ！$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
    .string "宝可梦的照片和化石\n"
    .string "被陈列着。$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
    .string "陈列着古代宝可梦\n"
    .string "货物。$"

