SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
    .string "……慢着！什么都别说！\p"
    .string "我有预感你需要这个！$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
    .string "{PLAYER}从超能先生那里\n"
    .string "得到招式学习器29。$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
    .string "你已经知道了，不是吗？\n"
    .string "招式学习器29是精神强念。\p"
    .string "这是一种可以降低目标\n"
    .string "特殊能力值的招式。$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
    .string "你想要把这个放哪儿？\n"
    .string "你的包包已经没有空间了。$"

