RockTunnel_B1F_Text_SofiaIntro::
    .string "你知道怎样避免\n"
    .string "在深山里迷路么？\p"
    .string "你可以折断树枝\n"
    .string "作为路标。$"

RockTunnel_B1F_Text_SofiaDefeat::
    .string "哦哦哦！\n"
    .string "我尽力了！$"

RockTunnel_B1F_Text_SofiaPostBattle::
    .string "我想回家！$"

RockTunnel_B1F_Text_DudleyIntro::
    .string "哈哈哈！\n"
    .string "你能战胜我的力量吗！$"

RockTunnel_B1F_Text_DudleyDefeat::
    .string "哎呀！\n"
    .string "我在力量上输了么！$"

RockTunnel_B1F_Text_DudleyPostBattle::
    .string "我只追求力量，\n"
    .string "因为我懒得思考！$"

RockTunnel_B1F_Text_CooperIntro::
    .string "你在补全宝可梦图鉴吗？\n"
    .string "可恶！我也想补全宝可梦图鉴！$"

RockTunnel_B1F_Text_CooperDefeat::
    .string "啊，真是的！我不甘心！$"

RockTunnel_B1F_Text_CooperPostBattle::
    .string "当你完成了你的宝可梦图鉴，\n"
    .string "可以把它送给我吗？$"

RockTunnel_B1F_Text_SteveIntro::
    .string "嗯…你了解\n"
    .string "宝可梦cosplay吗？$"

RockTunnel_B1F_Text_SteveDefeat::
    .string "好吧，就这样吧。$"

RockTunnel_B1F_Text_StevePostBattle::
    .string "所谓cosplay宝可梦，\n"
    .string "就是为了好玩打扮成宝可梦的样子！\p"
    .string "我最喜欢扮成皮皮了。$"

RockTunnel_B1F_Text_AllenIntro::
    .string "我的宝可梦招式，\n"
    .string "会把你打到哭！$"

RockTunnel_B1F_Text_AllenDefeat::
    .string "我投降！\n"
    .string "你是一个更好的技术员！$"

RockTunnel_B1F_Text_AllenPostBattle::
    .string "在山里，你经常会遇到\n"
    .string "岩石属性的宝可梦。$"

RockTunnel_B1F_Text_MarthaIntro::
    .string "虽然我不经常来这儿，\n"
    .string "但我还是要和你打一场。$"

RockTunnel_B1F_Text_MarthaDefeat::
    .string "啊！\n"
    .string "我输了！$"

RockTunnel_B1F_Text_MarthaPostBattle::
    .string "我喜欢小小的宝可梦。\n"
    .string "大的实在是太吓人了！$"

RockTunnel_B1F_Text_EricIntro::
    .string "好。\n"
    .string "你就尽情地放马过来吧！$"

RockTunnel_B1F_Text_EricDefeat::
    .string "哎呀！\n"
    .string "我被打败了！$"

RockTunnel_B1F_Text_EricPostBattle::
    .string "小子，我会培育我自己的宝可梦\n"
    .string "来打败你的！$"

RockTunnel_B1F_Text_WinstonIntro::
    .string "我在家里的时候，\n"
    .string "给宝可梦画插画。$"

RockTunnel_B1F_Text_WinstonDefeat::
    .string "呼呼…\n"
    .string "累死了…$"

RockTunnel_B1F_Text_WinstonPostBattle::
    .string "我是一名画师，不是战士。\n"
    .string "我要回家画画去了。$"

