CeladonCity_Condominiums_1F_Text_Meowth::
    .string "喵喵：喵～～呜！$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "光喝饮料可不健康。\p"
    .string "来试试这个！$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .string "没有什么能比热茶更解渴了。\p"
    .string "茶是最好的饮品！$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
    .string "我亲爱的宝可梦一直陪伴着我。\n"
    .string "喵喵还会拾钱回来呢！$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
    .string "你好哦，小朋友。\n"
    .string "我的茶好喝吗？\p"
    .string "对了，你是从真新镇来的吗？\n"
    .string "我认识一个从真新镇来的小女孩，\p"
    .string "好像是叫奈奈美吧，\n"
    .string "她经常陪我一起喝茶。\p"
    .string "而且总能看到\n"
    .string "她在玉虹百货那买茶叶呢。$"

CeladonCity_Condominiums_1F_Text_Clefairy::
    .string "皮皮：皮～皮皮～～！$"

CeladonCity_Condominiums_1F_Text_Nidoran::
    .string "尼多兰：咔 咔呜！$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
    .string "玉虹公寓\n"
    .string "经理套间$"

