CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
    .string "你知道的，宝可梦之笛\n"
    .string "能唤醒睡着的宝可梦。\p"
    .string "它能吹出一种只有宝可梦能听到的声音。$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia::
    .string "我从浅红市一路骑到这里。\p"
    .string "正好是单车路的上坡路，\n"
    .string "可把我累坏了。$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
    .string "要是我有辆自行车，\n"
    .string "我就能去单车路！$"

