Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend::
    .string "我正在和我的女友\n"
    .string "一起飙车放松呢！$"

Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes::
    .string "我们将会骑着我们的\n"
    .string "新自行车一起飞驶。$"

Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore::
    .string "一架望远镜……\n"
    .string "我来看看……\p"
    .string "那是玉虹百货公司！$"

Route16_NorthEntrance_2F_Text_LongPathOverWater::
    .string "一家望远镜……\n"
    .string "我来看看……\p"
    .string "在水上有一条\n"
    .string "通往远方的路。$"

Route16_NorthEntrance_2F_Text_GiveAmuletCoinIfCaught40::
    .string "嗨，还记得我吗？\n"
    .string "我是大木博士的助手之一。\p"
    .string "如果你的宝可梦图鉴已经收集了\n"
    .string "40种数据，我就会\l"
    .string "给你奖励。\p"
    .string "大木博士拜托我把\n"
    .string "护身金币给你。\p"
    .string "那么，{PLAYER}，让我来问问你。\p"
    .string "你至少已经取得了\n"
    .string "40种宝可梦了吗？$"

Route16_NorthEntrance_2F_Text_GreatHereYouGo::
    .string "太棒了！你已经拥有了\n"
    .string "{B_COPY_VAR_3}多种宝可梦了！\p"
    .string "恭喜！\n"
    .string "奖励，拿去吧！$"

Route16_NorthEntrance_2F_Text_ReceivedAmuletCoinFromAide::
    .string "{PLAYER}从助手那儿得到了\n"
    .string "护身金币。$"

Route16_NorthEntrance_2F_Text_ExplainAmuletCoin::
    .string "护身金币是一个\n"
    .string "由宝可梦携带的道具。\p"
    .string "如果这只宝可梦赢得了战斗，\n"
    .string "你将会得到更多钱！$"

