ThreeIsland_DunsparceTunnel_Text_ProspectingForGold::
    .string "嗨，那边的！\n"
    .string "你们怎么样？\p"
    .string "你问我在这里做什么？\n"
    .string "我在挖金矿！\p"
    .string "等到我挖成了富翁，\n"
    .string "我要在关都买一栋房子。$"

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou::
    .string "嗨！你们怎么样？\n"
    .string "你听见了吗？ 我挖到了金子！\p"
    .string "你还记得我曾经在这里挖矿吗？\p"
    .string "你无法想象我是多么的快乐！\p"
    .string "所以，我给你看！\n"
    .string "这个给你！$"

ThreeIsland_DunsparceTunnel_Text_ThatsANugget::
    .string "这是一个金珠！\p"
    .string "我无法将我的智慧传给你，\n"
    .string "那我就给你我的一部分财富吧！$"

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull::
    .string "噢，你的包包都被填满了！\n"
    .string "我以后再给你吧。$"

