ThreeIsland_Text_IslandSign::
    .string "三之岛\n"
    .string "大小一同的家庭之岛$"

ThreeIsland_Text_IslandBelongsToUs::
    .string "呀呼！\p"
    .string "从今天起，\n"
    .string "这个岛就是我们的了！$"

ThreeIsland_Text_GoBackToKanto::
    .string "我们不欢迎\n"
    .string "你们这些制造噪音和麻烦的家伙！\p"
    .string "滚回你们的关都去！$"

ThreeIsland_Text_BossIsOnHisWay::
    .string "喂，喂，吵死了。\n"
    .string "我们的老大正在路上。\p"
    .string "等他到了这里，\n"
    .string "我们会表演一场让你终身难忘的\l"
    .string "机车秀！$"

ThreeIsland_Text_GetOffIslandNow::
    .string "什，什么！？想都别想！\n"
    .string "给我马上滚！$"

ThreeIsland_Text_WhosGonnaMakeMe::
    .string "谁想让我滚？$"

ThreeIsland_Text_AreYouBossGoBackToKanto::
    .string "你就是老大？\n"
    .string "滚回你的关都去！$"

ThreeIsland_Text_JustGotHerePal::
    .string "啊？\p"
    .string "我刚刚才到这里，朋友。\p"
    .string "你们的态度怎么这么恶劣？\n"
    .string "实在太冷淡了！$"

ThreeIsland_Text_FollowersRaisingHavoc::
    .string "你的这群手下\n"
    .string "骑着车四处胡闹。\p"
    .string "你能想象他们给岛上的居民\n"
    .string "带来了多少麻烦吗？$"

ThreeIsland_Text_OughtToBeThankingUs::
    .string "我可一点不同意你的说法。\p"
    .string "你自己看看你这地方。\n"
    .string "你们有什么娱乐活动啊？\p"
    .string "你该感谢我们给这个\n"
    .string "沉闷的村庄带来了活力才对啊。\p"
    .string "不过，如果你硬要坚持的话，\n"
    .string "你可以试试赶我们走。$"

ThreeIsland_Text_YouCowardsToughInPack::
    .string "呃……你们这些废物……\n"
    .string "他们组队还真厉害……$"

ThreeIsland_Text_WannaMakeSomethingOfYourStaring::
    .string "你，干嘛盯着我看？\n"
    .string "你不知道这不礼貌吗？\p"
    .string "你想找我们茬儿吗？$"

ThreeIsland_Text_ThatsSmart::
    .string "聪明。\n"
    .string "别多管闲事。$"

ThreeIsland_Text_Biker1Intro::
    .string "嘿，我欣赏你的胆量。\n"
    .string "明知会败给我，还……$"

ThreeIsland_Text_Biker1Defeat::
    .string "哇……\n"
    .string "这孩子是什么来头？！$"

ThreeIsland_Text_Biker1PostBattle::
    .string "嗷，你……\n"
    .string "你敢再笑！$"

ThreeIsland_Text_Biker2Intro::
    .string "你不是关都人吗？\n"
    .string "你应该站我们这边才对！$"

ThreeIsland_Text_Biker2Defeat::
    .string "别胡闹了！$"

ThreeIsland_Text_Biker2PostBattle::
    .string "你干嘛那么拼命啊？\n"
    .string "一点都不酷！$"

ThreeIsland_Text_Biker3Intro::
    .string "我们把老大请来这里，\n"
    .string "可竟然全被你搞砸了！\p"
    .string "你让我们很不爽啊，小子！$"

ThreeIsland_Text_Biker3Defeat::
    .string "…… …… …… ……$"

ThreeIsland_Text_Biker3PostBattle::
    .string "老大，\n"
    .string "你一定要好好教训下这小子！$"

ThreeIsland_Text_PaxtonIntro::
    .string "我观察你很久了，\n"
    .string "你有些过分了哦。\p"
    .string "你和他们是什么关系？\n"
    .string "朋友还是别的什么？\p"
    .string "我猜你是准备好\n"
    .string "为了他们跟我宣战了。$"

ThreeIsland_Text_PaxtonDefeat::
    .string "好吧！\n"
    .string "如你们所愿，我们会走的！\p"
    .string "我们很高兴\n"
    .string "和这个无趣的岛说再见！$"

ThreeIsland_Text_PaxtonPostBattle::
    .string "哼！好吧，你就继续\n"
    .string "和这些乡巴佬混一起吧！$"

ThreeIsland_Text_ThankYouOhYourMonGotHurt::
    .string "谢谢！\n"
    .string "那些暴徒真是麻烦。\p"
    .string "噢，看啊，你的宝可梦因为我受伤了。$"

ThreeIsland_Text_GivenFullRestore::
    .string "{PLAYER}获得了\n"
    .string "一个全复药。$"

ThreeIsland_Text_OhYourBagIsFull::
    .string "喔？\n"
    .string "你的包包满了。$"

ThreeIsland_Text_YouveGotImpressiveMons::
    .string "你的宝可梦令人印象非常深刻。$"

ThreeIsland_Text_LostelleWentOffTowardsBondBridge::
    .string "如果有个像你这么厉害的人\n"
    .string "常住在这里可就好了。\p"
    .string "我希望你至少能多待上一会儿。\p"
    .string "……你说什么？\n"
    .string "你在找小迷？\p"
    .string "小迷不久前朝着\n"
    .string "索桥的方向去了。$"

ThreeIsland_Text_WouldntWantToSeeBikersHereAgain::
    .string "三之岛实际上\n"
    .string "是这里的岛屿中人口最多的一个。\p"
    .string "当然，可能是有点沉闷。\p"
    .string "但我不想再看到像那些暴走族一样的\n"
    .string "笨蛋到这里来了。$"

ThreeIsland_Text_WhenDodouEvolvesGoingToPlayGame::
    .string "我打算在树果森林训练我的嘟嘟。\p"
    .string "等它进化后，我打算\n"
    .string "带它去二之岛参加越野比赛。$"

ThreeIsland_Text_Doduo::
    .string "嘟嘟：唧唧！$"

