MtMoon_1F_Text_MarcosIntro::
    .string "哇！\n"
    .string "吓我一大跳！\l"
    .string "……不过就是个小孩嘛！$"

MtMoon_1F_Text_MarcosDefeat::
    .string "哇！\n"
    .string "吓我两大跳！$"

MtMoon_1F_Text_MarcosPostBattle::
    .string "像你这样的小朋友\n"
    .string "不应该在这么暗的地方晃悠。$"

MtMoon_1F_Text_JoshIntro::
    .string "你也是来这个山洞探险的吗？$"

MtMoon_1F_Text_JoshDefeat::
    .string "惨败！\n"
    .string "太丢人了。$"

MtMoon_1F_Text_JoshPostBattle::
    .string "我来这里的目的就是向\n"
    .string "女生们显摆我本人的形象。$"

MtMoon_1F_Text_MiriamIntro::
    .string "哇！\n"
    .string "这里宽敞得出乎我预料！$"

MtMoon_1F_Text_MiriamDefeat::
    .string "喔！\n"
    .string "我输了！$"

MtMoon_1F_Text_MiriamPostBattle::
    .string "你打算怎么从这儿出去？\n"
    .string "这里太大了，我都要迷路了。$"

MtMoon_1F_Text_JovanIntro::
    .string "干嘛！\n"
    .string "别鬼鬼祟祟地靠近我！$"

MtMoon_1F_Text_JovanDefeat::
    .string "我的宝可梦才不会这样！$"

MtMoon_1F_Text_JovanPostBattle::
    .string "嗯……！去哪里才能找到\n"
    .string "厉害的宝可梦呢……$"

MtMoon_1F_Text_IrisIntro::
    .string "什么？\n"
    .string "我在这儿等朋友来找我。$"

MtMoon_1F_Text_IrisDefeat::
    .string "我输了吗？$"

MtMoon_1F_Text_IrisPostBattle::
    .string "听说这里有罕见的\n"
    .string "化石，我就赶来了。$"

MtMoon_1F_Text_KentIntro::
    .string "山洞里有可疑的人。\n"
    .string "你又是谁？$"

MtMoon_1F_Text_KentDefeat::
    .string "……好强！$"

MtMoon_1F_Text_KentPostBattle::
    .string "我看见他们了！\n"
    .string "我可以肯定他们是火箭队的！$"

MtMoon_1F_Text_RobbyIntro::
    .string "你要穿过这个山洞\n"
    .string "才能到达华蓝市。$"

MtMoon_1F_Text_RobbyDefeat::
    .string "我输了。$"

MtMoon_1F_Text_RobbyPostBattle::
    .string "超音蝠是很难对付的！\n"
    .string "不过你收服了一只的话，\l"
    .string "你完全可以信任它。$"

MtMoon_1F_Text_ZubatIsABloodsucker::
    .string "注意！\n"
    .string "超音蝠就像一只吸血鬼！$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .string "嗨，我在月见山\n"
    .string "脚下挖掘化石。\p"
    .string "有时候，深灰道馆的小刚\n"
    .string "会来帮我的忙。$"
