PokemonMansion_B1F_Text_LewisIntro::
    .string "哇啊……\n"
    .string "我现在在哪里？$"

PokemonMansion_B1F_Text_LewisDefeat::
    .string "哇啊！$"

PokemonMansion_B1F_Text_LewisPostBattle::
    .string "你可以发现到处都是散落的东西。\n"
    .string "一定是居民们丢下的。$"

PokemonMansion_B1F_Text_IvanIntro::
    .string "这里很大，\n"
    .string "对于研究来说是个好地方。$"

PokemonMansion_B1F_Text_IvanDefeat::
    .string "接下来做什么好呢。$"

PokemonMansion_B1F_Text_IvanPostBattle::
    .string "我喜欢这里。\n"
    .string "它有助于我的研究。$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful::
    .string "日记：9月1号\n"
    .string "超梦太强大了。\p"
    .string "我们不能控制它了，\n"
    .string "它越来越邪恶了……$"

