SevenIsland_TrainerTower_Text_DarioIntro::
    .string "我感觉到了你在靠近。$"

SevenIsland_TrainerTower_Text_DarioDefeat::
    .string "放弃了……$"

SevenIsland_TrainerTower_Text_DarioPostBattle::
    .string "我感觉到在你的未来，\n"
    .string "你将会遇到许多人。\p"
    .string "你们会被一股奇异的力量\n"
    .string "互相联系在一起。$"

SevenIsland_TrainerTower_Text_RodetteIntro::
    .string "在这座岛上某个地方，\n"
    .string "有特别的宝可梦正在沉睡。$"

SevenIsland_TrainerTower_Text_RodetteDefeat::
    .string "多棒的训练家啊！$"

SevenIsland_TrainerTower_Text_RodettePostBattle::
    .string "在这座岛上某个地方，\n"
    .string "有特别的宝可梦正在沉睡。$"

SevenIsland_TrainerTower_Text_TrainerTowerSign::
    .string "训练家之塔入口\n"
    .string "上去挑战，训练家！$"

SevenIsland_TrainerTower_Text_TrainerTowerAhead::
    .string "前方是训练家之塔$"

@ Unused text perhaps indicating Trainer Tower was planned to be unlocked by something
SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed::
    .string "トレーナータワーには\n"
    .string "いまは　はいれない　みたい‥$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn::
    .string "トレーナータワーが　あいてる！\n"
    .string "さっそく　はいってみよう！$"

