Route7_EastEntrance_Text_ThirstyOnGuardDuty::
    .string "呃，我虽然很口渴得要命。\n"
    .string "但我仍然在第一线执勤！\p"
    .string "喂，站住！那条路禁止通行！$"

Route7_EastEntrance_Text_ThatTeaLooksTasty::
    .string "诶，那个茶……\n"
    .string "看起来很好喝的样子……$"

Route7_EastEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "嗯？我能喝这个吗？\n"
    .string "呃，谢谢！\l"
    .string "……\l"
    .string "咕噜……咕噜……\l"
    .string "……\l"
    .string "嗯……\l"
    .string "如果你想去\l"
    .string "金黄市的话……\l"
    .string "……\l"
    .string "就去吧。\p"
    .string "我去和其他的警卫\n"
    .string "一起分了这杯茶。$"

Route7_EastEntrance_Text_HiHowsItGoing::
    .string "嗨，最近怎么样？$"

