PokemonTower_7F_Text_Grunt1Intro::
    .string "你想干什么？\n"
    .string "在这里干嘛？$"

PokemonTower_7F_Text_Grunt1Defeat::
    .string "我、我输了！$"

PokemonTower_7F_Text_Grunt1PostBattle::
    .string "我永远不会忘记这件事！$"

PokemonTower_7F_Text_Grunt2Intro::
    .string "这老家伙直接走进我们的秘密基地。\p"
    .string "然后，他开始咆哮\n"
    .string "火箭队如何虐待宝可梦。\p"
    .string "所以，我们只是给他来了一场\n"
    .string "成年人的谈话。$"

PokemonTower_7F_Text_Grunt2Defeat::
    .string "拜托了！\n"
    .string "不要继续了！$"

PokemonTower_7F_Text_Grunt2PostBattle::
    .string "宝可梦唯一的好处就是赚钱。\n"
    .string "为什么不去利用他们呢？\p"
    .string "你离我们远点儿！$"

PokemonTower_7F_Text_Grunt3Intro::
    .string "你救不了任何人的，小子！$"

PokemonTower_7F_Text_Grunt3Defeat::
    .string "不要和我们火箭队作对！$"

PokemonTower_7F_Text_Grunt3PostBattle::
    .string "你会为此而后悔的！$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
    .string "富士老人：嗯？\n"
    .string "你是来救我的么？\p"
    .string "谢谢。但是，\n"
    .string "我来这里是自愿的。\p"
    .string "我打算来安抚卡拉卡拉\n"
    .string "母亲不安的灵魂。\p"
    .string "我想嘎啦嘎啦的灵魂\n"
    .string "终于离开了我们。\p"
    .string "十分感谢你的好心。\p"
    .string "跟我回一趟我的家吧，宝可梦之家，\n"
    .string "就在这座塔底下的。$"

