PewterCity_Museum_1F_Text_Its50YForChildsTicket::
    .string "好的。\n"
    .string "儿童票要¥50。\p"
    .string "你想进去吗？$"

PewterCity_Museum_1F_Text_ComeAgain::
    .string "以后再来哦！$"

PewterCity_Museum_1F_Text_Right50YThankYou::
    .string "好的。\n"
    .string "收你¥50！$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney::
    .string "你没有足够的钱。$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself::
    .string "请慢慢参观！$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs::
    .string "你不能从后门溜进来啊！\n"
    .string "身手不错，但这样做可不对。\p"
    .string "唉，不管怎么样！\n"
    .string "你知道什么是琥珀吗？$"

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter::
    .string "琥珀里面有古代宝可梦\n"
    .string "的遗传基因。\p"
    .string "在某个地方有一个研究所\n"
    .string "正努力从琥珀复活宝可梦。$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap::
    .string "琥珀实际上是树液，\n"
    .string "一种从树里面流出来的黏黏的液体。\p"
    .string "古老的树液化石经过\n"
    .string "很长时间以后变成了坚硬的琥珀。$"

@ Unused
PewterCity_Museum_1F_Text_PleaseGoAround::
    .string "あちらへ　おまわりください$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife::
    .string "感谢上苍让我\n"
    .string "活了这么长时间。\p"
    .string "我从没想过\n"
    .string "我能亲眼看见龙的化石！$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined::
    .string "嘘！听着，\n"
    .string "我要告诉你一个重要的秘密。\p"
    .string "我认为这块琥珀\n"
    .string "里面有宝可梦的DNA！\p"
    .string "如果宝可梦能从里面复活，\n"
    .string "这将是整个科学界\l"
    .string "一个重大的突破。\p"
    .string "但是，我的同事们\n"
    .string "都把我说的不当回事。\p"
    .string "所以我有一个请求！\p"
    .string "我想让你帮我把这个带到\n"
    .string "一个宝可梦实验室去检测一下。$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan::
    .string "{PLAYER}从他那里得到了秘密琥珀。$"

PewterCity_Museum_1F_Text_GetOldAmberChecked::
    .string "嘘！\n"
    .string "去检测这个秘密琥珀吧！$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis::
    .string "你的包包满了。$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit::
    .string "我们正在展出两只珍惜的\n"
    .string "史前宝可梦的化石。$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber::
    .string "这是一块漂亮的琥珀，\n"
    .string "闪烁着金黄色。$"

PewterCity_Museum_1F_Text_AerodactylFossil::
    .string "化石翼龙的化石\n"
    .string "一种原始且珍贵的宝可梦。$"

PewterCity_Museum_1F_Text_KabutopsFossil::
    .string "镰刀盔的化石\n"
    .string "一种原始且珍贵的宝可梦。$"

