SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn::
    .string "跳跃吧，舞动吧！\n"
    .string "吉利蛋舞！\p"
    .string "你也一起来跳吧！\n"
    .string "跳跃吧，舞动吧！$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance::
    .string "你也要一起跳吗？$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance::
    .string "来吧，跳吧！$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance::
    .string "{PLAYER}跳了吉利蛋舞！$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow::
    .string "哈哈哈！\p"
    .string "好了，你们现在都精神多了！\n"
    .string "运气真好！$"

SevenIsland_SevaultCanyon_House_Text_Chansey::
    .string "吉利蛋：琴茜！琴茜！$"
