VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "我正让我的波波飞去北边的金黄\n"
    .string "送一封信。$"

VermilionCity_House3_Text_Pidgey::
    .string "波波：咕噜咕！$"

VermilionCity_House3_Text_DearPippiLetter::
    .string "亲爱的比比，\n"
    .string "希望能很快见到你。\p"
    .string "我听说火箭队在金黄制造麻烦。\p"
    .string "枯叶似乎还安全。$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
    .string "我想和各种各样的人连接。\p"
    .string "我常把波波派去联盟交谊厅\n"
    .string "替我传递信件。$"

