Route18_Text_WiltonIntro::
    .string "我总是踏遍每一个草丛\n"
    .string "来寻找新的宝可梦。$"

Route18_Text_WiltonDefeat::
    .string "哎呀……！$"

Route18_Text_WiltonPostBattle::
    .string "我希望有一辆自行车！$"

Route18_Text_RamiroIntro::
    .string "咕咕……！\n"
    .string "怎么样？我的指笛！$"

Route18_Text_RamiroDefeat::
    .string "我不得不打扰你！$"

Route18_Text_RamiroPostBattle::
    .string "我在周末喜欢收集海洋的宝可梦，\n"
    .string "因为大海离我太近了。$"

Route18_Text_JacobIntro::
    .string "这一带是我们的地盘！\n"
    .string "你给我离远点！$"

Route18_Text_JacobDefeat::
    .string "见鬼！$"

Route18_Text_JacobPostBattle::
    .string "这是我最喜欢收服\n"
    .string "宝可梦的地方。$"

Route18_Text_RouteSign::
    .string "18号道路\n"
    .string "玉虹市-浅红市$"

Route18_Text_CyclingRoadSign::
    .string "单车路\n"
    .string "不允许步行的人进入！$"

