SafariZone_SecretHouse_Text_CongratsYouveWon::
    .string "啊！终于！\p"
    .string "你是来到神秘小屋的\n"
    .string "第一个人！\p"
    .string "虽然我为我们这个比赛\n"
    .string "制订了周密的计划，\p"
    .string "但我还是很担心会没有人\n"
    .string "能赢走我们的比赛奖品。\p"
    .string "祝贺你！\n"
    .string "你赢了！$"

SafariZone_SecretHouse_Text_ReceivedHM03FromAttendant::
    .string "{PLAYER} 从服务员那里\n"
    .string "得到了秘传学习器03！$"

SafariZone_SecretHouse_Text_ExplainSurf::
    .string "秘传学习器03是冲浪。\p"
    .string "宝可梦能够使用它\n"
    .string "载着你在水面上前进。\p"
    .string "还有，秘传学习器不是一次性的，\n"
    .string "所以你可以反复使用它。\p"
    .string "你非常幸运，赢得了\n"
    .string "这个令人难以置信的奖品！$"

SafariZone_SecretHouse_Text_DontHaveRoomForPrize::
    .string "你没有空间来接受这份\n"
    .string "这巨大的奖品！$"

