VictoryRoad_1F_Text_NaomiIntro::
    .string "我想知道你配得上做我的对手吗？$"

VictoryRoad_1F_Text_NaomiDefeat::
    .string "我输了……$"

VictoryRoad_1F_Text_NaomiPostBattle::
    .string "我不想输给任何人，\n"
    .string "尤其是一个年轻的孩子……$"

VictoryRoad_1F_Text_RolandoIntro::
    .string "我能感到你很厉害。\n"
    .string "让我看看你到底有多厉害！$"

VictoryRoad_1F_Text_RolandoDefeat::
    .string "我有胜算的……$"

VictoryRoad_1F_Text_RolandoPostBattle::
    .string "好！\n"
    .string "我承认，你比我强！$"

