CeruleanCity_House1_Text_AnyInterestInBerries::
    .string "我可以用树果粉末\n"
    .string "调制各种药物。\p"
    .string "用好的树果粉末的话，\n"
    .string "什么药我都能做出来。\p"
    .string "告诉我，你对树果\n"
    .string "有兴趣吗？$"

CeruleanCity_House1_Text_HaveJustTheThing::
    .string "啊，好的！为你，\n"
    .string "我只要那个东西。$"

CeruleanCity_House1_Text_GoCrushBerriesAtDirectCorner::
    .string "在宝可梦中心的二楼\n"
    .string "直连房间处\l"
    .string "有一些新的东西。\p"
    .string "他们安装了一个\n"
    .string "可以捣碎树果的机器。\p"
    .string "这就是你要去的地方。\p"
    .string "我有一个请求，\n"
    .string "我只能委托你了。\p"
    .string "你可以用那台机器\n"
    .string "给我做一些树果粉末吗？\p"
    .string "别忘了，那台机器在\n"
    .string "宝可梦中心的直连房间处。\p"
    .string "如果你给我带回一些树果粉末，\n"
    .string "我会给你调制一些药物。\p"
    .string "别忘了，把树果压碎成\n"
    .string "树果粉末带回来给我。$"

CeruleanCity_House1_Text_WhyMustYouLieNoBerries::
    .string "为什么要对我说谎？\p"
    .string "你有多少树果？\n"
    .string "一个也没有！$"

CeruleanCity_House1_Text_TakeInterestInAllSortsOfThings::
    .string "你对树果不感兴趣？\p"
    .string "年轻人，对各种事物感兴趣\n"
    .string "是很重要的。$"

CeruleanCity_House1_Text_HaveYouBroughtBerryPowder::
    .string "呃！你给我带回一些\n"
    .string "树果粉末了吗？$"

CeruleanCity_House5_Text_ExchangeWithWhat::
    .string "你想用它交换什么？$"

CeruleanCity_House1_Text_YoullExchangeBerryPowderForItem::
    .string "好的，你想用一份\n"
    .string "树果粉末交换{B_COPY_VAR_1}？$"

CeruleanCity_House1_Text_DontHaveEnoughBerryPowder::
    .string "嗯？你没有足够的树果粉末。$"

CeruleanCity_House1_Text_TradeMoreBerryPowder::
    .string "这真的是树果粉末。\n"
    .string "能用它制作出很好的药物。\p"
    .string "你想交换更多树果粉末\n"
    .string "来获得其他的东西吗？$"

CeruleanCity_House1_Text_HopeToSeeYouAgain::
    .string "好的。\n"
    .string "我希望你能再回来。$"

CeruleanCity_House1_Text_SeeMeIfYoudLikeToTradePowder::
    .string "如果你想交换你的树果粉末\n"
    .string "就来找我吧。$"

