Route20_Text_BarryIntro::
    .string "这儿的水很浅。\n"
    .string "有很多人在这儿游泳。$"

Route20_Text_BarryDefeat::
    .string "扑通！$"

Route20_Text_BarryPostBattle::
    .string "我希望能骑着我的宝可梦。\n"
    .string "你应该还不算太累。$"

Route20_Text_ShirleyIntro::
    .string "双子岛是一个安静的度假场所。\n"
    .string "我就是正在这儿休假。$"

Route20_Text_ShirleyDefeat::
    .string "快住手啊。$"

Route20_Text_ShirleyPostBattle::
    .string "这座岛下有个巨大的洞穴。$"

Route20_Text_TiffanyIntro::
    .string "我喜欢和鱼儿们一起\n"
    .string "飘游在波浪之中。$"

Route20_Text_TiffanyDefeat::
    .string "唔，是翻车鱼！$"

Route20_Text_TiffanyPostBattle::
    .string "你要来和我一起……\n"
    .string "随波逐流吗？$"

Route20_Text_IreneIntro::
    .string "你也是来度假的吗？$"

Route20_Text_IreneDefeat::
    .string "你下手真狠啊。$"

Route20_Text_IrenePostBattle::
    .string "在很久以前，\n"
    .string "双子岛是一座独立的小岛。$"

Route20_Text_DeanIntro::
    .string "快看！\n"
    .string "我这千锤百炼的身体！$"

Route20_Text_DeanDefeat::
    .string "太没用了。$"

Route20_Text_DeanPostBattle::
    .string "我应该让宝可梦的体格变强壮，\n"
    .string "而不是我的！$"

Route20_Text_DarrinIntro::
    .string "你为什么骑着宝可梦？\n"
    .string "你不会游泳吗？$"

Route20_Text_DarrinDefeat::
    .string "唔，咕嘟咕嘟……$"

Route20_Text_DarrinPostBattle::
    .string "骑着宝可梦看起来确实很有趣！$"

Route20_Text_RogerIntro::
    .string "我是骑着鸟宝可梦\n"
    .string "到这里来的。$"

Route20_Text_RogerDefeat::
    .string "噢，不！\n"
    .string "现在我该怎么办？$"

Route20_Text_RogerPostBattle::
    .string "我的鸟儿们精疲力竭了。\n"
    .string "它们再也无法载我飞回去了！$"

Route20_Text_NoraIntro::
    .string "男朋友给了我一颗\n"
    .string "很大很大的珍珠！$"

Route20_Text_NoraDefeat::
    .string "噢，不！\n"
    .string "我的珍珠还在里面！$"

Route20_Text_NoraPostBattle::
    .string "我的珍珠放在铁甲贝\n"
    .string "里面会变大吗？$"

Route20_Text_MissyIntro::
    .string "我从红莲镇游过来的。\n"
    .string "跟你讲，这可不轻松。$"

Route20_Text_MissyDefeat::
    .string "我太失望了！$"

Route20_Text_MissyPostBattle::
    .string "在红莲镇，宝可梦占据了\n"
    .string "那所被遗弃的建筑。\p"
    .string "那儿现在叫做宝可梦屋。$"

Route20_Text_MelissaIntro::
    .string "在红莲镇西方，\n"
    .string "有一个宝可梦的研究所。\p"
    .string "我的爸爸在那儿工作。$"

Route20_Text_MelissaDefeat::
    .string "等等！\n"
    .string "你给我站住！$"

Route20_Text_MelissaPostBattle::
    .string "红莲镇是一个火山岛。\p"
    .string "我听说在某一次火山喷发时，\n"
    .string "它从海上生成了。$"

Route20_Text_SeafoamIslands::
    .string "双子岛$"

Route20_Text_MistyTrainsHere::
    .string "在这儿经常能看到\n"
    .string "强大的训练家和强大的水属性宝可梦。\p"
    .string "据说华蓝道馆的小霞\n"
    .string "也在这儿训练。$"
