Route21_South_Text_JackIntro::
	.string "我的宝可梦\n"
	.string "是在海里捉到的。$"

Route21_South_Text_JackDefeat::
	.string "潜水者！！\n"
	.string "下去！$"

Route21_South_Text_JackPostBattle::
	.string "你在哪儿获得你的宝可梦？$"

Route21_South_Text_JeromeIntro::
	.string "现在，我在参加三项全能的竞赛。$"

Route21_South_Text_JeromeDefeat::
	.string "呼……\n"
	.string "呼……呼……$"

Route21_South_Text_JeromePostBattle::
	.string "我输了！但是，我仍然可以\n"
	.string "进行自行车和马拉松的比赛！$"

Route21_South_Text_RolandIntro::
	.string "啊～！\n"
	.string "阳光照在身上好舒服！$"

Route21_South_Text_RolandDefeat::
	.string "我输了！$"

Route21_South_Text_RolandPostBattle::
	.string "我被晒黑了！$"

Route21_South_Text_ClaudeIntro::
	.string "嘿，不要把鱼吓走了！$"

Route21_South_Text_ClaudeDefeat::
	.string "对不起！我刚刚太沮丧了，\n"
	.string "因为我没有收服到任何东西。$"

Route21_South_Text_ClaudePostBattle::
	.string "我什么也没有收服。\n"
	.string "难道这个地方实际上只是\l"
	.string "一个大水池或是其他什么鬼地方吗？$"

Route21_South_Text_NolanIntro::
	.string "鱼上钩之前\n"
	.string "我就陪你玩玩吧。$"

Route21_South_Text_NolanDefeat::
	.string "真是不错的消遣。$"

Route21_South_Text_NolanPostBattle::
	.string "噢，等等！\n"
	.string "我钓到一竿，耶！$"

Route21_North_Text_LilIntro::
	.string "千沙：呃？战斗？\n"
	.string "阿胜，你不能一个人去做吗？$"

Route21_North_Text_LilDefeat::
	.string "千沙：看吧？\n"
	.string "我们输了。满意了吗？$"

Route21_North_Text_LilPostBattle::
	.string "千沙：我累了。\n"
	.string "现在还不能回家吗？$"

Route21_North_Text_LilNotEnoughMons::
	.string "千沙：呃？战斗？\n"
	.string "我不能一个人战斗。\l"
	.string "带来两只宝可梦吧？$"

Route21_North_Text_IanIntro::
	.string "阿胜：我姐姐练习的太少了，\n"
	.string "所以我把她带到了这里。$"

Route21_North_Text_IanDefeat::
	.string "阿胜：啊，姐姐！\n"
	.string "一起战斗吧！$"

Route21_North_Text_IanPostBattle::
	.string "阿胜：加油，姐姐！\p"
	.string "你这样是不会减肥的！$"

Route21_North_Text_IanNotEnoughMons::
	.string "阿胜：我们希望来一场2对2的战斗。\n"
	.string "所以你能带两只宝可梦来吗？$"
