SafariZone_West_Text_RestHouse::
    .string "休息屋$"

SafariZone_West_Text_PleaseFindWardensLostTeeth::
    .string "寻物启示\p"
    .string "寻找狩猎地带园长\n"
    .string "丢失了的金假牙。\l"
    .string "它就掉在这里的某个地方。\p"
    .string "是有奖悬赏！\n"
    .string "联系人：园长$"

SafariZone_West_Text_SearchForSecretHouse::
    .string "……有用的公告牌！\p"
    .string "区域性的探险活动！\n"
    .string "搜索神秘小屋！$"

SafariZone_West_Text_AreaSign::
    .string "栖息地3\n"
    .string "往东：中部栖息地$"

