Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou::
    .string "好，在我的腰带上\n"
    .string "放置六个精灵球……\p"
    .string "没错，就是这样。你最多只能\n"
    .string "带六只宝可梦随行。$"

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean::
    .string "火箭队袭击了华蓝市\n"
    .string "的居民……\p"
    .string "没有哪天的新闻里\n"
    .string "不出现火箭队。$"

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500::
    .string "男子：看这里，少年！\n"
    .string "这笔好买卖我留着就等着和你做！\p"
    .string "神秘又强大的宝可梦鲤鱼王，\n"
    .string "惊喜价只要500！\p"
    .string "你肯定会买下它，对吧？$"

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500::
    .string "男子：看这里，少女！\n"
    .string "这笔好买卖我留着就等着和你做！\p"
    .string "神秘又强大的宝可梦鲤鱼王，\n"
    .string "惊喜价只要500！\p"
    .string "你肯定会买下它，对吧？$"

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp::
    .string "{PLAYER}付了500元，\n"
    .string "得到了鲤鱼王……$"

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou::
    .string "不？你说不？\n"
    .string "我已经给了你最大的优惠了！$"

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon::
    .string "看起来好像没有足够的空间\n"
    .string "来放更多的宝可梦了。$"

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney::
    .string "你的钱不够！$"

Route4_PokemonCenter_1F_Text_IDontGiveRefunds::
    .string "男子：一旦售出，绝不退款。\n"
    .string "买之前你就该想好！$"

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC::
    .string "有时，你带的宝可梦太多了\n"
    .string "以至于不能再增加新的。\p"
    .string "这样的话，你应该用任意电脑\n"
    .string "存放一些。$"

Route4_PokemonCenter_1F_Text_ItsANewspaper::
    .string "这是一份报纸。$"

