PokemonLeague_BrunosRoom_Text_Intro::
    .string "我是四天王中的希巴！\p"
    .string "不论是宝可梦还是人\n"
    .string "只要通过战斗的磨练\l"
    .string "都能变的更强。\p"
    .string "我就是靠着这股信念\n"
    .string "和宝可梦一起生活一起训练！\l"
    .string "而且之后我们也会永远会一起！\p"
    .string "{PLAYER}！\p"
    .string "尝尝我们强大的力量把你\n"
    .string "打倒的滋味吧！\p"
    .string "喝啊！{PLAY_BGM 0x56 0x01}$"

PokemonLeague_BrunosRoom_Text_RematchIntro::
    .string "我是四天王中的希巴！\p"
    .string "不论是宝可梦还是人\n"
    .string "只要通过战斗的磨练\l"
    .string "都能变的更强。\p"
    .string "我就是靠着这股信念\n"
    .string "和宝可梦一起生活一起训练！\l"
    .string "而且之后我们也会永远会一起！\p"
    .string "{PLAYER}！\p"
    .string "尝尝我们强大的力量的吧！\n"
    .string "同它把你打倒！\p"
    .string "喝啊！{PLAY_BGM 0x56 0x01}$"

PokemonLeague_BrunosRoom_Text_Defeat::
    .string "怎么会这样！\n"
    .string "……我竟然输了！$"

PokemonLeague_BrunosRoom_Text_PostBattle::
    .string "我的工作已经完成了。\n"
    .string "去面对你下一个挑战吧。$"

