SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
    .string "船长：呕……\n"
    .string "我很不舒服……\l"
    .string "呕！好晕啊……$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
    .string "{PLAYER}揉了揉船长的背！\p"
    .string "揉揉……\n"
    .string "揉揉……$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
    .string "船长：唔！谢谢你！\n"
    .string "我现在好多了。\p"
    .string "你想看我的秘传招式居合劈吗？\p"
    .string "如果我不是那么虚弱的话倒是可以让你\n"
    .string "见识下我独步天下的居合劈……\p"
    .string "我想起来了！给你这个！\n"
    .string "这个秘传学习器！\p"
    .string "把居合劈教给你的宝可梦，\n"
    .string "你就能让它随时表演居合劈给你看了！$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
    .string "{PLAYER}从船长那里\n"
    .string "获得了秘传学习器01！$"

SSAnne_CaptainsOffice_Text_ExplainCut::
    .string "使用居合劈，你就能砍掉小树。\p"
    .string "可以找枯叶市周围的树试试哦！$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
    .string "船长：……唔！\p"
    .string "我现在好了，\n"
    .string "我想时间也差不多到了。\p"
    .string "圣特安努号马上就要启航了！\p"
    .string "下次回枯叶市时我们再见！$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
    .string "哦，不！\n"
    .string "你已经没有多余的空间了！$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
    .string "真恶心！\n"
    .string "早知就不应该看！$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
    .string "怎么样才能克服晕船……\n"
    .string "船长正在阅读中！$"

