SilphCo_8F_Text_WonderIfSilphIsFinished::
    .string "恐怕西尔佛已经完蛋了……$"

SilphCo_8F_Text_ThanksForSavingUs::
    .string "谢谢你救了我！$"

SilphCo_8F_Text_Grunt1Intro::
    .string "你前进的道路到此为止！$"

SilphCo_8F_Text_Grunt1Defeat::
    .string "在气势上输了么。$"

SilphCo_8F_Text_Grunt1PostBattle::
    .string "如果你不马上滚回去……\n"
    .string "我要叫你好看！$"

SilphCo_8F_Text_ParkerIntro::
    .string "你给我们带来太多的麻烦了！$"

SilphCo_8F_Text_ParkerDefeat::
    .string "……？我输了吗？$"

SilphCo_8F_Text_ParkerPostBattle::
    .string "那么，你有什么对西尔佛\n"
    .string "大楼的迷宫有什么看法？$"

SilphCo_8F_Text_Grunt2Intro::
    .string "我是火箭队\n"
    .string "四兄弟之一！$"

SilphCo_8F_Text_Grunt2Defeat::
    .string "哇！\n"
    .string "啊，兄弟们！$"

SilphCo_8F_Text_Grunt2PostBattle::
    .string "我会把你留给我的兄弟们来对付。$"

SilphCo_8F_Text_FloorSign::
    .string "西尔佛公司总部\n"
    .string "8F$"

SilphCo_8F_Text_ToRocketBossMonsAreTools::
    .string "火箭队的头目\n"
    .string "是一个特别残忍的人！\p"
    .string "对他而言，宝可梦只是可以\n"
    .string "被利用的工具。\p"
    .string "如果这家伙接管了\n"
    .string "我们的公司就完了……$"
