SafariZone_East_Text_KeepAnyItemFoundOnSafari::
    .string "你能拿走任何你在狩猎地带\n"
    .string "找到的东西。\p"
    .string "但是如果你想要一次把\n"
    .string "所有东西都拿走的话，\p"
    .string "你的时间会耗尽的。$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
    .string "走到狩猎地带的最深处。\n"
    .string "你就会赢得奖品！$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
    .string "我的伊布进化成了火伊布。\p"
    .string "但是，我一个朋友的伊布进化成了\n"
    .string "水伊布。我不知道这是为什么？$"

