PokemonTower_4F_Text_PaulaIntro::
    .string "唔唔……可恶的恶灵……\n"
    .string "……咔！$"

PokemonTower_4F_Text_PaulaDefeat::
    .string "哈啊！\n"
    .string "幽、幽灵在哪里？$"

PokemonTower_4F_Text_PaulaPostBattle::
    .string "我刚刚一定在做梦……$"

PokemonTower_4F_Text_LaurelIntro::
    .string "被我诅咒吧！\n"
    .string "哈啊！$"

PokemonTower_4F_Text_LaurelDefeat::
    .string "……哈啊！$"

PokemonTower_4F_Text_LaurelPostBattle::
    .string "我们不能确定幽灵\n"
    .string "的真面目……$"

PokemonTower_4F_Text_JodyIntro::
    .string "呼呼呼……\n"
    .string "不要打我！$"

PokemonTower_4F_Text_JodyDefeat::
    .string "……嗯，我是？$"

PokemonTower_4F_Text_JodyPostBattle::
    .string "让死去的宝可梦\n"
    .string "安息吧……$"

