CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel::
    .string "白银喷雾可以防止\n"
    .string "弱小的宝可梦靠近你……\p"
    .string "嗯，它是种效果更好的除虫喷雾。$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
    .string "长途旅行的话，\n"
    .string "你该买些活力碎片带着。$"

CeladonCity_DepartmentStore_2F_Text_FloorSign::
    .string "为训练家准备的顶级物品！\p"
    .string "二楼：训练家商店$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes::
    .string "我们有个偶尔会来光顾的客人，\n"
    .string "就是阿渡。\p"
    .string "他总是来买披风。\p"
    .string "我很想知道……他家里是不是有很多\n"
    .string "一模一样的披风？$"
