LavenderTown_Mart_Text_SearchingForStatRaiseItems::
    .string "我正在寻找能提升宝可梦\n"
    .string "战斗力的物品。\p"
    .string "它们在一场战斗中可以力挽狂澜。\p"
    .string "力量强化，防御强化，速度强化，\n"
    .string "和特攻强化都是我在寻找的。\p"
    .string "你知道在哪儿能得到它们吗？$"

LavenderTown_Mart_Text_DidYouBuyRevives::
    .string "你要买一些活力碎片吗？\n"
    .string "这个能使昏厥的宝可梦恢复！$"

LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
    .string "有时候，会有一对训练家\n"
    .string "同时拿出两只宝可梦\l"
    .string "来挑战你。\p"
    .string "如果你遇上了，你就要\n"
    .string "拿出两只宝可梦来战斗。$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
    .string "この　あいだ　やまおくで\n"
    .string "きんのたまを　ひろい　ましてね！\p"
    .string "つかえない　しなもの　ですが\n"
    .string "うったら　なんと　¥5000でした$"
