SaffronCity_Dojo_Text_MasterKoichiIntro::
    .string "哼哼！\p"
    .string "我就是空手大王！\n"
    .string "也是这里的馆主！\p"
    .string "你想要挑战我？\n"
    .string "我可不会手下留情的！\p"
    .string "哇哈哈！$"

SaffronCity_Dojo_Text_MasterKoichiDefeat::
    .string "喝！\n"
    .string "可恶！败了！$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon::
    .string "我输了！这是事实！\p"
    .string "但是，我求你一件事，能不能\n"
    .string "别把我们的徽章作为你战利品！\p"
    .string "作为回报，我会送给你一只\n"
    .string "格斗属性宝可梦！\p"
    .string "选一只你喜欢的吧！$"

SaffronCity_Dojo_Text_StayAndTrainWithUs::
    .string "哼哼！\n"
    .string "在那儿站好陪我练练空手道吧！$"

SaffronCity_Dojo_Text_MikeIntro::
    .string "呜！\n"
    .string "快把鞋子脱掉！$"

SaffronCity_Dojo_Text_MikeDefeat::
    .string "我、我输了！$"

SaffronCity_Dojo_Text_MikePostBattle::
    .string "等你见到我们的掌门再说吧！\n"
    .string "和他比起来我不过是个杂鱼罢了！$"

SaffronCity_Dojo_Text_HidekiIntro::
    .string "我听说你很厉害！\n"
    .string "给我看看！$"

SaffronCity_Dojo_Text_HidekiDefeat::
    .string "嘿呀！得一分！$"

SaffronCity_Dojo_Text_HidekiPostBattle::
    .string "我师父是格斗家之神！\n"
    .string "要挑战他的话，你得抱有必死的决心！$"

SaffronCity_Dojo_Text_AaronIntro::
    .string "嘿呀！\n"
    .string "任何事情都不能吓到我！\p"
    .string "为了训练\n"
    .string "我每天都在练习击碎巨石！$"

SaffronCity_Dojo_Text_AaronDefeat::
    .string "啊呀！嘿呀！$"

SaffronCity_Dojo_Text_AaronPostBattle::
    .string "对我们格斗家来说\n"
    .string "最害怕的就是超能力！$"

SaffronCity_Dojo_Text_HitoshiIntro::
    .string "哗！\p"
    .string "你擅自闯入了我们的\n"
    .string "格斗道场！$"

SaffronCity_Dojo_Text_HitoshiDefeat::
    .string "唔！我输了！$"

SaffronCity_Dojo_Text_HitoshiPostBattle::
    .string "这位祖师级的格斗大师\n"
    .string "跋山涉水来到这里修炼。$"

SaffronCity_Dojo_Text_YouWantHitmonlee::
    .string "你想要这只擅长踢技的\n"
    .string "飞腿郎吗？$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster::
    .string "{PLAYER}从空手大王那里\n"
    .string "得到了{B_COPY_VAR_1}。$"

SaffronCity_Dojo_Text_YouWantHitmonchan::
    .string "你想要这只擅长拳击的\n"
    .string "快拳郎吗？$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2::
    .string "{PLAYER}は　カラテ　だいおう　から\n"
    .string "{STR_VAR_1}を　もらった！$"

SaffronCity_Dojo_Text_BetterNotGetGreedy::
    .string "别太贪心啊……$"

SaffronCity_Dojo_Text_EnemiesOnEverySide::
    .string "四面楚歌$"

SaffronCity_Dojo_Text_GoesAroundComesAround::
    .string "因果报应$"

SaffronCity_Dojo_Text_FightingDojo::
    .string "格斗道场！$"

