Aide_Text_HaventCaughtEnoughMonsForItem::
	.string "好吧，让我看看……\n"
	.string "哎哟！你只抓到了\l"
	.string "{B_COPY_VAR_3}种宝可梦！\p"
	.string "如果你想要{B_COPY_VAR_2}的话\n"
	.string "你需要抓到{B_COPY_VAR_1}种。$"

Aide_Text_GetEnoughMonsComeBackForItem::
	.string "……哦，这样。\p"
	.string "当你抓到{B_COPY_VAR_1}种宝可梦的时候，\n"
	.string "就可以回来找我要{B_COPY_VAR_2}。$"

Aide_Text_DontHaveAnyRoomForItem::
	.string "哦！我想你没有足够的\n"
	.string "位置来放{B_COPY_VAR_2}。$"
