@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife::
	.string "我是培育屋爷爷。\p"
	.string "我能帮助训练家们照看可爱的\n"
	.string "宝可梦。\p"
	.string "如果你想要我帮你照看\n"
	.string "宝可梦，就和我的妻子说吧。$"

DayCare_Text_DoYouWantEgg::
	.string "啊，你来了！\p"
	.string "我们正在训练着你的宝可梦呢，\n"
	.string "我的天，太令人惊讶了！\p"
	.string "你的宝可梦生出了一个蛋！\p"
	.string "我们不知道它是怎么出现的，\n"
	.string "但它应该是你的宝可梦的。\p"
	.string "你想要这个蛋吗？$"

DayCare_Text_YourMonIsDoingFine::
	.string "啊，你来了！见到你真高兴。\n"
	.string "你的{B_COPY_VAR_1}在我们这儿过得很好。$"

DayCare_Text_IllKeepIt::
	.string "好的，那么我会照看好它的。\n"
	.string "谢谢！$"

DayCare_Text_YouHaveNoRoomForIt::
	.string "你身上没有空位了……\n"
	.string "等你腾出了空间再过来吧。$"

DayCare_Text_ReceivedEgg::
	.string "{PLAYER}从培育屋爷爷\n"
	.string "手中拿到了蛋。$"

DayCare_Text_TakeGoodCareOfIt::
	.string "请好好照顾它。$"

DayCare_Text_SeeWifeIfYouWantToPickUpMon::
	.string "ポケモンを　ひきとりたい　ときは\n"
	.string "ばさんに　いって　おくれ$"

DayCare_Text_YourMonsAreDoingFine::
	.string "啊，你来了！{B_COPY_VAR_1}和\n"
	.string "{B_COPY_VAR_2}都过得很好。$"

DayCare_Text_IWillKeepDoYouWantIt::
	.string "那我就收下了。\n"
	.string "其实你还是想要的吧？$"

DayCare_Text_WouldYouLikeUsToRaiseMon::
	.string "我是培育屋奶奶。\p"
	.string "我们能为你培养你的宝可梦。\p"
	.string "需要我们的帮助吗？$"

DayCare_Text_WhichMonShouldWeRaise::
	.string "想要我们帮你培养哪只\n"
	.string "宝可梦？$"

DayCare_Text_WellRaiseYourMon::
	.string "好，现在我们会帮你\n"
	.string "照看{B_COPY_VAR_1}的。\p"
	.string "请过一段时间再来。$"

DayCare_Text_WeCanRaiseOneMore::
	.string "我们能为你培养两只宝可梦。\p"
	.string "你还需要我们再帮助你\n"
	.string "照看另一只宝可梦吗？$"

DayCare_Text_HusbandWasLookingForYou::
	.string "我的丈夫正在找你。$"

DayCare_Text_FineThenComeAgain::
	.string "好的，\n"
	.string "那么欢迎下次再来。$"

DayCare_Text_NotEnoughMoney::
	.string "你带的钱不够……$"

DayCare_Text_TakeOtherOneBackToo::
	.string "你需要我们把另外一只\n"
	.string "一起交还给你吗？$"

DayCare_Text_ComeAgain::
	.string "好，\n"
	.string "欢迎下次再来。$"

DayCare_Text_GoodToSeeYou::
	.string "啊，是你！\n"
	.string "看见你真高兴。\p"
	.string "你的宝可梦\n"
	.string "过得很好！$"

DayCare_Text_YourMonHasGrownXLevels::
	.string "你的{B_COPY_VAR_1}\n"
	.string "成长了{B_COPY_VAR_2}。$"

DayCare_Text_YourPartyIsFull::
	.string "你宝可梦的队伍满了。\n"
	.string "腾点空间，然后再来见我吧。$"

DayCare_Text_TakeBackWhichMon::
	.string "どっちの　ポケモンを　ひきとるかい？$"

DayCare_Text_ItWillCostX::
	.string "如果你想带回你的{B_COPY_VAR_1}，\n"
	.string "需要花费¥{B_COPY_VAR_2}。$"

DayCare_Text_HeresYourMon::
	.string "好！\n"
	.string "这是你的宝可梦。$"

DayCare_Text_TookBackMon::
	.string "{PLAYER}从培育屋奶奶那里\n"
	.string "拿回了{B_COPY_VAR_1}。$"

DayCare_Text_YouHaveJustOneMon::
	.string "喔？但你身上只剩一只\n"
	.string "宝可梦了。\p"
	.string "换个时间再来吧。$"

DayCare_Text_TakeYourMonBack::
	.string "想要要回你的宝可梦吗？$"

DayCare_Text_WhatWillYouBattleWith::
	.string "如果你把那只宝可梦扔在这里，\n"
	.string "你用什么来战斗呢？\p"
	.string "换个时间再来吧。$"

DayCare_Text_Huh::
	.string "嗯？$"
