gFameCheckerFlavorText_ProfOak0:: @ 0x81AD106
	.string "{COLOR 0x08}{SHADOW 0x09}这里是……？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}大木宝可梦研究所$"

gFameCheckerFlavorText_ProfOak1:: @ 0x81AD145
	.string "{COLOR 0x08}{SHADOW 0x09}这个人的梦想是什么？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}收集齐世界上\n"
	.string "所有宝可梦的资料……\p"
	.string "\p"
	.string "一直是我的梦想！$"

gFameCheckerFlavorText_ProfOak2:: @ 0x81AD1BB
	.string "{COLOR 0x08}{SHADOW 0x09}这么人怎么样？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}大木博士可能长得不是很帅，\n"
	.string "但是他是宝可梦研究的权威。\p"
	.string "\p"
	.string "宝可梦训练家都十分尊敬他。$"

gFameCheckerFlavorText_ProfOak3:: @ 0x81AD258
	.string "{COLOR 0x08}{SHADOW 0x09}家人与朋友？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}据说，大木博士和他的\n"
	.string "孙子孙女，奈奈美和{B_OPPONENT_MON1_NAME}一起生活。$"

gFameCheckerFlavorText_ProfOak4:: @ 0x81AD2B9
	.string "{COLOR 0x08}{SHADOW 0x09}家人与朋友？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}我听说大木\n"
	.string "相当疼你。\p"
	.string "那个老傻瓜\n"
	.string "曾经又猛又迷人！\p"
	.string "但那是几十年前的事了。\n"
	.string "现在的他已不复当年之勇了。$"

gFameCheckerFlavorText_ProfOak5:: @ 0x81AD377
	.string "{COLOR 0x08}{SHADOW 0x09}这个人的工作？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}大木博士要有他自己的\n"
	.string "广播节目了。\p"
	.string "这个节目被叫做大木博士\n"
	.string "的宝可梦大讲堂。$"

gFameCheckerFlavorText_Daisy0:: @ 0x81AD40C
	.string "{COLOR 0x08}{SHADOW 0x09}这个人是干什么的？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}如果你把你的宝可梦给娜娜妹看，\n"
	.string "她会告诉你宝可梦喜欢你的程度，\p"
	.string "有时候，她甚至会帮你的\n"
	.string "宝可梦梳理毛发。$"

gFameCheckerFlavorText_Daisy1:: @ 0x81AD4AE
	.string "{COLOR 0x08}{SHADOW 0x09}这个人怎么样？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}但是我觉得更喜欢\n"
	.string "宝可梦的人是奈奈美。$"

gFameCheckerFlavorText_Daisy2:: @ 0x81AD516
	.string "{COLOR 0x08}{SHADOW 0x09}这个人怎么样？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}她很温柔地照料着宝可梦……\n"
	.string "她真是一个小天使。\p"
	.string "那个小姑娘的名字好像是……\n"
	.string "她好像叫奈奈美。$"

gFameCheckerFlavorText_Daisy3:: @ 0x81AD5A7
	.string "{COLOR 0x08}{SHADOW 0x09}家人和朋友？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}据说，大木博士和他的\n"
	.string "孙子孙女，奈奈美和{B_OPPONENT_MON1_NAME}一起生活。$"

gFameCheckerFlavorText_Daisy4:: @ 0x81AD608
	.string "{COLOR 0x08}{SHADOW 0x09}这个人怎么样？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}一个从真新镇来的小女孩，叫奈奈美，\n"
	.string "她每天都要喝茶。\p"
	.string "她经常去玉虹百货公司买茶叶。$"

gFameCheckerFlavorText_Daisy5:: @ 0x81AD69F
	.string "{COLOR 0x08}{SHADOW 0x09}有传闻……\p"
	.string "{COLOR 0x02}{SHADOW 0x03}春季宝可梦华丽大赛的\n"
	.string "总冠军是来自真新镇\l"
	.string "的大木奈奈美！$"

gFameCheckerFlavorText_Brock0:: @ 0x81AD705
	.string "{COLOR 0x08}{SHADOW 0x09}这个人的工作？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}深灰市宝可梦道馆\n"
	.string "馆主：小刚。\l"
	.string "有如磐石般坚硬的宝可梦训练家！$"

gFameCheckerFlavorText_Brock1:: @ 0x81AD771
	.string "{COLOR 0x08}{SHADOW 0x09}最喜欢的宝可梦？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}我，以及我的宝可梦的意志力\n"
	.string "都和岩石一样坚定。\p"
	.string "身体都和岩石一样坚硬，\n"
	.string "没错，\p"
	.string "我的宝可梦\n"
	.string "都是岩石属性的！$"

gFameCheckerFlavorText_Brock2:: @ 0x81AD840
	.string "{COLOR 0x08}{SHADOW 0x09}这个人怎么样？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}这里没有那种很严肃的\n"
	.string "宝可梦训练家。\p"
	.string "他们都打扮得像个捉虫少年，\n"
	.string "你懂的，就是一种癖好。\p"
	.string "可深灰道馆的小刚并不像这样打扮。\n"
	.string "不像，一点都不像。$"

gFameCheckerFlavorText_Brock3:: @ 0x81AD908
	.string "{COLOR 0x08}{SHADOW 0x09}这个人怎么样？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}小刚不仅冷静，还很坚强。\n"
	.string "人们都很喜欢他，尊敬他。\p"
	.string "我想成为像他一样的\n"
	.string "道馆馆主。$"

gFameCheckerFlavorText_Brock4:: @ 0x81AD99A
	.string "{COLOR 0x08}{SHADOW 0x09}这个人的工作？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}嗨，我在月见山\n"
	.string "脚下挖掘化石。\p"
	.string "有时候，深灰道馆的小刚\n"
	.string "会来帮我的忙。$"

gFameCheckerFlavorText_Brock5:: @ 0x81ADA27
	.string "{COLOR 0x08}{SHADOW 0x09}这个人怎么样？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}小刚几乎不笑。但是据说，\n"
	.string "他一笑起来就停不下来。$"

gFameCheckerFlavorText_Misty0:: @ 0x81ADA91
	.string "{COLOR 0x08}{SHADOW 0x09}这个人的工作？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}华蓝市宝可梦道馆\n"
	.string "馆主：小霞。\l"
	.string "男孩子气的美人鱼！$"

gFameCheckerFlavorText_Misty1:: @ 0x81ADAF6
	.string "{COLOR 0x08}{SHADOW 0x09}最喜欢的宝可梦？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}我的战术就是用\n"
	.string "我的水属性宝可梦全力地猛攻！$"

gFameCheckerFlavorText_Misty2:: @ 0x81ADB5A
	.string "{COLOR 0x08}{SHADOW 0x09}这个人怎么样？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}小霞总是不断地提升着自己。\p"
	.string "她是不会输给像你这样的人的。$"

gFameCheckerFlavorText_Misty3:: @ 0x81ADBD9
	.string "{COLOR 0x08}{SHADOW 0x09}有传闻……\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}在这儿经常能看到\n"
	.string "强大的训练家和强大的水属性宝可梦。\p"
	.string "据说华蓝道馆的小霞\n"
	.string "也在这儿训练。$"

gFameCheckerFlavorText_Misty4:: @ 0x81ADC72
	.string "{COLOR 0x08}{SHADOW 0x09}有传闻……\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}这个海角是一个著名的景点。\p"
	.string "道馆馆主小霞也十分\n"
	.string "憧憬着这儿。$"

gFameCheckerFlavorText_Misty5:: @ 0x81ADCEB
	.string "{COLOR 0x08}{SHADOW 0x09}有传闻……\p"
	.string "{COLOR 0x02}{SHADOW 0x03}据说小霞很崇拜\n"
	.string "四天王之一的科拿。$"

gFameCheckerFlavorText_LtSurge0:: @ 0x81ADD3C
	.string "{COLOR 0x08}{SHADOW 0x09}这个人的工作？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}枯叶市宝可梦道馆\n"
	.string "馆主：马志士。\l"
	.string "闪电般的美国人！$"

gFameCheckerFlavorText_LtSurge1:: @ 0x81ADDA7
	.string "{COLOR 0x08}{SHADOW 0x09}最喜欢的宝可梦？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}我告诉你，小子，\n"
	.string "电属性宝可梦在战争中救过我！$"

gFameCheckerFlavorText_LtSurge2:: @ 0x81ADE0B
	.string "{COLOR 0x08}{SHADOW 0x09}这个人怎么样？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}当我在军队的时候，马志士\n"
	.string "是一个严厉的长官。\p"
	.string "他完成任务时总是很卖力。$"

gFameCheckerFlavorText_LtSurge3:: @ 0x81ADE82
	.string "{COLOR 0x08}{SHADOW 0x09}这个人怎么样？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}马志士以前在军队里\n"
	.string "以他的谨慎而出名。$"

gFameCheckerFlavorText_LtSurge4:: @ 0x81ADEEC
	.string "{COLOR 0x08}{SHADOW 0x09}这个人怎么样？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}训练馆的机关\n"
	.string "是马志士亲自安装的。\p"
	.string "他做的机关都是双层的。$"

gFameCheckerFlavorText_LtSurge5:: @ 0x81ADF6A
	.string "{COLOR 0x08}{SHADOW 0x09}有传闻……\p"
	.string "{COLOR 0x02}{SHADOW 0x03}马志士在美国的时候，\n"
	.string "是一名飞行员！\p"
	.string "他用宝可梦发电\n"
	.string "来驱动他的飞机。$"

gFameCheckerFlavorText_Erika0:: @ 0x81AE009
	.string "{COLOR 0x08}{SHADOW 0x09}这个人的工作？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}玉虹市宝可梦道馆\n"
	.string "馆主：莉佳。\l"
	.string "热爱自然的公主！$"

gFameCheckerFlavorText_Erika1:: @ 0x81AE072
	.string "{COLOR 0x08}{SHADOW 0x09}最喜欢的宝可梦？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}我还是一名\n"
	.string "花道师。\p"
	.string "所以我的宝可梦\n"
	.string "全是草属性的。$"

gFameCheckerFlavorText_Erika2:: @ 0x81AE0F3
	.string "{COLOR 0x08}{SHADOW 0x09}这个人怎么样？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}我们的馆主莉佳很文静，\n"
	.string "她在这一带可非常出名。$"

gFameCheckerFlavorText_Erika3:: @ 0x81AE15B
	.string "{COLOR 0x08}{SHADOW 0x09}这个人怎么样？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}我们在道馆里\n"
	.string "只使用草属性宝可梦。\p"
	.string "至于为什么嘛……\n"
	.string "我们也用它们来插花的！$"

gFameCheckerFlavorText_Erika4:: @ 0x81AE1E5
	.string "{COLOR 0x08}{SHADOW 0x09}最喜欢的宝可梦？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}我从不收集\n"
	.string "不可爱的宝可梦。$"

gFameCheckerFlavorText_Erika5:: @ 0x81AE247
	.string "{COLOR 0x08}{SHADOW 0x09}有传闻……\p"
	.string "{COLOR 0x02}{SHADOW 0x03}如果你去偷窥玉虹道馆的话，\n"
	.string "也许你会看到莉佳的睡脸。$"

gFameCheckerFlavorText_Koga0:: @ 0x81AE2B6
	.string "{COLOR 0x08}{SHADOW 0x09}这个人的工作？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}浅红市宝可梦道馆\n"
	.string "馆主：阿桔\l"
	.string "剧毒的忍者之王$"

gFameCheckerFlavorText_Koga1:: @ 0x81AE31D
	.string "{COLOR 0x08}{SHADOW 0x09}最喜欢的宝可梦？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}在毒属性宝可梦带来\n"
	.string "的绝望面前颤抖吧！$"

gFameCheckerFlavorText_Koga2:: @ 0x81AE37D
	.string "{COLOR 0x08}{SHADOW 0x09}这个人怎么样？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}即使我曾经失败过，\n"
	.string "我仍然会跟阿桔继续修炼，\l"
	.string "他是最强的忍者。$"

gFameCheckerFlavorText_Koga3:: @ 0x81AE407
	.string "{COLOR 0x08}{SHADOW 0x09}家人和朋友？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}我父亲是这座城市\n"
	.string "道馆的馆主。\p"
	.string "我日复一日的特训，就是为了成为\n"
	.string "父亲那样的毒属性宝可梦高手。$"

gFameCheckerFlavorText_Koga4:: @ 0x81AE48D
	.string "{COLOR 0x08}{SHADOW 0x09}有传闻……\p"
	.string "{COLOR 0x02}{SHADOW 0x03}阿桔在药材上\n"
	.string "有自己的研究。\p"
	.string "他甚至用自己配的药\n"
	.string "来治疗自己的宝可梦。$"

gFameCheckerFlavorText_Koga5:: @ 0x81AE51B
	.string "{COLOR 0x08}{SHADOW 0x09}这个人的工作？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}你不觉得狩猎地带\n"
	.string "实在是大得吓人吗？\p"
	.string "浅红市的道馆馆主阿桔，\n"
	.string "经常会在狩猎地带里巡逻。\p"
	.string "我们能在这里放心地游玩\n"
	.string "真是多亏了他呢。$"

gFameCheckerFlavorText_Sabrina0:: @ 0x81AE5E8
	.string "{COLOR 0x08}{SHADOW 0x09}这个人的工作？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}金黄市宝可梦道馆\n"
	.string "馆主：娜姿\l"
	.string "超能力属性宝可梦的大师！$"

gFameCheckerFlavorText_Sabrina1:: @ 0x81AE656
	.string "{COLOR 0x08}{SHADOW 0x09}最喜欢宝可梦？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}你认识金黄市的\n"
	.string "道馆馆主吗？\p"
	.string "她擅长使用超能力属性的宝可梦，\n"
	.string "没错吧？$"

gFameCheckerFlavorText_Sabrina2:: @ 0x81AE6D7
	.string "{COLOR 0x08}{SHADOW 0x09}这个人怎么样？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}当我还是个小女孩的时候。\p"
	.string "我拥有了超能力。\p"
	.string "那个早上我拿起汤勺\n"
	.string "使它弯曲了过来。$"

gFameCheckerFlavorText_Sabrina3:: @ 0x81AE762
	.string "{COLOR 0x08}{SHADOW 0x09}这个人怎么样？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}虽然我厌恶暴力，但如果你是认真的，\n"
	.string "我是不会手下留情的！$"

gFameCheckerFlavorText_Sabrina4:: @ 0x81AE7CB
	.string "{COLOR 0x08}{SHADOW 0x09}有传闻……\p"
	.string "{COLOR 0x02}{SHADOW 0x03}人们说娜姿\n"
	.string "在战斗中不用说话，\l"
	.string "就可以与她的宝可梦交流！$"

gFameCheckerFlavorText_Sabrina5:: @ 0x81AE841
	.string "{COLOR 0x08}{SHADOW 0x09}这个人怎么样？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}娜姿轻松地打败了\n"
	.string "隔壁的空手大王。$"

gFameCheckerFlavorText_Blaine0:: @ 0x81AE89E
	.string "{COLOR 0x08}{SHADOW 0x09}这个人的工作？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}红莲镇宝可梦道馆\n"
	.string "馆主：夏伯。\l"
	.string "燃烧的谜题狂人！$"

gFameCheckerFlavorText_Blaine1:: @ 0x81AE90A
	.string "{COLOR 0x08}{SHADOW 0x09}最喜欢的宝可梦？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}我炽烈的宝可梦都\n"
	.string "狂野而富有热情！\p"
	.string "它们会把所有的挑战者燃烧殆尽！$"

gFameCheckerFlavorText_Blaine2:: @ 0x81AE990
	.string "{COLOR 0x08}{SHADOW 0x09}最喜欢的宝可梦？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}我们的馆主，夏伯在山里迷路了，\n"
	.string "但幸运的是，\p"
	.string "当夜幕降临的时候，\n"
	.string "一只灼热的鸟宝可梦降临在他面前。\p"
	.string "它发出的光使\n"
	.string "夏伯找到了下山的路。$"

gFameCheckerFlavorText_Blaine3:: @ 0x81AEA59
	.string "{COLOR 0x08}{SHADOW 0x09}这个人怎么样？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}红莲道馆的夏伯\n"
	.string "很古怪！\p"
	.string "自从实验室建立以来\n"
	.string "他就一直住在岛上。$"

gFameCheckerFlavorText_Blaine4:: @ 0x81AEAEE
	.string "{COLOR 0x08}{SHADOW 0x09}家人和朋友？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}这张照片上的人是夏伯和\n"
	.string "富士老人。\p"
	.string "他们咧着嘴笑着，\n"
	.string "肩并肩的站在一起。$"

gFameCheckerFlavorText_Blaine5:: @ 0x81AEB69
	.string "{COLOR 0x08}{SHADOW 0x09}有传闻……\p"
	.string "{COLOR 0x02}{SHADOW 0x03}夏伯只有在想出谜题的答案时，\n"
	.string "才会摘下他的墨镜。$"

gFameCheckerFlavorText_Lorelei0:: @ 0x81AEBDF
	.string "{COLOR 0x08}{SHADOW 0x09}这个人的工作？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}我是四天王中的科拿。$"

gFameCheckerFlavorText_Lorelei1:: @ 0x81AEC28
	.string "{COLOR 0x08}{SHADOW 0x09}最喜欢的宝可梦？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}没有人比我更会使用\n"
	.string "冰属性的宝可梦。$"

gFameCheckerFlavorText_Lorelei2:: @ 0x81AEC82
	.string "{COLOR 0x08}{SHADOW 0x09}这人的出身地在哪？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}有一个伟大的训练家在这里长大。\n"
	.string "我猜你已经知道她是谁了。\l"
	.string "没错，\n"
	.string "她就是四天王的科拿！$"

gFameCheckerFlavorText_Lorelei3:: @ 0x81AED27
	.string "{COLOR 0x08}{SHADOW 0x09}这是个怎么样的人？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}她以缜密的计算和渊博的知识闻名\n"
	.string "而且有着超酷的战斗风格，\l"
	.string "但科拿却有个天大的秘密！$"

gFameCheckerFlavorText_Lorelei4:: @ 0x81AEDAA
	.string "{COLOR 0x08}{SHADOW 0x09}这是个怎么样的人？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}你知道科拿有许多许多\n"
	.string "的毛绒娃娃吗？\p"
	.string "每次她回四之岛，\n"
	.string "她的收藏都会增加！$"

gFameCheckerFlavorText_Lorelei5:: @ 0x81AEE51
	.string "{COLOR 0x08}{SHADOW 0x09}最喜欢的宝可梦？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}我猜她的拉普拉斯就是那只\n"
	.string "她在很小时候就遇到的宝可梦。\p"
	.string "我想她是在冻瀑洞窟\n"
	.string "收服到拉普拉斯的。\p"
	.string "可能从那时起那只宝可梦\n"
	.string "就一直陪伴着她。$"

gFameCheckerFlavorText_Bruno0:: @ 0x81AEF25
	.string "{COLOR 0x08}{SHADOW 0x09}这人是做什么的？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}我就是四天王中的希巴！$"

gFameCheckerFlavorText_Bruno1:: @ 0x81AEF6C
	.string "{COLOR 0x08}{SHADOW 0x09}最喜欢的宝可梦？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}我就是靠着这股信念\n"
	.string "和宝可梦一起生活一起训练！$"

gFameCheckerFlavorText_Bruno2:: @ 0x81AEFC6
	.string "{COLOR 0x08}{SHADOW 0x09}这是个怎么样的人？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}希巴参加四天王\n"
	.string "只是因为他的内心强烈地想要\l"
	.string "跟强大的训练家比试。$"

gFameCheckerFlavorText_Bruno3:: @ 0x81AF04C
	.string "{COLOR 0x08}{SHADOW 0x09}这是个怎么样的人？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}我的一个前辈叫做希巴。\n"
	.string "有时会他会和他的宝可梦\p"
	.string "一起来到这个温泉，\n"
	.string "在这里做水疗。$"

gFameCheckerFlavorText_Bruno4:: @ 0x81AF0F0
	.string "{COLOR 0x08}{SHADOW 0x09}有传闻……\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}据说他叫希巴。\n"
	.string "还是四天王之一。\p"
	.string "他得知兄弟俩的愤怒馒头\n"
	.string "全部卖光后，\l"
	.string "就失望地离开了。$"

gFameCheckerFlavorText_Bruno5:: @ 0x81AF19A
	.string "{COLOR 0x08}{SHADOW 0x09}家庭和朋友？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}甚至是希巴……\n"
	.string "他之前和一个叫做藤树\l"
	.string "的小伙子一起训练。$"

gFameCheckerFlavorText_Agatha0:: @ 0x81AF200
	.string "{COLOR 0x08}{SHADOW 0x09}这人是做什么的？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}我是四天王之一菊子。$"

gFameCheckerFlavorText_Agatha1:: @ 0x81AF248
	.string "{COLOR 0x08}{SHADOW 0x09}最喜欢的宝可梦？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}菊子的幽灵属性宝可梦\n"
	.string "真的强大得恐怖。$"

gFameCheckerFlavorText_Agatha2:: @ 0x81AF2B7
	.string "{COLOR 0x08}{SHADOW 0x09}这是个怎么样的人？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}那个老太太的脾气\n"
	.string "也不太好。\p"
	.string "我可没有说那个老太太\n"
	.string "什么坏话啊！$"

gFameCheckerFlavorText_Agatha3:: @ 0x81AF34E
	.string "{COLOR 0x08}{SHADOW 0x09}有传闻……\p"
	.string "{COLOR 0x02}{SHADOW 0x03}在她年轻的时候，菊子和大木博士\n"
	.string "都是强大的训练家\l"
	.string "而且还是一对劲敌。$"

gFameCheckerFlavorText_Agatha4:: @ 0x81AF3BE
	.string "{COLOR 0x08}{SHADOW 0x09}家庭和朋友？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}孩子我听说大木\n"
	.string "相当疼爱你。\p"
	.string "那个老傻瓜\n"
	.string "曾经又猛又迷人！\p"
	.string "但是，这只是几十年前的事了，\n"
	.string "现在的他已不复当年之勇了。$"

gFameCheckerFlavorText_Agatha5:: @ 0x81AF47C
	.string "{COLOR 0x08}{SHADOW 0x09}这是个怎么样的人？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}就拿菊子举个例子吧。\p"
	.string "她创下了历代最老四天王的记录。\n"
	.string "历代最老四天王的记录。$"

gFameCheckerFlavorText_Lance0:: @ 0x81AF4FD
	.string "{COLOR 0x08}{SHADOW 0x09}这人是做什么的？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}我是四天王的首领。\p"
	.string "你可以称呼我为龙之训练家，\n"
	.string "阿渡。$"

gFameCheckerFlavorText_Lance1:: @ 0x81AF567
	.string "{COLOR 0x08}{SHADOW 0x09}最喜欢的宝可梦？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}你应该知道龙是\n"
	.string "神圣传说中的宝可梦。\p"
	.string "它们很难收服和饲养，\n"
	.string "但只要培育得好，\p"
	.string "它们几乎坚不可摧。\n"
	.string "一般的攻击对它们是没有用的。$"

gFameCheckerFlavorText_Lance2:: @ 0x81AF641
	.string "{COLOR 0x08}{SHADOW 0x09}这是个怎么样的人？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}他就是正义的化身！\n"
	.string "而且冷静又富有激情！\l"
	.string "阿渡先生是最棒的！$"

gFameCheckerFlavorText_Lance3:: @ 0x81AF6BA
	.string "{COLOR 0x08}{SHADOW 0x09}有传闻……\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}我们有个偶尔会来光顾的客人，\n"
	.string "就是阿渡。\p"
	.string "他总是来买披风。\p"
	.string "我很想知道……他家里是不是有很多\n"
	.string "一模一样的披风？$"

gFameCheckerFlavorText_Lance4:: @ 0x81AF758
	.string "{COLOR 0x08}{SHADOW 0x09}家庭和朋友？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}据说阿渡的祖父是\n"
	.string "一个有名的龙使者家族里的\l"
	.string "一位长老。$"

gFameCheckerFlavorText_Lance5:: @ 0x81AF7CB
	.string "{COLOR 0x08}{SHADOW 0x09}家庭和朋友？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}我曾经听说过，\n"
	.string "阿渡是一位离这里很远的\l"
	.string "道馆馆主的表哥。$"

gFameCheckerFlavorText_Bill0:: @ 0x81AF83E
	.string "{COLOR 0x08}{SHADOW 0x09}这人是做什么的？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}总之，正辉是一个闻名全球的\n"
	.string "宝可梦狂。\p"
	.string "他发明了电脑上的\n"
	.string "宝可梦储存系统。$"

gFameCheckerFlavorText_Bill1:: @ 0x81AF8CA
	.string "{COLOR 0x08}{SHADOW 0x09}最喜欢的宝可梦？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}正辉有很多的宝可梦！\n"
	.string "他甚至收藏了非常珍贵的品种！$"

gFameCheckerFlavorText_Bill2:: @ 0x81AF929
	.string "{COLOR 0x08}{SHADOW 0x09}这是个怎么样的人？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}他是我的孙子！\p"
	.string "他从小时候已经\n"
	.string "开始收集不同的东西！$"

gFameCheckerFlavorText_Bill3:: @ 0x81AF998
	.string "{COLOR 0x08}{SHADOW 0x09}最喜欢的宝可梦？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}正辉是一个宝可梦狂，\n"
	.string "所以他每一种都喜欢。\p"
	.string "不过，他第一只抓的\n"
	.string "应该是凯西。$"

gFameCheckerFlavorText_Bill4:: @ 0x81AFA20
	.string "{COLOR 0x08}{SHADOW 0x09}家庭和朋友？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}正辉在满金市出生，\n"
	.string "他的家人现在还住在那里。\p"
	.string "我有听说过那是一个\n"
	.string "很热闹，很忙碌的城市。$"

gFameCheckerFlavorText_Bill5:: @ 0x81AFAB9
	.string "{COLOR 0x08}{SHADOW 0x09}这里有一个传言…\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}听说，正辉他对\n"
	.string "牛奶过敏。$"

gFameCheckerFlavorText_MrFuji0:: @ 0x81AFB0C
	.string "{COLOR 0x08}{SHADOW 0x09}这人是做什么的？\p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}他很善良。\p"
	.string "他常常照顾那些\n"
	.string "被遗弃的宝可梦。$"

gFameCheckerFlavorText_MrFuji1:: @ 0x81AFB76
	.string "{COLOR 0x08}{SHADOW 0x09}这是个怎么样的人？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}这老人气冲冲的冲到\n"
	.string "我们的秘密基地。\p"
	.string "然后，他开始唠叨我们\n"
	.string "火箭队滥用宝可梦的行为。\p"
	.string "所以我们来了一场\n"
	.string "用成年人的方式进行的谈话。$"

gFameCheckerFlavorText_MrFuji2:: @ 0x81AFC38
	.string "{COLOR 0x08}{SHADOW 0x09}这是个怎么样的人？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}宝可梦爱好者杂志\n"
	.string "那有着丰富奖品的“每日抽奖”！\p"
	.string "那个申请表格……\p"
	.string "没了！它被剪走了。\n"
	.string "一定是已经被人拿去填了。$"

gFameCheckerFlavorText_MrFuji3:: @ 0x81AFCE9
	.string "{COLOR 0x08}{SHADOW 0x09}有传闻……\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}我听说富士老人不是\n"
	.string "我们本地人。$"

gFameCheckerFlavorText_MrFuji4:: @ 0x81AFD49
	.string "{COLOR 0x08}{SHADOW 0x09}家庭和朋友？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}这是一张夏伯和\n"
	.string "富士老人的照片。\p"
	.string "他们咧着嘴笑着\n"
	.string "肩并肩的站在一起。$"

gFameCheckerFlavorText_MrFuji5:: @ 0x81AFDC4
	.string "{COLOR 0x08}{SHADOW 0x09}这是个怎么样的人？\p"
	.string "{COLOR 0x02}{SHADOW 0x03}编辑：那位害羞的富士老人拒绝了\n"
	.string "我们的采访请求。\p"
	.string "他是一位在紫苑镇里\n"
	.string "受到尊敬的仁慈的人。$"

gFameCheckerFlavorText_Giovanni0:: @ 0x81AFE68
	.string "{COLOR 0x08}{SHADOW 0x09}这人是做什么的？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}火箭队从世界各地\n"
	.string "抓捕宝可梦。\p"
	.string "它们对我们的\n"
	.string "犯罪事业很重要。\p"
	.string "而我就是他们的首领，坂木！$"

gFameCheckerFlavorText_Giovanni1:: @ 0x81AFF23
	.string "{COLOR 0x08}{SHADOW 0x09}最喜欢的宝可梦？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}那些混蛋占领\n"
	.string "了我们的大厦……\p"
	.string "他们的头目说他在找寻\n"
	.string "强大的宝可梦。$"

gFameCheckerFlavorText_Giovanni2:: @ 0x81AFFA8
	.string "{COLOR 0x08}{SHADOW 0x09}这是个怎么样的人？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}火箭队的头目\n"
	.string "是一个特别残忍的人！\p"
	.string "对于他来说，宝可梦只是一个\n"
	.string "可以被利用的工具。$"

gFameCheckerFlavorText_Giovanni3:: @ 0x81B0022
	.string "{COLOR 0x08}{SHADOW 0x09}这人是做什么的？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}欢迎来到我的秘密基地。\p"
	.string "在火箭队恢复往日的荣光之前，\n"
	.string "我只能这么做。$"

gFameCheckerFlavorText_Giovanni4:: @ 0x81B00A6
	.string "{COLOR 0x08}{SHADOW 0x09}这人是做什么的？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}难以置信！坂木是\n"
	.string "常青的道馆馆主？$"

gFameCheckerFlavorText_Giovanni5:: @ 0x81B0106
	.string "{COLOR 0x08}{SHADOW 0x09}家庭和朋友？\p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}你……你莫非是坂木的孩子？\n"
	.string "我没说错吧？\p"
	.string "不，我认错了。\n"
	.string "坂木的孩子是红头发。$"


gFameCheckerPersonName_ProfOak:: @ 0x81B0188
	.string "{COLOR 0x08}{SHADOW 0x09}大木博士$"

gFameCheckerPersonQuote_ProfOak:: @ 0x81B0198
	.string "{COLOR 0x08}{SHADOW 0x09}大木博士 (寄) \n"
	.string "{PLAYER} (收) \p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}为什么宝可梦会为你\n"
	.string "这么努力地互相竞争和战斗？\p"
	.string "这是因为它们看到\n"
	.string "你对宝可梦的\l"
	.string "信任和爱\p"
	.string "千万不要忘记了。$"

gFameCheckerPersonName_Daisy:: @ 0x81B0251
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}奈奈美$"

gFameCheckerPersonQuote_Daisy:: @ 0x81B025D
	.string "{COLOR 0x08}{SHADOW 0x09}奈奈美 (寄) \n"
	.string "{PLAYER} (收) \p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}当我在舒适地享受\n"
	.string "我的下午茶的时候，你变得\l"
	.string "更有经验，更为强大了。\p"
	.string "希望你能够继续作为\n"
	.string "我弟弟的一个很好的竞争对手。$"

gFameCheckerPersonName_Brock:: @ 0x81B030F
	.string "{COLOR 0x08}{SHADOW 0x09}小刚$"

gFameCheckerPersonQuote_Brock:: @ 0x81B031B
	.string "{COLOR 0x08}{SHADOW 0x09}小刚 (寄) \n"
	.string "{PLAYER} (收) \p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}在我们这个广阔的世界上\n"
	.string "一定还有更强大的训练家的。\p"
	.string "让我们一起努力训练\n"
	.string "然后变得更强吧！$"

gFameCheckerPersonName_Misty:: @ 0x81B03B3
	.string "{COLOR 0x08}{SHADOW 0x09}小霞$"

gFameCheckerPersonQuote_Misty:: @ 0x81B03BF
	.string "{COLOR 0x08}{SHADOW 0x09}小霞 (寄) \n"
	.string "{PLAYER} (收) \p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}我会留在道馆里\n"
	.string "继续训练的。\p"
	.string "当我变得更强后\n"
	.string "我想我会尝试去旅行。$"

gFameCheckerPersonName_LtSurge:: @ 0x81B0446
	.string "{COLOR 0x08}{SHADOW 0x09}马志士$"

gFameCheckerPersonQuote_LtSurge:: @ 0x81B0456
	.string "{COLOR 0x08}{SHADOW 0x09}马志士 (寄) \n"
	.string "{PLAYER} (收) \p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}哟，小鬼！\n"
	.string "在我们的战斗间你令我吃了一惊！\p"
	.string "我从来没有看到过\n"
	.string "像你这般有勇气的训练家。\p"
	.string "它令我改变了\n"
	.string "我对你的印象！$"

gFameCheckerPersonName_Erika:: @ 0x81B0504
	.string "{COLOR 0x08}{SHADOW 0x09}莉佳$"

gFameCheckerPersonQuote_Erika:: @ 0x81B0510
	.string "{COLOR 0x08}{SHADOW 0x09}莉佳 (寄) \n"
	.string "{PLAYER} (收) \p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}有你这样强大的\n"
	.string "训练家我真是太高兴了。\p"
	.string "这成为激励着我\n"
	.string "去加倍努力的动力。\p"
	.string "请你要再来喔。\n"
	.string "Zzz…$"

gFameCheckerPersonName_Koga:: @ 0x81B05C2
	.string "{COLOR 0x08}{SHADOW 0x09}阿桔$"

gFameCheckerPersonQuote_Koga:: @ 0x81B05CD
	.string "{COLOR 0x08}{SHADOW 0x09}阿桔 (寄) \n"
	.string "{PLAYER} (收) \p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}你和我，都把目标定得长远，\n"
	.string "同时努力修行去\l"
	.string "达到我们的目标。\p"
	.string "现在，我得去和我的女儿进行培训了。$"

gFameCheckerPersonName_Sabrina:: @ 0x81B0667
	.string "{COLOR 0x08}{SHADOW 0x09}娜姿$"

gFameCheckerPersonQuote_Sabrina:: @ 0x81B0675
	.string "{COLOR 0x08}{SHADOW 0x09}娜姿 (寄) \n"
	.string "{PLAYER} (收) \p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}你和你的\n"
	.string "宝可梦之间的爱…\p"
	.string "这是一种永远不会被\n"
	.string "我的超能力打败的力量。$"

gFameCheckerPersonName_Blaine:: @ 0x81B06FB
	.string "{COLOR 0x08}{SHADOW 0x09}夏伯$"

gFameCheckerPersonQuote_Blaine:: @ 0x81B0708
	.string "{COLOR 0x08}{SHADOW 0x09}夏伯 (寄) \n"
	.string "{PLAYER} (收) \p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}我的火属性宝可梦！\n"
	.string "它们会越来越强的！\p"
	.string "好吧，回答我的问题。共有多少种\n"
	.string "已知的火属性宝可梦？$"

gFameCheckerPersonName_Lorelei:: @ 0x81B079F
	.string "{COLOR 0x08}{SHADOW 0x09}科拿$"

gFameCheckerPersonQuote_Lorelei:: @ 0x81B07AD
	.string "{COLOR 0x08}{SHADOW 0x09}科拿 (寄) \n"
	.string "{PLAYER} (收) \p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}我要感谢\n"
	.string "你的帮忙。\p"
	.string "不过别想我下次\n"
	.string "跟你战斗会手下留情。\p"
	.string "下次战斗的时候小心为上！$"

gFameCheckerPersonName_Bruno:: @ 0x81B0845
	.string "{COLOR 0x08}{SHADOW 0x09}希巴$"

gFameCheckerPersonQuote_Bruno:: @ 0x81B0851
	.string "{COLOR 0x08}{SHADOW 0x09}希巴 (寄) \n"
	.string "{PLAYER} (收) \p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}你和你的宝可梦的\n"
	.string "超强战斗力我已经领教过了。\p"
	.string "也许，下次让我给你看看\n"
	.string "我是怎么样训练自己的。$"

gFameCheckerPersonName_Agatha:: @ 0x81B08EE
	.string "{COLOR 0x08}{SHADOW 0x09}菊子$"

gFameCheckerPersonQuote_Agatha:: @ 0x81B08FB
	.string "{COLOR 0x08}{SHADOW 0x09}菊子 (寄) \n"
	.string "{PLAYER} (收) \p"
	.string "{FONT_FEMALE}{COLOR 0x02}{SHADOW 0x03}当你变老了的时候\n"
	.string "你不要做大木一样的烂老头啊！\p"
	.string "要学我一直保持着去战斗！$"

gFameCheckerPersonName_Lance:: @ 0x81B097F
	.string "{COLOR 0x08}{SHADOW 0x09}阿渡$"

gFameCheckerPersonQuote_Lance:: @ 0x81B098B
	.string "{COLOR 0x08}{SHADOW 0x09}阿渡 (寄) \n"
	.string "{PLAYER} (收) \p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}我现在在考虑\n"
	.string "返回我的故乡。\p"
	.string "我想去再训练我的龙属性\n"
	.string "宝可梦并加强它们的战斗力。\n"
	.string "希望我有一天\n"
	.string "能正式邀请你到我家乡看看。$"

gFameCheckerPersonName_Bill:: @ 0x81B0A45
	.string "{COLOR 0x08}{SHADOW 0x09}正辉$"

gFameCheckerPersonQuote_Bill:: @ 0x81B0A50
	.string "{COLOR 0x08}{SHADOW 0x09}正辉 (寄) \n"
	.string "{PLAYER} (收) \p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}哟，好久不见！阿锦除了夸你之外\n"
	.string "再没有做过其它的什么了。\p"
	.string "我听到后感到非常的高兴。\p"
	.string "当你抓到珍贵的宝可梦时，\n"
	.string "记得要带来让我看，可以吗？约好了哦！$"

gFameCheckerPersonName_MrFuji:: @ 0x81B0AFF
	.string "{COLOR 0x08}{SHADOW 0x09}富士老人$"

gFameCheckerPersonQuote_MrFuji:: @ 0x81B0B0E
	.string "{COLOR 0x08}{SHADOW 0x09}富士老人 (寄) \n"
	.string "{PLAYER} (收) \p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}除了为你自己的宝可梦\n"
	.string "祈求幸福外……\p"
	.string "……我能请求你替\n"
	.string "所有的宝可梦祈求幸福吗？$"

gFameCheckerPersonName_Giovanni:: @ 0x81B0BA6
	.string "{COLOR 0x08}{SHADOW 0x09}坂木$"

gFameCheckerPersonQuote_Giovanni:: @ 0x81B0BB5
	.string "{COLOR 0x08}{SHADOW 0x09}坂木 (寄) \n"
	.string "{PLAYER} (收) \p"
	.string "{FONT_MALE}{COLOR 0x02}{SHADOW 0x03}我没有什么\n"
	.string "要跟你说的。\p"
	.string "我只要专于继续令自己变强，\n"
	.string "也就没有其它的什么了。$"

gFameCheckerFlavorTextOriginLocation_ProfOak0:: @ 0x81B0C45
	.string "真新镇$"

gFameCheckerFlavorTextOriginLocation_ProfOak1::
	.string "研究所$"

gFameCheckerFlavorTextOriginLocation_ProfOak2::
	.string "研究所$"

gFameCheckerFlavorTextOriginLocation_ProfOak3::
	.string "常青市$"

gFameCheckerFlavorTextOriginLocation_ProfOak4::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_ProfOak5::
	.string "研究所$"

gFameCheckerFlavorTextOriginLocation_Daisy0::
	.string "研究所$"

gFameCheckerFlavorTextOriginLocation_Daisy1::
	.string "枯叶市$"

gFameCheckerFlavorTextOriginLocation_Daisy2::
	.string "水之迷宫$"

gFameCheckerFlavorTextOriginLocation_Daisy3::
	.string "常青市$"

gFameCheckerFlavorTextOriginLocation_Daisy4::
	.string "玉虹大厦$"

gFameCheckerFlavorTextOriginLocation_Daisy5::
	.string "四之岛$"

gFameCheckerFlavorTextOriginLocation_Brock0::
	.string "深灰市$"

gFameCheckerFlavorTextOriginLocation_Brock1::
	.string "深灰道馆$"

gFameCheckerFlavorTextOriginLocation_Brock2::
	.string "深灰市$"

gFameCheckerFlavorTextOriginLocation_Brock3::
	.string "4号道路$"

gFameCheckerFlavorTextOriginLocation_Brock4::
	.string "月见山$"

gFameCheckerFlavorTextOriginLocation_Brock5::
	.string "深灰博物馆$"

gFameCheckerFlavorTextOriginLocation_Misty0::
	.string "华蓝市$"

gFameCheckerFlavorTextOriginLocation_Misty1::
	.string "华蓝道馆$"

gFameCheckerFlavorTextOriginLocation_Misty2::
	.string "华蓝道馆$"

gFameCheckerFlavorTextOriginLocation_Misty3::
	.string "双子岛$"

gFameCheckerFlavorTextOriginLocation_Misty4::
	.string "华蓝之岬$"

gFameCheckerFlavorTextOriginLocation_Misty5::
	.string "华蓝市$"

gFameCheckerFlavorTextOriginLocation_LtSurge0::
	.string "枯叶市$"

gFameCheckerFlavorTextOriginLocation_LtSurge1::
	.string "枯叶道馆$"

gFameCheckerFlavorTextOriginLocation_LtSurge2::
	.string "枯叶道馆$"

gFameCheckerFlavorTextOriginLocation_LtSurge3::
	.string "枯叶道馆$"

gFameCheckerFlavorTextOriginLocation_LtSurge4::
	.string "枯叶道馆$"

gFameCheckerFlavorTextOriginLocation_LtSurge5::
	.string "枯叶市$"

gFameCheckerFlavorTextOriginLocation_Erika0::
	.string "玉虹市$"

gFameCheckerFlavorTextOriginLocation_Erika1::
	.string "玉虹道馆$"

gFameCheckerFlavorTextOriginLocation_Erika2::
	.string "玉虹道馆$"

gFameCheckerFlavorTextOriginLocation_Erika3::
	.string "玉虹道馆$"

gFameCheckerFlavorTextOriginLocation_Erika4::
	.string "玉虹道馆$"

gFameCheckerFlavorTextOriginLocation_Erika5::
	.string "玉虹大厦$"

gFameCheckerFlavorTextOriginLocation_Koga0::
	.string "浅红市$"

gFameCheckerFlavorTextOriginLocation_Koga1::
	.string "浅红道馆$"

gFameCheckerFlavorTextOriginLocation_Koga2::
	.string "浅红道馆$"

gFameCheckerFlavorTextOriginLocation_Koga3::
	.string "浅红市$"

gFameCheckerFlavorTextOriginLocation_Koga4::
	.string "浅红市$"

gFameCheckerFlavorTextOriginLocation_Koga5::
	.string "狩猎地带$"

gFameCheckerFlavorTextOriginLocation_Sabrina0::
	.string "金黄市$"

gFameCheckerFlavorTextOriginLocation_Sabrina1::
	.string "三之岛$"

gFameCheckerFlavorTextOriginLocation_Sabrina2::
	.string "金黄道馆$"

gFameCheckerFlavorTextOriginLocation_Sabrina3::
	.string "金黄道馆$"

gFameCheckerFlavorTextOriginLocation_Sabrina4::
	.string "金黄市$"

gFameCheckerFlavorTextOriginLocation_Sabrina5::
	.string "金黄道馆$"

gFameCheckerFlavorTextOriginLocation_Blaine0::
	.string "红莲镇$"

gFameCheckerFlavorTextOriginLocation_Blaine1::
	.string "红莲道馆$"

gFameCheckerFlavorTextOriginLocation_Blaine2::
	.string "红莲道馆$"

gFameCheckerFlavorTextOriginLocation_Blaine3::
	.string "红莲镇$"

gFameCheckerFlavorTextOriginLocation_Blaine4::
	.string "红莲道馆$"

gFameCheckerFlavorTextOriginLocation_Blaine5::
	.string "高级度假村$"

gFameCheckerFlavorTextOriginLocation_Lorelei0::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Lorelei1::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Lorelei2::
	.string "四之岛$"

gFameCheckerFlavorTextOriginLocation_Lorelei3::
	.string "五之岛$"

gFameCheckerFlavorTextOriginLocation_Lorelei4::
	.string "四之岛$"

gFameCheckerFlavorTextOriginLocation_Lorelei5::
	.string "四之岛$"

gFameCheckerFlavorTextOriginLocation_Bruno0::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Bruno1::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Bruno2::
	.string "金黄市$"

gFameCheckerFlavorTextOriginLocation_Bruno3::
	.string "灯火温泉$"

gFameCheckerFlavorTextOriginLocation_Bruno4::
	.string "二之岛$"

gFameCheckerFlavorTextOriginLocation_Bruno5::
	.string "七宝溪谷$"

gFameCheckerFlavorTextOriginLocation_Agatha0::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Agatha1::
	.string "石英高原$"

gFameCheckerFlavorTextOriginLocation_Agatha2::
	.string "石英高原$"

gFameCheckerFlavorTextOriginLocation_Agatha3::
	.string "七之岛$"

gFameCheckerFlavorTextOriginLocation_Agatha4::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Agatha5::
	.string "六之岛$"

gFameCheckerFlavorTextOriginLocation_Lance0::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Lance1::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Lance2::
	.string "金黄市$"

gFameCheckerFlavorTextOriginLocation_Lance3::
	.string "玉虹百货公司$"

gFameCheckerFlavorTextOriginLocation_Lance4::
	.string "石英高原$"

gFameCheckerFlavorTextOriginLocation_Lance5::
	.string "石英高原$"

gFameCheckerFlavorTextOriginLocation_Bill0::
	.string "华蓝市$"

gFameCheckerFlavorTextOriginLocation_Bill1::
	.string "华蓝市$"

gFameCheckerFlavorTextOriginLocation_Bill2::
	.string "浅红市$"

gFameCheckerFlavorTextOriginLocation_Bill3::
	.string "一之岛$"

gFameCheckerFlavorTextOriginLocation_Bill4::
	.string "一之岛$"

gFameCheckerFlavorTextOriginLocation_Bill5::
	.string "一之岛$"

gFameCheckerFlavorTextOriginLocation_MrFuji0::
	.string "紫苑镇$"

gFameCheckerFlavorTextOriginLocation_MrFuji1::
	.string "宝可梦塔$"

gFameCheckerFlavorTextOriginLocation_MrFuji2::
	.string "紫苑镇$"

gFameCheckerFlavorTextOriginLocation_MrFuji3::
	.string "紫苑镇$"

gFameCheckerFlavorTextOriginLocation_MrFuji4::
	.string "红莲道馆$"

gFameCheckerFlavorTextOriginLocation_MrFuji5::
	.string "红莲镇$"

gFameCheckerFlavorTextOriginLocation_Giovanni0::
	.string "火箭队基地$"

gFameCheckerFlavorTextOriginLocation_Giovanni1::
	.string "西尔佛公司$"

gFameCheckerFlavorTextOriginLocation_Giovanni2::
	.string "西尔佛公司$"

gFameCheckerFlavorTextOriginLocation_Giovanni3::
	.string "常青道馆$"

gFameCheckerFlavorTextOriginLocation_Giovanni4::
	.string "常青道馆$"

gFameCheckerFlavorTextOriginLocation_Giovanni5::
	.string "火箭队仓库$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
	.string "签名$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
	.string "大木博士$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
	.string "助手$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
	.string "宝可梦特刊$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
	.string "菊子$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
	.string "助手$"

gFameCheckerFlavorTextOriginObjectName_Daisy0::
	.string "助手$"

gFameCheckerFlavorTextOriginObjectName_Daisy1::
	.string "女子$"

gFameCheckerFlavorTextOriginObjectName_Daisy2::
	.string "男子$"

gFameCheckerFlavorTextOriginObjectName_Daisy3::
	.string "宝可梦特刊$"

gFameCheckerFlavorTextOriginObjectName_Daisy4::
	.string "老妇人$"

gFameCheckerFlavorTextOriginObjectName_Daisy5::
	.string "宝可梦特刊$"

gFameCheckerFlavorTextOriginObjectName_Brock0::
	.string "签名$"

gFameCheckerFlavorTextOriginObjectName_Brock1::
	.string "小刚$"

gFameCheckerFlavorTextOriginObjectName_Brock2::
	.string "男青年$"

gFameCheckerFlavorTextOriginObjectName_Brock3::
	.string "男孩$"

gFameCheckerFlavorTextOriginObjectName_Brock4::
	.string "男子$"

gFameCheckerFlavorTextOriginObjectName_Brock5::
	.string "宝可梦特刊$"

gFameCheckerFlavorTextOriginObjectName_Misty0::
	.string "签名$"

gFameCheckerFlavorTextOriginObjectName_Misty1::
	.string "小霞$"

gFameCheckerFlavorTextOriginObjectName_Misty2::
	.string "洋平$"

gFameCheckerFlavorTextOriginObjectName_Misty3::
	.string "男青年$"

gFameCheckerFlavorTextOriginObjectName_Misty4::
	.string "夫人$"

gFameCheckerFlavorTextOriginObjectName_Misty5::
	.string "宝可梦特刊$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
	.string "签名$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
	.string "马志士$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
	.string "奥尔森$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
	.string "奥尔森$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
	.string "达彦$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
	.string "宝可梦特刊$"

gFameCheckerFlavorTextOriginObjectName_Erika0::
	.string "签名$"

gFameCheckerFlavorTextOriginObjectName_Erika1::
	.string "莉佳$"

gFameCheckerFlavorTextOriginObjectName_Erika2::
	.string "沙由美$"

gFameCheckerFlavorTextOriginObjectName_Erika3::
	.string "丽子$"

gFameCheckerFlavorTextOriginObjectName_Erika4::
	.string "莉佳$"

gFameCheckerFlavorTextOriginObjectName_Erika5::
	.string "宝可梦特刊$"

gFameCheckerFlavorTextOriginObjectName_Koga0::
	.string "签名$"

gFameCheckerFlavorTextOriginObjectName_Koga1::
	.string "阿桔$"

gFameCheckerFlavorTextOriginObjectName_Koga2::
	.string "乔治$"

gFameCheckerFlavorTextOriginObjectName_Koga3::
	.string "阿杏$"

gFameCheckerFlavorTextOriginObjectName_Koga4::
	.string "宝可梦特刊$"

gFameCheckerFlavorTextOriginObjectName_Koga5::
	.string "男子$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
	.string "签名$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
	.string "男青年$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
	.string "娜姿$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
	.string "娜姿$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
	.string "宝可梦特刊$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
	.string "勇美$"

gFameCheckerFlavorTextOriginObjectName_Blaine0::
	.string "签名$"

gFameCheckerFlavorTextOriginObjectName_Blaine1::
	.string "夏伯$"

gFameCheckerFlavorTextOriginObjectName_Blaine2::
	.string "良明$"

gFameCheckerFlavorTextOriginObjectName_Blaine3::
	.string "女子$"

gFameCheckerFlavorTextOriginObjectName_Blaine4::
	.string "照片$"

gFameCheckerFlavorTextOriginObjectName_Blaine5::
	.string "宝可梦特刊$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
	.string "科拿$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.string "科拿$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.string "老人$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.string "宝可梦特刊$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.string "小女孩$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.string "老妇人$"

gFameCheckerFlavorTextOriginObjectName_Bruno0::
	.string "希巴$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.string "希巴$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.string "宝可梦特刊$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.string "碾碎者$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.string "女子$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.string "碾碎者$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.string "菊子$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.string "碾碎者$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.string "碾碎者$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.string "宝可梦特刊$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.string "菊子$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.string "老妇人$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.string "阿渡$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.string "阿渡$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.string "女子$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.string "小女孩$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.string "宝可梦特刊$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.string "男青年$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.string "小男孩$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.string "老人$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.string "阿锦$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.string "阿锦$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.string "阿锦$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.string "小女孩$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.string "火箭队$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.string "杂志$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.string "男子$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.string "照片$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.string "宝可梦特刊$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.string "坂木$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.string "流浪研究员$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.string "流浪研究员$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.string "坂木$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.string "男子$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.string "纯雄$"

PokemonJournal_Text_SpecialFeatureBrock::
	.string "宝可梦特刊\p"
	.string "专题：深灰道馆\n"
	.string "馆主小刚！\p"
	.string "小刚几乎不怎么笑，\n"
	.string "但是据说他笑起来就停不下。$"

PokemonJournal_Text_SpecialFeatureMisty::
	.string "宝可梦特刊\p"
	.string "专题：华蓝道馆\n"
	.string "馆主小霞！\p"
	.string "据说，小霞很崇拜四天王\n"
	.string "的科拿。$"

PokemonJournal_Text_SpecialFeatureLtSurge::
	.string "宝可梦特刊\p"
	.string "专题：枯叶道馆\n"
	.string "馆主马志士！\p"
	.string "据说马志士在美国做过\n"
	.string "飞行员。\p"
	.string "他用宝可梦所发的电\n"
	.string "驱动飞机。$"

PokemonJournal_Text_SpecialFeatureErika::
	.string "宝可梦特刊\p"
	.string "专题：玉虹道馆\n"
	.string "馆主莉佳！\p"
	.string "据说：如果你经常偷窥玉虹道馆，\n"
	.string "那你就会看到，\l"
	.string "莉佳打瞌睡的情景。$"

PokemonJournal_Text_SpecialFeatureKoga::
	.string "宝可梦特刊\p"
	.string "专题：浅红道馆\n"
	.string "馆主阿桔！\p"
	.string "据说阿桔在医药方面\n"
	.string "有很深厚的知识功底。\p"
	.string "据说他用自己所配的药方\n"
	.string "治疗自己的宝可梦。$"

PokemonJournal_Text_SpecialFeatureSabrina::
	.string "宝可梦特刊\p"
	.string "专题：金黄道馆\n"
	.string "馆主娜姿！\p"
	.string "人们说，娜姿在战斗中，\n"
	.string "可以不动声色地\l"
	.string "用超能力与宝可梦交流。$"

PokemonJournal_Text_SpecialFeatureBlaine::
	.string "宝可梦特刊\p"
	.string "专题：红莲道馆\n"
	.string "馆主夏伯！\p"
	.string "据说夏伯仅仅会在想出\n"
	.string "问题的答案后\l"
	.string "摘下黑眼睛。$"

PokemonJournal_Text_SpecialFeatureLorelei::
	.string "宝可梦特刊\p"
	.string "专题：\n"
	.string "四天王的科拿！\p"
	.string "由于她的强大、有逻辑的头脑，\n"
	.string "以及冷静的对战方式，科拿\l"
	.string "一直都是一个谜！$"

PokemonJournal_Text_SpecialFeatureBruno::
	.string "宝可梦特刊\p"
	.string "专题：\n"
	.string "四天王的希巴！\p"
	.string "显然，希巴加入天王\n"
	.string "四并非为了他的野心，\l"
	.string "而是为了与最强的训练家战斗。$"

PokemonJournal_Text_SpecialFeatureAgatha::
	.string "宝可梦特刊\p"
	.string "专题：\n"
	.string "四天王的菊子！\p"
	.string "在早些年，菊子和博士.\n"
	.string "大木在争夺最强训练家上，\l"
	.string "可是对手呢！$"

PokemonJournal_Text_SpecialFeatureLance::
	.string "宝可梦特刊\p"
	.string "专题：\n"
	.string "四天王的阿渡！\p"
	.string "阿渡的祖父\n"
	.string "是一个龙属性家族\l"
	.string "更加年长的大师。$"

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "宝可梦特刊\p"
	.string "专题：大木博士，\n"
	.string "宝可梦研究者！\p"
	.string "据说大木博士与他的孙子孙女\n"
	.string "{B_OPPONENT_MON1_NAME}和奈奈美一起生活。$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.string "这是一条多年前的\n"
	.string "宝可梦特刊。\p"
	.string "宝可梦特刊\n"
	.string "长官NTEST Special！\p"
	.string "春季宝可梦大赛的总冠军\n"
	.string "是来自真新镇的\l"
	.string "大木奈奈美！$"

PokemonJournal_Text_SpecialFeatureMrFuji::
	.string "宝可梦特刊\p"
	.string "专题：\n"
	.string "宝可梦之家的富士老人！\p"
	.string "编辑：羞涩的富士老人推辞了\n"
	.string "我们的采访。\p"
	.string "他很善良，在紫苑镇\n"
	.string "他很受人喜欢与尊敬。$"
