@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "上面放满了关于\n"
	.string "宝可梦的书。$"

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap::
	.string "一份地图。$"

Text_PokeMartShelf::
	.string "哇喔！\n"
	.string "好多宝可梦娃娃！$"

Text_DishesPlatesNeatlyLinedUp::
	.string "盘子和碗洗得干干净净\n"
	.string "整齐的放在一起。$"

Text_Kitchen::
	.string "有人在这里做饭！\n"
	.string "闻起来真香啊。$"

Text_Dresser::
	.string "一个精美的梳妆台。\n"
	.string "能放得下很多东西。$"

Text_Snacks::
	.string "这里放着许多好吃的点心。$"

Text_PokemartSign::
	.string "您想要的道具应有尽有！\n"
	.string "宝可梦商店$"

Text_PokecenterSign::
	.string "回复宝可梦的体力！\n"
	.string "宝可梦中心$"

Text_Indigo_UltimateGoal::
	.string "石英高原\p"
	.string "训练家的终级目标！\n"
	.string "宝可梦联盟总部$"

Text_Indigo_HighestAuthority::
	.string "石英高原\p"
	.string "宝可梦界的最高权威！\n"
	.string "宝可梦联盟总部$"

Text_Food::
	.string "看起来它把所有好吃的东西\n"
	.string "都装了进去。$"

Text_Blueprints::
	.string "是一张什么东西的设计图。\n"
	.string "上面画满了表格写满了字。$"

Text_Painting::
	.string "是一张宝可梦漂亮的图片。\n"
	.string "看起来它感觉不错。$"

Text_PowerPlantMachine::
	.string "这是某种机器吗！？\n"
	.string "还是别随便乱碰比较好！$"

Text_Telephone::
	.string "是电话。\n"
	.string "最好别去用它。$"

Text_Computer::
	.string "一些既杂乱无章又毫无意义的\n"
	.string "文字和数字……$"

Text_AdvertisingPoster::
	.string "一张关于所有产品的\n"
	.string "广告海报。$"

Text_TastyFood::
	.string "好香的味道！\n"
	.string "肚子都咕咕叫了！$"

Text_TrashBin::
	.string "这里面……\n"
	.string "……\p"
	.string "什么都没有嘛！$"

Text_Cup::
	.string "在这上面全是\n"
	.string "宝可梦的图案。$"

Text_PolishedWindow::
	.string "擦得非常干净的窗子！$"

Text_BeautifulSkyWindow::
	.string "窗户外面……\p"
	.string "天空看起来\n"
	.string "是如此绚丽。$"

Text_BlinkingLights::
	.string "光线一闪一闪地\n"
	.string "变化着颜色。$"

Text_NeatlyLinedUpTools::
	.string "各种各样的道具\n"
	.string "摆放得整整齐齐$"

Text_ImpressiveMachine::
	.string "虽然不知道这是什么机器。\n"
	.string "但是感觉很厉害的样子。$"

Text_VideoGame::
	.string "这是最强的家用机游戏了！\n"
	.string "看起来真好玩！$"

Text_Burglary::
	.string "这儿有一个小偷做的\n"
	.string "很明显的记号……$"

Text_PlayerFacingTVScreen::
	.string "有宝可梦在电视上！\n"
	.string "它们看起来很高兴。$"
