Help_Text_WhatShouldIDo::
	.string "在这种情况下我应该做什么？$"

Help_Text_HowDoIDoThis::
	.string "我要怎样做？$"

Help_Text_WhatDoesThisTermMean::
	.string "这个术语是什么意思？$"

Help_Text_AboutThisGame::
	.string "关于本游戏$"

Help_Text_TypeMatchupList::
	.string "属性相克表$"

Help_Text_Exit::
	.string "退出$"

Help_Text_Cancel::
	.string "取消$"

Help_Text_TryDoingItOnYourOwn::
	.string "じぶんの ちからで やってみよう！$"

Help_Text_DescWhatShouldIDo::
	.string "在战斗中\n"
	.string "获得有利的暗示。$"

Help_Text_DescHowDoIDoThis::
	.string "细节说明是为\n"
	.string "不同的操作所准备的。$"

Help_Text_DescWhatDoesThisTermMean::
	.string "细节描述是给在游戏中\n"
	.string "出现的术语所准备的。$"

Help_Text_DescAboutThisGame::
	.string "在游戏中，可以获得\n"
	.string "细节描述。$"

Help_Text_DescTypeMatchupList::
	.string "列出了\n"
	.string "宝可梦和招式的种类。$"

Help_Text_DescExit::
	.string "按下则退出帮助系统。$"

Help_Text_Greetings::
	.string "嗨！这是帮助系统！\n"
	.string "无论何时何地，遇到问题\l"
	.string "就按下L或R键打开它吧！\l"
	.string "针对不同的情况，帮助的信息也会改变。\l"
	.string "因此，请多多使用帮助系统吧！$"

Help_Text_PlayingForFirstTime::
	.string "我第一玩这个游戏！求助！$"

Help_Text_WhatShouldIBeDoing::
	.string "我应该做什么？$"

Help_Text_CantGetOutOfRoom::
	.string "我不能从房间里出去。$"

Help_Text_CantFindPersonIWant::
	.string "我找不到我想找的人。$"

Help_Text_TalkedToEveryoneNowWhat::
	.string "我不得不和每个人对话。要怎么办？$"

Help_Text_SomeoneBlockingMyWay::
	.string "有人挡在我的路上！$"

Help_Text_ICantGoOn::
	.string "我无法继续了！$"

Help_Text_OutOfThingsToDo::
	.string "我没有事可做了！$"

Help_Text_WhatHappenedToItemIGot::
	.string "我得到的道具有何用处？$"

Help_Text_WhatAreMyAdventureBasics::
	.string "我的冒险的基本知识？$"

Help_Text_HowAreRoadsForestsDifferent::
	.string "路和树林有多大的不同？$"

Help_Text_HowAreCavesDifferent::
	.string "洞穴有何不同？$"

Help_Text_HowDoIProgress::
	.string "我该如何继续？$"

Help_Text_WhenCanIUseItem::
	.string "我何时可以使用物品？$"

Help_Text_WhatsABattle::
	.string "战斗是什么？$"

Help_Text_HowDoIPrepareForBattle::
	.string "我要如何准备战斗？$"

Help_Text_WhatIsAMonsVitality::
	.string "宝可梦的体力是什么？$"

Help_Text_MyMonsAreHurt::
	.string "我的宝可梦受伤了！$"

Help_Text_WhatIsStatusProblem::
	.string "状态是什么？$"

Help_Text_WhatHappensIfAllMyMonsFaint::
	.string "如果我所有宝可梦都倒下了会怎样？$"

Help_Text_CantCatchMons::
	.string "我没有办法收服宝可梦！$"

Help_Text_RanOutOfPotions::
	.string "我没有伤药了！$"

Help_Text_CanIBuyPokeBalls::
	.string "我能买精灵球吗？$"

Help_Text_WhatsATrainer::
	.string "训练家是什么？$"

Help_Text_HowDoIWinAgainstTrainer::
	.string "我如何打赢一个训练家？$"

Help_Text_WhereDoMonsAppear::
	.string "宝可梦在哪儿出现？$"

Help_Text_WhatAreMoves::
	.string "宝可梦的招式是什么？$"

Help_Text_WhatAreHiddenMoves::
	.string "秘传招式是什么？$"

Help_Text_WhatMovesShouldIUse::
	.string "我应该使用什么招式？$"

Help_Text_WantToAddMoreMoves::
	.string "我想增加更多招式。$"

Help_Text_WantToMakeMonStronger::
	.string "我想让我的宝可梦更强大。$"

Help_Text_FoeMonsTooStrong::
	.string "对手的宝可梦太强了！$"

Help_Text_WhatDoIDoInCave::
	.string "在洞穴里我要做什么？$"

Help_Text_NothingIWantToKnow::
	.string "我什么也不想知道！$"

Help_Text_WhatsPokemonCenter::
	.string "宝可梦中心是什么？$"

Help_Text_WhatsPokemonMart::
	.string "宝可梦商店是什么？$"

Help_Text_WantToEndGame::
	.string "我不想结束游戏。$"

Help_Text_WhatsAMon::
	.string "宝可梦是什么？$"

Help_Text_WhatIsThatPersonLike::
	.string "那个人怎么样？$"

Help_Text_WhatDoesHiddenMoveDo::
	.string "一个秘传可以用来干什么？$"

Help_Text_WhatDoIDoInSafari::
	.string "在狩猎地带游戏，我要做什么？$"

Help_Text_WhatAreSafariRules::
	.string "狩猎地带游戏的游戏规则？$"

Help_Text_WantToEndSafari::
	.string "我想结束狩猎地带游戏！$"

Help_Text_WhatIsAGym::
	.string "道馆是什么？$"

Help_Text_AnswerPlayingForFirstTime::
	.string "你就是探索这个\n"
	.string "宝可梦世界的主角。\l"
	.string "通过和人们对话，解决谜题，\l"
	.string "新的道路就将会向你开启！\l"
	.string "与你精心培养的宝可梦\l"
	.string "一起为了目标奋斗吧！$"

Help_Text_AnswerWhatShouldIBeDoing::
	.string "当你看到一个另一个人时，\n"
	.string "走向他们，按下A键。\l"
	.string "就可以与他们对话了。\l"
	.string "以同样的方式，\l"
	.string "你也可以调查不同的道具和物品。\l"
	.string "经常与人们交谈\l"
	.string "从而获得更多情报吧！$"

Help_Text_AnswerCantGetOutOfRoom::
	.string "红色的地毯\n"
	.string "连接着出口的楼梯。\l"
	.string "把主角移动到\l"
	.string "地毯的前面，\l"
	.string "再按下十字键，\l"
	.string "就可以离开这里了。$"

Help_Text_AnswerCantFindPersonIWant::
	.string "这并不是什么\n"
	.string "能让你那么担心的事。\l"
	.string "多与人交谈，检查路标、物品等等。\l"
	.string "有时，你也许需要\l"
	.string "去到一个新的城镇。$"

Help_Text_AnswerTalkedToEveryoneNowWhat::
	.string "尝试向新的城镇、道路\n"
	.string "或者目的地进发吧。$"

Help_Text_AnswerSomeoneBlockingMyWay::
	.string "在城镇里或者大楼内部\n"
	.string "可能会有些要“触发”的东西。\l"
	.string "尝试与那块区域里的人再交流一下。\l"
	.string "如果他们遇到需要解决的问题，\l"
	.string "你就需要帮他们。\l"
	.string "然后，再一次和\l"
	.string "阻挡你前进的人交涉看看。$"

Help_Text_AnswerICantGoOn::
	.string "走向人群，按下A键，\n"
	.string "多和他们说说话吧。\l"
	.string "同样，也对那些小树、岩石\l"
	.string "也按下A键调查看看吧。\l"
	.string "试着按下十字键\l"
	.string "去那些看起来无法到达的地方吧。$"

Help_Text_AnswerOutOfThingsToDo::
	.string "试着去一些\n"
	.string "你还没有去过的地方。\l"
	.string "也要按下A键，\l"
	.string "检查那些看起来可疑的东西。$"

Help_Text_AnswerWhatHappenedToItemIGot::
	.string "所有人给你的道具都会\n"
	.string "放入你的包包。\l"
	.string "并自动归类。\l"
	.string "想要知道怎么用包包的话，\l"
	.string "就参考一下帮助系统的\l"
	.string "“我要怎样做？”吧。$"

Help_Text_AnswerWhatAreMyAdventureBasics::
	.string "如果宝可梦在战斗中受伤，\n"
	.string "就带它们去宝可梦中心，\l"
	.string "让乔伊治好它们。\l"
	.string "养成经常存档的习惯。\l"
	.string "要到很远的地方旅行时，\l"
	.string "到宝可梦商店准备够需要的道具吧。$"

Help_Text_AnswerHowAreRoadsForestsDifferent::
	.string "森林基本上和道路一样，\n"
	.string "但它们更像迷宫。\l"
	.string "所有的森林都有出去的路，\l"
	.string "所以就算迷路了也不要放弃。$"

Help_Text_AnswerHowAreCavesDifferent::
	.string "洞穴很阴暗，很危险。\n"
	.string "野生的宝可梦在其中无处不在。\l"
	.string "如果有紧急情况，\l"
	.string "就快去宝可梦中心或者使用道具。\l"
	.string "新的城镇就在那些洞穴外，\l"
	.string "所以不要放弃。$"

Help_Text_AnswerHowDoIProgress::
	.string "游戏的目的是训练宝可梦\n"
	.string "并且继续朝更远的目标迈进。\l"
	.string "你一定要收集情报，解决问题。\l"
	.string "比如说，如果你想回避障碍物，\l"
	.string "想想你都需要些什么？\l"
	.string "怎样把挡在路上的人\l"
	.string "支开？$"

Help_Text_AnswerWhenCanIUseItem::
	.string "道具分为好几类。\n"
	.string "有些只能在战斗外使用。\l"
	.string "有些只能在战斗中使用。\l"
	.string "有些可以在任何情况下使用。\l"
	.string "经常使用道具吧！\l"
	.string "但如果不能使用的话，\l"
	.string "你就要注意了。$"

Help_Text_AnswerWhatsABattle::
	.string "对战中宝可梦需要尽力消耗\n"
	.string "对方的HP。\l"
	.string "如果宝可梦的HP归零，\l"
	.string "它就倒下了。同时另一者的宝可梦\l"
	.string "就赢了。赢得战斗的同时，\l"
	.string "宝可梦也获得可以让他们\l"
	.string "等级上升的经验值！$"

Help_Text_AnswerHowDoIPrepareForBattle::
	.string "首先，在任何一间宝可梦中心\n"
	.string "都能完全治疗你的队伍中的宝可梦。\l"
	.string "你也要在宝可梦商店买道具\l"
	.string "来应对紧急状况。$"

Help_Text_AnswerWhatIsAMonsVitality::
	.string "一只宝可梦的生命值就是HP。\n"
	.string "如果宝可梦在对战中受伤，\l"
	.string "HP就会减少。\l"
	.string "如果HP归零，它就倒下了。\l"
	.string "用道具或者去宝可梦中心\l"
	.string "治疗宝可梦吧。$"

Help_Text_AnswerMyMonsAreHurt::
	.string "一个宝可梦中心就像是\n"
	.string "宝可梦的小旅馆。\l"
	.string "那儿的治疗机，会完全治疗宝可梦的\l"
	.string "异常状态和HP。\l"
	.string "而且免费！\l"
	.string "所以养成常去那里的习惯吧。$"

Help_Text_AnswerWhatIsStatusProblem::
	.string "异常状态是由对方的攻击\n"
	.string "导致宝可梦出现的小毛病。\l"
	.string "它们包括灼伤，\l"
	.string "麻痹、中毒、沉睡，以及冰冻。\l"
	.string "可以去宝可梦中心\l"
	.string "或者使用道具治疗。$"

Help_Text_AnswerWhatHappensIfAllMyMonsFaint::
	.string "如果你携带的宝可梦倒下了，\l"
	.string "你就会输掉金钱，\l"
	.string "并回到家或者是宝可梦中心。\l"
	.string "为了少让那种事发生，\l"
	.string "多去宝可梦中心吧。\l"
	.string "也要养成治疗它们的习惯。$"

Help_Text_AnswerCantCatchMons::
	.string "如果野生宝可梦从精灵球中挣脱，\n"
	.string "说明它还有体力。\l"
	.string "尝试再削弱它的HP，\l"
	.string "或者是在抓它之前，\l"
	.string "让它陷入麻痹或者睡眠状态。\l"
	.string "如果精灵球摇动一会儿，\l"
	.string "说明你快得手了。$"

Help_Text_AnswerRanOutOfPotions::
	.string "有一些像宝可梦商店\n"
	.string "贩卖道具这样的地方。\l"
	.string "在街道、洞穴或者森林里，\l"
	.string "你将找不到宝可梦商店的身影。\l"
	.string "当你去一个拥有宝可梦商店的城镇时，\l"
	.string "多买些道具吧。$"

Help_Text_AnswerCanIBuyPokeBalls::
	.string "在任何城镇的宝可梦商店中，\n"
	.string "你也许会买精灵球。\l"
	.string "在森林、道路、洞穴里，\l"
	.string "你将找不到宝可梦商店。\l"
	.string "当你到一个有宝可梦商店的小镇时，\l"
	.string "买够精灵球吧。$"

Help_Text_AnswerWhatsATrainer::
	.string "训练家是通过对战训练\n"
	.string "宝可梦的人。\l"
	.string "训练家在任何地方，\l"
	.string "都会对你发出挑战，\l"
	.string "不管是街道、森林、洞穴，任何地方。\l"
	.string "如果他们看到你了，\l"
	.string "你就不得不接受挑战，\l"
	.string "所以小心点儿！$"

Help_Text_AnswerHowDoIWinAgainstTrainer::
	.string "为了在对战中打败训练家，\n"
	.string "就用压倒对方宝可梦属性的\l"
	.string "宝可梦吧。你也可以用\l"
	.string "拥有压倒性实力的宝可梦。\l"
	.string "用有效的策略\l"
	.string "压制住对手的宝可梦吧。$"

Help_Text_AnswerWhereDoMonsAppear::
	.string "野生宝可梦会在草地、\n"
	.string "道路和森林中出现。\l"
	.string "它们也会在洞穴的任何地方出现。\l"
	.string "在城镇里没有野生宝可梦\l"
	.string "或者训练家。因此它们是安全之地。$"

Help_Text_AnswerWhatAreMoves::
	.string "宝可梦会学习最多四个招式。\n"
	.string "招式多种多样，有攻击招式，\l"
	.string "也有拥有特殊效果的招式。\l"
	.string "任意的宝可梦\l"
	.string "都可以学到不同的招式。\l"
	.string "一些稀有的招式可以通过招式学习器学习。$"

Help_Text_AnswerWhatAreHiddenMoves::
	.string "秘传招式是那些\n"
	.string "对你的冒险很重要的招式。\l"
	.string "在战斗外使用这样的招式，\l"
	.string "就打开“宝可梦”菜单，\l"
	.string "然后让那些会的宝可梦使用。\l"
	.string "就算是被打败的宝可梦，\l"
	.string "也可以在战斗外使用隐藏招式。$"

Help_Text_AnswerWhatMovesShouldIUse::
	.string "选择“格斗”随后招式菜单\n"
	.string "就会出现。考虑招式匹配，\l"
	.string "选择最有效的招式吧。\l"
	.string "你也可以通过\l"
	.string "选择“宝可梦”选项，\l"
	.string "选中一只宝可梦，打开“概况”，\l"
	.string "然后打开“宝可梦能力”。$"

Help_Text_AnswerWantToAddMoreMoves::
	.string "一只宝可梦最多能学四个招式。\n"
	.string "随着等级上升可以学到。\l"
	.string "当然也可以使用招式学习器学习。\l"
	.string "而且还有一些传授招式的人。$"

Help_Text_AnswerWantToMakeMonStronger::
	.string "让你的宝可梦变强的关键\n"
	.string "是让它们经常在战斗中获胜。\l"
	.string "伴随战斗的胜利，\l"
	.string "就会得到使宝可梦等级上升的\l"
	.string "经验值。\l"
	.string "经常和野生宝可梦对战，\l"
	.string "壮大你的队伍吧。$"

Help_Text_AnswerFoeMonsTooStrong::
	.string "如果对手的宝可梦很强，\n"
	.string "就试着多让你的宝可梦提升等级吧。\l"
	.string "回到你经过的地方，\l"
	.string "和野生的宝可梦对战来壮大你的队伍。\l"
	.string "你也可以和那些你以前\l"
	.string "没有交手过的训练家对战。$"

Help_Text_AnswerWhatDoIDoInCave::
	.string "与道路和森林不同，\n"
	.string "洞穴里的野生宝可梦无处不在。\l"
	.string "如果你的宝可梦在洞穴中受伤，\l"
	.string "就快去宝可梦中心\l"
	.string "或者用道具治疗它们。\l"
	.string "在洞穴中靠运气很危险。$"

Help_Text_AnswerNothingIWantToKnow::
	.string "相信你的知识和力量。\n"
	.string "自信一些，找到你自己的路吧！$"

Help_Text_AnswerWhatsPokemonCenter::
	.string "宝可梦中心的标志是\n"
	.string "上面写着“P.C.”的牌子和红色屋顶。\l"
	.string "每个宝可梦中心都会提供类似\l"
	.string "恢复宝可梦和免费使用电脑的服务。\l"
	.string "那对你的旅行很重要。\l"
	.string "楼上是和你的朋友及他人\l"
	.string "联络的工具。$"

Help_Text_AnswerWhatsPokemonMart::
	.string "宝可梦商店的标记是\n"
	.string "写着“MART”的蓝色屋顶。\l"
	.string "道具可以在任意宝可梦商店中买卖。\l"
	.string "一些商店只卖\l"
	.string "仅仅在他们城镇特有的道具。$"

Help_Text_AnswerWantToEndGame::
	.string "通过在菜单中选择“保存”\n"
	.string "你可以安全地结束游戏。\l"
	.string "当你保存完存档之后，\l"
	.string "你就可以结束游戏了。\l"
	.string "当游戏再次开始的时候，\l"
	.string "你就会回到你存档时的状态。$"

Help_Text_AnswerWhatsAMon::
	.string "宝可梦是身上还有着\n"
	.string "许多未解之谜的生物。\l"
	.string "你可以在草地、海洋、洞穴中看到它们。\l"
	.string "它们的出现都引起\l"
	.string "训练家们去收复它们的愿望。$"

Help_Text_AnswerWhatIsThatPersonLike::
	.string "在你包包的重要道具口袋中，\n"
	.string "使用声音记录器。\l"
	.string "它会给你点提示，所以多用用吧。$"

Help_Text_AnswerWhatDoesHiddenMoveDo::
	.string "秘传招式是宝可梦\n"
	.string "使用秘传学习器习得的。\l"
	.string "秘传招式可是帮助你冒险的\l"
	.string "重要招式。举个例子，\l"
	.string "有的招式可以照亮暗黑的洞穴。\l"
	.string "有的可以砍倒挡路小树。\l"
	.string "有的甚至能让你跨越海洋！\l"
	.string "但这仅仅是冰山一角。$"

Help_Text_AnswerWhatDoIDoInSafari::
	.string "试着抛出特殊的狩猎球\n"
	.string "来抓野生的宝可梦吧。\l"
	.string "你也可以留着你找到的任何道具。$"

Help_Text_AnswerWhatAreSafariRules::
	.string "狩猎游戏会在一段时间之后，\n"
	.string "或者你扔完狩猎球之后结束。\l"
	.string "可以打开菜单来确认一下\l"
	.string "剩余的步数以及狩猎球。$"

Help_Text_AnswerWantToEndSafari::
	.string "如果你想提早结束\n"
	.string "狩猎游戏，打开菜单然后选择\l"
	.string "列表最上方的“退出”。$"

Help_Text_AnswerWhatIsAGym::
	.string "宝可梦道馆是由\n"
	.string "宝可梦联盟管理着的\l"
	.string "训练家训练设施。它们\l"
	.string "遍布在哥哥村子和城市之中。\l"
	.string "每个道馆都由馆主带领，他们\l"
	.string "都是很经验的训练家。打败\l"
	.string "馆主来得到徽章。$"

Help_Text_UsingPokedex::
	.string " 使用“图鉴”$"

Help_Text_UsingPokemon::
	.string " 使用“宝可梦”$"

Help_Text_UsingSummary::
	.string " 使用“概况”$"

Help_Text_UsingSwitch::
	.string "  使用“换位”$"

Help_Text_UsingItem::
	.string "  使用“道具”$"

Help_Text_UsingBag::
	.string " 使用“包包”$"

Help_Text_UsingAnItem::
	.string "  使用一个道具$"

Help_Text_UsingKeyItem::
	.string "  使用一个重要道具$"

Help_Text_UsingPokeBall::
	.string "  使用一个精灵球$"

Help_Text_UsingPlayer::
	.string " 使用“玩家”$"

Help_Text_UsingSave::
	.string " 使用“保存”$"

Help_Text_UsingOption::
	.string " 使用“设定”$"

Help_Text_UsingPotion::
	.string "    使用一个伤药$"

Help_Text_UsingTownMap::
	.string "    使用城镇地图$"

Help_Text_UsingTM::
	.string "    使用一个招式学习器$"

Help_Text_UsingHM::
	.string "    使用一个秘传学习器$"

Help_Text_UsingMoveOutsideOfBattle::
	.string "在战斗外使用招式$"

Help_Text_RidingBicycle::
	.string "    骑在自行车上$"

Help_Text_EnteringName::
	.string "输入一个名字$"

Help_Text_UsingPC::
	.string "使用电脑$"

Help_Text_UsingBillsPC::
	.string " 使用“{B_COPY_VAR_1}的电脑”$"

Help_Text_UsingWithdraw::
	.string "  使用“取出”$"

Help_Text_UsingDeposit::
	.string "  使用“存放”$"

Help_Text_UsingMove::
	.string "  使用“移动”$"

Help_Text_MovingItems::
	.string "  移动道具$"

Help_Text_UsingPlayersPC::
	.string " 登录“{PLAYER}的电脑”$"

Help_Text_UsingWithdrawItem::
	.string "  使用“取出道具”$"

Help_Text_UsingDepositItem::
	.string "  使用“存放道具”$"

Help_Text_UsingMailbox::
	.string "  使用“邮箱”$"

Help_Text_UsingProfOaksPC::
	.string " 登录“大木博士的电脑”$"

Help_Text_OpeningMenu::
	.string "打开菜单$"

Help_Text_UsingFight::
	.string " 使用“格斗”$"

Help_Text_UsingPokemon2::
	.string " 使用“宝可梦”$"

Help_Text_UsingShift::
	.string "  使用“替换”$"

Help_Text_UsingSummary2::
	.string "  使用“概况”$"

Help_Text_UsingBag2::
	.string " 使用“包包”$"

Help_Text_ReadingPokedex::
	.string " 查看“宝可梦图鉴”$"

Help_Text_UsingHomePC::
	.string "使用家里的电脑$"

Help_Text_UsingItemStorage::
	.string "使用道具储存系统$"

Help_Text_UsingWithdrawItem2::
	.string "  使用“取出道具”$"

Help_Text_UsingDepositItem2::
	.string "  使用“存放道具”$"

Help_Text_UsingMailbox2::
	.string "使用邮箱$"

Help_Text_UsingRun::
	.string " 使用“逃跑”$"

Help_Text_RegisterKeyItem::
	.string "  “登记”一个重要道具$"

Help_Text_UsingBall::
	.string " 使用“球”$"

Help_Text_UsingBait::
	.string " 使用“饵食”$"

Help_Text_UsingRock::
	.string " 使用“石头”$"

Help_Text_UsingHallOfFame::
	.string " 打开“登入名人堂”$"

Help_Text_HowToUsePokedex::
	.string "{CIRCLE_1}选择菜单上的“宝可梦图鉴”。\n"
	.string "{CIRCLE_2}使用不同的命令\n"
	.string "   像是“宝可梦列表”，\n"
	.string "   “宝可梦的栖息地”，或\n"
	.string "   “搜索”来选择宝可梦。\n"
	.string "{CIRCLE_3}挑选一只宝可梦去看更\n"
	.string "   详细的资料。$"

Help_Text_HowToUsePokemon::
	.string "{CIRCLE_1}在菜单中选择“宝可梦”。\n"
	.string "{CIRCLE_2}在队伍中选择一只宝可梦。 \n"
	.string "{CIRCLE_3}选择“概况”、“换位”\n"
	.string "   或者“道具”。$"

Help_Text_HowToUseSummary::
	.string "{CIRCLE_1}选择“概况”。\n"
	.string "{CIRCLE_2}按下十字键的左右键\n"
	.string "   来查看以下资料：\n"
	.string "   “宝可梦情报”\n"
	.string "   “宝可梦能力”\n"
	.string "   “学会的招式”$"

Help_Text_HowToUseSwitch::
	.string "{CIRCLE_1}选择你想改变\n"
	.string "   位置的宝可梦。\n"
	.string "{CIRCLE_2}选择“换位”。\n"
	.string "{CIRCLE_3}选择一只宝可梦来跟\n"
	.string "   第一只交换位置。\n"
	.string "在画面最左边的宝可梦 \n"
	.string "会是第一只出战的队员。$"

Help_Text_HowToUseItem::
	.string "{CIRCLE_1}选择“道具”。\n"
	.string "{CIRCLE_2}选择你想“携带”\n"
	.string "   宝可梦去持有的道具，\n"
	.string "   或者“拿出”持有中的道具。\n"
	.string "一只宝可梦同时不能持有\n"
	.string "多于一个道具。$"

Help_Text_HowToUseBag::
	.string "{CIRCLE_1}选择菜单中的“包包”。\n"
	.string "{CIRCLE_2}按下十字键的左右键\n"
	.string "   来查看以下项目：\n"
	.string "   “道具”\n"
	.string "   “重要道具”\n"
	.string "   “精灵球”\n"
	.string "   按上下键来选择一个道具。$"

Help_Text_HowToUseAnItem::
	.string "{CIRCLE_1}选择“道具”口袋。\n"
	.string "{CIRCLE_2}按十字键的上下键\n"
	.string "   来选择一个道具。\n"
	.string "{CIRCLE_3}选择“使用”去使用\n"
	.string "   被选择的道具。\n"
	.string "有些道具不能在\n"
	.string "特定地方和场合使用。$"

Help_Text_HowToUseKeyItem::
	.string "{CIRCLE_1}选择“重要道具”口袋。\n"
	.string "{CIRCLE_2}按十字键的上下键\n"
	.string "   来选择一个重要道具。\n"
	.string "{CIRCLE_3}选择“使用”去使用\n"
	.string "   选择了的重要道具。$"

Help_Text_HowToUsePokeBall::
	.string "{CIRCLE_1}再跟野生的宝可梦战斗时，\n"
	.string "   选择包包里的“精灵球”\n"
	.string "   口袋。\n"
	.string "{CIRCLE_2}按十字键的上下键\n"
	.string "  来选择一个精灵球。\n"
	.string "{CIRCLE_3}选择“使用”去抛出\n"
	.string "   选择了的精灵球。$"

Help_Text_HowToUsePlayer::
	.string "{CIRCLE_1}选择菜单上的“玩家”。\n"
	.string "{CIRCLE_2}你的训练家卡片带着基本资料\n"
	.string "  脸朝上的展示着。按下\n"
	.string "   A键去把卡片反转。\n"
	.string "{CIRCLE_3}多种资料都可以\n"
	.string "   在卡片的背面找到。$"

Help_Text_HowToUseSave::
	.string "{CIRCLE_1} 选择菜单上的“保存”。\n"
	.string "{CIRCLE_2} 选择“是”会把你的进度\n"
	.string "   保存在存档中。\n"
	.string "当保存后，你可以\n"
	.string "把游戏关掉。下次游戏会从\n"
	.string "你保存的地方继续。$"

Help_Text_HowToUseOption::
	.string "{CIRCLE_1}选择菜单中的“设定”。\n"
	.string "{CIRCLE_2}按十字键的上下键\n"
	.string "   去选择选项，然后\n"
	.string "   按左右键来\n"
	.string "   做出改变。\n"
	.string "{CIRCLE_3}选择“取消”或者按\n"
	.string "   B键来取消。$"

Help_Text_HowToUsePotion::
	.string "{CIRCLE_1}打开菜单。\n"
	.string "{CIRCLE_2}按十字键的上下键\n"
	.string "   来选择“包包”。\n"
	.string "{CIRCLE_3}选择“道具”口袋里的\n"
	.string "   “伤药”。\n"
	.string "{CIRCLE_4}选择“使用”。\n"
	.string "{CIRCLE_5}选择要治疗的宝可梦。$"

Help_Text_HowToUseTownMap::
	.string "{CIRCLE_1}打开菜单。\n"
	.string "{CIRCLE_2}按十字键的上下键\n"
	.string "   P来选择“包包”。\n"
	.string "{CIRCLE_3}按左右键来打开\n"
	.string "   “重要道具”口袋然后按\n"
	.string "   上或者下键来选择“城镇地图”。\n"
	.string "{CIRCLE_4}选择“使用”来使用城镇地图。$"

Help_Text_HowToUseTM::
	.string "{CIRCLE_1}打开菜单。\n"
	.string "{CIRCLE_2}打开“包包”里的\n"
	.string "   “重要道具”口袋。\n"
	.string "{CIRCLE_3}“打开”招式学习器盒。\n"
	.string "{CIRCLE_4}选择然后“使用”一个学习器。\n"
	.string "{CIRCLE_5}选择可以学会该\n"
	.string "   招式的宝可梦。$"

Help_Text_HowToUseHM::
	.string "{CIRCLE_1}打开菜单。\n"
	.string "{CIRCLE_2}打开“包包”里的\n"
	.string "   “重要道具”口袋。\n"
	.string "{CIRCLE_3}“打开”招式学习器盒。\n"
	.string "{CIRCLE_4}选择然后“使用”一个秘传学习器。\n"
	.string "{CIRCLE_5}选择可以学习该招式的宝可梦。\n"
	.string "   秘传招式很难忘记，要谨慎选择！$"

Help_Text_HowToUseMoveOutsideOfBattle::
	.string "{CIRCLE_1}打开菜单。\n"
	.string "{CIRCLE_2}选择“宝可梦。”\n"
	.string "{CIRCLE_3}选择学会HM\n"
	.string "   的宝可梦。可被使用的HM招式\n"
	.string "   会以蓝字显示。选择\n"
	.string "   招式来破坏\n"
	.string "   目标，飞行或者冲浪等等。$"

Help_Text_HowToRideBicycle::
	.string "{CIRCLE_1}打开菜单。打开\n"
	.string "   “包包”里的“重要道具”口袋\n"
	.string "   然后选择“自行车”。\n"
	.string "{CIRCLE_2}要骑上自行车的话\n"
	.string "   就选择“使用”。你也可以\n"
	.string "   “登记”它来用\n"
	.string "   选择键来快速使用。$"

Help_Text_HowToEnterName::
	.string "{CIRCLE_1}用十字键把选择框移到\n"
	.string "  你想选择的字母上，然后\n"
	.string "   按下A键来输入。\n"
	.string "{CIRCLE_2}按B键删除。\n"
	.string "{CIRCLE_3}按选择键在\n"
	.string "   大写跟小写间切换。\n"
	.string "{CIRCLE_4}在“OK”上按A键。$"

Help_Text_HowToUsePC::
	.string "{CIRCLE_1}前往任何宝可梦中心，走到\n"
	.string "   电脑前，然后按下A键。$"

Help_Text_HowToUseBillsPC::
	.string "{CIRCLE_1}选择电脑里的“{B_COPY_VAR_1}的电脑”。\n"
	.string "{CIRCLE_2}从菜单的三个选项中\n"
	.string "   选择一个登陆到宝可梦\n"
	.string "   储存系统。\n"
	.string "如果你抓到新的宝可梦时\n"
	.string "队伍中有满了，新的宝可梦会自动\n"
	.string "送到系统的盒子里！$"

Help_Text_HowToUseWithdraw::
	.string "{CIRCLE_1}用十字键选择在\n"
	.string "  盒子里的宝可梦。\n"
	.string "{CIRCLE_2}选择“取出”去把\n"
	.string "   宝可梦从盒子移到\n"
	.string "   你的队伍中。\n"
	.string "如果你队伍中已经有六只宝可梦\n"
	.string "你就不能再把宝可梦放进队伍里。$"

Help_Text_HowToUseDeposit::
	.string "{CIRCLE_1}用十字键选择\n"
	.string "   队伍中的宝可梦。\n"
	.string "{CIRCLE_2}选择“存放。”\n"
	.string "{CIRCLE_3}选择盒子，然后按下\n"
	.string "   A键来储存宝可梦。\n"
	.string "如果你只有一只宝可梦在队伍中，\n"
	.string "它将不能被储存！$"

Help_Text_HowToUseMove::
	.string "{CIRCLE_1}选择一只在盒子中的宝可梦.\n"
	.string "{CIRCLE_2}用“移动”去选择移动一只\n"
	.string "   宝可梦然后以十字键\n"
	.string "   把它移到任何地方。\n"
	.string "{CIRCLE_3}把宝可梦移到盒子名字上\n"
	.string "   然后按左右键\n"
	.string "   移到其他盒子。$"

Help_Text_HowToMoveItems::
	.string "{CIRCLE_1}淡化地显示的宝可梦 \n"
	.string "   可以在它上按A键\n"
	.string "   来让它持有一个道具。\n"
	.string "{CIRCLE_2}清晰地显示的宝可梦\n"
	.string "   可以用A键把它们身上的\n"
	.string "  道具交给其他宝可梦，或者\n"
	.string "   送回包包去。$"

Help_Text_HowToUsePlayersPC::
	.string "{CIRCLE_1}选择电脑里的“{PLAYER}的电脑”。\n"
	.string "{CIRCLE_2}选择“道具仓库”或\n"
	.string "   “邮箱”。\n"
	.string "如果你的包包满了\n"
	.string "你可以存到你的电脑中。你也可以\n"
	.string "从电脑中把道具拿出来。$"

Help_Text_HowToUseWithdrawItem::
	.string "{CIRCLE_1}选择“取出道具”。\n"
	.string "{CIRCLE_2}选择要拿出来的道具。\n"
	.string "{CIRCLE_3}拿出来的道具可以\n"
	.string "  放到包包里的道具口袋。\n"
	.string "   你也可以直接把道具\n"
	.string "   交给宝可梦去持有。$"

Help_Text_HowToUseDepositItem::
	.string "{CIRCLE_1}选择“存放道具。”\n"
	.string "{CIRCLE_2}包包里的道具\n"
	.string "   用十字键来选择来丢弃。\n"
	.string "{CIRCLE_3} 如果要存放一个以上的 \n"
	.string "   的道具。\n"
	.string "   按住键，\n"
	.string "   然后按A键。$"

Help_Text_HowToUseMailbox::
	.string "如果获得了带有信纸的宝可梦邮件，\n"
	.string "邮件会被移动到邮箱，\n"
	.string "没有邮件的话，邮箱不能使用\n"
	.string "{CIRCLE_1} 在电脑上选择选择“{PLAYER}的电脑”\n"
	.string "{CIRCLE_2} 选择“邮箱”来阅读邮件\n"
	.string "   或者宝可梦携带的邮件。$"

Help_Text_HowToUseProfOaksPC::
	.string "{CIRCLE_1} 在电脑上选择“大木博士的电脑”\n"
	.string "{CIRCLE_2} 大木博士会给你的\n"
	.string "   宝可梦图鉴做出评价\n"
	.string "他的评价会给你\n"
	.string "收服宝可梦带来更多的动力！$"

Help_Text_HowToOpenMenu::
	.string "{CIRCLE_1} 按开始键。\n"
	.string "{CIRCLE_2} 菜单会在屏幕右侧打开。\n"
	.string "{CIRCLE_3} 根据设置的不同，菜单\n"
	.string "   会有不同的外观。\n"
	.string "菜单在发生对话，\n"
	.string "战斗，以及其它一些事的时候\n"
	.string "是不能打开的。$"

Help_Text_HowToUseFight::
	.string "{CIRCLE_1} 选择“格斗”\n"
	.string "{CIRCLE_2} 选择一个显示出来的招式，\n"
	.string "然后这个招式就会被使出来！$"

Help_Text_HowToUsePokemon2::
	.string "{CIRCLE_1} 选择“宝可梦”\n"
	.string "{CIRCLE_2} 选择在你队伍中的\n"
	.string "   你想使用的宝可梦。\n"
	.string "{CIRCLE_3} 如果你有两只以上的宝可梦\n"
	.string "   你可以通过“替换”\n"
	.string "   交换它们的顺序，通过“概况”\n"
	.string "   查看它们的状态。$"

Help_Text_HowToUseShift::
	.string "这个操作可以在战斗中更换\n"
	.string "你队伍里的宝可梦。\n"
	.string "{CIRCLE_1} 选中想要上场的宝可梦。\n"
	.string "{CIRCLE_2} 选择“替换”\n"
	.string "{CIRCLE_3} 选中的宝可梦将会\n"
	.string "   代替现在场上的宝可梦上场！$"

Help_Text_HowToUseSummary2::
	.string "{CIRCLE_1} 选择“概况”\n"
	.string "{CIRCLE_2} 通过十字键的\n"
	.string "   左和右来查看以下信息：\n"
	.string "   “宝可梦情报”\n"
	.string "   “宝可梦能力”\n"
	.string "   “学会的招式”$"

Help_Text_HowToUseBag2::
	.string "{CIRCLE_1} 选择“包包”\n"
	.string "{CIRCLE_2} 通过按动十字键的\n"
	.string "   左和右，上面显示的字会变化。\n"
	.string "   “道具”\n"
	.string "   “重要道具”\n"
	.string "   “精灵球”\n"
	.string "   按上或者下来选择道具。$"

Help_Text_HowToReadPokedex::
	.string "{CIRCLE_1} 宝可梦被收服之后\n"
	.string "   在宝可梦图鉴上会\n"
	.string "   显示出一个精灵球的标志。\n"
	.string "{CIRCLE_2} 被收服的宝可梦会\n"
	.string "   提供大量的数据。\n"
	.if REVISION < 1
	.string "{CIRCLE_3} 选择“栖息地”可以在镇\n"
	.string "   地图显示宝可梦的栖息地。$"
	.else
	.string "{CIRCLE_3} Select “NEXT DATA” to display the\n"
	.string "   TOWN MAP with its habitat(s).$"
	.endif

Help_Text_HowToUseHomePC::
	.string "{CIRCLE_1} 走到家中的电脑前，\n"
	.string "   然后按下A键。\n"
	.string "{CIRCLE_2} 电脑将会启动。\n"
	.string "{CIRCLE_3} 选择“道具仓库”或者\n"
	.string "   “邮箱”$"

Help_Text_HowToUseItemStorage::
	.string "{CIRCLE_1} 选择“取出道具”\n"
	.string "   取出你电脑里存储的道具。\n"
	.string "{CIRCLE_2} 选择“存放道具” \n"
	.string "   将你包包里的道具存入电脑。$"

Help_Text_HowToUseWithdrawItem2::
	.string "{CIRCLE_1} 选择“取出道具”\n"
	.string "{CIRCLE_2} 选中需要取出的道具。\n"
	.string "{CIRCLE_3} 选中的道具会被取出\n"
	.string "   放进包包的口袋里。\n"
	.string "   同样也可以直接交给\n"
	.string "   宝可梦装备上。$"

Help_Text_HowToUseDepositItem2::
	.string "{CIRCLE_1} 选择“存放道具。”\n"
	.string "{CIRCLE_2} 通过十字键选择包包\n"
	.string "   里需要存放的道具。\n"
	.string "{CIRCLE_3} 如果包包里没有任何东西，\n"
	.string "   这个功能就用不了！$"

Help_Text_HowToUseMailbox2::
	.string "当邮件被从宝可梦身上拿走时，\n"
	.string "它会被传到邮箱。如果\n"
	.string "没有邮件的话，那就不能用邮箱了。\n"
	.string "{CIRCLE_1}选择邮件标题来阅读\n"
	.string "   或者让宝可梦持有它。$"

Help_Text_HowToUseRun::
	.string "你不可以从跟训练家的\n"
	.string "战斗中“逃跑”！\n"
	.string "{CIRCLE_1}你可以在跟野生宝可梦的战斗中“逃跑”。\n"
	.string "{CIRCLE_2}如果你的宝可梦的速度够快\n"
	.string "   你逃跑的机率会提高。$"

Help_Text_HowToRegisterKeyItem::
	.string "你可以用选择来\n"
	.string "“登记”一个贵重物品！\n"
	.string "{CIRCLE_1}打开“重要道具”的口袋。\n"
	.string "{CIRCLE_2}选择一个贵重物品，然后选\n"
	.string "   “登记”。$"

Help_Text_HowToUseBall::
	.string "{CIRCLE_1}选择这个来抛出只在\n"
	.string "   狩猎地带使用的精灵球。\n"
	.string "当野生宝可梦出现时，抛出\n"
	.string "一大堆狩猎球来抓它们吧！$"

Help_Text_HowToUseBait::
	.string "{CIRCLE_1}选择这个来抛出\n"
	.string "   狩猎地带专用的食物。\n"
	.string "这是被卷成球状的宝可梦食物\n"
	.string "非常容易食用。当饵食被\n"
	.string "抛出，野生的宝可梦可能会被\n"
	.string "吸引，也不容易逃走！$"

Help_Text_HowToUseRock::
	.string " {CIRCLE_1} 选择这个来抛出在\n"
	.string "   狩猎地带地上的石头。\n"
	.string "对宝可梦抛石头\n"
	.string "可能会把它吓走，不过它会\n"
	.string "更容易被收服！$"

Help_Text_HowToUseHallOfFame::
	.string "{CIRCLE_1} 在电脑中选择“登入名人堂”。\n"
	.string "{CIRCLE_2} 进入过名人堂的宝可梦的资料\n"
	.string "   可以在这查看。$"

Help_Text_HP::
	.string "HP$"

Help_Text_EXP::
	.string "经验 {LEFT_PAREN}经验值{RIGHT_PAREN}$"

Help_Text_Moves::
	.string "招式$"

Help_Text_Attack::
	.string "攻击$"

Help_Text_Defense::
	.string "防御$"

Help_Text_SpAtk::
	.string "特攻$"

Help_Text_SpDef::
	.string "特防$"

Help_Text_Speed::
	.string "速度$"

Help_Text_Level::
	.string "Lv. {LEFT_PAREN}等级{RIGHT_PAREN}$"

Help_Text_Type::
	.string "属性$"

Help_Text_OT::
	.string "初训家$"

Help_Text_Item::
	.string "道具$"

Help_Text_Ability::
	.string "特性$"

Help_Text_Money::
	.string "零花钱$"

Help_Text_MoveType::
	.string "招式属性$"

Help_Text_Nature::
	.string "性格$"

Help_Text_IDNo::
	.string "ID No.$"

Help_Text_PP::
	.string "PP$"

Help_Text_Power::
	.string "威力$"

Help_Text_Accuracy::
	.string "命中$"

Help_Text_FNT::
	.string "昏厥$"

Help_Text_Items::
	.string "道具$"

Help_Text_KeyItems::
	.string "重要道具$"

Help_Text_PokeBalls::
	.string "精灵球$"

Help_Text_Pokedex::
	.string "图鉴$"

Help_Text_PlayTime::
	.string "游戏时间$"

Help_Text_Badges::
	.string "徽章$"

Help_Text_TextSpeed::
	.string "语速$"

Help_Text_BattleScene::
	.string "战斗动画$"

Help_Text_BattleStyle::
	.string "比赛规则$"

Help_Text_Sound::
	.string "音乐$"

Help_Text_ButtonMode::
	.string "按键模式$"

Help_Text_Frame::
	.string "边框$"

Help_Text_Cancel2::
	.string "取消$"

Help_Text_TM::
	.string "招式学习器$"

Help_Text_HM::
	.string "秘传学习器$"

Help_Text_HMMove::
	.string "秘传招式$"

Help_Text_Evolution::
	.string "进化$"

Help_Text_StatusProblem::
	.string "异常状态$"

Help_Text_Pokemon::
	.string "宝可梦$"

Help_Text_IDNo2::
	.string "ID No.$"

Help_Text_Money2::
	.string "零花钱$"

Help_Text_Badges2::
	.string "徽章$"

Help_Text_DefineHP::
	.string "HP就是宝可梦的生命值。\n"
	.string "如果宝可梦的HP降至零，它就会\l"
	.string "晕倒且不能战斗。\l"
	.string "所以，战斗的要点就是要把\l"
	.string "对手的HP降至零。\l"
	.string "如果你的宝可梦受伤了，可以在\l"
	.string "宝可梦中心或者用道具恢复HP。$"

Help_Text_DefineEXP::
	.string "经验值就是战斗经验的简称。\n"
	.string "宝可梦得到经验值的方法就是\l"
	.string "在战斗中取得胜利。\l"
	.string "当宝可梦积累了足够的\l"
	.string "经验值后，它就会升级。那个经验条\l"
	.string "代表了目前积累了的经验值。\l"
	.string "升级后经验条将会清零。$"

Help_Text_DefineMoves::
	.string "宝可梦最多可以记住\n"
	.string "四个招式。招式有很多种，\l"
	.string "包括了攻击招式和\l"
	.string "带有特殊效果的招式。\l"
	.string "可以学到这些招式的宝可梦\l"
	.string "有很多。有些招式可以\l"
	.string "用道具学到。$"

Help_Text_DefineAttack::
	.string "攻击代表了攻击性的\n"
	.string "招式的力量。数值越高，\l"
	.string "作出的伤害越高。\l"
	.string "这个数值会影响以下属性的\l"
	.string "攻击力：一般，毒，地上，\l"
	.string "飞行，虫，格斗，岩石，幽灵\l"
	.string "和钢。$"

Help_Text_DefineDefense::
	.string "防御代表了\n"
	.string "宝可梦对物理攻击的抗性。\l"
	.string "数值越高，对方的物理攻击\l"
	.string "作出的伤害就越少。$"

Help_Text_DefineSpAtk::
	.string "特攻(特殊攻击)代表\n"
	.string "特殊攻击的威力。\l"
	.string "数值越高，用特殊攻击招式\l"
	.string "打出的伤害越高。\l"
	.string "这个数值会影响以下属性的\l"
	.string "攻击力：火，水，电，草，\l"
	.string "冰，超能力，龙和恶。$"

Help_Text_DefineSpDef::
	.string "特防(特殊防御)代表了\n"
	.string "宝可梦对特殊攻击的抗性。\l"
	.string "数值越高，对方的特殊攻击\l"
	.string "作出的伤害就越少。$"

Help_Text_DefineSpeed::
	.string "速度代表了宝可梦\n"
	.string "的灵活性。在战斗中这个数值\l"
	.string "比对方的高，宝可梦就可以\l"
	.string "对比它慢的对手先行动。$"

Help_Text_DefineLevel::
	.string "Lv.(等级)代表了\n"
	.string "宝可梦的成长度和力量。\l"
	.string "一般来说，当宝可梦升级时，\l"
	.string "它的能力值像是HP，攻击\l"
	.string "和防御都会提升，使它更强。\l"
	.string "宝可梦升级时可能会\l"
	.string "学到新的招式。$"

Help_Text_DefineType::
	.string "宝可梦和招式都是以属性划分。\n"
	.string "每个属性相对于\l"
	.string "其他属性都有优势跟劣势。\l"
	.string "就像是剪刀石头布游戏，\l"
	.string "水对火属性很有效，\l"
	.string "可是对着草属性\l"
	.string "就没有太大效果了。$"

Help_Text_DefineOT::
	.string "初训家代表“宝可梦的原主人”\n"
	.string "就是第一个抓到\l"
	.string "这只宝可梦的训练家。\l"
	.string "就算宝可梦被交换了，\l"
	.string "初训家的名字也不会改变。$"

Help_Text_DefineItem::
	.string "所有宝可梦同一时间\n"
	.string "都可持有一个道具。\l"
	.string "有些可以在特定情况下\l"
	.string "自动被宝可梦使用。\l"
	.string "要让宝可梦持有道具，\l"
	.string "在包包里选择道具然后选择\l"
	.string "“携带”交给宝可梦。$"

Help_Text_DefineAbility::
	.string "所有宝可梦都有特别的特性。\n"
	.string "这些特性有很多种，有些只在战斗中有用，\l"
	.string "有些什么时候都有用。\l"
	.string "每个种族的特性都不同。\l"
	.string "有些甚至在同种族中\l"
	.string "都有不同的特性。$"

Help_Text_DefineMoney::
	.string "不管你在什么地方战胜了\n"
	.string "一个训练家，你都会得到奖金。\l"
	.string "好好地把钱存起来，\l"
	.string "然后在宝可梦商店尽情购物！$"

Help_Text_DefineMoveType::
	.string "招式都有属性加成。\n"
	.string "如果宝可梦使出了跟自己\l"
	.string "一样属性的招式，\l"
	.string "招式的威力也会增加。\l"
	.string "如果招式的属性\l"
	.string "可以克制对手的属性的话，\l"
	.string "它作出的伤害也会增加。$"

Help_Text_DefineNature::
	.string "所有宝可梦都有自己的个性，\n"
	.string "或者叫“性格”。\l"
	.string "宝可梦的性格会影响\l"
	.string "宝可梦升级时的成长方向。$"

Help_Text_DefineIDNo::
	.string "ID No.是一组证明你是\n"
	.string "训练家的特别数字。\l"
	.string "跟OT的名字一样，\l"
	.string "ID No.是用来精确地确认\l"
	.string "训练家的身份的。\l"
	.string "就算宝可梦被交换了\l"
	.string "这个ID No.都不会改变。$"

Help_Text_DefinePP::
	.string "PP代表了“能量点数”。\n"
	.string "它代表了一个招式在战斗中\l"
	.string "可以使用的次数。\l"
	.string "像HP、PP一样，\l"
	.string "可以到宝可梦中心\l"
	.string "或者使用特定种类道具恢复。$"

Help_Text_DefinePower::
	.string "能力代表了\n"
	.string "攻击性招式的威力。\l"
	.string "数值越高，\l"
	.string "对对方作出的伤害就会更高！$"

Help_Text_DefineAccuracy::
	.string "命中率代表了\n"
	.string "招式击中对方的机率。\l"
	.string "数值越高，\l"
	.string "击中对方的机率越大。$"

Help_Text_DefineFNT::
	.string "昏厥代表了“昏倒”\n"
	.string "宝可梦的HP降至零的时候\l"
	.string "就会昏倒。\l"
	.string "它不能再参加战斗。\l"
	.string "要恢复昏倒了的宝可梦可以去\l"
	.string "宝可梦中心或者使用道具。$"

Help_Text_DefineItems::
	.string "所有在宝可梦商店买的普通道具\n"
	.string "都放在道具口袋里。\l"
	.string "道具可以被使用，交给\l"
	.string "宝可梦携带或者当做垃圾丢掉。$"

Help_Text_DefineKeyItems::
	.string "你找到或者得到的重要道具\n"
	.string "都会被放在\l"
	.string "重要道具口袋里。\l"
	.string "重要的道具可以被使用，或者\l"
	.string "登录后用选择键快捷使用。\l"
	.string "当登录后，登录了的道具\l"
	.string "可以跳过菜单和包包直接使用。$"

Help_Text_DefinePokeBalls::
	.string "精灵球，是用来抓\n"
	.string "野生宝可梦的道具，会被\l"
	.string "放在精灵球口袋里。\l"
	.string "精灵球可以在\l"
	.string "宝可梦商店买到。\l"
	.string "它们可以被使用，交给宝可梦\l"
	.string "携带或者当垃圾丢掉。$"

Help_Text_DefinePokedex::
	.string "这代表了宝可梦图鉴中\n"
	.string "记录了由你抓到以及进化过的\l"
	.string "宝可梦的数目。\l"
	.string "努力去抓\l"
	.string "各种的宝可梦吧！$"

Help_Text_DefinePlayTime::
	.string "这是你的\n"
	.string "总游戏时间。$"

Help_Text_DefineBadges::
	.string "你得到的宝可梦联盟徽章\n"
	.string "会在这里登记和展出。\l"
	.string "你可以在不同城市打败道馆馆主\l"
	.string "来得到徽章。$"

Help_Text_DefineTextSpeed::
	.string "你可以在这调节\n"
	.string "文字显示的速度。可以从：慢速，中速，\l"
	.string "或者快速中选择。$"

Help_Text_DefineBattleScene::
	.string "你可以选择\n"
	.string "战斗动画的开启或关闭。$"

Help_Text_DefineBattleStyle::
	.string "你可以选择在跟训练家的\n"
	.string "战斗中在对方的宝可梦昏倒后\l"
	.string "要不要交换在场的宝可梦。\l"
	.string "设置为“替换”可以在\l"
	.string "对方宝可梦昏倒后\l"
	.string "手动选择交换与否。$"

Help_Text_DefineSound::
	.string "你可以从单声道和\n"
	.string "立体声两个声效中选择。$"

Help_Text_DefineButtonMode::
	.string "设置为“帮助”让你在按下\n"
	.string "L或者R键时呼出帮助页面。\l"
	.string "设置为“LR”让你可以在\l"
	.string "宝可梦图鉴页面和包包口袋里\l"
	.string "用L或者R键翻页。\l"
	.string "设置为“L=A”能使\l"
	.string "L键的作用和A键一样。$"

Help_Text_DefineFrame::
	.string "你可以在几个不同的\n"
	.string "窗口外框中选择。\l"
	.string "可以按照你的喜好选择。$"

Help_Text_DefineCancel2::
	.string "所作出了的设定\n"
	.string "会被标记为红色，然后你就会\l"
	.string "返回到菜单。$"

Help_Text_DefineTM::
	.string "TM(招式学习器)是一个用来\n"
	.string "教宝可梦招式的装置。\l"
	.string "这种装置有很多不同种类。\l"
	.string "一个招式学习器只能教给\l"
	.string "可以学会该招式的宝可梦。\l"
	.string "招式在使用后会坏掉。$"

Help_Text_DefineHM::
	.string "HM(秘传学习器)是一个用来\n"
	.string "教宝可梦秘传招式的装置。\l"
	.string "秘传招式只能教给\l"
	.string "可以学会该招式的宝可梦。\l"
	.string "跟普通招式不同，HM可以多次使用，\l"
	.string "而且秘传招式不容易\l"
	.string "被宝可梦所忘记。$"

Help_Text_DefineHMMove::
	.string "秘传招式对你的\n"
	.string "冒险之旅非常的重要。\l"
	.string "要在战斗外使用，\l"
	.string "打开“宝可梦”菜单\l"
	.string "然后让学会那个招式的\l"
	.string "宝可梦使用它。昏倒的宝可梦\l"
	.string "也可以在战斗外使用秘传招式。$"

Help_Text_DefineEvolution::
	.string "在各种宝可梦中，有些会在\n"
	.string "达到一定等级时\l"
	.string "经历重大改变(也就是进化)。\l"
	.string "进化使宝可梦改变外貌，\l"
	.string "改变名字，甚至使其可学习的招式\l"
	.string "产生变化。有些宝可梦会在\l"
	.string "达到升级外的特定条件下进化。$"

Help_Text_DefineStatusProblem::
	.string "特殊状态包括：\n"
	.string "睡眠：不能使用招式。\l"
	.string "中毒：HP不断减少。\l"
	.string "麻痹：可能不能使用招式。\l"
	.string "灼伤：HP减少，攻击降低。\l"
	.string "冰冻：不能使用招式。\l"
	.string "这些特殊状态可以用道具治疗。$"

Help_Text_DefinePokemon::
	.string "宝可梦是指\n"
	.string "在这个世界的每个角落上\l"
	.string "栖息着的生物。\l"
	.string "人们饲养宝可梦来当宠物，\l"
	.string "以及用它们来战斗，等等。$"

Help_Text_DefineIDNo2::
	.string "ID No.是一组证明你是\n"
	.string "训练家的特别数字。\l"
	.string "跟OT的名字一样，\l"
	.string "ID No.是用来精确地确认\l"
	.string "训练家的身份的。\l"
	.string "就算宝可梦被交换了\l"
	.string "这个ID No.都不会改变。$"

Help_Text_DefineMoney2::
	.string "不管在什么地方你战胜了\n"
	.string "一个训练家，你都会得到奖金。\l"
	.string "好好地把钱存起来然后\l"
	.string "在宝可梦商店尽情购物！$"

Help_Text_DefineBadges2::
	.string "这代表了你得到的\n"
	.string "宝可梦联盟徽章的数目。\l"
	.string "你可以在不同城市打败道馆馆主\l"
	.string "来得到徽章。$"

Help_Text_TheHelpSystem::
	.string "帮助系统$"

Help_Text_TheGame::
	.string "游戏$"

Help_Text_WirelessAdapter::
	.string "无线接收器$"

Help_Text_GameFundamentals1::
	.string "游戏基础 1$"

Help_Text_GameFundamentals2::
	.string "游戏基础 2$"

Help_Text_GameFundamentals3::
	.string "游戏基础 3$"

Help_Text_WhatArePokemon::
	.string "宝可梦是什么呢？$"

Help_Text_DescTheHelpSystem::
	.string "帮助信息会随着\n"
	.string "你旅程的进程而改变。\l"
	.string "它们是为在你需要帮助时\l"
	.string "而存在的。\l"
	.string "如果你有什么不明白的，\l"
	.string "请去帮助系统找找吧！$"

Help_Text_DescTheGame::
	.string "你作为探索宝可梦\n"
	.string "世界的主人公！\l"
	.string "通过与其他人交谈解决发现的未解之谜。\l"
	.string "新的道路将会为你开放。\l"
	.string "和你神奇的宝可梦一起\l"
	.string "向着目标努力前进吧！$"

Help_Text_DescWirelessAdapter::
	.string "这个游戏通过\n"
	.string "使用无线接收器来进行无线连接。\p"
	.string "去和无论身处何方，所处何时的任何人，\n"
	.string "无线连接吧！\p"
	.string "试着在无线信号能够覆盖的地方\n"
	.string "玩这个游戏吧！$"

Help_Text_DescGameFundamentals1::
	.string "游览每一座城市和小镇，\n"
	.string "走过每一条道路，\l"
	.string "穿过每一个山洞，\l"
	.string "面对所有的挑战，\l"
	.string "努力成为最棒的宝可梦训练家！$"

Help_Text_DescGameFundamentals2::
	.string "在你冒险的道路上，\n"
	.string "你将会遇到一些阻碍，\l"
	.string "所有的问题都可以通过做某些事\l"
	.string "或是解决一些谜题来解决。\l"
	.string "一些小障碍受一些\l"
	.string "之前发生了的事的影响。$"

Help_Text_DescGameFundamentals3::
	.string "一些挡在你面前的障碍\n"
	.string "可以让你的宝可梦\l"
	.string "学习特定的招式来解决。$"

Help_Text_DescWhatArePokemon::
	.string "宝可梦是谜一样的奇妙生物\n"
	.string "你在整个世界可能都会遇到它们…\l"
	.string "在草丛，在山洞，\l"
	.string "在海里，等等。\l"
	.string "它们似乎对收服它们的\l"
	.string "训练家会变得听话。$"

Help_Text_UsingTypeMatchupList::
	.string "属性相克一览$"

Help_Text_OwnMoveDark::
	.string "自己招式的属性：恶$"

Help_Text_OwnPokemonDark::
	.string "自己宝可梦的属性：恶$"

Help_Text_OwnMoveRock::
	.string "自己招式的属性：岩石$"

Help_Text_OwnPokemonRock::
	.string "自己宝可梦的属性：岩石$"

Help_Text_OwnMovePsychic::
	.string "自己招式的属性：超能力$"

Help_Text_OwnPokemonPsychic::
	.string "自己宝可梦的属性：超能力$"

Help_Text_OwnMoveFighting::
	.string "自己招式的属性：格斗$"

Help_Text_OwnPokemonFighting::
	.string "自己宝可梦的属性：格斗$"

Help_Text_OwnMoveGrass::
	.string "自己招式的属性：草$"

Help_Text_OwnPokemonGrass::
	.string "自己宝可梦的属性：草$"

Help_Text_OwnMoveGhost::
	.string "自己招式的属性：幽灵$"

Help_Text_OwnPokemonGhost::
	.string "自己宝可梦的属性：幽灵$"

Help_Text_OwnMoveIce::
	.string "自己招式的属性：冰$"

Help_Text_OwnPokemonIce::
	.string "自己宝可梦的属性：冰$"

Help_Text_OwnMoveGround::
	.string "自己招式的属性：地上$"

Help_Text_OwnPokemonGround::
	.string "自己宝可梦的属性：地上$"

Help_Text_OwnMoveElectric::
	.string "自己招式的属性：电$"

Help_Text_OwnPokemonElectric::
	.string "自己宝可梦的属性：电$"

Help_Text_OwnMovePoison::
	.string "自己招式的属性：毒$"

Help_Text_OwnPokemonPoison::
	.string "自己宝可梦的属性：毒$"

Help_Text_OwnMoveDragon::
	.string "自己招式的属性：龙$"

Help_Text_OwnPokemonDragon::
	.string "自己宝可梦的属性：龙$"

Help_Text_OwnMoveNormal::
	.string "自己招式的属性：一般$"

Help_Text_OwnPokemonNormal::
	.string "自己宝可梦的属性：一般$"

Help_Text_OwnMoveSteel::
	.string "自己招式的属性：钢$"

Help_Text_OwnPokemonSteel::
	.string "自己宝可梦的属性：钢$"

Help_Text_OwnMoveFlying::
	.string "自己招式的属性：飞行$"

Help_Text_OwnPokemonFlying::
	.string "自己宝可梦的属性：飞行$"

Help_Text_OwnMoveFire::
	.string "自己招式的属性：火$"

Help_Text_OwnPokemonFire::
	.string "自己宝可梦的属性：火$"

Help_Text_OwnMoveWater::
	.string "自己招式的属性：水$"

Help_Text_OwnPokemonWater::
	.string "自己宝可梦的属性：水$"

Help_Text_OwnMoveBug::
	.string "自己招式的属性：虫$"

Help_Text_OwnPokemonBug::
	.string "自己宝可梦的属性：虫$"

Help_Text_HowToUseTypeMatchupList::
	.string "根据使用的招式的属性和\n"
	.string "目标宝可梦的属性不同\l"
	.string "招式的效果也是不同的：\l"
	.string "{CIRCLE_DOT}：效果绝佳！\l"
	.string "{TRIANGLE}：不是很有效\l"
	.string "{BIG_MULT_X}：完全无效\l"
	.string "(其它情况则没有变化)$"

Help_Text_TypeMatchupOwnMoveDark::
	.string "对对方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：超能力、幽灵\p"
	.string "   {TRIANGLE}：格斗、恶、钢$"

Help_Text_TypeMatchupOwnPokemonDark::
	.string "对方的招式对己方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：格斗、虫\p"
	.string "   {TRIANGLE}：幽灵、恶\p"
	.string "   {BIG_MULT_X}：超能力$"

Help_Text_TypeMatchupOwnMoveRock::
	.string "对对方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：火、冰、飞行、虫\p"
	.string "   {TRIANGLE}：格斗、超能力、钢$"

Help_Text_TypeMatchupOwnPokemonRock::
	.string "对方的招式对己方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：水、草、格斗、\n"
	.string "       超能力、钢\p"
	.string "   {TRIANGLE}：一般、火、毒、飞行$"

Help_Text_TypeMatchupOwnMovePsychic::
	.string "对对方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：格斗、毒\p"
	.string "   {TRIANGLE}：超能力、钢\p"
	.string "   {BIG_MULT_X}：恶$"

Help_Text_TypeMatchupOwnPokemonPsychic::
	.string "对方的招式对己方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：虫、幽灵、恶\p"
	.string "   {TRIANGLE}：格斗、超能力$"

Help_Text_TypeMatchupOwnMoveFighting::
	.string "对对方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：一般、冰、岩石、恶、钢\p"
	.string "   {TRIANGLE}：毒、飞行、超能力、虫\p"
	.string "   {BIG_MULT_X}：幽灵$"

Help_Text_TypeMatchupOwnPokemonFighting::
	.string "对方的招式对己方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：飞行、超能力\p"
	.string "   {TRIANGLE}：虫、岩石、恶$"

Help_Text_TypeMatchupOwnMoveGrass::
	.string "对对方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：水、超能力、岩石\p"
	.string "   {TRIANGLE}：火、草、毒、飞行、\n"
	.string "       虫、龙、钢$"

Help_Text_TypeMatchupOwnPokemonGrass::
	.string "对方的招式对己方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：火、冰、毒、飞行、虫\p"
	.string "   {TRIANGLE}：水、电、草、地上$"

Help_Text_TypeMatchupOwnMoveGhost::
	.string "对对方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：超能力、幽灵\p"
	.string "   {TRIANGLE}：恶、钢\p"
	.string "   {BIG_MULT_X}：一般$"

Help_Text_TypeMatchupOwnPokemonGhost::
	.string "对方的招式对己方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：幽灵、恶\p"
	.string "   {TRIANGLE}：毒、虫\p"
	.string "   {BIG_MULT_X}：一般、格斗$"

Help_Text_TypeMatchupOwnMoveIce::
	.string "对对方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：草、超能力、飞行、龙\p"
	.string "   {TRIANGLE}：火、水、冰、钢$"

Help_Text_TypeMatchupOwnPokemonIce::
	.string "对方的招式对己方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：火、格斗、岩石、钢\p"
	.string "   {TRIANGLE}：冰$"

Help_Text_TypeMatchupOwnMoveGround::
	.string "对对方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：火、电、毒、岩石、\n"
	.string "       钢\p"
	.string "   {TRIANGLE}：草、虫\n"
	.string "   {BIG_MULT_X}：飞行$"

Help_Text_TypeMatchupOwnPokemonGround::
	.string "对方的招式对己方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：水、草、冰\p"
	.string "   {TRIANGLE}：毒、岩石\p"
	.string "   {BIG_MULT_X}：电$"

Help_Text_TypeMatchupOwnMoveElectric::
	.string "对对方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：水、飞行\p"
	.string "   {TRIANGLE}：电、草、龙\p"
	.string "   {BIG_MULT_X}：地上$"

Help_Text_TypeMatchupOwnPokemonElectric::
	.string "对方的招式对己方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：地上\p"
	.string "   {TRIANGLE}：电、飞行、钢$"

Help_Text_TypeMatchupOwnMovePoison::
	.string "对对方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：草\p"
	.string "   {TRIANGLE}：毒、超能力、岩石、幽灵\p"
	.string "   {BIG_MULT_X}：钢$"

Help_Text_TypeMatchupOwnPokemonPoison::
	.string "对方的招式对己方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：超能力、超能力\p"
	.string "   {TRIANGLE}：草、格斗、毒、虫$"

Help_Text_TypeMatchupOwnMoveDragon::
	.string "对对方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：龙\p"
	.string "   {TRIANGLE}：钢$"

Help_Text_TypeMatchupOwnPokemonDragon::
	.string "对方的招式对己方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：冰、龙\p"
	.string "   {TRIANGLE}：火、水、电、草$"

Help_Text_TypeMatchupOwnMoveNormal::
	.string "对对方宝可梦的效果：\p"
	.string "   {TRIANGLE}：岩石、钢\p"
	.string "   {BIG_MULT_X}：幽灵$"

Help_Text_TypeMatchupOwnPokemonNormal::
	.string "对方的招式对己方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：格斗\p"
	.string "   {BIG_MULT_X}：幽灵$"

Help_Text_TypeMatchupOwnMoveSteel::
	.string "对对方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：冰、岩石\p"
	.string "   {TRIANGLE}：火、水、电、钢$"

Help_Text_TypeMatchupOwnPokemonSteel::
	.string "对方的招式对己方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：火、格斗、地上\n"
	.string "   {TRIANGLE}：一般、草、冰、飞行、\l"
	.string "       超能力、虫、岩石、幽灵、\l"
	.string "       龙、恶、钢\l"
	.string "   {BIG_MULT_X}：毒$"

Help_Text_TypeMatchupOwnMoveFlying::
	.string "对对方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：草、格斗、虫\p"
	.string "   {TRIANGLE}：电、岩石、钢$"

Help_Text_TypeMatchupOwnPokemonFlying::
	.string "对方的招式对己方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：电、冰、岩石\p"
	.string "   {TRIANGLE}：草、格斗、虫\p"
	.string "   {BIG_MULT_X}：地上$"

Help_Text_TypeMatchupOwnMoveFire::
	.string "对对方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：草、冰、虫、钢\p"
	.string "   {TRIANGLE}：火、水、岩石、龙$"

Help_Text_TypeMatchupOwnPokemonFire::
	.string "对方的招式对己方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：水、超能力、岩石\p"
	.string "   {TRIANGLE}：火、草、冰、虫、钢$"

Help_Text_TypeMatchupOwnMoveWater::
	.string "对对方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：火、超能力、岩石\p"
	.string "   {TRIANGLE}：水、草、龙$"

Help_Text_TypeMatchupOwnPokemonWater::
	.string "对方的招式对己方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：电、草\p"
	.string "   {TRIANGLE}：火、水、冰、钢$"

Help_Text_TypeMatchupOwnMoveBug::
	.string "对对方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：草、超能力、恶\p"
	.string "   {TRIANGLE}：火、格斗、毒、\n"
	.string "       飞行、幽灵、钢$"

Help_Text_TypeMatchupOwnPokemonBug::
	.string "对方的招式对己方宝可梦的效果：\p"
	.string "   {CIRCLE_DOT}：火、飞行、岩石\p"
	.string "   {TRIANGLE}：草、格斗、地上$"

