Trade_Text_LookingForMonWannaTradeForMon::
	.string "我正在找\n"
	.string "一只{B_COPY_VAR_1}！\p"
	.string "你要用{B_COPY_VAR_1}交换\n"
	.string "我的{B_COPY_VAR_2}吗？$"

Trade_Text_AwwOhWell::
	.string "啊啊！\n"
	.string "哦，算了……$"

Trade_Text_WhatThatsNoMon::
	.string "什么？\n"
	.string "你根本没有{B_COPY_VAR_1}！$"

Trade_Text_HeyThanks::
	.string "嘿，太感谢了！$"

Trade_Text_IsntMyOldMonGreat::
	.string "我的老伙伴{B_COPY_VAR_2}还好吗？$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "你好，\n"
	.string "你有一只{B_COPY_VAR_1}吗？\p"
	.string "你要考虑一下\n"
	.string "和我的{B_COPY_VAR_2}交换吗？$"

Trade_Text_WellIfYouDontWantTo::
	.string "好吧，如果你真的不想的话……$"

Trade_Text_ThisIsntMon::
	.string "嗯嗯？\n"
	.string "这只不是{B_COPY_VAR_1}呢。\p"
	.string "等你抓到一只后再来和我换吧。$"

Trade_Text_Thanks::
	.string "谢谢你了！$"

Trade_Text_HasTradedMonGrownStronger::
	.string "我跟你交换的{B_COPY_VAR_2}，\n"
	.string "有没有变得更强了？$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "你好！\n"
	.string "请问你有{B_COPY_VAR_1}吗？\p"
	.string "要不要用{B_COPY_VAR_1}\n"
	.string "跟我换{B_COPY_VAR_2}？$"

Trade_Text_ThatsTooBad::
	.string "这太可惜了。$"

Trade_Text_ThisIsNoMon::
	.string "……这不是{B_COPY_VAR_1}。\p"
	.string "如果你找到一只，再来跟我交换吧。$"

Trade_Text_ThanksYoureAPal::
	.string "谢谢，你真是个好朋友！$"

Trade_Text_HowIsMyOldMon::
	.string "我的{STR_VAR_2}最近如何？\n"
	.string "我的{STR_VAR_1}过得非常好！$"
