gOtherText_NewName::
    .string "新名字$"

gNameChoice_Green::
    .string "青绿$"

gNameChoice_Red::
    .string "赤红$"

gNameChoice_Leaf::
    .string "叶子$"

gNameChoice_Fire::
    .string "小火$"

gNameChoice_Gary::
    .string "小茂$"

gNameChoice_Kaz::
    .string "恒和$"

gNameChoice_Toru::
    .string "小聪$"

gNameChoice_Ash::
    .string "小智$"

gNameChoice_Kene::
    .string "小建$"

gNameChoice_Geki::
    .string "茂树$"

gNameChoice_Jak::
    .string "杰克$"

gNameChoice_Janne::
    .string "阿简$"

gNameChoice_Jonn::
    .string "约翰$"

gNameChoice_Kamon::
    .string "加门$"

gNameChoice_Karl::
    .string "小隆$"

gNameChoice_Taylor::
    .string "宗佑$"

gNameChoice_Oscar::
    .string "小彻$"

gNameChoice_Hiro::
    .string "小广$"

gNameChoice_Max::
    .string "正雄$"

gNameChoice_Jon::
    .string "孝雄$"

gNameChoice_Ralph::
    .string "武弘$"

gNameChoice_Kay::
    .string "阿敬$"

gNameChoice_Tosh::
    .string "小均$"

gNameChoice_Roak::
    .string "小弘$"

gNameChoice_Omi::
    .string "清美$"

gNameChoice_Jodi::
    .string "智子$"

gNameChoice_Amanda::
    .string "千穗$"

gNameChoice_Hillary::
    .string "京子$"

gNameChoice_Makey::
    .string "真纪子$"

gNameChoice_Michi::
    .string "美纪子$"

gNameChoice_Paula::
    .string "美智子$"

gNameChoice_June::
    .string "纯子$"

gNameChoice_Cassie::
    .string "绫子$"

gNameChoice_Rey::
    .string "理惠$"

gNameChoice_Seda::
    .string "节子$"

gNameChoice_Kiko::
    .string "雪子$"

gNameChoice_Mina::
    .string "茉莉$"

gNameChoice_Norie::
    .string "纪惠$"

gNameChoice_Sai::
    .string "久惠$"

gNameChoice_Momo::
    .string "桃子$"

gNameChoice_Suzi::
    .string "美铃$"

gControlsGuide_Text_Intro::
    .string "首先，进行对游戏的操作\n"
    .string "以及所分配的按键的说明。$"

gControlsGuide_Text_DPad::
    .string "用于控制主角的行动。\n"
    .string "也可以用于选择不同的选项。$"

gControlsGuide_Text_AButton::
    .string "用于决定选项，调查物品，\n"
    .string "与NPC聊天以及继续显示对话内容。$"

gControlsGuide_Text_BButton::
    .string "用于退出或者取消选项，\n"
    .string "也用于退出菜单。$"

gControlsGuide_Text_StartButton::
    .string "用于打开菜单。$"

gControlsGuide_Text_SelectButton::
    .string "用于移动或登录物品\n"
    .string "或使用被登录的物品。$"

gControlsGuide_Text_LRButtons::
    .string "如果在游戏中遇到不明白的地方\n"
    .string "可以按L或R键打开帮助。$"

gOakSpeech_Text_AskPlayerGender::
    .string "好了，告诉我你是男孩\n"
    .string "还是女孩？$"

gPikachuIntro_Text_Page1::
    .string "您即将进入这个神奇的世界，\n"
    .string "并且会踏上一场大冒险，\n"
    .string "而您将成为这个故事的主角。\n"
    .string "\n"
    .string "无论您走到哪里，多和人交流，\n"
    .string "收集各种各样的物品，\n"
    .string "无论是城镇，道路或洞穴。\n"
    .string "从每个地方收集各种情报。$"

gPikachuIntro_Text_Page2::
    .string "帮助有需要的人以开辟新的道路。\n"
    .string "战胜各种困难，解开谜题，\n"
    .string "迎接挑战，勇于探索。\n"
    .string "\n"
    .string "有时，你会被各种训练家挑战，\n"
    .string "或者被野生生物袭击。\n"
    .string "要勇敢地继续走下去。$"

gPikachuIntro_Text_Page3::
    .string "在您的冒险中，\n"
    .string "我们希望您能向不同的人学习，\n"
    .string "在学习中不断成长。\n"
    .string "这是我们不断追求的最大目标。\n"
    .string "\n"
    .string "按下A键，\n"
    .string "开始您的冒险之旅吧！$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "你好！\n"
    .string "很高兴能见到你！\p"
    .string "欢迎来到宝可梦的世界！\p"
    .string "我叫大木。\p"
    .string "大家都叫我\n"
    .string "“宝可梦博士”。\p$"

gOakSpeech_Text_ThisWorld::
    .string "这个世界……$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "到处都栖息一种\n"
    .string "叫做宝可梦的生物。\p$"

gOakSpeech_Text_IStudyPokemon::
    .string "对于一些人来说，宝可梦是宠物。\n"
    .string "有些人则用它们来进行对战。\p"
    .string "而我……\p"
    .string "则是作为一个宝可梦专家\n"
    .string "对它们进行研究。\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "不过，首先，\n"
    .string "告诉我关于你的事情吧。\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "你叫什么名字？\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "嗯……\n"
    .string "你的名字叫{PLAYER}？$"

gOakSpeech_Text_WhatWasHisName::
    .string "这是我的孙子。\p"
    .string "你们从小一起长大，\n"
    .string "是伙伴，也是劲敌。\p"
    .string "……嗯，他叫什么名字来着？$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "你的劲敌叫什么名字？$"

gOakSpeech_Text_ConfirmRivalName::
    .string "……呃，是{RIVAL}吗？$"

gOakSpeech_Text_RememberRivalsName::
    .string "啊！我现在想起来了！\n"
    .string "他的确叫做{B_OPPONENT_MON1_NAME}！\p$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}！\p"
    .string "属于你的宝可梦传说\n"
    .string "即将开始！\p"
    .string "一个与宝可梦一起，充满\n"
    .string "梦想与冒险的世界等待着你！\p"
    .string "现在就开始吧！$"
