Text_ObtainedTheX::
	.string "获得了{B_COPY_VAR_2}！$"

Text_BagIsFull::
	.string "包包满了……$"

Text_PutItemAway::
	.string "{PLAYER}把{B_COPY_VAR_2}\n"
	.string "放到了{B_COPY_VAR_3}。$"

Text_FoundOneItem::
	.string "{PLAYER}找到一个{B_COPY_VAR_2}！$"

Text_TooBadBagFull::
	.string "糟糕！\n"
	.string "包包满了……$"

Text_FoundXCoins::
	.string "{PLAYER}找到了\n"
	.string "{B_COPY_VAR_1}{B_COPY_VAR_2}！$"

Text_PutCoinsAwayInCoinCase::
	.string "{PLAYER}把代币放到\n"
	.string "代币盒里面。$"

Text_CoinCaseIsFull::
	.string "糟糕！\n"
	.string "代币盒满了……$"

Text_NothingToPutThemIn::
	.string "糟糕！\n"
	.string "没有能放下它们的地方了……$"

Text_FoundXItems::
	.string "{PLAYER}找到了\n"
	.string "{B_COPY_VAR_1}{B_COPY_VAR_2}！$"

Text_ObtainedTheDecor::
	.string "得到了{B_COPY_VAR_2}！$"

Text_NoRoomForAnotherDecor::
	.string "糟糕！已经没有\n"
	.string "再放下另一个{B_COPY_VAR_2}的空间了……$"

Text_DecorTransferredToPC::
	.string "{B_COPY_VAR_2}已经传送\n"
	.string "到电脑去了。$"
