Text_MonSentToBoxInSomeonesPC::
    .string "{B_COPY_VAR_2}被传送到\n"
    .string "某人的电脑。\p"
    .string "被存放到了\n"
    .string "盒子“{B_COPY_VAR_1}”中。$"

Text_MonSentToBoxInBillsPC::
    .string "{B_COPY_VAR_2}被传送到\n"
    .string "正辉的电脑。\p"
    .string "被存放到了\n"
    .string "盒子“{B_COPY_VAR_1}”中。$"

Text_MonSentToBoxSomeonesBoxFull::
    .string "某人的电脑的盒子“{B_COPY_VAR_3}”\n"
    .string "已经满了。\p"
    .string "{B_COPY_VAR_2}被传送到了\n"
    .string "盒子“{B_COPY_VAR_1}”中。$"

Text_MonSentToBoxBillsBoxFull::
    .string "正辉的电脑的盒子“{B_COPY_VAR_3}”\n"
    .string "已经满了。\p"
    .string "{B_COPY_VAR_2}被传送到了\n"
    .string "盒子“{B_COPY_VAR_1}”中。$"

Text_PlayerObtainedTheMon::
    .string "{PLAYER}得到了\n"
    .string "{B_COPY_VAR_1}！$"

@ Unused. Translated below
@ You cannot carry any more Pokemon, so {STR_VAR_2} was sent to PC Box {STR_VAR_1}!
Text_MonSentToBoxInPC::
    .string "ポケモンを　もちきれないので\n"
    .string "パソコンの　ボックス“{STR_VAR_1}”　に\l"
    .string "{STR_VAR_2}を　てんそうした！$"

Text_NoMoreRoomForPokemon::
    .string "已经没有空位放宝可梦了！\p"
    .string "宝可梦寄存箱全都满了，\n"
    .string "不能再抓了！$"
