PokedexRating_Text_HowIsPokedexComingAlong::
	.string "大木：见到你真高兴啊！\n"
	.string "宝可梦图鉴完成得怎么样了？\p"
	.string "来，给我看看吧。$"

PokedexRating_Text_SeenXOwnedY::
	.string "到目前为止，你的宝可梦图鉴\n"
	.string "所含的数据是：\p"
	.string "发现了{B_COPY_VAR_1}种宝可梦，\n"
	.string "拥有了{B_COPY_VAR_2}种宝可梦。\p"
	.string "{FONT_NORMAL}大木博士的评价：$"

PokedexRating_Text_LessThan10::
	.string "你要做的还有很多啊！\p"
	.string "去每一片草地，\n"
	.string "寻找宝可梦吧！$"

PokedexRating_Text_LessThan20::
	.string "看起来你做的不错，\n"
	.string "至少你的路线是对的。\p"
	.string "我已经把秘传学习器闪光，交给了\n"
	.string "我的助手之一，去找他要吧！$"

PokedexRating_Text_LessThan30::
	.string "你的宝可梦图鉴仍需多加努力。\p"
	.string "试着收服其它种类的\n"
	.string "宝可梦！$"

PokedexRating_Text_LessThan40::
	.string "不错！可得出来\n"
	.string "你一定是下了不少功夫。\p"
	.string "我已经把探宝器交给了\n"
	.string "我一个的助手，快去找他要吧！$"

PokedexRating_Text_LessThan50::
	.string "你的宝可梦图鉴完成得很好啊！\p"
	.string "我已经把护身金币，交给了\n"
	.string "我的助手之一，去找他要吧！$"

PokedexRating_Text_LessThan60::
	.string "啊，你已经收集了50种！\p"
	.string "我已经把学习装置交给了我的\n"
	.string "助手之一。去找他要吧！$"

PokedexRating_Text_LessThan70::
	.string "嗯！你的宝可梦图鉴\n"
	.string "收集得真是相当优秀！$"

PokedexRating_Text_LessThan80::
	.string "非常好！\p"
	.string "不过如果你去钓鱼的话\n"
	.string "你会得到更多种宝可梦！$"

PokedexRating_Text_LessThan90::
	.string "干得好！我想你一定\n"
	.string "很喜欢收集东西，对吗？$"

PokedexRating_Text_LessThan100::
	.string "真厉害！\n"
	.string "这做起来一定不简单！$"

PokedexRating_Text_LessThan110::
	.string "你已经收集了100种！\n"
	.string "你简直是太厉害了！$"

PokedexRating_Text_LessThan120::
	.string "你甚至还有进化型的\n"
	.string "宝可梦！真棒！$"

PokedexRating_Text_LessThan130::
	.string "太棒了！和朋友通讯吧，\n"
	.string "能收集到更多哦！$"

PokedexRating_Text_LessThan140::
	.string "你真伟大！\n"
	.string "你在这方面可真是个专家啊！$"

PokedexRating_Text_LessThan150::
	.string "我已经没什么可说的了。\n"
	.string "现在，你就是宝可梦博士！$"

PokedexRating_Text_Complete::
	.string "你的宝可梦图鉴已经全部完成了！\n"
	.string "恭喜！$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "你的全国宝可梦图鉴现在是：\p"
	.string "发现了{B_COPY_VAR_1}种宝可梦，\n"
	.string "拥有了{B_COPY_VAR_2}种宝可梦。$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "真希望你能\n"
	.string "完成全国宝可梦图鉴！$"

PokedexRating_Text_YouveCompletedDex::
	.string "终于……\p"
	.string "你完成了\n"
	.string "宝可梦图鉴！\p"
	.string "这真是太伟大了！\n"
	.string "真的，这真的是一个伟大的功绩！$"

PokedexRating_Text_Wroooaaarrr::
	.string "喔噢噢噢噢～！$"

PokedexRating_Text_HaHa::
	.string "はあ はあ‥$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "谢谢你，{PLAYER}。\n"
	.string "真的谢谢你！\l"
	.string "谢谢你实现了我的梦想！$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "大木：啊，欢迎！\p"
	.string "告诉我，你的宝可梦图鉴\n"
	.string "收集得怎么样了？\p"
	.string "哇！\p"
	.string "事实上，我早就知道了……\n"
	.string "但我无论如何还是想看看！\p"
	.string "让我看看……$"
