Text_MayIHelpYou::
	.string "嗨！\n"
	.string "有什么能帮到你的吗？$"

Text_FillOutQuestionnaire::
	.string "这儿有一个调查表，\n"
	.string "可以麻烦你填一下可以吗？$"

Text_QuestionnaireThankYou::
	.string "非常感谢！\p"
	.string "你所反馈的建议\n"
	.string "将会被用在未来的建设上！$"

Text_YouKnowThoseWords::
	.string "哦，嗨！\n"
	.string "你知道这些关键字？\p"
	.string "那你一定知道\n"
	.string "神秘礼物了？\p"
	.string "从现在起，你就可以收到\n"
	.string "神秘礼物了！$"

Text_YouCanAccessMysteryGift::
	.string "当你下次存档时，\n"
	.string "你就可以开启神秘礼物了。$"

Text_ThankYouForAccessingMysteryGift::
	.string "感谢您使用\n"
	.string "神秘礼物系统。$"
