Pokedude_Text_SpeedierBattlerGoesFirst::
	.string "电视小哥：对战的双方\n"
	.string "速度较高的一方会先进行攻击。$"

Pokedude_Text_MyRattataFasterThanPidgey::
	.string "看起来我的小拉达的速度\n"
	.string "比那只波波快。$"

Pokedude_Text_BattlersTakeTurnsAttacking::
	.string "对战双方交替进行攻击\n"
	.string "以削减对手的HP。$"

Pokedude_Text_MyRattataWonGetsEXP::
	.string "我的小拉达令对手的HP\n"
	.string "削减到零，所以它赢了！\p"
	.string "所有参与战斗的宝可梦 \n"
	.string "都能得到经验值。\p"
	.string "当一只宝可梦得到足够的\n"
	.string "经验值，它就会升级。\p"
	.string "升级会让你的宝可梦\n"
	.string "变得比以前更强。$"

Pokedude_Text_UhOhRattataPoisoned::
	.string "电视小哥：呀啊……\n"
	.string "我的小拉达中毒了……\p"
	.string "如果宝可梦中毒了，它的\n"
	.string "HP会不断的减少。$"

Pokedude_Text_HealStatusRightAway::
	.string "如果宝可梦进入了\n"
	.string "不良状态，最好马上治好它。$"

Pokedude_Text_UsingItemTakesTurn::
	.string "在宝可梦身上使用道具\n"
	.string "会用掉一整个回合，请谨记。\p"
	.string "好了，现在是对手的回合！$"

Pokedude_Text_YayWeManagedToWin::
	.string "太棒了！\n"
	.string "我们赢了！$"

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass::
	.string "电视小哥：泡沫这个招式是\n"
	.string "水属性的攻击。\p"
	.string "攻击的目标走路草是一只\n"
	.string "草兼毒属性的宝可梦。\p"
	.string "水属性的攻击会被\n"
	.string "草属性宝可梦挡去一部份……\p"
	.string "于是，招式的效果变得\n"
	.string "不太有效，所以只能得到\l"
	.string "平时一半的伤害。$"

Pokedude_Text_GrassEffectiveAgainstWater::
	.string "噢，糟糕了！\p"
	.string "你刚刚见到的吸取\n"
	.string "是一招草属性的招式。\p"
	.string "蚊香蝌蚪是水属性的宝可梦。\p"
	.string "所以，吸取变得\n"
	.string "非常有效，造成双倍伤害。$"

Pokedude_Text_LetsTryShiftingMons::
	.string "这个情况要赢\n"
	.string "有点有难度……\p"
	.string "我们来交换宝可梦吧！$"

Pokedude_Text_ShiftingUsesTurn::
	.string "在战斗中交换宝可梦 \n"
	.string "会用掉一整个回合。\p"
	.string "好了，现在是对手的回合。$"

Pokedude_Text_ButterfreeDoubleResistsGrass::
	.string "巴大蝶是虫兼飞行属性的\n"
	.string "宝可梦。\p"
	.string "不要对它作出\n"
	.string "草属性的攻击……\p"
	.string "因为草属性对虫属性的宝可梦 \n"
	.string "只能造成一半的伤害……\p"
	.string "……还有，对飞行属性的宝可梦 \n"
	.string "也只能造成一半的伤害。\p"
	.string "所以用草属性攻击巴大蝶，\n"
	.string "它只会受到四分之一的伤害。$"

Pokedude_Text_ButterfreeGoodAgainstOddish::
	.string "走路草是草兼毒属性的\n"
	.string "宝可梦。\p"
	.string "用飞行或者超能力属性的攻击\n"
	.string "会非常有效。\p"
	.string "这两种攻击都能\n"
	.string "比平时多一倍的伤害。\p"
	.string "好了，我们上吧！$"

Pokedude_Text_YeahWeWon::
	.string "耶！\n"
	.string "我们赢了！$"

Pokedude_Text_WeakenMonBeforeCatching::
	.string "电视小哥：当你想要\n"
	.string "收服一只宝可梦，不要直接 \l"
	.string "抛出精灵球。\p"
	.string "首先，你要削减它的HP\n"
	.string "来让它变得虚弱。$"

Pokedude_Text_BestIfTargetStatused::
	.string "好了，这应该可以了。\p"
	.string "不过，在可行的情况下，把\n"
	.string "不良状态加到对手身上\l"
	.string "就更好了。\p"
	.string "例如，如果对象是在\n"
	.string "睡眠或者麻痹状态下\l"
	.string "会更容易被收服。$"

Pokedude_Text_CantDoubleUpOnStatus::
	.string "这会让宝可梦变得\n"
	.string "更容易被收服！\p"
	.string "啊，对了。如果你麻痹了\n"
	.string "那只宝可梦，你不能在\l"
	.string "麻痹状态上叠加睡眠状态。\p"
	.string "换句话说，你不能够让对方在同一时间\n"
	.string "拥有两个不良状态，明白吗？$"

Pokedude_Text_LetMeThrowBall::
	.string "好了！\n"
	.string "让我抛出我的精灵球！$"

Pokedude_Text_PickBestKindOfBall::
	.string "在你抛出精灵球前，\n"
	.string "考虑现场情况和\l"
	.string "宝可梦的属性来选择 \l"
	.string "适合的精灵球以得到最佳效果。$"
