Text_OnlySkilledTrainersAllowedThrough::
	.string "只有最出色的训练家才可以\n"
	.string "通过这里。\p"
	.string "你没有得到{B_COPY_VAR_1}的话\n"
	.string "你就没有通过这里的资格。$"

Text_CantLetYouPass::
	.string "制度就是制度。\n"
	.string "我不能让你通过。$"

Text_OhThatsBadgeGoRightAhead::
	.string "哦！这是{B_COPY_VAR_1}！\n"
	.string "好的，请前进。$"

Text_OnlyPassWithBadgeDontHaveYet::
	.string "你持有{B_COPY_VAR_1}的话\n"
	.string "就可以通过这里。\p"
	.string "你现在\n"
	.string "还没有{B_COPY_VAR_1}。\p"
	.string "你想到达宝可梦联盟\n"
	.string "就必须得到它。$"

Text_OnlyPassWithBadgeOhGoAhead::
	.string "你持有{B_COPY_VAR_1}的话\n"
	.string "就可以通过这里。\p"
	.string "哦哦！这就是{B_COPY_VAR_1}！{PAUSE_MUSIC}{PLAY_BGM 0x01 0x01}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "这样的话。\n"
	.string "好的，请前进。$"
