gText_WouldYouLikeToSaveTheGame::
	.string "你要保存游戏记录吗？$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
	.string "这里已经有了一个存档了。\n"
	.string "要覆盖这个存档吗？$"

gText_SavingDontTurnOffThePower::
	.string "保存中……\n"
	.string "请不要切断电源。$"

gText_PlayerSavedTheGame::
	.string "{PLAYER}保存了游戏。$"

gText_SaveFailed2::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile::
	.string "注意！\p"
	.string "这里已经保存了\n"
	.string "另外一个游戏的存档。\p"
	.string "如果你现在存档的话，另一个\n"
	.string "冒险进程，包括包包物品和拥有的\l"
	.string "宝可梦都会消失且无法恢复。\p"
	.string "你确定你现在要保存\n"
	.string "以及覆盖另一个存档吗？$"
