@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight::
	.string "呃……\n"
	.string "是那样吗…$"

PalletTown_Text_OhLookLook::
	.string "哦！\n"
	.string "快看，快看！$"

PalletTown_Text_ReadItReadIt::
	.string "快读，快读！$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu::
	.string "……有用的公告牌！\p"
	.string "请按下开始按钮来打开菜单！$"

PalletTown_Text_SignsAreUsefulArentThey::
	.string "公告牌很有用，对吧？$"

PalletTown_Text_LookCopiedTrainerTipsSign::
	.string "快看快看！\p"
	.string "我把其中一个有用的公告牌\n"
	.string "上所写的内容抄了下来！$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy::
	.string "……有用的公告牌！\p"
	.string "请按下开始按钮来打开菜单！$"
