CeladonCity_GameCorner_Text_TryPokemonPrinter::
	.string "宝可梦打印机！\p"
	.string "他可以在你的训练家卡片的后面\n"
	.string "影印上你的宝可梦。\p"
	.string "而且仅仅要¥50哦，\n"
	.string "要不要试试呢？$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney::
	.string "你的钱不够……$"

CeladonCity_GameCorner_Text_ChoosePrintType::
	.string "请选择印刷的样式。$"

CeladonCity_GameCorner_Text_BigSmileForPhoto::
	.string "要拍照了，来，微笑吧！\n"
	.string "3…2…1…\p"
	.string "咔嚓！$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard::
	.string "你的宝可梦已经印刷完毕了！\n"
	.string "快看看你的训练家卡片吧。$"

FourIsland_House2_Text_WishICouldShowOffStickers::
	.string "呃……\n"
	.string "我收集大量的贴纸。\l"
	.string "我希望我能够以它们为资本\l"
	.string "好好炫耀一下…$"

FourIsland_House2_Text_GiveYouStickerIfYouBrag::
	.string "哦，太棒了！\n"
	.string "你可真是来对地方了！\p"
	.string "快看，快看！\n"
	.string "看到了吧！\n"
	.string "这些是我的贴纸！\l"
	.string "你看，我得到了很多吧！\p"
	.string "我猜你也想要一些。\n"
	.string "一定是这样！\p"
	.string "如果你在我面前自夸，\n"
	.string "我就给你一个贴纸\p"
	.string "好了，快夸我吧！$"

FourIsland_House2_Text_BragAboutSomethingForMe::
	.string "快说我的好话！\n"
	.string "我会给你一个贴纸。$"

FourIsland_House2_Text_BragAboutWhatToday::
	.string "哦，嗨！\n"
	.string "那个吹嘘自己的人来了！\p"
	.string "今天你打算\n"
	.string "做什么？$"

FourIsland_House2_Text_WowHoFLowest::
	.string "哦，哇哦！你已经进入了\n"
	.string "名人堂。\p"
	.string "你真的太厉害了！\n"
	.string "我会给你一个贴纸。$"

FourIsland_House2_Text_WowHoFLow::
	.string "哦，哇哦！你经常进入\n"
	.string "名人堂！\p"
	.string "太不可思议了！\n"
	.string "我会给你一张贴纸。$"

FourIsland_House2_Text_WowHoFHigh::
	.string "哇！你进入\n"
	.string "名人堂的次数太频繁了！\l"
	.string "这可真是太令人难以置信了！\p"
	.string "你已经是宝可梦联盟了！\n"
	.string "我会给你一个贴纸。$"

FourIsland_House2_Text_WowHoFHighest::
	.string "不！你已经进入\n"
	.string "名人堂那么多次了？\p"
	.string "你已经超越奇迹了！\n"
	.string "真的，我一定要把这个给你。$"

FourIsland_House2_Text_HoFStickerApplied::
	.string "名人堂贴纸\n"
	.string "已经粘在了训练家卡片上。$"

FourIsland_House2_Text_ComeBackWithBetterStoryHoF::
	.string "呃……\p"
	.string "下次来的时候\n"
	.string "带一些更好的经历，行吗？$"

FourIsland_House2_Text_LivingLegendHoF::
	.string "哦，不，没有人能做到！\p"
	.string "你简直是一个活着的传说！\n"
	.string "我已经没有剩下的贴纸给你了。$"

FourIsland_House2_Text_WowEggsLowest::
	.string "哦，哇哦！那是宝可梦的蛋？\n"
	.string "我都不知道诶！\p"
	.string "那真是太好了！\n"
	.string "我会给你一个贴纸。$"

FourIsland_House2_Text_WowEggsLow::
	.string "你已经腐化了许多蛋？\n"
	.string "你真的很喜欢他们呢！\p"
	.string "不可思议！\n"
	.string "我会给你一张贴纸。$"

FourIsland_House2_Text_WowEggsHigh::
	.string "哇！你已经孵化了\n"
	.string "一群蛋！\p"
	.string "你真是一台孵蛋机！\n"
	.string "我会给你一张贴纸。$"

FourIsland_House2_Text_WowEggsHighest::
	.string "呃……你孵化了那么多蛋？\p"
	.string "在你对蛋的爱的背后隐藏着什么？\n"
	.string "这已经不仅仅是不可思议了！\p"
	.string "我告诉你，你真是太令人敬畏了！\n"
	.string "没错，我一定要给你一张贴纸。$"

FourIsland_House2_Text_EggStickerApplied::
	.string "蛋贴纸\n"
	.string "粘在了训练家卡片上。$"

FourIsland_House2_Text_ComeBackWithBetterStoryEggs::
	.string "呃……\p"
	.string "下次来的时候\n"
	.string "带来你更多的故事，好吗？$"

FourIsland_House2_Text_LivingLegendEggs::
	.string "哦，不，没有人能做到！\p"
	.string "你真是一个活生生的传说！\n"
	.string "我已经没有贴纸给你了。$"

FourIsland_House2_Text_WowLinkWinsLowest::
	.string "哇！你成功在通讯对战中\n"
	.string "胜利了？\p"
	.string "你真是太强大了！\n"
	.string "我会给你一张通讯对战。$"

FourIsland_House2_Text_WowLinkWinsLow::
	.string "你已经在通讯对战中\n"
	.string "打败了你很多朋友，是吗？\p"
	.string "你强大的真是不可思议！\n"
	.string "我会给你一张贴纸。$"

FourIsland_House2_Text_WowLinkWinsHigh::
	.string "哇！你已经打败你的朋友\n"
	.string "多次了？\p"
	.string "因为这个，你失去朋友了吗？\n"
	.string "我会给你一张贴纸。$"

FourIsland_House2_Text_WowLinkWinsHighest::
	.string "哇哦！\n"
	.string "你总是赢得胜利！\p"
	.string "你的到来\n"
	.string "让我停止沉思你有多强。\p"
	.string "你可真是无法摆脱的强大！\n"
	.string "没错，我一定要给你贴纸。$"

FourIsland_House2_Text_VictoryStickerApplied::
	.string "优胜标签\n"
	.string "粘在了训练家卡片上。$"

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins::
	.string "呃……\p"
	.string "下次来的时候\n"
	.string "带来更多关于你的故事好吗？$"

FourIsland_House2_Text_LivingLegendLinkWins::
	.string "哦，不，没有人能做到！\p"
	.string "你真是一个活生生的传说！\n"
	.string "我已经没有贴纸给你了。$"
