VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "电量不足。\p"
	.string "到充满电\n"
	.string "要求的步数：{B_COPY_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "附近没有训练家\n"
	.string "可以战斗……\p"
	.string "对战搜寻器被关闭了。{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "其他的训练家\n"
	.string "还没有做好应战的准备。\p"
	.string "让我们再等等吧。{PAUSE_UNTIL_PRESS}$"

Route3_Text_ColtonRematchIntro::
	.string "啊，你是！\n"
	.string "我在常青森林里见过你！$"

Route3_Text_BenRematchIntro::
	.string "嗨！我喜欢穿短裤！\n"
	.string "它们穿起来轻便又宽松！\p"
	.string "你也应该穿上短裤！$"

Route3_Text_JaniceRematchIntro::
	.string "真实力！\n"
	.string "你一直在盯着我看，我没说错吧？$"

Route3_Text_GregRematchIntro::
	.string "你是一名训练家，没错吧？\n"
	.string "让我们马上战上一场！$"

Route3_Text_SallyRematchIntro::
	.string "你那张脸使我感觉到……\n"
	.string "你一定对我有什么阴谋！$"

Route3_Text_CalvinRematchIntro::
	.string "嘿？你怎么了？\n"
	.string "你居然还没有穿上短裤！$"

Route3_Text_JamesRematchIntro::
	.string "我将会用宝可梦与你战斗。\n"
	.string "我一直在提升自己。$"

Route3_Text_RobinRematchIntro::
	.string "……呀啊！\n"
	.string "你刚才推了我吧？$"

Route4_Text_CrissyRematchIntro::
	.string "我经常在月见山\n"
	.string "收服蘑菇宝可梦。$"

Route6_Text_RickyRematchIntro::
	.string "噢！你就是偷听\n"
	.string "我们谈话那个爱管闲事的小孩！$"

Route6_Text_NancyRematchIntro::
	.string "对不起！莫非我没有告诉你\n"
	.string "这是一场私人的谈话？\p"
	.string "不要偷听，\n"
	.string "你这个没有教养的小子！$"

Route6_Text_KeigoRematchIntro::
	.string "我在寻找好东西……\n"
	.string "那不是虫属性宝可梦，但是……$"

Route6_Text_JeffRematchIntro::
	.string "嗯？\n"
	.string "你想再次和我玩玩？$"

Route6_Text_IsabelleRematchIntro::
	.string "我？\n"
	.string "好，很好。我这次会尽力的。$"

Route6_Text_ElijahRematchIntro::
	.string "嘿，好久不见！\n"
	.string "你变得更强了吗？$"

Route8_Text_AidanRematchIntro::
	.string "你对宝可梦很擅长，\n"
	.string "但是你的化学成绩如何呢？$"

Route8_Text_StanRematchIntro::
	.string "很好！\n"
	.string "让我们再玩一场！$"

Route8_Text_GlennRematchIntro::
	.string "想要在战斗中要赢得胜利\n"
	.string "那就需要讲究战略。\p"
	.string "你遵从我的意见了吗？$"

Route8_Text_PaigeRematchIntro::
	.string "我收集了很多的尼多家族的宝可梦。\n"
	.string "我想让它们进化，但是……$"

Route8_Text_LeslieRematchIntro::
	.string "学校非常有趣，但是我认为\n"
	.string "宝可梦同样十分有趣。$"

Route8_Text_AndreaRematchIntro::
	.string "喵喵和猫老大真的太可爱了，\n"
	.string "喵，喵，喵！$"

Route8_Text_MeganRematchIntro::
	.string "我们站在这里可能看起来很蠢\n"
	.string "但是我仍能战一场。$"

Route8_Text_RichRematchIntro::
	.string "我是一个潇洒的赌博大师！\n"
	.string "我正感受到胜利的气流！$"

Route8_Text_JuliaRematchIntro::
	.string "哪只宝可梦长得又可爱，\n"
	.string "还毛茸茸的？\p"
	.string "你现在知道了吧！$"

Route8_Text_RicardoRematchIntro::
	.string "小子，我的自行车依然能飞驰。$"

Route8_Text_JarenRematchIntro::
	.string "好吧，小鬼！\n"
	.string "这次别指望我会手下留情！$"

Route8_Text_EliRematchIntro::
	.string "莉娜：我们双胞胎的同步率\n"
	.string "增强了！$"

Route8_Text_AnneRematchIntro::
	.string "卡娜：我们双胞胎的能量提升了！$"

Route9_Text_AliciaRematchIntro::
	.string "我们要再战一场？\n"
	.string "现在换我虐你了！$"

Route9_Text_ChrisRematchIntro::
	.string "我永远也忘不了\n"
	.string "带着可爱的宝可梦的你。$"

Route9_Text_DrewRematchIntro::
	.string "我打算从岩山隧道前往\n"
	.string "紫苑……\p"
	.string "但是我一直被沿路的人所阻挠……$"

Route9_Text_CaitlinRematchIntro::
	.string "今天你敢不敢不放水！\n"
	.string "我们真刀真枪的战一场！$"

Route9_Text_JeremyRematchIntro::
	.string "叭哈哈！\n"
	.string "很好！我又感到无聊了！嗯哼！$"

Route9_Text_BriceRematchIntro::
	.string "哈哈哈！\n"
	.string "一如既往的难缠！$"

Route9_Text_BrentRematchIntro::
	.string "我每天都起得很早\n"
	.string "就是为了从小开始培养我的宝可梦！$"

Route9_Text_AlanRematchIntro::
	.string "哈哈哈哈！\n"
	.string "这次一定是我赢！$"

Route9_Text_ConnerRematchIntro::
	.string "上吧，我的超级虫属性宝可梦！$"

Route10_Text_MarkRematchIntro::
	.string "哇喔，你又来了？\n"
	.string "也许你也是一名宝可梦狂？\l"
	.string "想要姥姥我的收藏吗？$"

Route10_Text_ClarkRematchIntro::
	.string "哈…哈哈…啊哈！\n"
	.string "喷嚏止不住！$"

Route10_Text_HermanRematchIntro::
	.string "嗨，小朋友！\n"
	.string "想要看看我的宝可梦吗？$"

Route10_Text_HeidiRematchIntro::
	.string "我又去了趟宝可梦道馆挑战。\p"
	.string "…但是和往常一样我又输了。$"

Route10_Text_TrentRematchIntro::
	.string "啊！\n"
	.string "这座山上的空气真是新鲜又美味！\l"
	.string "太棒了，我不想回家了！$"

Route10_Text_CarolRematchIntro::
	.string "我眼前开始冒出星星了。\n"
	.string "我已经登了很长时间的山了……$"

Route11_Text_HugoRematchIntro::
	.string "胜，败，还是平！\n"
	.string "让我们再战一场！$"

Route11_Text_JasperRematchIntro::
	.string "比试胜负让人激动万分！\n"
	.string "我还得不到满足！$"

Route11_Text_EddieRematchIntro::
	.string "你懂的，对吧？\n"
	.string "开始了，不许作弊！$"

Route11_Text_BraxtonRematchIntro::
	.string "嗨，看这里！\p"
	.string "但是要留点神！\n"
	.string "我还在埋光缆！$"

Route11_Text_DillonRematchIntro::
	.string "我成为一名训练家有一段时间了。\n"
	.string "但是，我认为我能赢。$"

Route11_Text_DirkRematchIntro::
	.string "呒哈哈哈！\n"
	.string "我这个人就没有输过！\p"
	.string "……如果我输过了\n"
	.string "那我也早就会把它忘了！$"

Route11_Text_DarianRematchIntro::
	.string "我这个人就没赢过……\p"
	.string "也许命中注定\n"
	.string "我还得在这条失败之路走下去……$"

Route11_Text_YasuRematchIntro::
	.string "在我们班我是最强的。\n"
	.string "日日夜夜我都在做训练！$"

Route11_Text_BernieRematchIntro::
	.string "把眼睛睁大了小心那些电线！$"

Route11_Text_DaveRematchIntro::
	.string "我十分认真地训练我的宝可梦。\n"
	.string "它们应该准备好了。\l"
	.string "就是这场决战，我相信它们能赢。$"

Route12_Text_NedRematchIntro::
	.string "耶！\n"
	.string "看这里！我被咬了！\l"
	.string "千真万确！$"

Route12_Text_ChipRematchIntro::
	.string "你终于又来了。\n"
	.string "垂钓就是一个比耐心的游戏。$"

Route12_Text_JustinRematchIntro::
	.string "还是找不到月之石……\n"
	.string "你找到了吗？$"

Route12_Text_LucaRematchIntro::
	.string "电一直是我的\n"
	.string "专长。\p"
	.string "说到海里的宝可梦\n"
	.string "我一窍不通。$"

Route12_Text_HankRematchIntro::
	.string "钓鱼白痴对决宝可梦小孩！\n"
	.string "新回合，开战！$"

Route12_Text_ElliotRematchIntro::
	.string "我爱钓鱼，你可别误会我。\n"
	.string "但是，如果我能有更多的事可做……\l"
	.string "……要我放弃钓鱼果然很困难啊！$"

Route12_Text_AndrewRematchIntro::
	.string "我收服了什么？\p"
	.string "除非你击败了我\n"
	.string "否则你永远不会知道！$"

Route12_Text_JesRematchIntro::
	.string "阿重：今天我一定会赢\n"
	.string "然后我就向我的阿谀求婚。$"

Route12_Text_GiaRematchIntro::
	.string "阿谀：嘿，阿重……\n"
	.string "这一刻我已经等了很久了。\p"
	.string "如果今天我们能赢，我就嫁给你！$"

Route13_Text_SebastianRematchIntro::
	.string "我的鸟宝可梦还记得你！$"

Route13_Text_SusieRematchIntro::
	.string "当我还是个孩子时\n"
	.string "我就立志成为一名最强的训练家！$"

Route13_Text_ValerieRematchIntro::
	.string "哇喔！\n"
	.string "你得到了更多更酷的徽章！$"

Route13_Text_GwenRematchIntro::
	.string "我可爱的宝可梦变得\n"
	.string "更像和你亲热了。$"

Route13_Text_AlmaRematchIntro::
	.string "我为了买更多的速度增强剂\n"
	.string "花光了所有的积蓄。$"

Route13_Text_PerryRematchIntro::
	.string "这次我不会输了。\n"
	.string "风会指引我前进的道路！$"

Route13_Text_LolaRematchIntro::
	.string "哦，你回来了？\p"
	.string "很好，我会再陪你玩玩的。\n"
	.string "亲爱的。$"

Route13_Text_SheilaRematchIntro::
	.string "你忘了之前\n"
	.string "你和我的那场战斗了吗？$"

Route13_Text_JaredRematchIntro::
	.string "你在看什么？$"

Route13_Text_RobertRematchIntro::
	.string "我经常和我的鸟宝可梦一起出去\n"
	.string "我对它们倾注了一切。$"

Route14_Text_CarterRematchIntro::
	.string "我用招式学习器来教\n"
	.string "我的宝可梦厉害的招式。$"

Route14_Text_MitchRematchIntro::
	.string "我的鸟宝可梦\n"
	.string "为这场战斗做好准备了。$"

Route14_Text_BeckRematchIntro::
	.string "你对宝可梦使用过招式学习器了吗？\n"
	.string "只是存着它们是没用的。$"

Route14_Text_MarlonRematchIntro::
	.string "你教会你的宝可梦\n"
	.string "怎么使用飞翔了吗？\p"
	.string "你将会飞到天空中！\n"
	.string "试试看吧！$"

Route14_Text_DonaldRematchIntro::
	.string "幻影之翼的传说……\n"
	.string "你也听说过，对吧？$"

Route14_Text_BennyRematchIntro::
	.string "我真的没有进去，不过还行。\n"
	.string "开始吧！$"

Route14_Text_LukasRematchIntro::
	.string "嘿！\n"
	.string "我记得你！\p"
	.string "来吧，来吧。\n"
	.string "开始吧，开始吧，开始吧！$"

Route14_Text_IsaacRematchIntro::
	.string "你又到这儿来了，嗯哼？\n"
	.string "闭上你的嘴巴来打一场。$"

Route14_Text_GeraldRematchIntro::
	.string "托这里开阔的地形的福\n"
	.string "我们终于骑到了这里。$"

Route14_Text_MalikRematchIntro::
	.string "宝可梦战斗，对吧？\n"
	.string "酷！轰轰！$"

Route14_Text_KiriRematchIntro::
	.string "阿雾：惠娜，我希望我们今天能赢。$"

Route14_Text_JanRematchIntro::
	.string "惠娜：阿雾，我们开始吧！\n"
	.string "让我们享受这到手的胜利！$"

Route15_Text_KindraRematchIntro::
	.string "我和这只通过通信\n"
	.string "得到的宝可梦一起不停战斗。$"

Route15_Text_BeckyRematchIntro::
	.string "你看起来很有礼貌，\n"
	.string "所以我认为我能够打败你。\p"
	.string "我会再试一次的！$"

Route15_Text_EdwinRematchIntro::
	.string "每当我吹起口哨，\n"
	.string "鸟宝可梦就会集结在我周围。\p"
	.string "它们实在太可爱了！$"

Route15_Text_ChesterRematchIntro::
	.string "嗯？我的鸟开始颤抖了！\n"
	.string "等一下，莫非你就是那个训练家……$"

Route15_Text_GraceRematchIntro::
	.string "哦，你这个小可爱！\n"
	.string "就像一只可爱的宝可梦！\l"
	.string "我记起你来了！$"

Route15_Text_OliviaRematchIntro::
	.string "我训练我的宝可梦就是为了\n"
	.string "保护我在独处时不受伤害。\p"
	.string "这一点没有改变。$"

Route15_Text_ErnestRematchIntro::
	.string "嘿，小朋友！来吧！\n"
	.string "我从战败的阴影脱身了！$"

Route15_Text_AlexRematchIntro::
	.string "如果你战败了\n"
	.string "你得把你身上所有的现金交给我，小子！$"

Route15_Text_CeliaRematchIntro::
	.string "什么事情又酷又让人意想不到？\n"
	.string "没错，训练宝可梦。$"

Route15_Text_YazminRematchIntro::
	.string "想要和我的宝可梦\n"
	.string "再玩一场？$"

Route15_Text_MyaRematchIntro::
	.string "阿力： 嗨，我们再谈谈。\n"
	.string "好吗？\p"
	.string "能不能再帮我训练一下我的\n"
	.string "弟弟？$"

Route15_Text_RonRematchIntro::
	.string "阿铁：我姐姐已经\n"
	.string "变得更强了……$"

Route16_Text_LaoRematchIntro::
	.string "你想怎样？$"

Route16_Text_KojiRematchIntro::
	.string "真不错的自行车！\n"
	.string "快交出来！$"

Route16_Text_LukeRematchIntro::
	.string "出来玩玩吧，小老鼠。\n"
	.string "我会好好款待你的！$"

Route16_Text_HideoRematchIntro::
	.string "嘿，等一下！\n"
	.string "别想叫我一声然后就跑了！$"

Route16_Text_CamronRematchIntro::
	.string "我感觉好饿！\n"
	.string "我真的需要一个拳击袋！$"

Route16_Text_RubenRematchIntro::
	.string "嘿，看看瞧瞧！\n"
	.string "我们将会度过一段愉快的旅途！$"

Route16_Text_JedRematchIntro::
	.string "阿神：我们的爱永无止境，\n"
	.string "你是来见证它的吗？$"

Route16_Text_LeaRematchIntro::
	.string "嘉穗：有的时候我们的爱强烈得\n"
	.string "甚至会吓到我。$"

Route17_Text_RaulRematchIntro::
	.string "我告诉你，\n"
	.string "通过和小朋友战斗钱来得不快。$"

Route17_Text_IsaiahRematchIntro::
	.string "来吧，朋友！\n"
	.string "我对我的身材非常自豪！$"

Route17_Text_VirgilRematchIntro::
	.string "你出来就为了散步？$"

Route17_Text_BillyRematchIntro::
	.string "我们是飙车族！\n"
	.string "我们掌控公路，伙计！$"

Route17_Text_NikolasRematchIntro::
	.string "我的霹雳电球决定，\n"
	.string "今天由你给它充电！$"

Route17_Text_ZeekRematchIntro::
	.string "我让我的宝可梦不断的升级，\n"
	.string "但它们始终不进化，怎么回事？$"

Route17_Text_JamalRematchIntro::
	.string "嘎啊！我急需锻炼\n"
	.string "然后减掉我松弛的肌肉！$"

Route17_Text_CoreyRematchIntro::
	.string "特立独行是男人的标志！$"

Route17_Text_JaxonRematchIntro::
	.string "哟，真不错的自行车！\n"
	.string "操纵感如何？$"

Route17_Text_WilliamRematchIntro::
	.string "认输吧，小子！\n"
	.string "我累坏了！$"

Route18_Text_WiltonRematchIntro::
	.string "我走遍每一片草地\n"
	.string "希望能遇到新的宝可梦。\p"
	.string "但这个没我想的那么简单……$"

Route18_Text_RamiroRematchIntro::
	.string "咕噜咯噜唬噜噜！\n"
	.string "我呼唤鸟的技术有提高吧？$"

Route18_Text_JacobRematchIntro::
	.string "我之前警告过你了，\n"
	.string "这是属于我的草地！\p"
	.string "我不想看到你在旁边晃来晃去。$"

Route19_Text_RichardRematchIntro::
	.string "一听说要出去游泳\n"
	.string "我全身就开始发热了。$"

Route19_Text_ReeceRematchIntro::
	.string "等等！慢点！\n"
	.string "撞着我了怎么办？$"

Route19_Text_MatthewRematchIntro::
	.string "我爱游泳！\n"
	.string "我猜你是爱好冲浪的那类。$"

Route19_Text_DouglasRematchIntro::
	.string "地平线上面是什么？\n"
	.string "你看到了吗？$"

Route19_Text_DavidRematchIntro::
	.string "我再次尝试潜水去寻找宝可梦，\n"
	.string "和之前一样还是没有收获。$"

Route19_Text_TonyRematchIntro::
	.string "每当我看见大海\n"
	.string "我就能忘掉所有不愉快的事。\p"
	.string "……比如上次我败给你的那个事！$"

Route19_Text_AnyaRematchIntro::
	.string "你总是骑在你的\n"
	.string "宝可梦身上……\p"
	.string "看起来很舒服的样子……\n"
	.string "如果我赢了你能不能让我也骑一下？$"

Route19_Text_AliceRematchIntro::
	.string "游泳的感觉太妙了！\n"
	.string "太阳晒不着我！$"

Route19_Text_AxleRematchIntro::
	.string "这片水域暗藏杀机！\n"
	.string "你已经回不去了！$"

Route19_Text_ConnieRematchIntro::
	.string "我只是和我朋友一起游到这里的……\n"
	.string "我累得不行了……\l"
	.string "我们必须战斗么？$"

Route19_Text_LiaRematchIntro::
	.string "真奈：你知道我的弟弟刚刚\n"
	.string "成为一名训练家吧？\p"
	.string "我想要让它变得更强。\n"
	.string "所以再次需要你的帮助了。$"

Route19_Text_LucRematchIntro::
	.string "阿弘：我的姐姐教我\n"
	.string "所有关于宝可梦的事情。\p"
	.string "我希望我能变得更强。$"

Route20_Text_BarryRematchIntro::
	.string "这里的水很浅。\n"
	.string "人们都在这儿游泳。$"

Route20_Text_ShirleyRematchIntro::
	.string "你对我能在双子\n"
	.string "度假感到羡慕嫉妒恨吧？$"

Route20_Text_TiffanyRematchIntro::
	.string "我喜欢和鱼儿们一起在\n"
	.string "海浪上航行。$"

Route20_Text_IreneRematchIntro::
	.string "你也在度假吧？$"

Route20_Text_DeanRematchIntro::
	.string "看看瞧瞧我的体格！\p"
	.string "和以前相比\n"
	.string "现在的我可是满状态的！$"

Route20_Text_DarrinRematchIntro::
	.string "为什么你要骑在宝可梦身上？\n"
	.string "没人教过你怎么游泳吗？$"

Route20_Text_RogerRematchIntro::
	.string "我是骑着鸟宝可梦\n"
	.string "到这里来的。$"

Route20_Text_NoraRematchIntro::
	.string "我的男朋友给了我一些巨大的珍珠。\n"
	.string "它们会变得更大的！$"

Route20_Text_MissyRematchIntro::
	.string "我从红莲镇游到了这里。\n"
	.string "说实话，那可真不太轻松。$"

Route20_Text_MelissaRematchIntro::
	.string "在西面的红莲那里\n"
	.string "有一个宝可梦的研究所\p"
	.string "我爸爸就在那里工作。$"

Route21_North_Text_RonaldRematchIntro::
	.string "如果鱼正在咬你的钩\n"
	.string "你想不想马上就知道呢？$"

Route21_North_Text_WadeRematchIntro::
	.string "我又拉了一批大货！\n"
	.string "想要再来一场吗？$"

Route21_North_Text_SpencerRematchIntro::
	.string "大海——\n"
	.string "是男人的浪漫——！$"

@ Unused trainer from RB that had a rematch intro added
Route21_North_Text_CueBallRematchIntro::
	.string "きょうも　およぎに\n"
	.string "きちまったぜ$"

Route21_South_Text_JackRematchIntro::
	.string "我在海里收服了我的宝可梦。\n"
	.string "现在我也在那里训练它们。$"

Route21_South_Text_JeromeRematchIntro::
	.string "现在，我又参加了另一个\n"
	.string "铁人三项大赛！$"

Route21_South_Text_RolandRematchIntro::
	.string "啊～！\n"
	.string "阳光照在身上好舒服！$"

Route21_South_Text_ClaudeRematchIntro::
	.string "嘿，你不能等会再砍么。\n"
	.string "你把鱼都给吓跑了！$"

Route21_South_Text_NolanRematchIntro::
	.string "鱼上钩之前\n"
	.string "我就陪你玩玩吧。$"

Route21_North_Text_LilRematchIntro::
	.string "千沙：嗯？想再打一场？\n"
	.string "阿胜，你不会想一个人在战斗吧？$"

Route21_North_Text_IanRematchIntro::
	.string "阿胜：我姐姐还是那么差劲。\n"
	.string "请帮我激起她的斗志！$"

Route25_Text_JoeyRematchIntro::
	.string "我绝不会在这里认输！$"

Route25_Text_DanRematchIntro::
	.string "爸爸带我在枯叶市\n"
	.string "那里的圣特安努号度过了愉快的假期。$"

Route25_Text_FlintRematchIntro::
	.string "我非常帅气。\n"
	.string "我交到了女朋友！\p"
	.string "这次我一定要让她\n"
	.string "看到我有多帅！$"

Route25_Text_KelseyRematchIntro::
	.string "嗨！\n"
	.string "我的男朋友实在是太帅了！\l"
	.string "我今天的心情非常好！$"

Route25_Text_ChadRematchIntro::
	.string "我有这种感觉……\n"
	.string "我知道我必须和你再战一场！$"

Route25_Text_HaleyRematchIntro::
	.string "我朋友有许多可爱的宝可梦。\n"
	.string "我真是嫉妒死了！$"

Route25_Text_FranklinRematchIntro::
	.string "我只在月见山上训练，\n"
	.string "但我一直没有放松过！$"

Route25_Text_NobRematchIntro::
	.string "有一位宝可梦狂住在海角上\n"
	.string "你没有看到过他的收藏吗？$"

Route25_Text_WayneRematchIntro::
	.string "你又想去见正辉了？\n"
	.string "首先，让我再战一场吧！$"

Route24_Text_ShaneRematchIntro::
	.string "呵呵……！你的出色表现\n"
	.string "我在草丛里可都看到了。$"

Route24_Text_EthanRematchIntro::
	.string "好！\n"
	.string "我来虐你了！$"

Route24_Text_ReliRematchIntro::
	.string "你看起来总是很忙……\n"
	.string "你就不累吗？$"

Route24_Text_TimmyRematchIntro::
	.string "你肯定很乐意到\n"
	.string "金珠大桥来。$"

Route24_Text_AliRematchIntro::
	.string "我们曾经有过战斗……\p"
	.string "尽管我输了，\n"
	.string "但我还是最棒的，不是吗？$"

Route24_Text_CaleRematchIntro::
	.string "人们都把这里叫做金珠\n"
	.string "诚子！\p"
	.string "你曾经击败过我们，\n"
	.string "所以你不必再接受我们的挑战了。\p"
	.string "……但是我们很欢迎\n"
	.string "你对我们的再次挑战。$"

OneIsland_TreasureBeach_Text_AmaraRematchIntro::
	.string "躺着，耳边是摇滚的旋律……\n"
	.string "时间在不知不觉中流逝了……$"

OneIsland_KindleRoad_Text_MariaRematchIntro::
	.string "天气真是好啊！\n"
	.string "我来把它变坏试试吧。$"

OneIsland_KindleRoad_Text_AbigailRematchIntro::
	.string "我的皮肤被晒伤了……$"

OneIsland_KindleRoad_Text_FinnRematchIntro::
	.string "那只火鸟在山上\n"
	.string "投下了巨大的阴影……$"

OneIsland_KindleRoad_Text_GarrettRematchIntro::
	.string "我有强烈的预感\n"
	.string "我这次会赢！$"

OneIsland_KindleRoad_Text_TommyRematchIntro::
	.string "等一下！我是说再等一下！\n"
	.string "我确定我这次钓上大鱼了！$"

OneIsland_KindleRoad_Text_SharonRematchIntro::
	.string "你又来给我\n"
	.string "送经验值了吗？$"

OneIsland_KindleRoad_Text_TanyaRematchIntro::
	.string "在训练中我们甚至没有\n"
	.string "虚度过一天！$"

OneIsland_KindleRoad_Text_SheaRematchIntro::
	.string "在每天吃早饭之前，\n"
	.string "我都会围绕这个岛游……\l"
	.string "三遍！$"

OneIsland_KindleRoad_Text_HughRematchIntro::
	.string "衣服穿好了再来战斗！\n"
	.string "舍弃那些轻浮的打扮！$"

OneIsland_KindleRoad_Text_BryceRematchIntro::
	.string "你知道吗，当你在野外的时候\n"
	.string "所有东西尝起来都是可口的。$"

OneIsland_KindleRoad_Text_ClaireRematchIntro::
	.string "我又吃撑了，你能和我们战斗一场\n"
	.string "帮助我消化消化吗？$"

OneIsland_KindleRoad_Text_KiaRematchIntro::
	.string "阿幸：我的哥哥和我组成了\n"
	.string "最棒的组合！\p"
	.string "我们不会再输了！$"

OneIsland_KindleRoad_Text_MikRematchIntro::
	.string "阿和：只要和阿幸在一起，\n"
	.string "我们就不会惧怕任何事情！\p"
	.string "这次我们会证明给你看！$"

ThreeIsland_BondBridge_Text_NikkiRematchIntro::
	.string "我们要再战一场？$"

ThreeIsland_BondBridge_Text_VioletRematchIntro::
	.string "你又来了，\n"
	.string "什么时候才能结束呢？$"

ThreeIsland_BondBridge_Text_AmiraRematchIntro::
	.string "我希望有那么一天\n"
	.string "我可以不用救生圈游泳了。$"

ThreeIsland_BondBridge_Text_AlexisRematchIntro::
	.string "哈哈！\n"
	.string "宝可梦！$"

ThreeIsland_BondBridge_Text_TishaRematchIntro::
	.string "喔，不，难道我没有告诉过你吗？\n"
	.string "请，离我远点！$"

ThreeIsland_BondBridge_Text_JoyRematchIntro::
	.string "由井：我们可是变强了！\n"
	.string "不是一般的强！$"

ThreeIsland_BondBridge_Text_MegRematchIntro::
	.string "理子：你战胜不了今天的我们了！$"

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
	.string "嗨，你好！\p"
	.string "你打算在一个好的环境里\n"
	.string "训练你的宝可梦吗？$"

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
	.string "借助这些力量，\n"
	.string "来书写我今天的胜利。$"

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
	.string "我们必须得再战斗一场？\n"
	.string "我正在努力创作。\l"
	.string "请不要破坏我精心构建的画面！$"

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
	.string "我依然没有任何进步……\n"
	.string "我还是没有找到正确的角度……$"

FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
	.string "哦，你是打算给我和你\n"
	.string "再战一场的机会吗？$"

FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
	.string "他们基本上完成了\n"
	.string "给宝可梦修建这个湖的工程。\p"
	.string "你有空最好来这里逛逛。$"

FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
	.string "我是一个好短跑者。\n"
	.string "我已经得到了更快的速度！$"

FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
	.string "啊，朋友！\n"
	.string "让我们愉快的度过我们在一起的时光吧！$"

FiveIsland_MemorialPillar_Text_MiloRematchIntro::
	.string "在驯鸟师兄弟里\n"
	.string "我年龄最大，没忘记我吧？\p"
	.string "很好，我就是喜欢\n"
	.string "鸟类们锐利的喙的那位！$"

FiveIsland_MemorialPillar_Text_ChazRematchIntro::
	.string "在驯鸟师兄弟里\n"
	.string "我是老二。\p"
	.string "我喜欢鸟类们的翅膀\n"
	.string "让我们再战一场！$"

FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
	.string "在驯鸟师兄弟里\n"
	.string "我年龄最小。\p"
	.string "我喜欢鸟类们的羽毛。\n"
	.string "我从没有想过我能再见到你！$"

SixIsland_OutcastIsland_Text_TylorRematchIntro::
	.string "我依然没有交上任何好运。\n"
	.string "在这场战斗里应该能转运了！$"

SixIsland_OutcastIsland_Text_MymoRematchIntro::
	.string "哈……哈……\p"
	.string "我又从六之岛的港口\n"
	.string "游到了这里。$"

SixIsland_OutcastIsland_Text_NicoleRematchIntro::
	.string "当我游泳时，\n"
	.string "你总是一个人就过来了。$"

SixIsland_OutcastIsland_Text_AvaRematchIntro::
	.string "美香：让我们再来一场\n"
	.string "二对二的战斗吧！$"

SixIsland_OutcastIsland_Text_GebRematchIntro::
	.string "阿雅：我姐姐变得比\n"
	.string "以前更厉害可！$"

SixIsland_GreenPath_Text_JaclynRematchIntro::
	.string "……嗯？\p"
	.string "我在脑内构想我的房子，但是瞬间移动\n"
	.string "总是把我带到这里来！$"

SixIsland_WaterPath_Text_RoseRematchIntro::
	.string "喔，你好。\n"
	.string "再一次迎面吹来凉爽的风$"

SixIsland_WaterPath_Text_EdwardRematchIntro::
	.string "呵呵呵，我在准备\n"
	.string "新的阴谋了。$"

SixIsland_WaterPath_Text_SamirRematchIntro::
	.string "什么，看到我这样的\n"
	.string "游泳的人你觉得很困扰？\p"
	.string "啊啊，可别怪我！\n"
	.string "我们再战一场吧。$"

SixIsland_WaterPath_Text_DeniseRematchIntro::
	.string "唉……\n"
	.string "我的男朋友依然很忙……$"

SixIsland_WaterPath_Text_EarlRematchIntro::
	.string "来吧，告诉我吧。\n"
	.string "围绕着这里的山到底在哪里？$"

SixIsland_WaterPath_Text_MiuRematchIntro::
	.string "美羽：你好，宝可梦！\n"
	.string "是时候再战一场了！$"

SixIsland_WaterPath_Text_MiaRematchIntro::
	.string "美绪：你好，宝可梦！\n"
	.string "是时候再战一场了！$"

SixIsland_RuinValley_Text_StanlyRematchIntro::
	.string "这个世界上\n"
	.string "有很多的未解之谜。$"

SixIsland_RuinValley_Text_FosterRematchIntro::
	.string "嗨，我们见过面的吧？\n"
	.string "什么风又把你吹回来了？$"

SixIsland_RuinValley_Text_LarryRematchIntro::
	.string "据说在这个岛上\n"
	.string "有些神秘的石头。\p"
	.string "在我们最后一次见面前\n"
	.string "你有什么发现吗？$"

SixIsland_RuinValley_Text_DarylRematchIntro::
	.string "和你有一场复赛，加油了！$"

SixIsland_RuinValley_Text_HectorRematchIntro::
	.string "在这个岛上的其它东西面前\n"
	.string "我实在是太普通了。$"

SevenIsland_TrainerTower_Text_DarioRematchIntro::
	.string "我能感应到你的来临。$"

SevenIsland_TrainerTower_Text_RodetteRematchIntro::
	.string "在这个岛的某些地方，奇特的\n"
	.string "宝可梦在沉睡。$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
	.string "嘎哈哈哈！\p"
	.string "再来一次不能改变任何事。\n"
	.string "我轻轻一弹指头就能把你打飞！$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
	.string "嘿！你是我们爱好者\n"
	.string "俱乐部的一员，我没搞错吧？$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
	.string "这个岛实在是太大了……\n"
	.string "在这儿巡逻真麻烦……$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
	.string "我绝不会原谅那些滥用\n"
	.string "宝可梦的人！$"

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
	.string "阿夕：为了再次和你战斗\n"
	.string "我和阿高会再次站在一起$"

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
	.string "阿高：当我身边还有阿夕的时候，\n"
	.string "好像我就没输过，那次除外。$"

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
	.string "让我们再战一场吧。\n"
	.string "我的状态可是满满的！$"

SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
	.string "如果你带着最强的宝可梦\n"
	.string "那也毫无影响……\p"
	.string "如果你不懂得怎么去运用它们\n"
	.string "那也说明不了任何问题！$"

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
	.string "我的工作是保护环境。\n"
	.string "同样，大自然也会保护我。$"

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
	.string "我们每次相遇\n"
	.string "你都穿着很时髦的鞋子。$"

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
	.string "你一定变得更强了吧。\n"
	.string "请你一定要跟我对战，拜托了！$"

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
	.string "我接受了最高等的教育\n"
	.string "才变得这么强的！\p"
	.string "这次我不会输的了。\n"
	.string "绝对不会！$"

SevenIsland_SevaultCanyon_Text_LexRematchIntro::
	.string "阿力：我最亲爱的阿雪，我们\n"
	.string "一起的话一定能赢的！$"

SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
	.string "阿雪：我不会拖累我的好友\n"
	.string "阿力的！我们一定会赢！$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
	.string "你有没有发现\n"
	.string "这石室的什么秘密？$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
	.string "传说有一种神秘的宝可梦\n"
	.string "在这里沉睡着。$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
	.string "我的老师正在给我\n"
	.string "展示怎样才能画的更好。$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
	.string "今天，我们上了课之后，\n"
	.string "再次来到了这个石室。$"
