Text_FirstShouldRestoreMonsHealth::
	.string "首先，你要把你的\n"
	.string "宝可梦恢复到最佳状态。$"

Text_MonsHealedShouldBuyPotions::
	.string "你的宝可梦\n"
	.string "已经完全恢复了！\p"
	.string "如果宝可梦的HP很低，\n"
	.string "抓紧来宝可梦中心哦！\p"
	.string "如果你需要在野外停留很久，\n"
	.string "可以在宝可梦商店\l"
	.string "买一些伤药以备不时之需。\p"
	.string "要加油哦！$"

Text_MonsHealed::
	.string "你的宝可梦\n"
	.string "已经痊愈了哦！\p"
	.string "欢迎下次再来。$"

Text_HadQuiteAnExperienceTakeRest::
	.string "妈妈：{PLAYER}！\n"
	.string "欢迎回家。\p"
	.string "听起来你似乎经历了一场\n"
	.string "相当的冒险啊！\p"
	.string "也许你要休息一下了。$"

Text_MomExplainHPGetPotions::
	.string "妈妈：哦，太好了！\n"
	.string "你和你的宝可梦看起来精力充沛！\p"
	.string "我刚刚从大木博士那儿得知，\p"
	.string "宝可梦的HP就是它们的体力。\p"
	.string "当你的宝可梦的HP很低时，\n"
	.string "就去宝可梦中心回复吧。\p"
	.string "如果你要到很远的地方旅行，\n"
	.string "就在宝可梦商店买一些\l"
	.string "伤药带着吧。\p"
	.string "加油，孩子！\p"
	.string "要坚持到底哦！$"

Text_WhitedOutLostMoney::
	.string "{PLAYER}没有能用的\n"
	.string "宝可梦了！\p"
	.string "{PLAYER}很害怕，同时丢掉了¥{B_COPY_VAR_1}…\p"
	.string "…… ……\p"
	.string "{PLAYER}眼前一片黑！$"

Text_WhitedOut::
	.string "{PLAYER}没有能用的\n"
	.string "宝可梦了！\p"
	.string "{PLAYER}眼前一片黑！$"
