LavenderTown_Text_DoYouBelieveInGhosts::
    .string "你相信世界上真的有幽灵吗？$"

LavenderTown_Text_SoThereAreBelievers::
    .string "真的？\n"
    .string "真有相信的啊……$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "哈哈哈，我可不这么认为喔。\p"
    .string "看你肩膀上那只白色的鬼手……\n"
    .string "……这只是我的想象而已。$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "这个小镇因有着\n"
    .string "宝可梦们的坟墓而闻名。\p"
    .string "悼念它们的活动就在\n"
    .string "宝可梦塔里举办。$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "幽灵在宝可梦塔里出没。\p"
    .string "我想那应该是被火箭队杀掉的 \n"
    .string "宝可梦的灵魂吧。$"

LavenderTown_Text_TownSign::
    .string "紫苑镇\n"
    .string "高贵的紫色小镇$"

LavenderTown_Text_SilphScopeNotice::
    .string "新的西尔佛检视镜！\n"
    .string "让无形的东西变得有形！\p"
    .string "西尔佛公司.$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "紫苑宝可梦\n"
    .string "救助所$"

LavenderTown_Text_PokemonTowerSign::
    .string "宝可梦塔\n"
    .string "宝可梦的灵魂在这里安息$"

