PokemonMansion_Text_PressSecretSwitchJP::
    .string "ひみつの　スイッチが　ある！\p"
    .string "おして　みますか？$"

PokemonMansion_Text_LetsTryIt::
    .string "おしてみよう！　‥ポチッとな$"

PokemonMansion_Text_GaveUpOnPressingSwitch::
    .string "おすのは　あきらめた$"

PokemonMansion_1F_Text_SimonIntro::
    .string "说起来，\n"
    .string "这房子还真是大啊！$"

PokemonMansion_1F_Text_SimonDefeat::
    .string "啊呀！$"

PokemonMansion_1F_Text_SimonPostBattle::
    .string "……我想知道我伙伴去哪了？$"

PokemonMansion_1F_Text_BraydonIntro::
    .string "我老师以前就住在这里。$"

PokemonMansion_1F_Text_BraydonDefeat::
    .string "呼！\n"
    .string "让人喘不过气来！$"

PokemonMansion_1F_Text_BraydonPostBattle::
    .string "所以，你被卡住了吗？\n"
    .string "试着从那边跳下去！$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo::
    .string "日记：2月6号\n"
    .string "梦幻生产了。\p"
    .string "我们把新生的宝可梦称作超梦。$"

