Route2_EastBuilding_Text_GiveHM05IfSeen10Mons::
    .string "嗨！还记得我吗？\n"
    .string "我是一个大木博士的助手。\p"
    .string "如果你的宝可梦图鉴收集了十个\n"
    .string "数据，我会给你\l"
    .string "一个小奖品。\p"
    .string "大木博士委托我带\n"
    .string "秘传学习器05给你。\p"
    .string "{PLAYER}，我问问你。\p"
    .string "你收集了十个不同\n"
    .string "的宝可梦数据了吗？$"

Route2_EastBuilding_Text_GreatHereYouGo::
    .string "太好了！你已经拥有了\n"
    .string "{B_COPY_VAR_3}种宝可梦的数据！\p"
    .string "恭喜你！\n"
    .string "它是你的了！$"

Route2_EastBuilding_Text_ReceivedHM05FromAide::
    .string "{PLAYER}从助手那里\n"
    .string "得到了秘传学习器05。$"

Route2_EastBuilding_Text_ExplainHM05::
    .string "秘传学习器05包含了隐藏招式\n"
    .string "闪光。\p"
    .string "闪光能照亮黑暗的洞穴\n"
    .string "和隧道。$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel::
    .string "一旦有宝可梦学会了闪光，\n"
    .string "你就能通过岩山隧道了。$"

