Route12_Text_MonSprawledOutInSlumber::
    .string "宝可梦似乎\n"
    .string "睡得很舒服的样子。$"

Text_SnorlaxWokeUp::
    .string "卡比兽醒来了！\p"
    .string "它发动着狂暴的攻击扑了过来！$"

Text_SnorlaxReturnedToMountains::
    .string "卡比兽平静了下来。\n"
    .string "它打了个大哈欠…\l"
    .string "回山上去了。$"

Text_WantToUsePokeFlute::
    .string "要使用宝可梦之笛吗？$"

Text_PlayedPokeFlute::
    .string "{PLAYER}吹起了宝可梦之笛。$"

Route12_Text_NedIntro::
    .string "噢、噢！\n"
    .string "上钩了，上钩了！$"

Route12_Text_NedDefeat::
    .string "切！\n"
    .string "是条小鱼……$"

Route12_Text_NedPostBattle::
    .string "坚持！\n"
    .string "我的线卡住了！$"

Route12_Text_ChipIntro::
    .string "……不要急！\n"
    .string "等待也是钓鱼的乐趣之一！$"

Route12_Text_ChipDefeat::
    .string "哎呀……！\n"
    .string "你等一下。$"

Route12_Text_ChipPostBattle::
    .string "用这根好点的钓竿，\n"
    .string "就可以钓起来更好的宝可梦……$"

Route12_Text_JustinIntro::
    .string "我在寻找月之石。\n"
    .string "你有看到过吗？$"

Route12_Text_JustinDefeat::
    .string "哎呀呀呀……！$"

Route12_Text_JustinPostBattle::
    .string "我的宝可梦需要靠\n"
    .string "月之石进化。\p"
    .string "我打赌一定会赢的。$"

Route12_Text_LucaIntro::
    .string "电属性就是我的特长。\p"
    .string "海里的宝可梦什么的，\n"
    .string "我完全不懂。$"

Route12_Text_LucaDefeat::
    .string "呼呀、呼呀……$"

Route12_Text_LucaPostBattle::
    .string "水导电，\n"
    .string "所以电能打败海里的宝可梦。$"

Route12_Text_HankIntro::
    .string "钓鱼白痴VS\n"
    .string "宝可梦小孩！$"

Route12_Text_HankDefeat::
    .string "太感人了！$"

Route12_Text_HankPostBattle::
    .string "我猜你在你爱好的事情方面\n"
    .string "很在行。\p"
    .string "我承认你在宝可梦方面赢了我，\n"
    .string "但在垂钓方面你撼动不了我的王座。$"

Route12_Text_ElliotIntro::
    .string "我热爱钓鱼，你可别冤枉了我。\p"
    .string "但是我如果有更多的活可干\n"
    .string "就更好了。$"

Route12_Text_ElliotDefeat::
    .string "这并不容易……$"

Route12_Text_ElliotPostBattle::
    .string "没关系。\n"
    .string "失败不能影响我。$"

Route12_Text_AndrewIntro::
    .string "钓到了什么？\p"
    .string "你永远不能提前知道\n"
    .string "你钓到了什么！$"

Route12_Text_AndrewDefeat::
    .string "失手了啊。$"

Route12_Text_AndrewPostBattle::
    .string "什么，又是鲤鱼王？\p"
    .string "我钓到的总是它！真的。\n"
    .string "可它们实在太弱了。$"

Route12_Text_RouteSign::
    .string "12号道路 \n"
    .string "往北到紫苑$"

Route12_Text_SportfishingArea::
    .string "垂钓地带$"

Route12_Text_JesIntro::
    .string "阿重：如果我赢了，\n"
    .string "我就答应阿谀的求婚。$"

Route12_Text_JesDefeat::
    .string "阿重：喔，拜托，\n"
    .string "为什么不让我们赢啊？$"

Route12_Text_JesPostBattle::
    .string "阿重：噢，阿谀，原谅我，\n"
    .string "亲爱的！$"

Route12_Text_JesNotEnoughMons::
    .string "阿重：阿谀和我，\n"
    .string "我们会永远在一起\p"
    .string "如果你没有两只宝可梦\n"
    .string "我们不会和你战斗。$"

Route12_Text_GiaIntro::
    .string "阿谀：嘿，阿重……\p"
    .string "如果我们赢了，我就要娶你！$"

Route12_Text_GiaDefeat::
    .string "阿谀：哦，为什么？$"

Route12_Text_GiaPostBattle::
    .string "阿谀：阿重，你太笨了！\n"
    .string "你毁了这一切！$"

Route12_Text_GiaNotEnoughMons::
    .string "阿谀：我可不能忍受\n"
    .string "没有我的阿重的战斗！\p"
    .string "你还有更多宝可梦吗？$"
