SaffronCity_Gym_Text_SabrinaIntro::
    .string "我能预知到你的到来。\p"
    .string "当我还是小女孩的时候，\n"
    .string "我就拥有了超能力。\p"
    .string "某个早上我拿起汤勺\n"
    .string "使它弯曲了过来。\p"
    .string "虽然我厌恶暴力，但如果你是认真的，\n"
    .string "我是不会手下留情的！{PLAY_BGM 0x56 0x01}$"

SaffronCity_Gym_Text_SabrinaDefeat::
    .string "真是惊讶，我竟然输了！\n"
    .string "不过，输了就是输了。\p"
    .string "我承认，\n"
    .string "我没有用尽全力来取得胜利。\p"
    .string "为了嘉奖你的胜利，\n"
    .string "给予你这枚金黄徽章。$"

SaffronCity_Gym_Text_SabrinaPostBattle::
    .string "超能力并不只是\n"
    .string "少数人的特异功能。\p"
    .string "每个人都拥有超能力。\n"
    .string "只是人们没有意识到这一点罢了。$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
    .string "金黄徽章能让\n"
    .string "70级以下的宝可梦听从你的命令。\p"
    .string "越强大的宝可梦会更具有野性，\n"
    .string "在战斗中可能会无视你的命令。\p"
    .string "为了避免这个问题，就不要把\n"
    .string "你的宝可梦训练得过于强大。\p"
    .string "这个招式学习器也送个你吧。$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
    .string "{PLAYER}从娜姿那里\n"
    .string "得到了招式学习器04。$"

SaffronCity_Gym_Text_ExplainTM04::
    .string "招式学习器04是“冥想”！\p"
    .string "它能让宝可梦集中起精力\n"
    .string "把特攻和特防一起提升。$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
    .string "你的包包装满了其它道具。$"

SaffronCity_Gym_Text_AmandaIntro::
    .string "娜姿比我更年轻。\n"
    .string "但是我依然尊敬她。$"

SaffronCity_Gym_Text_AmandaDefeat::
    .string "输了！$"

SaffronCity_Gym_Text_AmandaPostBattle::
    .string "在普通的战斗中，\n"
    .string "更强的那只将会成为赢家。\p"
    .string "如果你想打败娜姿，\n"
    .string "就集中精神祈祷你能够胜利吧。$"

SaffronCity_Gym_Text_JohanIntro::
    .string "我们隐藏的力量吓到你了吗？$"

SaffronCity_Gym_Text_JohanDefeat::
    .string "我也是会输的啊……$"

SaffronCity_Gym_Text_JohanPostBattle::
    .string "超能力属性宝可梦只害怕\n"
    .string "幽灵和虫子们！$"

SaffronCity_Gym_Text_StacyIntro::
    .string "从宝可梦身上看得出它们训练家\n"
    .string "的样子。\p"
    .string "你的宝可梦一定是强大的那种！$"

SaffronCity_Gym_Text_StacyDefeat::
    .string "啊……果然是这样。$"

SaffronCity_Gym_Text_StacyPostBattle::
    .string "我还有得学呢……\p"
    .string "我必须掌握好超能力，然后教给\n"
    .string "我的宝可梦……$"

SaffronCity_Gym_Text_TyronIntro::
    .string "你明白了吗？\p"
    .string "只靠蛮力并不足以在\n"
    .string "宝可梦的世界中获胜？$"

SaffronCity_Gym_Text_TyronDefeat::
    .string "我不相信！$"

SaffronCity_Gym_Text_TyronPostBattle::
    .string "娜姿轻松地打败了\n"
    .string "隔壁的空手大王。$"

SaffronCity_Gym_Text_TashaIntro::
    .string "你和我，我们的宝可梦必须\n"
    .string "战上一场！$"

SaffronCity_Gym_Text_TashaDefeat::
    .string "唔……！\n"
    .string "我果然被打败了么。$"

SaffronCity_Gym_Text_TashaPostBattle::
    .string "我早就知道会\n"
    .string "结果会是这样。$"

SaffronCity_Gym_Text_CameronIntro::
    .string "虽然娜姿很年轻，但她也是\n"
    .string "我们本领高强的领袖。\p"
    .string "你要超越她很难！$"

SaffronCity_Gym_Text_CameronDefeat::
    .string "我输了！$"

SaffronCity_Gym_Text_CameronPostBattle::
    .string "在金黄曾经有两个\n"
    .string "宝可梦道馆。\p"
    .string "不过隔壁的格斗道场\n"
    .string "不再是道馆了。\p"
    .string "当我们决定只保留一个道馆时，\n"
    .string "我们就把它们简单地合并了。$"

SaffronCity_Gym_Text_PrestonIntro::
    .string "金黄宝可梦道馆以\n"
    .string "超能力训练而闻名。\p"
    .string "你想见娜姿，对吗？\n"
    .string "我已经预感到了！$"

SaffronCity_Gym_Text_PrestonDefeat::
    .string "呜哇啊啊……！$"

SaffronCity_Gym_Text_PrestonPostBattle::
    .string "我用读心术了解了你的想法！\n"
    .string "没错！$"

SaffronCity_Gym_Text_GymGuyAdvice::
    .string "哟！\n"
    .string "未来的冠军！\p"
    .string "娜姿的宝可梦用超能力\n"
    .string "来对抗暴力。\p"
    .string "超能力属性宝可梦对\n"
    .string "格斗属性宝可梦效果绝佳。\p"
    .string "甚至在它们还没打出一拳之前，\n"
    .string "就被撂翻在地了。$"

SaffronCity_Gym_Text_GymGuyPostVictory::
    .string "超能力的力量，哈？\p"
    .string "如果我也有，我就能把力量\n"
    .string "萃集在一起。$"

SaffronCity_Gym_Text_GymStatue::
    .string "金黄宝可梦道馆\n"
    .string "馆主：娜姿\p"
    .string "优胜训练家：\n"
    .string "{B_OPPONENT_MON1_NAME}$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
    .string "金黄宝可梦道馆\n"
    .string "馆主：娜姿\p"
    .string "优胜训练家：\n"
    .string "{B_OPPONENT_MON1_NAME}，{PLAYER}$"

