PokemonTower_6F_Text_AngelicaIntro::
    .string "给……我……\n"
    .string "血……$"

PokemonTower_6F_Text_AngelicaDefeat::
    .string "咕哇！$"

PokemonTower_6F_Text_AngelicaPostBattle::
    .string "我感到乏力而虚弱……$"

PokemonTower_6F_Text_EmiliaIntro::
    .string "呃……\n"
    .string "嗬啊！$"

PokemonTower_6F_Text_EmiliaDefeat::
    .string "……有什么东西从\n"
    .string "我身上离开了！$"

PokemonTower_6F_Text_EmiliaPostBattle::
    .string "我头发才没有掉出来！\n"
    .string "那是一个邪恶的幽灵！$"

PokemonTower_6F_Text_JenniferIntro::
    .string "啊啊……啊……啊！\n"
    .string "……啊、啊啊……啊啊！$"

PokemonTower_6F_Text_JenniferDefeat::
    .string "啊！$"

PokemonTower_6F_Text_JenniferPostBattle::
    .string "这儿发生了什么事？$"

PokemonTower_6F_Text_BeGoneIntruders::
    .string "离开这里……\n"
    .string "入侵者……$"

PokemonTower_6F_Text_GhostWasCubonesMother::
    .string "这个幽灵是卡拉卡拉母亲\n"
    .string "不能安息的灵魂！$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
    .string "母亲的灵魂平静了下来。\p"
    .string "它转世投胎去了……$"

