VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .string "有一些邪恶的人们\n"
    .string "用宝可梦从事犯罪活动。\p"
    .string "比如说，火箭队\n"
    .string "非法交易珍贵的宝可梦。\p"
    .string "他们也遗弃那些他们认为\n"
    .string "不受欢迎的或没用了的宝可梦。\p"
    .string "我说的就是火箭队，\n"
    .string "他们真是一群可怕的人。$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .string "我认为宝可梦品质的好坏\n"
    .string "完全取决于它的训练家，\p"
    .string "你觉得呢？$"

