Text_ExplosionTeach::
    .string "你能想象吗？\n"
    .string "如果这座火山喷发？\p"
    .string "随之而来的爆炸会要了\n"
    .string "我们的命。那该有多恐怖？\p"
    .string "趁我们还在害怕的时候，\n"
    .string "你想让我教你大爆炸吗？$"

Text_ExplosionDeclined::
    .string "嗯，没错。\n"
    .string "这太可怕了。$"

Text_ExplosionWhichMon::
    .string "你真是勇敢！\p"
    .string "哪只宝可梦想要学会\n"
    .string "大爆炸？$"

Text_ExplosionTaught::
    .string "在这座火山上使用大爆炸……\p"
    .string "这真是让我毛骨悚然地兴奋！$"

@ Below 4 are unused JP versions of the above texts
Text_ExplosionTeachJP::
    .string "こ　この　かざんが\n"
    .string "もし　だいばくはつ　したら\l"
    .string "お　おれら　ひとたまりも\l"
    .string "ないなあ　‥ブルブル！\p"
    .string "こ　こわい　ついでに\n"
    .string "だいばくはつ　でも　おぼえてみる？$"

Text_ExplosionDeclinedJP::
    .string "や　やっぱ　こわいもんな\n"
    .string "ブルブル$"

Text_ExplosionWhichMonJP::
    .string "つ　つよきだね！\n"
    .string "じゃあ　どの　ポケモンに　する？$"

Text_ExplosionTaughtJP::
    .string "かざんで　だいばくはつを‥\n"
    .string "す　すごい　スリル！$"

MtEmber_Exterior_Text_WellTryDiggingHere::
    .string "在这里。\n"
    .string "我们会试着在这里挖掘。\p"
    .string "干部们谈论的宝藏应该就在这里。$"

MtEmber_Exterior_Text_YoureInTheWayGetLost::
    .string "搞什么呢……?\n"
    .string "你挡道了。给我滚开。$"

MtEmber_Exterior_Text_PunchedThroughAtLast::
    .string "呼，总算打穿了。\n"
    .string "让我们去挖掘宝藏吧！$"

MtEmber_Exterior_Text_WhatsPasswordAgain::
    .string "我们发现的任何宝藏，\n"
    .string "都要拖回仓库的，明白吗？\p"
    .string "……哦，顺便密码是什么？\n"
    .string "我是说火箭队仓库的密码。$"

MtEmber_Exterior_Text_FirstPasswordGoldeen::
    .string "什么，你把密码忘了？\n"
    .string "实际上密码有两个。\p"
    .string "第一个是“多多少少\n"
    .string "少少多多。”\p"
    .string "第二个是……$"

MtEmber_Exterior_Text_SnoopsBeenListeningIn::
    .string "嘿！\n"
    .string "这家伙一直在偷听！$"

MtEmber_Exterior_Text_Grunt1Intro::
    .string "你一直在偷听我们说话，\n"
    .string "对吗？$"

MtEmber_Exterior_Text_Grunt1Defeat::
    .string "呃，什么？$"

MtEmber_Exterior_Text_Grunt1PostBattle::
    .string "为什么你一定要赢？$"

MtEmber_Exterior_Text_Grunt2Intro::
    .string "想要着偷走我们的宝藏？\n"
    .string "趁早放弃吧！$"

MtEmber_Exterior_Text_Grunt2Defeat::
    .string "等等！\n"
    .string "但是该怎么做？$"

MtEmber_Exterior_Text_Grunt2PostBattle::
    .string "健忘症能很方便地\n"
    .string "使你忘记你所听到的一切！$"

MtEmber_Exterior_Text_WellRegroupDontStepInsideThere::
    .string "好一次挫折啊……\n"
    .string "我们要重新组队。\p"
    .string "你！不要妄想从这儿往里走一步！\p"
    .string "如果你想知道做什么最好，\n"
    .string "那就放弃往里走的念头吧！$"

MtEmber_Exterior_Text_LoganIntro::
    .string "活火山是指正在喷发的，\n"
    .string "或将要喷发的火山。$"

MtEmber_Exterior_Text_LoganDefeat::
    .string "呜……太热了！\n"
    .string "汗山爆发啊！$"

MtEmber_Exterior_Text_LoganPostBattle::
    .string "有人说世界上有超过1500个活火山。\p"
    .string "只是想想就让我感到全身发热！$"

MtEmber_Exterior_Text_BethIntro::
    .string "你知道火山中的洞穴是如何形成的吗？$"

MtEmber_Exterior_Text_BethDefeat::
    .string "啊！\n"
    .string "你真是令人震惊的强大！$"

MtEmber_Exterior_Text_BethPostBattle::
    .string "当岩浆表面的熔岩变硬，\n"
    .string "其内部的岩浆流了出来，\l"
    .string "洞穴就形成了。$"

MtEmber_Exterior_Text_JocelynIntro::
    .string "我不断地锻炼来修补\n"
    .string "我破碎的心……\p"
    .string "那至少让我在身体上更坚韧！\n"
    .string "嗬呀！$"

MtEmber_Exterior_Text_JocelynDefeat::
    .string "我觉得我做太过了……$"

MtEmber_Exterior_Text_JocelynPostBattle::
    .string "你战斗的方式，\n"
    .string "使我想起了甩了我的家伙……$"

