SSAnne_B1F_Room4_Text_LeonardIntro::
    .string "你知道他们是怎样\n"
    .string "评价水手的战斗的！$"

SSAnne_B1F_Room4_Text_LeonardDefeat::
    .string "好！\n"
    .string "真是一场不错的对战。$"

SSAnne_B1F_Room4_Text_LeonardPostBattle::
    .string "哈哈哈！\n"
    .string "你要不要也来当水手啊？$"

SSAnne_B1F_Room4_Text_DuncanIntro::
    .string "那就来吧！\n"
    .string "赌上我身为水手的尊严！$"

SSAnne_B1F_Room4_Text_DuncanDefeat::
    .string "你的精神让我沉没了！$"

SSAnne_B1F_Room4_Text_DuncanPostBattle::
    .string "你见过枯叶市的\n"
    .string "钓鱼大师了吗？$"

