Text_RockSlideTeach::
    .string "像这种落石繁多的山，\n"
    .string "会有偶尔岩崩的危险！\p"
    .string "你敢想象么？\n"
    .string "巨石滚下来砸到你了？\p"
    .string "就是那样，哇啊啊啊啊哈！\n"
    .string "恐怖吧！\p"
    .string "你看起来似乎并不害怕呀。\n"
    .string "你想让宝可梦学会岩崩吗？$"

Text_RockSlideDeclined::
    .string "哦呀，其实你还是很害怕的嘛。$"

Text_RockSlideWhichMon::
    .string "哪只宝可梦\n"
    .string "想要学会岩崩？$"

Text_RockSlideTaught::
    .string "我害怕在这条隧道里\n"
    .string "用它……$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
    .string "提示：岩石可能会改变\n"
    .string "水的流向。$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
    .string "危险\n"
    .string "水流湍急！$"

