CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
    .string "只有这里才能买到\n"
    .string "宝可梦能力增强剂。\p"
    .string "HP增强剂增加宝可梦的基础HP。\p"
    .string "特攻增强剂提升宝可梦的基础特攻。\p"
    .string "特防增强剂提升宝可梦的基础特防。\p"
    .string "速度增强剂提升宝可梦的基础速度。$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
    .string "我是来这里\n"
    .string "买宝可梦能力增强剂的。\p"
    .string "攻击增强剂增加宝可梦的基础攻击。\p"
    .string "防御增强剂增加宝可梦的基础防御。$"

CeladonCity_DepartmentStore_5F_Text_Drugstore::
    .string "五楼：药店$"

