SilphCo_7F_Text_HaveMonForSavingUs::
    .string "啊！你！你不是火箭队的吧！\n"
    .string "你是来救我们吗？\l"
    .string "呃，谢谢！\p"
    .string "我想把这个宝可梦送给你\n"
    .string "来表达感谢。$"

SilphCo_7F_Text_ObtainedLaprasFromEmployee::
    .string "{PLAYER}从西尔佛的员工处\n"
    .string "得到了一只拉普拉斯！$"

SilphCo_7F_Text_ExplainLapras::
    .string "这是一只拉普拉斯。\n"
    .string "这种宝可梦非常聪明！\p"
    .string "它不应该一辈子待在实验室，\n"
    .string "而是应该有属于它更广阔的天地！\p"
    .string "你是优秀的训练家，\n"
    .string "它应该跟着你！\p"
    .string "拉普拉斯还是游泳高手，\n"
    .string "它能带你漫游四海！$"

SilphCo_7F_Text_RocketBossWentToBoardroom::
    .string "火箭队的头目闯进了\n"
    .string "会议室！\p"
    .string "我现在很担心\n"
    .string "我们老板的安危！$"

SilphCo_7F_Text_OhNo::
    .string "あ‥　もう　もてないぞ$"

SilphCo_7F_Text_SavedAtLast::
    .string "たすかったよ　ありがと！$"

SilphCo_7F_Text_RocketsAfterMasterBall::
    .string "火箭队想抢劫大师球，\n"
    .string "那是能抓住任何宝可梦的精灵球。$"

SilphCo_7F_Text_CanceledMasterBallProject::
    .string "我们延缓了大师球开发项目，\n"
    .string "就是因为担心火箭队搞破坏！$"

SilphCo_7F_Text_BadIfTeamRocketTookOver::
    .string "如果西尔佛公司被火箭队占领，\n"
    .string "那后果将不堪设想！$"

SilphCo_7F_Text_WowYouChasedOffTeamRocket::
    .string "真的吗？\p"
    .string "你一个人就赶走了\n"
    .string "全部火箭队成员？$"

SilphCo_7F_Text_ReallyDangerousHere::
    .string "小朋友！\n"
    .string "这里很危险！\p"
    .string "你要来救我？\n"
    .string "你做不到的！$"

SilphCo_7F_Text_ThankYouSoMuch::
    .string "终于得救了……谢谢你！$"

SilphCo_7F_Text_Grunt3Intro::
    .string "哎呀！\n"
    .string "我闻到了一只小老鼠的气味！$"

SilphCo_7F_Text_Grunt3Defeat::
    .string "这怎么可能！$"

SilphCo_7F_Text_Grunt3PostBattle::
    .string "别到处乱窜了！\n"
    .string "我不会让你妨碍老大的！$"

SilphCo_7F_Text_JoshuaIntro::
    .string "哈哈哈！\p"
    .string "你把我当成\n"
    .string "西尔佛的员工了吧？$"

SilphCo_7F_Text_JoshuaDefeat::
    .string "我完成了！$"

SilphCo_7F_Text_JoshuaPostBattle::
    .string "尽管你如此年轻，你也是一个\n"
    .string "技术高超的训练家！$"

SilphCo_7F_Text_Grunt1Intro::
    .string "我是火箭队\n"
    .string "四兄弟之一！$"

SilphCo_7F_Text_Grunt1Defeat::
    .string "哎咳！\n"
    .string "哥哥，我输了！$"

SilphCo_7F_Text_Grunt1PostBattle::
    .string "没关系。\n"
    .string "我的哥哥们会好好回报你的！$"

SilphCo_7F_Text_Grunt2Intro::
    .string "一个少年入侵者？\n"
    .string "那一定就是你！$"

SilphCo_7F_Text_Grunt2Defeat::
    .string "好吧！\n"
    .string "我输了！$"

SilphCo_7F_Text_Grunt2PostBattle::
    .string "在把我们的老大惹火之前\n"
    .string "赶快回家吧！$"

SilphCo_7F_Text_RivalWhatKeptYou::
    .string "{B_OPPONENT_MON1_NAME}：你来的可真慢，{PLAYER}？$"

SilphCo_7F_Text_RivalIntro::
    .string "{B_OPPONENT_MON1_NAME}：哈哈哈！我等在这儿\n"
    .string "还以为会让你感动万分呢！\p"
    .string "我猜火箭队拖慢了你\n"
    .string "的脚步？我才不会管那些呢！\p"
    .string "我在金黄市看到了你，所以我决定\n"
    .string "来看看你是否有所成长了！$"

SilphCo_7F_Text_RivalDefeat::
    .string "噢，伙计！\n"
    .string "那么，你已经准备好面对\l"
    .string "火箭队老大了吗！$"

SilphCo_7F_Text_RivalVictory::
    .string "{RIVAL}“おまえなあ‥\p"
    .string "こんな　うでまえじゃ\n"
    .string "まだまだ‥\l"
    .string "いちにんまえ　とは　いえないぜ$"

SilphCo_7F_Text_RivalPostBattle::
    .string "好，{PLAYER}！\n"
    .string "那我先走一步了！\p"
    .string "只要查询宝可梦图鉴，我\n"
    .string "就能知道哪个宝可梦比较强以及\l"
    .string "它们是怎么进化的！\p"
    .string "哈哈我真是个天才啊\p"
    .string "我准备去宝可梦联盟把\n"
    .string "四天王消灭掉。\p"
    .string "我将会成为世界上\n"
    .string "最强大的训练家！\p"
    .string "{PLAYER}，嗯，祝你好运！\n"
    .string "别翻白眼哦！\l"
    .string "哈哈！$"

SilphCo_7F_Text_FloorSign::
    .string "西尔佛公司总部\n"
    .string "7F$"

