SixIsland_WaterPath_House1_Text_LoveItNeedItHeracross::
    .string "赫拉，赫拉，赫拉克罗斯！\n"
    .string "威武闪光的虫属性之王！\l"
    .string "我爱它，我需要它！赫拉克罗斯！$"

SixIsland_WaterPath_House1_Text_MayIMeasureHeracross::
    .string "哎呦！\n"
    .string "那是一只赫拉克罗斯！\p"
    .string "快，快！\n"
    .string "我能量量它有多大吗……$"

SixIsland_WaterPath_House1_Text_ItsXInchesDeserveReward::
    .string "哎呦，它居然有{B_COPY_VAR_2}英寸！\n"
    .string "我从来没见过这样大的！\l"
    .string "这是你应得的奖励。$"

SixIsland_WaterPath_House1_Text_WantToSeeBiggerOne::
    .string "我想看到一只比这个\n"
    .string "还要大一些的赫拉克罗斯。\p"
    .string "啊，我是多么喜欢它啊！\n"
    .string "巨大的赫拉克罗斯！$"

SixIsland_WaterPath_House1_Text_ItsXInchesSameAsBefore::
    .string "哼？这只{B_COPY_VAR_2}英寸的……\n"
    .string "不是和原来那只一样吗！$"

SixIsland_WaterPath_House1_Text_ItsXInchesYInchesWasBiggest::
    .string "哦，它只有{B_COPY_VAR_2}英寸。\n"
    .string "原来那只赫拉克罗斯比它更大。\p"
    .string "它有{B_COPY_VAR_3}英寸，\n"
    .string "那是我见过的最大的赫拉克罗斯。$"

SixIsland_WaterPath_House1_Text_ThisWontDo::
    .string "哦，不！这不可能是赫拉克罗斯！\p"
    .string "赫拉克罗斯看起来更有气概，\n"
    .string "更加冷酷，还有一只可爱的触角！$"

SixIsland_WaterPath_House1_Text_YourBagIsFull::
    .string "你的包包满了。\n"
    .string "装不下我的奖励了。$"

SixIsland_WaterPath_House1_Text_BiggestHeracrossIsXInches::
    .string "目前为止，我看过的最大的赫拉克罗斯，\n"
    .string "尺寸为：\p"
    .string "{B_COPY_VAR_3}英寸！$"

SixIsland_WaterPath_House1_Text_BlankChartOfSomeSort::
    .string "那差不多是一张空白的图表。\p"
    .string "它有空间\n"
    .string "来写一些记录。$"

