RocketHideout_B1F_Text_Grunt1Intro::
    .string "……你是谁？\n"
    .string "是怎么进来的？$"

RocketHideout_B1F_Text_Grunt1Defeat::
    .string "哦！\n"
    .string "我被打败了！$"

RocketHideout_B1F_Text_Grunt1PostBattle::
    .string "该死……是你瞧不起\n"
    .string "火箭队的吧？$"

RocketHideout_B1F_Text_Grunt2Intro::
    .string "就是你闯入了火箭队的\n"
    .string "总部吧？太不像话了！$"

RocketHideout_B1F_Text_Grunt2Defeat::
    .string "轰隆～！$"

RocketHideout_B1F_Text_Grunt2PostBattle::
    .string "我们不会轻易放过\n"
    .string "你的，小子！$"

RocketHideout_B1F_Text_Grunt3Intro::
    .string "发现入侵者！$"

RocketHideout_B1F_Text_Grunt3Defeat::
    .string "我做不到！$"

RocketHideout_B1F_Text_Grunt3PostBattle::
    .string "西尔佛检视镜？哼！\n"
    .string "我不知道它在哪里。$"

RocketHideout_B1F_Text_Grunt4Intro::
    .string "你为什么来这里？$"

RocketHideout_B1F_Text_Grunt4Defeat::
    .string "不可能！$"

RocketHideout_B1F_Text_Grunt4PostBattle::
    .string "好吧，我说……\n"
    .string "乘电梯去见我们的老大吧。$"

RocketHideout_B1F_Text_Grunt5Intro::
    .string "你迷路了吗，小老鼠？$"

RocketHideout_B1F_Text_Grunt5Defeat::
    .string "为什么……？$"

RocketHideout_B1F_Text_Grunt5PostBattle::
    .string "喔不，那阵骚动不知怎的\n"
    .string "打开了门！$"

