SixIsland_PokemonCenter_1F_Text_SomethingHiddenOnThisIsland::
    .string "我已经寻找遗迹\n"
    .string "十余年了。\p"
    .string "不，也许是二十年。\p"
    .string "我能感觉到\n"
    .string "这个岛上一定藏着什么东西。$"

SixIsland_PokemonCenter_1F_Text_SomeMonsEvolveByTradingWithHeldItem::
    .string "你知道那些只能\n"
    .string "通讯进化的宝可梦，对吗？\p"
    .string "但你知道的东西\n"
    .string "可能不全面哦。\p"
    .string "一些宝可梦只有携带特殊的道具\n"
    .string "才能通讯进化哦！$"

SixIsland_PokemonCenter_1F_Text_RivalImpossibleToGetAllMonsAroundHere::
    .string "{B_OPPONENT_MON1_NAME}：嘿，{PLAYER}！\n"
    .string "你的宝可梦图鉴收集的怎么样了？\p"
    .string "不过看起来，在这片大陆\n"
    .string "没有办法收集齐宝可梦啊……\p"
    .string "也许，在我们未知的领域，\n"
    .string "还有其它不同的宝可梦呢……\p"
    .string "…… …… ……\p"
    .string "啊，不过我不能做到的话\n"
    .string "你也一定做不到。\p"
    .string "但我不会放弃的！\p"
    .string "我会在训练宝可梦的过程中，\n"
    .string "也在继续努力收复宝可梦。\p"
    .string "所以我已经没有理由再呆在这儿了。\l"
    .string "也许，我也会离开家。\p"
    .string "没错，然后……\n"
    .string "展开我新的旅程！$"

