RocketHideout_B4F_Text_GiovanniIntro::
    .string "首先，我想我必须承认，我对你\n"
    .string "能来到这里很是惊讶。\p"
    .string "火箭队从世界各地\n"
    .string "收服宝可梦。\p"
    .string "它们是让我们的犯罪事业\n"
    .string "持续下去的重要工具。\p"
    .string "而我就是他们的老大，坂木！\p"
    .string "你的嚣张到此为止了，\n"
    .string "你将会承受到整个世界的痛苦！$"

RocketHideout_B4F_Text_GiovanniDefeat::
    .string "什么！\n"
    .string "这不可能！$"

RocketHideout_B4F_Text_GiovanniPostBattle::
    .string "我看到你养育的宝可梦\n"
    .string "是被你悉心照顾的。\p"
    .string "像你这样的孩子永远不会\n"
    .string "理解我所希望达到的目的。\p"
    .string "这一次我先选择撤退！\p"
    .string "我希望我们能再次见面……$"

RocketHideout_B4F_Text_Grunt2Intro::
    .string "我认识你！\n"
    .string "是你毁了我们在月见山的计划！$"

RocketHideout_B4F_Text_Grunt2Defeat::
    .string "又被毁了！$"

RocketHideout_B4F_Text_Grunt2PostBattle::
    .string "你对火箭队有\n"
    .string "特殊的感情吗？$"

RocketHideout_B4F_Text_Grunt3Intro::
    .string "难道你看不懂\n"
    .string "我们的邪恶的美学吗？$"

RocketHideout_B4F_Text_Grunt3Defeat::
    .string "啊呀！$"

RocketHideout_B4F_Text_Grunt3PostBattle::
    .string "老大！\n"
    .string "对不起我让你失望了！$"

RocketHideout_B4F_Text_Grunt1Intro::
    .string "电梯不运行？\n"
    .string "谁有电梯的钥匙呀？$"

RocketHideout_B4F_Text_Grunt1Defeat::
    .string "不要啊！$"

RocketHideout_B4F_Text_Grunt1PostBattle::
    .string "哦，不！\n"
    .string "我把电梯的钥匙给弄丢了！$"

