SafariZone_North_Text_RestHouse::
    .string "休息屋$"

SafariZone_North_Text_SecretHouseStillAhead::
    .string "……有用的公告牌！\p"
    .string "神秘小屋仍在前方。$"

SafariZone_North_Text_Area2::
    .string "栖息地2$"

SafariZone_North_Text_ZigzagThroughTallGrass::
    .string "……有用的公告牌！\p"
    .string "宝可梦隐藏在高高的草丛中。\p"
    .string "在草丛中区折前行，\n"
    .string "就能把他们找出来。$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
    .string "……有用的公告牌！\p"
    .string "找到神秘小屋就\n"
    .string "能获得免费的秘传学习器。$"

