VictoryRoad_2F_Text_DawsonIntro::
    .string "如果你能从这里通过，\n"
    .string "你就可以去见四天王。$"

VictoryRoad_2F_Text_DawsonDefeat::
    .string "……这不可能！$"

VictoryRoad_2F_Text_DawsonPostBattle::
    .string "要是谈起宝可梦方面的知识，\n"
    .string "我绝对比你强！$"

VictoryRoad_2F_Text_DaisukeIntro::
    .string "这里就是冠军之路。\n"
    .string "这是训练家的最终试炼！$"

VictoryRoad_2F_Text_DaisukeDefeat::
    .string "阿嚏！$"

VictoryRoad_2F_Text_DaisukePostBattle::
    .string "当你被卡住的时候，\n"
    .string "试着移动一些在周围的巨石。$"

VictoryRoad_2F_Text_NelsonIntro::
    .string "啊，你想挑战\n"
    .string "四天王吗？$"

VictoryRoad_2F_Text_NelsonDefeat::
    .string "……好强！$"

VictoryRoad_2F_Text_NelsonPostBattle::
    .string "{B_OPPONENT_MON1_NAME}到此一游。$"

VictoryRoad_2F_Text_VincentIntro::
    .string "来吧！\n"
    .string "我会击垮你！$"

VictoryRoad_2F_Text_VincentDefeat::
    .string "呀啊！$"

VictoryRoad_2F_Text_VincentPostBattle::
    .string "你获得了进入\n"
    .string "冠军之路的权利……$"

VictoryRoad_2F_Text_GregoryIntro::
    .string "怎么样！\n"
    .string "冠军之路难走吗？$"

VictoryRoad_2F_Text_GregoryDefeat::
    .string "干得好！$"

VictoryRoad_2F_Text_GregoryPostBattle::
    .string "许多训练家放弃在\n"
    .string "这里的挑战，回老家结婚去了。$"

@ Unused, old text for Moltres
VictoryRoad_2F_Text_Gyaoo::
    .string "ギヤーオ！$"

