SSAnne_Deck_Text_ShipDepartingSoon::
    .string "派对结束了。\n"
    .string "船很快就要离港了。$"

SSAnne_Deck_Text_ScrubbingDecksHardWork::
    .string "真是的！\n"
    .string "打扫甲板真是太不让人省心了！$"

SSAnne_Deck_Text_FeelSeasick::
    .string "呃……我不舒服……\p"
    .string "我晕船，所以我出来\n"
    .string "呼吸点新鲜空气……$"

SSAnne_Deck_Text_EdmondIntro::
    .string "嗨，朋友！\p"
    .string "我们来跳支舞吧！$"

SSAnne_Deck_Text_EdmondDefeat::
    .string "你真了不起！$"

SSAnne_Deck_Text_EdmondPostBattle::
    .string "你认为这个世界上\n"
    .string "一共有多少种宝可梦？$"

SSAnne_Deck_Text_TrevorIntro::
    .string "喂，你！\n"
    .string "你晕船吗？$"

SSAnne_Deck_Text_TrevorDefeat::
    .string "大意了么。$"

SSAnne_Deck_Text_TrevorPostBattle::
    .string "我老爸说一共有100种宝可梦。\n"
    .string "我感觉应该不止这么多。$"

