FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons::
    .string "科拿： 把你肮脏的手从\n"
    .string "洞穴里的宝可梦中挪开！\p"
    .string "照我说的做，不然要你好看！$"

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe::
    .string "啊，请冷静一下，小姐，\n"
    .string "让我们冷静一下。\p"
    .string "别让你的眼镜上爬满雾气啊！$"

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut::
    .string "科拿：{PLAYER}？！\n"
    .string "你在这儿做什么？\p"
    .string "别急，我们等会儿能赶上的。\n"
    .string "现在，我需要你的帮助。\p"
    .string "在这些入侵者做出什么之前，\n"
    .string "帮我把他们赶出去。\p"
    .string "他们在这里捉宝可梦，\n"
    .string "然后统统拿拿出去去卖了！\p"
    .string "准备好了吗？\n"
    .string "你去对付他！$"

FourIsland_IcefallCave_Back_Text_GruntIntro::
    .string "什-什么？！\p"
    .string "为啥我们不能用抓到的宝可梦\n"
    .string "做我们想做的事情？$"

FourIsland_IcefallCave_Back_Text_GruntDefeat::
    .string "我们没想到结果会是这样！$"

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons::
    .string "科拿：哼。\n"
    .string "真是弱爆了。\p"
    .string "你！\n"
    .string "告诉我！\p"
    .string "你把你们抓到的宝可梦放在哪了？\p"
    .string "不说的话我就\n"
    .string "砸烂你的戒指！$"

FourIsland_IcefallCave_Back_Text_NotTellingYouThat::
    .string "没-没门！\n"
    .string "我不会告诉你的！$"

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou::
    .string "科拿：我的拉普拉斯对你们对它同伴的\n"
    .string "所做所为感到十分愤怒。\p"
    .string "如果你不肯说出来的话，\n"
    .string "就让它把你们冻成冰块吧。\p"
    .string "上吧，拉普拉斯！\n"
    .string "冰冻光束！$"

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland::
    .string "哇！好吧！\n"
    .string "我说！\p"
    .string "宝可梦在五之岛的\n"
    .string "火箭队仓库里面。\p"
    .string "就在哪里！我都交代了…\n"
    .string "我们现在能过去吧！\p"
    .string "……但是我怀疑你能不能进得了\n"
    .string "火箭队仓库！\p"
    .string "呵呵呵呵！$"

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
    .string "{PLAYER}，谢谢你。\n"
    .string "但情况太糟糕了……\p"
    .string "我在这片岛屿上出生和长大。\p"
    .string "我没想到那些可恶的\n"
    .string "罪犯会来这里……$"

