CeruleanCity_House2_Text_RocketsStoleTMForDig::
    .string "那些卑鄙的火箭队！\p"
    .string "看看他们在我家里都干了些什么！\p"
    .string "他们偷了一个招式学习器去教\n"
    .string "宝可梦如何挖洞！\p"
    .string "我之前还打算把它用在\n"
    .string "猴怪或者穿山鼠上的……\p"
    .string "买它花了我好多钱呢！$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM::
    .string "我想丢的东西就丢了吧。\p"
    .string "我打算让地鼠不通过招式学习器\n"
    .string "学会挖洞。$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood::
    .string "火箭队一定想通过挖洞\n"
    .string "来做见不得人的事。$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut::
    .string "火箭队逃跑时留下了个洞！$"

