SSAnne_2F_Room2_Text_BrooksIntro::
    .string "与年轻人的对战\n"
    .string "才是人生的乐趣！$"

SSAnne_2F_Room2_Text_BrooksDefeat::
    .string "一场不错的对战。\n"
    .string "我好像重返年轻了。$"

SSAnne_2F_Room2_Text_BrooksPostBattle::
    .string "如果放在15年前，我肯定我能赢！$"

SSAnne_2F_Room2_Text_DaleIntro::
    .string "你看，这可都是\n"
    .string "我钓到的鱼哟！$"

SSAnne_2F_Room2_Text_DaleDefeat::
    .string "全都倒下了！$"

SSAnne_2F_Room2_Text_DalePostBattle::
    .string "聚会？\p"
    .string "船上的聚会现在应该结束了。$"

