VermilionCity_Text_GrimerMultipliesInSludge::
    .string "我们十分注重对环境的保护。\p"
    .string "我们曾经听说臭泥\n"
    .string "会在有毒的污泥里繁殖。$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor::
    .string "你看到圣特安努号\n"
    .string "停泊在港口了吗？$"

VermilionCity_Text_SSAnneHasDepartedForYear::
    .string "这样啊，圣特安努号离港了？\p"
    .string "她明年会回到\n"
    .string "枯叶来的。$"

VermilionCity_Text_BuildingOnThisLand::
    .string "我在这片土地上修房子。\n"
    .string "你所见的这一切都是我的。\p"
    .string "我的宝可梦\n"
    .string "在夯实这里的地块作为地基。$"

VermilionCity_Text_Machop::
    .string "腕力：嚎喔～～嚎嚎嚎～～$"

VermilionCity_Text_MachopStompingLandFlat::
    .string "腕力一边叫喊，\n"
    .string "一边弄平地面！$"

VermilionCity_Text_SSAnneVisitsOnceAYear::
    .string "圣特安努号是一艘\n"
    .string "著名的游轮。\p"
    .string "每年都来枯叶一次。$"

VermilionCity_Text_CitySign::
    .string "枯叶市\n"
    .string "落日下美丽的港口$"

VermilionCity_Text_SnorlaxBlockingRoute12::
    .string "通知！\p"
    .string "12号道路被一只\n"
    .string "熟睡着的宝可梦堵死了。\p"
    .string "请从岩山隧道绕道至\n"
    .string "紫苑镇。\p"
    .string "枯叶警察局$"

VermilionCity_Text_PokemonFanClubSign::
    .string "宝可梦发烧友俱乐部\n"
    .string "欢迎所有的宝可梦爱好者！$"

VermilionCity_Text_GymSign::
    .string "枯叶市宝可梦道馆\n"
    .string "馆主：马志士\l"
    .string "闪电般的美国人！$"

VermilionCity_Text_VermilionHarbor::
    .string "枯叶海港$"

VermilionCity_Text_WelcomeToTheSSAnne::
    .string "欢迎您搭乘圣特安努号！$"

VermilionCity_Text_DoYouHaveATicket::
    .string "欢迎来到圣特安努号！\p"
    .string "抱歉，您是否带了票？$"

VermilionCity_Text_FlashedSSTicket::
    .string "{FONT_NORMAL}{PLAYER}出示了船票！\p"
    .string "{FONT_MALE}很好！\n"
    .string "欢迎来到圣特安努号！$"

VermilionCity_Text_DontHaveNeededSSTicket::
    .string "{FONT_NORMAL}{PLAYER}没有带着他要的\n"
    .string "船票。\p"
    .string "{FONT_MALE}对不起！\p"
    .string "想登船必须得有票。$"

VermilionCity_Text_TheShipSetSail::
    .string "船顺利地航行着。$"

VermilionCity_Text_BoardSeagallopTriPass::
    .string "啊，你带着三岛通行证。\p"
    .string "想坐海烈焰马号\n"
    .string "来此海上旅行吗？$"

VermilionCity_Text_Seagallop7Departing::
    .string "好，万事俱备了。\p"
    .string "海烈焰马号将以7倍的高速\n"
    .string "马上起航。$"

VermilionCity_Text_BoardSeagallopRainbowPass::
    .string "啊，你带着彩虹通行证。\p"
    .string "想坐海烈焰马号\n"
    .string "来次海上旅行吗？$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock::
    .string "哦！是神秘船票啊！\n"
    .string "这可是难得的珍稀之物。\p"
    .string "您要是想前往肚脐岩，\n"
    .string "我们随时恭候大驾。$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland::
    .string "哦！是极光船票啊！\n"
    .string "这可是难得的珍稀之物。\p"
    .string "您要是想前往诞生之岛，\n"
    .string "我们随时恭候大驾。$"

VermilionCity_Text_BoardSeagallopFerry::
    .string "你想乘坐海烈焰马号游艇吗？$"

VermilionCity_Text_Seagallop10Departing::
    .string "好了，您登艇的相关手续已经\n"
    .string "办理完毕。\p"
    .string "海烈焰马号将以10倍的高速\n"
    .string "马上起航。$"

VermilionCity_Text_Seagallop12Departing::
    .string "好了，您登艇的相关手续已经\n"
    .string "办理完毕。\p"
    .string "海烈焰马号将以12倍的高速\n"
    .string "开始起航。$"

VermilionCity_Text_Route2AideHasPackageForYou::
    .string "嘿，你好啊，{PLAYER}！\n"
    .string "最近还好么？\p"
    .string "我是大木博士的一名助手。\p"
    .string "你碰到过其他助手吗？\p"
    .string "{PLAYER}，有人从博士那里带了一件包裹。\p"
    .string "他说会他在2号道路附近等你。\p"
    .string "如果你要去2号道路那边的话，\n"
    .string "请与他联系一下。$"

