@ All Trainer Tower text (Lobby and Roof) is interleaved here

TrainerTower_Lobby_Text_WelcomeToTrainerTower::
    .string "您好！\p"
    .string "欢迎来到来自各地的训练家的聚集地\n"
    .string "训练家之塔！$"

TrainerTower_Lobby_Text_TrainersUpToFloorNum::
    .string "来自世界各地的训练家\n"
    .string "聚到这里来对斗。\p"
    .string "我看看……\p"
    .string "现在，只有{B_COPY_VAR_1}层的训练家了！$"

TrainerTower_Lobby_Text_TrainersUpEighthFloor::
    .string "训练家正在第八层\n"
    .string "等着你的挑战。$"

TrainerTower_Lobby_Text_LikeToChallengeTrainers::
    .string "你想要挑战等待着你的训练家吗？$"

TrainerTower_Lobby_Text_StartClockGetSetGo::
    .string "好的，我要开始计时了，\n"
    .string "请尽你最大的努力去\p"
    .string "夺得分数……\p"
    .string "准备……\p"
    .string "开始！$"

TrainerTower_Lobby_Text_PleaseVisitUsAgain::
    .string "敬请再次光临！$"

TrainerTower_Lobby_Text_TooBadComeBackTryAgain::
    .string "太糟糕了。\p"
    .string "我想你已经很努力地在战斗了。\p"
    .string "请以后再来试试吧！$"

TrainerTower_Lobby_Text_GiveItYourBest::
    .string "我希望你发挥出了你所有的实力。$"

TrainerTower_Lobby_Text_MoveCounterHereWhenTrainersSwitch::
    .string "当训练家交换场地的时候，\n"
    .string "移动会很混乱。\p"
    .string "为了避免拥堵，\n"
    .string "我们将服务台移到了这儿，\p"
    .string "对您造成的不便深感歉意。$"

TrainerTower_Roof_Text_ImOwnerBattledPerfectly::
    .string "你好……\p"
    .string "我是这座塔的主人……\p"
    .string "天空屹立在塔顶之上……\p"
    .string "轻风温柔地抚摸着它……\p"
    .string "一切都是那么完美……\p"
    .string "你战斗的方式……\n"
    .string "也是一样的完美……$"

TrainerTower_Roof_Text_ThisIsForYou::
    .string "这是给你的……$"

TrainerTower_Roof_Text_DoneItInRecordTime::
    .string "真了不起！\p"
    .string "你能这么快地爬上来\n"
    .string "真是不可思议。\p"
    .string "事实上，\n"
    .string "你刚刚创造了最快的时间记录……\p"
    .string "我要将你的记录\n"
    .string "贴在在服务台那里。$"

TrainerTower_Roof_Text_TookSweetTimeGettingHere::
    .string "你好像花了\n"
    .string "不少时间才到达这里……$"

TrainerTower_Roof_Text_IdLikeToSeeBetterTime::
    .string "我希望能看到你更好的表现……\p"
    .string "我期待着你。\p"
    .string "在那个时候到来之前，再会了……$"

TrainerTower_Text_XMinYZSec::
    .string "{B_COPY_VAR_1}分{B_COPY_VAR_2}。{B_COPY_VAR_3}秒。$"

TrainerTower_Lobby_Text_HereAreTheResults::
    .string "せいせきひょうです$"

TrainerTower_Lobby_Text_NeedTwoMonsForDouble::
    .string "这是一场二对二的战斗。\p"
    .string "你至少需要有两只宝可梦才能战斗。$"

TrainerTower_Lobby_Text_ExplainTrainerTower::
    .string "在这个训练家之塔里，\n"
    .string "有一个叫做进攻计时的项目。\p"
    .string "您会被记录下从服务台\n"
    .string "到塔顶主人那儿的时间\l"
    .string "看看您到底有多快。\p"
    .string "最快的时间将会被记录在\n"
    .string "时间看板上\p"
    .string "试一试与您的朋友们比赛\n"
    .string "看看谁能最快到达。\p"
    .string "在这里打败训练家\n"
    .string "您将不会得到任何经验值和金钱。$"

TrainerTower_Lobby_Text_ThanksForCompeting::
    .string "感谢您的挑战！$"

TrainerTower_Lobby_Text_WonderWhatKindsOfTrainers::
    .string "我来这儿试试我有多厉害。\p"
    .string "我想知道会有什么样的训练家\n"
    .string "在等着我呢？\p"
    .string "真是伤脑筋啊！$"

TrainerTower_Lobby_Text_StairsTougherThanAnyBattle::
    .string "呼，呼……\p"
    .string "不管战斗了！\n"
    .string "爬这些楼梯比任何战斗都困难……$"

