PokemonLeague_LoreleisRoom_Text_Intro::
    .string "欢迎来到宝可梦联盟。\p"
    .string "我是四天王中的科拿。\p"
    .string "没有人能够比我更会使用\n"
    .string "冰属性的宝可梦。\p"
    .string "冰属性的招式是最强大的。\p"
    .string "当你的宝可梦被冻成冰块的时候\n"
    .string "它们就任我宰割！\p"
    .string "哈哈哈！\n"
    .string "你准备好了吗？{PLAY_BGM 0x56 0x01}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "欢迎来到宝可梦联盟。\p"
    .string "我，四天王中的科拿，\n"
    .string "重新回到了联盟！\p"
    .string "不管之前发生了什么。\n"
    .string "没有人比我更会使用\l"
    .string "冰属性的宝可梦。\p"
    .string "冰属性的招式是最强大的。\p"
    .string "当你的宝可梦被冻成冰块的时候\n"
    .string "它们就任我宰割！\p"
    .string "哈哈哈！\n"
    .string "你准备好了吗？{PLAY_BGM 0x56 0x01}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "……这不可能！$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "你比我想象的更厉害。\n"
    .string "朝下一个房间前进吧。\p"
    .string "宝可梦联盟的力量\n"
    .string "不止是如此而已。$"

