CeladonCity_Gym_Text_ErikaIntro::
    .string "你好……\n"
    .string "真是个好天气，对吧？\l"
    .string "太舒服了……\p"
    .string "……啊，亲爱的……\n"
    .string "我刚才一定是睡着了，欢迎你。\p"
    .string "我是莉佳。\n"
    .string "玉虹市的道馆馆主。\p"
    .string "我还是一名花道师。\p"
    .string "所以我的宝可梦全是草属性的。\p"
    .string "……啊，不好意思，我没注意到\n"
    .string "你是来挑战我的。\p"
    .string "来吧，不过我是不会输的。{PLAY_BGM 0x56 0x01}$"

CeladonCity_Gym_Text_ErikaDefeat::
    .string "啊！\n"
    .string "我认输了。\l"
    .string "你真是太强了。\p"
    .string "我必须授予你彩虹徽章。$"

CeladonCity_Gym_Text_ErikaPostBattle::
    .string "你在收集宝可梦？\n"
    .string "真是一项了不起的工程啊！\p"
    .string "我从不收集不可爱的宝可梦。$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis::
    .string "彩虹徽章可以让50级以下的\n"
    .string "宝可梦听从你的指挥。\p"
    .string "它也可以让你的宝可梦在战斗中\n"
    .string "和战斗外都能使用怪力。\p"
    .string "也请你收下这个。$"

CeladonCity_Gym_Text_ReceivedTM19FromErika::
    .string "{PLAYER}获得了招式学习器19。$"

CeladonCity_Gym_Text_ExplainTM19::
    .string "招式学习器19是“超级吸取”！\p"
    .string "这个招式造成伤害的一半\n"
    .string "会被宝可梦吸收以回复体力。\p"
    .string "学会了它宝可梦就能一直战斗！\n"
    .string "棒极了对不对！$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis::
    .string "你的包包满了。$"

CeladonCity_Gym_Text_KayIntro::
    .string "我要给你介绍一下这个道馆。\p"
    .string "只有真正的淑女才被允许进入！$"

CeladonCity_Gym_Text_KayDefeat::
    .string "你太粗鲁了！$"

CeladonCity_Gym_Text_KayPostBattle::
    .string "啊啊！\n"
    .string "我真希望莉佳好好教训你一下！$"

CeladonCity_Gym_Text_BridgetIntro::
    .string "哎呀，欢迎欢迎。\n"
    .string "我正好觉得有些无聊呢！$"

CeladonCity_Gym_Text_BridgetDefeat::
    .string "我化的妆！$"

CeladonCity_Gym_Text_BridgetPostBattle::
    .string "草属性宝可梦对水属性很有优势。\p"
    .string "它们也是岩石属性和地面属性\n"
    .string "宝可梦的克星。$"

CeladonCity_Gym_Text_TinaIntro::
    .string "……你之前是在偷看这里吗？$"

CeladonCity_Gym_Text_TinaDefeat::
    .string "你让我大开眼界！$"

CeladonCity_Gym_Text_TinaPostBattle::
    .string "啊，你是在看莉佳……\n"
    .string "不是看我……$"

CeladonCity_Gym_Text_TamiaIntro::
    .string "喂，喂！\n"
    .string "看看我的宝可梦！\p"
    .string "我喜欢草属性宝可梦。\n"
    .string "它们培育起来很容易。$"

CeladonCity_Gym_Text_TamiaDefeat::
    .string "不要啊！$"

CeladonCity_Gym_Text_TamiaPostBattle::
    .string "我们在道馆里只使用草属性宝可梦。\p"
    .string "至于为什么嘛……\n"
    .string "我们也用它们来插花的！$"

CeladonCity_Gym_Text_LisaIntro::
    .string "嘿，你好！\p"
    .string "我们不欢迎虫属性和火属性宝可梦！$"

CeladonCity_Gym_Text_LisaDefeat::
    .string "啊！你这家伙！$"

CeladonCity_Gym_Text_LisaPostBattle::
    .string "我们的馆主莉佳很文静，\n"
    .string "她在这一带可非常出名。$"

CeladonCity_Gym_Text_LoriIntro::
    .string "很高兴见到你。\n"
    .string "我的兴趣是训练宝可梦。$"

CeladonCity_Gym_Text_LoriDefeat::
    .string "你真是本领高强。$"

CeladonCity_Gym_Text_LoriPostBattle::
    .string "我马上要去相亲。\n"
    .string "所以必须得保持礼貌，\l"
    .string "特别是要对战的时候。$"

CeladonCity_Gym_Text_MaryIntro::
    .string "欢迎来到玉虹道馆！\p"
    .string "你最好不要\n"
    .string "小瞧了这里的小姐们。$"

CeladonCity_Gym_Text_MaryDefeat::
    .string "你可真厉害啊！$"

CeladonCity_Gym_Text_MaryPostBattle::
    .string "我没带上我最厉害的宝可梦。\n"
    .string "下次等着瞧！$"

CeladonCity_Gym_Text_GymStatue::
    .string "玉虹宝可梦道馆\n"
    .string "馆主：莉佳\p"
    .string "获胜训练家：\n"
    .string "{B_OPPONENT_MON1_NAME}$"

CeladonCity_Gym_Text_GymStatuePlayerWon::
    .string "玉虹宝可梦道馆\n"
    .string "馆主：莉佳\p"
    .string "获胜训练家：\n"
    .string "{B_OPPONENT_MON1_NAME}，{PLAYER}$"

