CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink::
    .string "我渴！\n"
    .string "我要饮料嘛！\p"
    .string "{FONT_NORMAL}给她一杯喝的吗？$"

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink::
    .string "要送她哪种饮料呢？$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis::
    .string "哇～哦！\p"
    .string "这个美味之水是送给我的吗？\p"
    .string "多谢款待！\p"
    .string "作为回礼，\n"
    .string "就把我的宝物送给你吧！$"

Text_ReceivedItemFromLittleGirl::
    .string "{PLAYER}从小女孩那里\n"
    .string "获得了一个{B_COPY_VAR_2}。$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16::
    .string "招式学习器16是“光墙”！\p"
    .string "这个招式可以\n"
    .string "减少宝可梦受到的特殊攻击伤害。$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis::
    .string "哇～哦！\p"
    .string "这个劲爽汽水是送给我的吗？\p"
    .string "多谢款待！\p"
    .string "作为回礼，\n"
    .string "就把我的宝物送给你吧！$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20::
    .string "招式学习器20是“神秘守护”！\p"
    .string "这个招式可以\n"
    .string "使你的宝可梦免受异常状态影响。$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis::
    .string "哇～哦！\p"
    .string "这个果汁牛奶是送给我的吗？\p"
    .string "多谢款待！\p"
    .string "作为回礼，\n"
    .string "就把我的宝物送给你吧！$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33::
    .string "招式学习器33是“反射壁”！\p"
    .string "这个招式可以\n"
    .string "减少宝可梦受到的物理攻击伤害。$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis::
    .string "你的包包满了！$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll::
    .string "不用了，谢谢！\n"
    .string "我一点不渴了！$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature::
    .string "信不信由你，\n"
    .string "我妹妹也是一个训练家。\p"
    .string "不过，她太任性了，\n"
    .string "都快把我逼疯了！$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink::
    .string "我快渴死了！\n"
    .string "我要喝饮料嘛！$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign::
    .string "天台：\n"
    .string "自动售货机$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave::
    .string "是自动贩卖机！\n"
    .string "想要的饮料是……$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney::
    .string "钱不够！$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut::
    .string "一罐{B_COPY_VAR_1}的饮料掉出来了！$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff::
    .string "你的包包满了！$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty::
    .string "口不渴了！$"

