Text_MetronomeTeach::
    .string "喔嚯嚯嚯！\n"
    .string "我想要教你一个有趣的招式！\p"
    .string "把它教给宝可梦，\n"
    .string "然后开心地看着它用出来的那一刻！\p"
    .string "这个招式的大名叫做挥指。\n"
    .string "你心动了吗？$"

Text_MetronomeDeclined::
    .string "我告诉你，真的很有趣！$"

Text_MetronomeWhichMon::
    .string "很好！\n"
    .string "哪只宝可梦想要学会这个招式？$"

Text_MetronomeTaught::
    .string "喔嚯嚯嚯！\n"
    .string "我来告诉你挥指的原理吧！\p"
    .string "它能刺激宝可梦的大脑\n"
    .string "来用出它并不会的招式！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe::
    .string "嘿！\p"
    .string "我是一个十二分重要的研究员。\n"
    .string "没错，十二分的重要。\p"
    .string "看，我在研究宝可梦的化石。\n"
    .string "每时每刻，我都在进行研究。\p"
    .string "你！\n"
    .string "有化石带给我吗？$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad::
    .string "噢！\n"
    .string "太不好了！$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP::
    .string "ちょっと　じかん　かかるよ！\p"
    .string "そこらへんを　すこし\n"
    .string "ブラブラ　してくると　よろしー！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife::
    .string "你来晚了。\n"
    .string "你跑哪儿去了？\p"
    .string "你的化石复活了！\n"
    .string "正如我所预料的那样，是一只{B_COPY_VAR_1}！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor::
    .string "{PLAYER}从研究员的手中\n"
    .string "得到了{B_COPY_VAR_1}。$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon::
    .string "ポケモン　いっぱいで　もてないね！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain::
    .string "喔！\n"
    .string "那正是{B_COPY_VAR_2}，我没看错！\p"
    .string "那是{B_COPY_VAR_1}的化石，\n"
    .string "一种被认为灭绝了的宝可梦！\p"
    .string "我研制的复活机器\n"
    .string "能让那只宝可梦回到这个世界！$"

@ TODO: Resolve text dump error below?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor::
    .string "所以呢！\n"
    .string "你得快点把它交给我！\p"
    .string "{FONT_NORMAL}{PLAYER}把\n"
    .string "{B_COPY_VAR_2}交给了这个奇怪的研究员$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk::
    .string "我只需要一点点时间！\n"
    .string "现在你可以出去走走！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain::
    .string "哎哎！\n"
    .string "你又来了！$"

