Route21_North_Text_RonaldIntro::
	.string "你想不想知道这儿的鱼是否咬人？$"

Route21_North_Text_RonaldDefeat::
	.string "铛！$"

Route21_North_Text_RonaldPostBattle::
	.string "我什么也捉不到。\n"
	.string "没有一只好的宝可梦！$"

Route21_North_Text_WadeIntro::
	.string "爆护！爆护！\n"
	.string "要和我的宝可梦战斗吗？$"

Route21_North_Text_WadeDefeat::
	.string "呵呵，鲤鱼王不仅仅\n"
	.string "是以等级区分的，懂吗？$"

Route21_North_Text_WadePostBattle::
	.string "为什么我钓到的\n"
	.string "都是鲤鱼王呢！$"

Route21_North_Text_SpencerIntro::
	.string "大海——\n"
	.string "是男人的浪漫——！$"

Route21_North_Text_SpencerDefeat::
	.string "啊呀！$"

Route21_North_Text_SpencerPostBattle::
	.string "大海是很伟大的，能包容一切，\n"
	.string "但是我也很喜欢山。$"

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro::
	.string "おれだって　たまには\n"
	.string "およぎに　くるぜ！$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat::
	.string "ぐわわ！$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle::
	.string "うきやすそう　だと？\n"
	.string "うるせー　おおきな　おせわだッ！$"
