CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor::
    .string "欢迎光临！\p"
    .string "你能去隔壁用代币换\n"
    .string "非常棒的奖品。$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins::
    .string "欢迎来到火箭游戏城！\p"
    .string "你需要代币吗？\n"
    .string "是否想购买一些呢？$"

CeladonCity_GameCorner_Text_ComePlaySometime::
    .string "不需要？\n"
    .string "那改天再来玩玩！$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase::
    .string "啊，抱歉。\n"
    .string "你还没有代币盒。$"

CeladonCity_GameCorner_Text_CoinCaseIsFull::
    .string "哎哟！\n"
    .string "你的代币盒满了。$"

CeladonCity_GameCorner_Text_CantAffordCoins::
    .string "你的代币数不够。$"

CeladonCity_GameCorner_Text_HereAreYourCoins::
    .string "谢谢。\n"
    .string "给你代币！$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace::
    .string "嘘，小声点。\p"
    .string "据说这里是火箭队经营的。$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds::
    .string "我认为这些机器的赔率都不同。$"

CeladonCity_GameCorner_Text_DoYouWantToPlay::
    .string "孩子，你想来一把吗？$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan::
    .string "{PLAYER}获得了10个代币。$"

CeladonCity_GameCorner_Text_DontNeedMyCoins::
    .string "我的代币可不能给你！$"

CeladonCity_GameCorner_Text_WinsComeAndGo::
    .string "有赢就有输。\n"
    .string "世事无常。$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck::
    .string "这些老虎机游戏……\n"
    .string "输赢全凭运气。$"

CeladonCity_GameCorner_Text_GymGuyAdvice::
    .string "嘿！\p"
    .string "别荒废在这里了，\n"
    .string "未来的冠军！\p"
    .string "玉虹道馆的馆主是莉佳。\p"
    .string "她是个与大自然融为一体的\n"
    .string "草属性宝可梦使用者。\p"
    .string "她精于花道，\n"
    .string "虽然她看上去很娇小……\p"
    .string "但她绝不是个可以小看的对手！$"

CeladonCity_GameCorner_Text_RareMonsForCoins::
    .string "你可以用赢来的代币可以去那儿\n"
    .string "换取稀有的宝可梦。\p"
    .string "但是，我老是赢不了！$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked::
    .string "赌博真是可怕！\n"
    .string "实在是太容易让人上瘾了！$"

CeladonCity_GameCorner_Text_WantSomeCoins::
    .string "怎么了？\n"
    .string "想要点代币吗？$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy::
    .string "{PLAYER}获得了20个代币。$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins::
    .string "你有好多代币啊！$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant::
    .string "哎呀！我需要更多的代币来换\n"
    .string "我想要的宝可梦！$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo::
    .string "干嘛干嘛？别烦我！\n"
    .string "给你代币，拿了就走吧！$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan::
    .string "{PLAYER}获得了20个代币。$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins::
    .string "你已经有那么多代币啦！$"

CeladonCity_GameCorner_Text_WatchReelsClosely::
    .string "窍门就是紧紧盯着轮盘看。$"

CeladonCity_GameCorner_Text_GruntIntro::
    .string "我负责看守这张海报！\n"
    .string "快走开，否则给你好看！$"

CeladonCity_GameCorner_Text_GruntDefeat::
    .string "铛！$"

CeladonCity_GameCorner_Text_GruntPostBattle::
    .string "火箭队藏身处被发现了！\p"
    .string "我得马上报告老大！$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt::
    .string "咦！\p"
    .string "海报后面有个开关！？\n"
    .string "试着按下去！$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired::
    .string "你还没有代币盒……$"

CeladonCity_GameCorner_Text_DontHaveCoinCase::
    .string "哎呀！\n"
    .string "你还没有代币盒哦！$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay::
    .string "一台老虎机！\n"
    .string "想玩玩吗？$"

CeladonCity_GameCorner_Text_OutOfOrder::
    .string "发生故障\n"
    .string "此机器已坏。$"

CeladonCity_GameCorner_Text_OutToLunch::
    .string "外出用餐\n"
    .string "此位置已预留。$"

CeladonCity_GameCorner_Text_SomeonesKeys::
    .string "不知是谁的钥匙！\n"
    .string "他们还会回来的。$"

