CinnabarIsland_Text_DoorIsLocked::
    .string "门被锁上了……$"

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab::
    .string "红莲道馆的夏伯很古怪。\p"
    .string "自从实验室建立以来\n"
    .string "他就一直住在岛上。$"

CinnabarIsland_Text_ScientistsExperimentInMansion::
    .string "科学家们在烧焦的建筑里\n"
    .string "做实验。\p"
    .string "就是在那边被称做是\n"
    .string "宝可梦屋的地方。$"

CinnabarIsland_Text_IslandSign::
    .string "红莲镇\n"
    .string "燃烧着炽热欲望的小镇$"

CinnabarIsland_Text_PokemonLab::
    .string "宝可梦研究所$"

CinnabarIsland_Text_GymSign::
    .string "红莲镇宝可梦道馆\n"
    .string "馆主：夏伯\l"
    .string "燃烧的谜题狂人！$"

CinnabarIsland_Text_HeyIfItIsntPlayer::
    .string "嗯？\n"
    .string "嘿，这不是{PLAYER}吗！$"

CinnabarIsland_Text_ComeWithMeToOneIsland::
    .string "看，是我，正辉。\n"
    .string "真是好久不见了！\p"
    .string "希望你还在使用我的\n"
    .string "电脑系统。\p"
    .string "既然我们在这里遇上，\n"
    .string "要不要陪我一下？\p"
    .string "在遥远的南方有个小岛\n"
    .string "叫做一之岛。\p"
    .string "一个朋友邀请我过去玩玩，\n"
    .string "我正在去他那儿的路上。\p"
    .string "怎么样？\n"
    .string "你想跟我一块去吗？$"

CinnabarIsland_Text_AllRightLetsGo::
    .string "那么好吧。\n"
    .string "我们走！$"

CinnabarIsland_Text_IllBeWaitingInPokeCenter::
    .string "什么，你很忙？\p"
    .string "那好吧。\n"
    .string "船到现在还没有到。\p"
    .string "我会在宝可梦中心等着你。\p"
    .string "你忙完了之后，\n"
    .string "再过来找我吧。$"

CinnabarIsland_Text_MyPalsBoatArrived::
    .string "看起来我同伴的船也到了。\p"
    .string "他是特意来\n"
    .string "红莲镇接我的。$"

CinnabarIsland_Text_IfYouHaveTriPassYouCanGoAgain::
    .string "这次的旅程有点长吧？\p"
    .string "我伙伴锦辉似乎很喜欢\n"
    .string "和你在一起度过的时光。\p"
    .string "如果你再次拜访他，\n"
    .string "他肯定会很欢迎你的。\p"
    .string "有了三岛通行证之后，\n"
    .string "你可以在枯叶港乘船。\l"
    .string "就这样吧，谢谢你陪我！$"

