SilphCo_6F_Text_RocketsTookOverBuilding::
    .string "火箭队闯进来\n"
    .string "占领了这幢大厦！$"

SilphCo_6F_Text_BetterGetBackToWork::
    .string "……好了好了！\n"
    .string "去工作啊去工作！$"

SilphCo_6F_Text_HelpMePlease::
    .string "哆了个嗦……\n"
    .string "我的神啊救救我吧……$"

SilphCo_6F_Text_WeGotEngaged::
    .string "我们已经订婚了！\n"
    .string "……没想到我也会害羞啊。$"

SilphCo_6F_Text_ThatManIsSuchACoward::
    .string "那个坐在我旁边的人……\n"
    .string "真是个懦夫！$"

SilphCo_6F_Text_NeedsMeToLookAfterHim::
    .string "他很绝望，他需要\n"
    .string "像我这样的人来照顾他。$"

SilphCo_6F_Text_RocketsTryingToConquerWorld::
    .string "火箭队正试图用宝可梦\n"
    .string "征服世界。$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou::
    .string "火箭队逃跑了，\n"
    .string "这都对亏有你！$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts::
    .string "他们一定是因为宝可梦产品\n"
    .string "而盯上了我们西尔佛。$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder::
    .string "等你长大了就来\n"
    .string "西尔佛来上班吧。$"

SilphCo_6F_Text_Grunt1Intro::
    .string "我是火箭队\n"
    .string "四兄弟之一！$"

SilphCo_6F_Text_Grunt1Defeat::
    .string "熄火！$"

SilphCo_6F_Text_Grunt1PostBattle::
    .string "没关系！\n"
    .string "我的兄弟们会为我报仇的！$"

SilphCo_6F_Text_TaylorIntro::
    .string "那个可恶的总裁！\p"
    .string "该死的家伙用船把我送\n"
    .string "到了缇斯基分部！\p"
    .string "我敢肯定这就是为什么火箭队\n"
    .string "追着我们不放！$"

SilphCo_6F_Text_TaylorDefeat::
    .string "怎么会这样。$"

SilphCo_6F_Text_TaylorPostBattle::
    .string "缇斯基分部？\n"
    .string "在俄罗斯语里这是无人岛的意思！$"

SilphCo_6F_Text_Grunt2Intro::
    .string "别以为背叛火箭队后，\n"
    .string "你能拍拍屁股一走了之！$"

SilphCo_6F_Text_Grunt2Defeat::
    .string "你这个叛徒！$"

SilphCo_6F_Text_Grunt2PostBattle::
    .string "如果你代表正义，那你\n"
    .string "就出卖了我们这些坏家伙！$"

SilphCo_6F_Text_FloorSign::
    .string "西尔佛公司总部\n"
    .string "6F$"

