FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon::
    .string "只训练厉害的宝可梦\n"
    .string "你永远成为不了强大的训练家\p"
    .string "但是训练许多宝可梦\n"
    .string "也不是一件轻松的事。$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian::
    .string "常青市西边\n"
    .string "有一条小道，\p"
    .string "通向宝可梦联盟总部。\n"
    .string "总部统管所有的训练家。$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex::
    .string "如果你在收集宝可梦图鉴，\n"
    .string "去浅红市狩猎地带看看吧。\p"
    .string "那里有其他地方见不到的\n"
    .string "稀有宝可梦。$"

