SaffronCity_Text_WhatDoYouWantGetLost::
    .string "你想干什么？\n"
    .string "滚开！$"

SaffronCity_Text_BossTakeTownForTeamRocket::
    .string "老大说他会把这座城镇\n"
    .string "命名为火箭队！$"

SaffronCity_Text_DontGetDefiantOrIllHurtYou::
    .string "不要惹我生气！\n"
    .string "否则我会狠狠地报复你的！$"

SaffronCity_Text_SaffronBelongsToTeamRocket::
    .string "金黄永远属于火箭队！$"

SaffronCity_Text_CriminalLifeMakesMeFeelAlive::
    .string "只有犯罪才会让我觉得\n"
    .string "是如此的有意义！$"

SaffronCity_Text_WatchWhereYoureWalking::
    .string "噢！\n"
    .string "给我好好走路！$"

SaffronCity_Text_WeCanExploitMonsAroundWorld::
    .string "在我们控制了西尔佛之后，\n"
    .string "我们将会拥有全世界的宝可梦！\p"
    .string "富甲天下，哇哈哈哈！$"

SaffronCity_Text_YouBeatTeamRocket::
    .string "你一人就打败了火箭队？\n"
    .string "真难以想象！$"

SaffronCity_Text_SafeToGoOutAgain::
    .string "耶！火箭队被赶跑了！\n"
    .string "外面都安全喽！$"

SaffronCity_Text_PeopleComingBackToSaffron::
    .string "当火箭队来的时候，\n"
    .string "人们成群结队地逃离这里。\p"
    .string "他们现在要涌回\n"
    .string "金黄了。$"

SaffronCity_Text_FlewHereOnPidgeot::
    .string "我听说西尔佛的事件后，\n"
    .string "立马乘着大比鸟飞过来了。\p"
    .string "现在一切都解决了吗？\n"
    .string "我错过了写报导的最好时机……$"

SaffronCity_Text_Pidgeot::
    .string "大比鸟：比比比！$"

SaffronCity_Text_SawRocketBossEscaping::
    .string "我看见火箭队的头目\n"
    .string "从西尔佛大楼仓皇逃窜！$"

SaffronCity_Text_ImASecurityGuard::
    .string "我是一名保安。\p"
    .string "我决不允许可疑的孩子进入！$"

SaffronCity_Text_HesTakingASnooze::
    .string "……\n"
    .string "鼾声传了出来……\p"
    .string "哈！他正在打盹儿！$"

SaffronCity_Text_CitySign::
    .string "金黄市\n"
    .string "遍布商机的闪耀之地$"

SaffronCity_Text_FightingDojo::
    .string "格斗道场！$"

SaffronCity_Text_GymSign::
    .string "金黄市宝可梦道馆\n"
    .string "馆主：娜姿\l"
    .string "超能力属性宝可梦的大师！$"

SaffronCity_Text_FullHealCuresStatus::
    .string "……有用的公告牌！\p"
    .string "万灵药能治愈\n"
    .string "像灼伤，麻痹，中毒，\l"
    .string "冰冻和睡眠等异常状态。\p"
    .string "虽然有点贵，但是\n"
    .string "比一个一个买其他商品更方便。$"

SaffronCity_Text_GreatBallImprovedCatchRate::
    .string "……有用的公告牌！\p"
    .string "新的超级球提高了\n"
    .string "收服率。\p"
    .string "试试用它去抓那些\n"
    .string "很难收服的宝可梦。$"

SaffronCity_Text_SilphCoSign::
    .string "西尔佛公司办公大楼$"

SaffronCity_Text_MrPsychicsHouse::
    .string "超能先生的家$"

SaffronCity_Text_SilphsLatestProduct::
    .string "西尔佛的最新产品！\n"
    .string "即将开始销售……$"

SaffronCity_Text_TrainerFanClubSign::
    .string "宝可梦训练家迷俱乐部\p"
    .string "许多训练家在这里\n"
    .string "留下了他们的名字。$"

SaffronCity_Text_HowCanClubNotRecognizeLance::
    .string "这个俱乐部里面……\n"
    .string "没人有异议！\p"
    .string "谁不知道\n"
    .string "阿渡的实力？\p"
    .string "他就是正义的化身！\n"
    .string "而且冷静又富有激情！\l"
    .string "阿渡先生是最棒的！$"

