TwoIsland_Text_IslandSign::
    .string "二之岛\n"
    .string "又叫友谊岛$"

TwoIsland_Text_JoyfulGameCornerSign::
    .string "跳绳和树果！\n"
    .string "欢乐的游戏城$"

TwoIsland_Text_DangerFastCurrent::
    .string "危险！水流湍急！\n"
    .string "禁止钓鱼和冲浪！$"

TwoIsland_Text_WelcomeToShopMerchandiseLimited::
    .string "啊！\n"
    .string "你好，欢迎来我的小店！\p"
    .string "小店最近才开张。\p"
    .string "买的东西还不多，\n"
    .string "希望能有你需要的。$"

TwoIsland_Text_AddedMerchandiseForLostelle::
    .string "我不知道该怎么感谢你才好，\n"
    .string "你救了小迷。\p"
    .string "多亏了你的壮举，\n"
    .string "让三之岛的人改变了\l"
    .string "对关都人的看法。\p"
    .string "你要知道，我就一个是关都人。\p"
    .string "三之岛的人们帮我\n"
    .string "添置了很多新货品。$"

TwoIsland_Text_HopeYouGiveItYourBest::
    .string "嗨！我会全力以赴的。\n"
    .string "希望你也一样，{PLAYER}。$"

TwoIsland_Text_BringingItemsFromDistantLands::
    .string "嗨，你好，{PLAYER}！\n"
    .string "欢迎光临！\p"
    .string "我从远方的岛上\n"
    .string "运来新货品了。\p"
    .string "我现在也开始卖些稀有物品了。\n"
    .string "请随便看看！$"

TwoIsland_Text_FellowMovedFromCeladonCity::
    .string "那边那个小伙子，\n"
    .string "他是从玉虹市过来的。\p"
    .string "他和他弟弟开了个店。\p"
    .string "你也许会怀疑他到底\n"
    .string "懂不懂怎么开店。$"

TwoIsland_Text_ShopkeepersBrotherWorksGameCorner::
    .string "店主的弟弟在游戏城找了个工作。\p"
    .string "他想多攒点钱，\n"
    .string "这样就能进更多货了。$"

TwoIsland_Text_BrunoCameToIslandWhileBack::
    .string "喂，喂。\n"
    .string "你知道吗？\p"
    .string "有个著名的训练家\n"
    .string "来岛上没多久就走了。\p"
    .string "据说他叫希巴。\n"
    .string "还是四天王之一。\p"
    .string "他得知兄弟俩的愤怒馒头\n"
    .string "卖完后就失望地离开了。$"

TwoIsland_Text_BuyRareItemsHere::
    .string "有眼光的顾客\n"
    .string "都会来这里买稀有物品！$"

TwoIsland_Text_OldWomanLivesOutOnCape::
    .string "远方的小屋里住着个老太太。\p"
    .string "她能用她的眼睛对宝可梦做出判断。\n"
    .string "这有点令人不安呢。$"

TwoIsland_Text_HaveYouTriedJumpingGame::
    .string "卟卟卟！卟卟卟！\n"
    .string "你试过越野赛吗？\p"
    .string "能参加的宝可梦是……\n"
    .string "卟卟卟！\p"
    .string "有些速度慢，卟卟卟！\p"
    .string "有些速度超级快，卟卟卟卟卟卟！\p"
    .string "你听懂了吗？\n"
    .string "卟卟卟！$"

