FiveIsland_ResortGorgeous_House_Text_PleaseHearMyWish::
    .string "秋穗：哦？\n"
    .string "我在什么地方见过你吗？\p"
    .string "呃，算了，那无所谓。\p"
    .string "我实在是太无聊了，\n"
    .string "所以，请听听我的愿望吧！$"

FiveIsland_ResortGorgeous_House_Text_WishToSeeMonPlease::
    .string "我想见一只宝可梦。\n"
    .string "一只可爱的{B_COPY_VAR_1}。\p"
    .string "我迫不及待，想马上见到！\n"
    .string "求你了，实现我的愿望吧！$"

FiveIsland_ResortGorgeous_House_Text_OhImTiredOfWaiting::
    .string "秋穗：哦，我已经不耐烦了！\n"
    .string "你总是让我失望了！\p"
    .string "好吧，这次我就暂且原谅你，\n"
    .string "但下次别给我失败！$"

FiveIsland_ResortGorgeous_House_Text_MonYouCaughtForMeThankYou::
    .string "秋穗：哦！\p"
    .string "哦，太好了！那一定是你\n"
    .string "为我收服的{B_COPY_VAR_1}。\p"
    .string "咯咯……\n"
    .string "看起来和你蛮像的。\p"
    .string "真的很感谢你！\p"
    .string "…… …… ……\n"
    .string "还有什么事吗？\p"
    .string "你可以走了。\p"
    .string "…… …… ……\n"
    .string "呃，好吧。我知道了！\p"
    .string "庆介！\n"
    .string "快给我出来！$"

FiveIsland_ResortGorgeous_House_Text_ButlerYesMyLady::
    .string "管家：我在，大小姐。$"

FiveIsland_ResortGorgeous_House_Text_SelphyGiveTokenOfAppreciation::
    .string "秋穗：你就负责\n"
    .string "给那个人点什么奖励吧！$"

FiveIsland_ResortGorgeous_House_Text_ButlerIShallDoAsYouBid::
    .string "管家：好的，我会按照您的吩咐。\n"
    .string "大小姐。$"

FiveIsland_ResortGorgeous_House_Text_ButlerPleaseAcceptThisAsHerThanks::
    .string "管家：真的谢谢你\n"
    .string "让大小姐这么开心。\p"
    .string "请接受你应得的奖励吧……$"

FiveIsland_ResortGorgeous_House_Text_ButlerBagAppearsToBeFull::
    .string "管家：真不幸，\n"
    .string "你的包包好像满了……$"

FiveIsland_ResortGorgeous_House_Text_OhHowDisappointing::
    .string "喔……\n"
    .string "太遗憾了！$"

FiveIsland_ResortGorgeous_House_Text_SelphyWishYouBestOfLuck::
    .string "秋穗：祝你好运。$"

FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun::
    .string "管家：秋穗小姐的微笑\n"
    .string "就像温暖的阳光。\p"
    .string "拜托了！\n"
    .string "请带给秋穗小姐快乐！$"

