CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
    .string "只有有能力的训练家能够\n"
    .string "收集到宝可梦徽章。\p"
    .string "我看你应该是他们中的一个。\p"
    .string "那些徽章都有着惊人的秘密，\n"
    .string "你知道吗？$"

CeruleanCity_House1_Text_DescribeWhichBadge::
    .string "那现在……\p"
    .string "我应该描述八个徽章中的\n"
    .string "哪一个呢？$"

CeruleanCity_House1_Text_ComeVisitAnytime::
    .string "你要是改变主意了，\n"
    .string "随时都可以来问我。$"

CeruleanCity_House1_Text_AttackStatFlash::
    .string "稍微提高你的宝可梦的攻击。\p"
    .string "也可以让你在不战斗\n"
    .string "的时候使用闪光。$"

CeruleanCity_House1_Text_ObeyLv30Cut::
    .string "30级以内的宝可梦\n"
    .string "都会听你的话。\p"
    .string "包括你交换得来的宝可梦。\p"
    .string "但是较高级别的宝可梦\n"
    .string "仍然很难控制。\p"
    .string "也可以让你在\n"
    .string "不战斗的时候使用居合劈。$"

CeruleanCity_House1_Text_SpeedStatFly::
    .string "稍微提高你的宝可梦的速度。\p"
    .string "还可以让你的宝可梦\n"
    .string "在战斗之外使用飞翔。$"

CeruleanCity_House1_Text_ObeyLv50Strength::
    .string "50级以内的宝可梦\n"
    .string "都会听你的话，\p"
    .string "包括你交换得来的宝可梦。\p"
    .string "但是较高级别的宝可梦\n"
    .string "仍然很难控制。\p"
    .string "还可以让你的宝可梦\n"
    .string "在战斗之外使用怪力推动巨石。$"

CeruleanCity_House1_Text_DefenseStatSurf::
    .string "稍微提高你的宝可梦的防御。\p"
    .string "也可以让你的宝可梦\n"
    .string "在战斗之外使用冲浪渡过海洋。$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
    .string "70级以内的宝可梦\n"
    .string "都会听从你的指令，\p"
    .string "包括你交换得来的宝可梦。\p"
    .string "不过更高级别的宝可梦\n"
    .string "仍然很难控制。\p"
    .string "也可以让你的宝可梦在战斗之外\n"
    .string "使用碎岩打碎挡路的岩石！$"

CeruleanCity_House1_Text_SpStatsWaterfall::
    .string "稍微提高你的宝可梦的特攻和特防。\p"
    .string "也可以让你的宝可梦\n"
    .string "在战斗之外使用攀瀑登上瀑布。$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
    .string "所有宝可梦都会听你的话！$"

