ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "接待员告诉我。\p"
    .string "可以随便使用角落里的电脑。\n"
    .string "她真是太和蔼了！$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "每一个镇都有宝可梦中心。\p"
    .string "并且都是免费的，所以\n"
    .string "不要不好意思去治疗你的宝可梦。$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "宝可梦中心能治愈你的\n"
    .string "受伤的，或者昏厥的宝可梦。\p"
    .string "他们能使你的宝可梦\n"
    .string "完全恢复健康。$"

