Text_DoubleEdgeTeach::
    .string "你应该为自己感到骄傲，\n"
    .string "你已经在这条冠军之路上\l"
    .string "勇敢的杀出了属于自己的路。\p"
    .string "作为对你成绩的认可，\n"
    .string "我会教你舍身冲撞。\p"
    .string "你想要我教你学这个招式吗？$"

Text_DoubleEdgeDeclined::
    .string "我随时都能教你这个招式的。$"

Text_DoubleEdgeWhichMon::
    .string "我要教哪个宝可梦\n"
    .string "舍身冲撞？$"

Text_DoubleEdgeTaught::
    .string "保持那股动力，\n"
    .string "去参加宝可梦联盟吧！\p"
    .string "去会会他们\n"
    .string "并将他们通通击败吧！$"

VictoryRoad_3F_Text_GeorgeIntro::
    .string "听闻有个孩子\n"
    .string "强大的令人震惊。$"

VictoryRoad_3F_Text_GeorgeDefeat::
    .string "果然所言非虚。$"

VictoryRoad_3F_Text_GeorgePostBattle::
    .string "莫非，就是你击败了\n"
    .string "火箭队的坂木吗？$"

VictoryRoad_3F_Text_AlexaIntro::
    .string "训练家的人生就是\n"
    .string "去寻找更强的对手。$"

VictoryRoad_3F_Text_AlexaDefeat::
    .string "啊，你很强！$"

VictoryRoad_3F_Text_AlexaPostBattle::
    .string "在艰难的战斗中，\n"
    .string "你会变得更强。$"

VictoryRoad_3F_Text_CarolineIntro::
    .string "我会让你看看你到底\n"
    .string "有多强……还是多弱！$"

VictoryRoad_3F_Text_CarolineDefeat::
    .string "我很气愤！$"

VictoryRoad_3F_Text_CarolinePostBattle::
    .string "你只不过证明了我有多强……$"

VictoryRoad_3F_Text_ColbyIntro::
    .string "只有被选中之人\n"
    .string "才能通过这里！$"

VictoryRoad_3F_Text_ColbyDefeat::
    .string "我不相信！$"

VictoryRoad_3F_Text_ColbyPostBattle::
    .string "这里所有的训练家都以\n"
    .string "宝可梦联盟为目标。\p"
    .string "不要放松警惕。$"

VictoryRoad_3F_Text_RayIntro::
    .string "阿新：我们俩在一起会更强大！$"

VictoryRoad_3F_Text_RayDefeat::
    .string "阿新：真可笑！\n"
    .string "这是不可能的！$"

VictoryRoad_3F_Text_RayPostBattle::
    .string "阿新：你打败了我们。\n"
    .string "强大的人总是难以捉摸……$"

VictoryRoad_3F_Text_RayNotEnoughMons::
    .string "阿新：我们俩一起着向冠军努力。\p"
    .string "请你带上两只宝可梦\n"
    .string "来跟我们战斗。$"

VictoryRoad_3F_Text_TyraIntro::
    .string "佳代：我们正试着一起\n"
    .string "变成冠军。$"

VictoryRoad_3F_Text_TyraDefeat::
    .string "佳代：哦，但是……$"

VictoryRoad_3F_Text_TyraPostBattle::
    .string "佳代：你教会了我，\n"
    .string "实力有无数种形式和形态。$"

VictoryRoad_3F_Text_TyraNotEnoughMons::
    .string "佳代：如果你只有一只宝可梦，\n"
    .string "就不能和我们战斗。$"

