SevenIsland_House_Room1_Text_OnlyEnjoymentWatchingBattles::
    .string "虽然看起来不像，\n"
    .string "但是我年轻时……\p"
    .string "我曾飞到每个地方，\n"
    .string "挑战每一个我遇到的训练家。\p"
    .string "现在，我仅有的乐趣\n"
    .string "就是在看对战时\l"
    .string "回想着我的往事。$"

SevenIsland_House_Room1_Text_SlightBreezeAroundBox::
    .string "在箱子的四周\n"
    .string "有微风吹着。$"

SevenIsland_House_Room1_Text_ChallengeVisitingTrainer::
    .string "啊呀！\n"
    .string "欢迎，我的朋友！\p"
    .string "让我告诉你点东西吧。这里的\n"
    .string "地下层有个隐藏的房间。\p"
    .string "一个叫{B_COPY_VAR_1}的训练家\n"
    .string "在那里等着。\p"
    .string "告诉我，你是来挑战\n"
    .string "{B_COPY_VAR_1}的，对不？$"

SevenIsland_House_Room1_Text_OhYouWontBattle::
    .string "噢……\n"
    .string "你不想对战啊……\p"
    .string "好吧，好吧。\n"
    .string "……\p"
    .string "嗯，如果你想\n"
    .string "改变主意的话，就来找我吧。$"

SevenIsland_House_Room1_Text_LimitThreeMonsPerSide::
    .string "啊！\n"
    .string "你会为我而战？\p"
    .string "那么，这就值得我把\n"
    .string "这些箱子推到一边去。\p"
    .string "……\n"
    .string "不过还有一个小问题。\p"
    .string "这个密室不是建得\n"
    .string "非常牢固。\p"
    .string "我可以把你战斗的\n"
    .string "宝可梦限制在三只吗？$"

SevenIsland_House_Room1_Text_SaveProgressBeforeBattle::
    .string "很好！在你开始前，\n"
    .string "你要先记录吗？$"

SevenIsland_House_Room1_Text_DontHoldAnythingBack::
    .string "好了。\n"
    .string "尽你的全力吧！$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_1::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room2_Text_MatchEndedUpDraw::
    .string "这场比赛打成平手。$"

SevenIsland_House_Room1_Text_DrawWasIt::
    .string "平手，嗯哼？\p"
    .string "不过，我可以说这场\n"
    .string "是一场很精彩的比赛。\p"
    .string "我可以肯定的说，\n"
    .string "这是一场很有深度的比赛！$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_2::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_AstoundingBattle::
    .string "太美了！\p"
    .string "太美了，真的！\n"
    .string "真是场令人震惊的比赛！\p"
    .string "真让人非常震惊，真的。\n"
    .string "这让我感动得流泪了！\p"
    .string "信任和熟练的技巧还有\n"
    .string "巧妙的回避！\p"
    .string "力量跟力量间的对决！\p"
    .string "是的！\n"
    .string "这就是最壮丽的事情了！$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_3::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_FeelYourDisappointment::
    .string "太糟糕了！\n"
    .string "我能感到你的失落。\p"
    .string "不过，\n"
    .string "失败乃是成功之母！\p"
    .string "运用它，从它学习，然后让它\n"
    .string "成为你寻求成功的动力。\p"
    .string "忘记这次失败，\n"
    .string "然后加倍的训练！$"

