TwoIsland_JoyfulGameCorner_Text_WhereHasLostelleGottenTo::
    .string "那么，小迷\n"
    .string "究竟到哪里去了啊？\p"
    .string "这时间她应该\n"
    .string "给我送午餐来了的啊？$"

TwoIsland_JoyfulGameCorner_Text_PleaseHelpFindLostelle::
    .string "嗯？就是你！\n"
    .string "你是不是小迷的朋友？\p"
    .string "你有没有在附近见过小迷？\n"
    .string "我不知道她在哪里。\l"
    .string "她应该到了这很久的了。\p"
    .string "小迷她很可爱。\n"
    .string "和我一样的可爱……\p"
    .string "如果我的小迷\n"
    .string "有什么意外的话……？！\p"
    .string "请，请你帮我找她吧！\n"
    .string "请你去三之岛找她吧！$"

TwoIsland_JoyfulGameCorner_Text_IsThisOnlyThreeIsland::
    .string "啥？这就是游戏城？\n"
    .string "它会使多少人破产？\p"
    .string "话说这帮骗子……\p"
    .string "说好在这里集合的\n"
    .string "他们去哪儿了？\p"
    .string "啊，就是你！\n"
    .string "这里是不是三之岛？$"

TwoIsland_JoyfulGameCorner_Text_ThisIsTwoIslandMoveIt::
    .string "给我在你滚下床前\n"
    .string "清醒过来，笨蛋。\p"
    .string "这里是二之岛！\p"
    .string "滚开！扶着你的脏车\n"
    .string "滚出我的房间！$"

TwoIsland_JoyfulGameCorner_Text_TheseIslandsAreConfusing::
    .string "呃……\n"
    .string "哦，哦，知道了。\p"
    .string "啧……\n"
    .string "这些岛真让人搞不清……$"

TwoIsland_JoyfulGameCorner_Text_PunkScuffedUpMyFloor::
    .string "你看，\n"
    .string "这帮混蛋弄脏了我的地板。$"

TwoIsland_JoyfulGameCorner_Text_PleaseGoToThreeIsland::
    .string "嘿，听着！我求你了，\n"
    .string "你一定要去三之岛。\p"
    .string "如果我的小迷\n"
    .string "发生什么事情的话……\p"
    .string "我就住在三之岛\n"
    .string "的一个红色屋顶的房子。\p"
    .string "她还有可能会过来的，\n"
    .string "我只能在这里继续等着。\p"
    .string "只好让你去帮我\n"
    .string "找我的小迷了。$"

TwoIsland_JoyfulGameCorner_Text_NotRunningAnyGamesToday::
    .string "很抱歉，\n"
    .string "我们今天不举行任何游戏。$"

TwoIsland_JoyfulGameCorner_Text_GetGamesGoingSoon::
    .string "很快，\n"
    .string "我们将会恢复营业的。$"

TwoIsland_JoyfulGameCorner_Text_YouRescuedLostelle::
    .string "那么，你救了小迷？\n"
    .string "我要如何感谢你才好呢？\p"
    .string "小迷，我的宝贝，请原谅我！\p"
    .string "爸爸并不知道你的恐惧\n"
    .string "也不知道你曾深陷危险。$"

TwoIsland_JoyfulGameCorner_Text_LostelleItsOkayDaddy::
    .string "小迷：没关系，爸爸。\n"
    .string "我和{PLAYER}已经成为了朋友！$"

TwoIsland_JoyfulGameCorner_Text_ThisIsForMe::
    .string "哦，那是什么？\n"
    .string "什么？你说这是给我的？\p"
    .string "你怎么知道\n"
    .string "我喜欢珍贵的石头和宝石的？\p"
    .string "你真的很擅长\n"
    .string "讨人喜欢啊。$"

TwoIsland_JoyfulGameCorner_Text_HandedMeteoriteToLostellesDaddy::
    .string "{PLAYER}把陨石\n"
    .string "交给了小迷的爸爸。$"

TwoIsland_JoyfulGameCorner_Text_OhThisIsFromBill::
    .string "哦，我明白了。这是正辉让你转交的。\n"
    .string "你一定要帮我谢谢他！\p"
    .string "你真是太好了！\n"
    .string "希望你能收下这个。$"

TwoIsland_JoyfulGameCorner_Text_ReceivedMoonStoneFromLostellesDaddy::
    .string "{PLAYER}从小迷的爸爸那儿\n"
    .string "得到了月之石。$"

TwoIsland_JoyfulGameCorner_Text_NotGoingToFitInBag::
    .string "你的包包装不下\n"
    .string "其它东西了……$"

TwoIsland_JoyfulGameCorner_Text_IllGetGameCornerRunning::
    .string "接下来，游戏城将会\n"
    .string "正常运行了。\p"
    .string "请一定要带你的朋友\n"
    .string "来玩玩啊！$"

TwoIsland_JoyfulGameCorner_Text_PleaseShowMeYouBeingCool::
    .string "听着，听着！\p"
    .string "再向我展示一次\n"
    .string "你的那份冷静吧！$"

