Route22_Text_EarlyRivalIntro::
	.string "{B_OPPONENT_MON1_NAME}：喂！{PLAYER}！\p"
	.string "你想要到宝可梦联盟里去？\n"
	.string "得了吧！\p"
	.string "你得到的徽章\n"
	.string "还不够吧？\p"
	.string "这样的话，\n"
	.string "守卫是不会让你通过的。\p"
	.string "顺便问一句，\n"
	.string "你的宝可梦变强了吗？$"

Route22_Text_EarlyRivalDefeat::
	.string "啊啊！\n"
	.string "你只是运气好罢了！$"

Route22_Text_EarlyRivalPostBattle::
	.string "我听说宝可梦联盟遍布\n"
	.string "很厉害的训练家。\p"
	.string "我必须想想该怎样\n"
	.string "战胜他们。\p"
	.string "你不能这样磨磨蹭蹭了，\n"
	.string "继续前进吧！$"

@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons::
	.string "{RIVAL}“なんだ？\n"
	.string "ポケモン　2ひきも\l"
	.string "もってるの　なぜか　だって？\p"
	.string "おまえも\n"
	.string "つかまえれば　いい　じゃん！$"

Route22_Text_LateRivalIntro::
	.string "{B_OPPONENT_MON1_NAME}：什么？{PLAYER}！\n"
	.string "在这儿碰到你真是令我惊讶！\p"
	.string "你是打算去宝可梦联盟吗？\p"
	.string "你也收集齐了全部徽章？\n"
	.string "真是太好了！\p"
	.string "作为去宝可梦联盟之前的热身！\n"
	.string "我要先击败你，{PLAYER}\p"
	.string "来吧！$"

Route22_Text_LateRivalDefeat::
	.string "什么！？\p"
	.string "我太大意了！$"

Route22_Text_LateRivalPostBattle::
	.string "这下我放松多了。\n"
	.string "已经为宝可梦联盟做好了充分准备！\p"
	.string "{PLAYER}，你还得再练习练习。\p"
	.string "不过，你自己应该很清楚吧！\n"
	.string "我走了，回见！$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory::
	.string "{RIVAL}“ひゃははッ　{PLAYER}ー！\n"
	.string "それで　がんばってるのかよ！\l"
	.string "おれの　さいのうに　くらべりゃ\l"
	.string "{PLAYER}は　まだまだ　だな！\p"
	.string "もっと　れんしゅう　こいよ！\n"
	.string "あははーッ！$"

Route22_Text_LeagueGateSign::
	.string "宝可梦联盟\n"
	.string "正门$"

