SilphCo_11F_Text_ThanksForSavingMeDearBoy::
    .string "总裁：哦，勇敢的少年！\n"
    .string "谢谢你救了西尔佛。\p"
    .string "我永远不会忘记，你在我们危险的时候\n"
    .string "救了我们。\p"
    .string "我必须想办法来感谢你。\p"
    .string "我很富有，我可以给你\n"
    .string "任何东西。\p"
    .string "来拿着，这个或许有用。$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
    .string "总裁：哦，亲爱的少女！\n"
    .string "谢谢你救了西尔佛。\p"
    .string "我永远不会忘记，你在我们危险的时候\n"
    .string "救了我们。\p"
    .string "我要想办法来感谢你。\p"
    .string "我很富有，我可以给你\n"
    .string "任何东西。\p"
    .string "来拿着，这个或许有用。$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
    .string "{PLAYER}从西尔佛总裁那里\n"
    .string "得到了一个大师球！$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
    .string "西尔佛总裁：你在任何地方\n"
    .string "都买不到它。\p"
    .string "这是我们秘密制作的试验品\n"
    .string "大师球。\p"
    .string "它将能成功收服任何\n"
    .string "宝可梦！\p"
    .string "不过你在使用它时\n"
    .string "千万不要声张。$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
    .string "你的包包里没有空间了。$"

SilphCo_11F_Text_ThanksForRescuingUs::
    .string "秘书：谢谢你救了我们所有人\p"
    .string "我们全公司上下，包括总裁，\n"
    .string "都欠了你一个天大的人情。$"

SilphCo_11F_Text_GiovanniIntro::
    .string "啊，{PLAYER}！\n"
    .string "我们又见面了！\p"
    .string "总裁和我正在讨论\n"
    .string "一个重要的商业计划。\p"
    .string "你还是别太关心\n"
    .string "大人的事为好……\p"
    .string "知道这些可是相当痛苦的呢！$"

SilphCo_11F_Text_GiovanniDefeat::
    .string "呃！！\n"
    .string "我又输了！？$"

SilphCo_11F_Text_GiovanniPostBattle::
    .string "该死！\n"
    .string "你毁了我们在西尔佛的计划！\p"
    .string "但是，火箭队不会倒下的！\p"
    .string "{PLAYER}！永远不要忘记所有\n"
    .string "宝可梦都是为火箭队存在的！\p"
    .string "我得走了，但我会回来的！$"

SilphCo_11F_Text_Grunt2Intro::
    .string "给我站住！\n"
    .string "你敢再走一步！$"

SilphCo_11F_Text_Grunt2Defeat::
    .string "不要……\n"
    .string "求你了！$"

SilphCo_11F_Text_Grunt2PostBattle::
    .string "那么，你想要见我的老大？$"

SilphCo_11F_Text_Grunt1Intro::
    .string "站住！你和我的老大\n"
    .string "预约过吗？$"

SilphCo_11F_Text_Grunt1Defeat::
    .string "啊呀！被打败了！$"

SilphCo_11F_Text_Grunt1PostBattle::
    .string "走路给我小心点……\n"
    .string "我的老大喜欢强大的宝可梦！$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
    .string "显示屏上有宝可梦！$"

SilphCo_11F_Text_FloorSign::
    .string "西尔佛公司总部\n"
    .string "11F$"

