CinnabarIsland_Gym_Text_BlaineIntro::
    .string "啊哈！\p"
    .string "夏伯就是我，\n"
    .string "红莲道馆火热的馆主！\p"
    .string "我炽烈的宝可梦都\n"
    .string "狂野而富有热情！\p"
    .string "它们会把所有的挑战者燃烧殆尽！\p"
    .string "好了！\n"
    .string "开战前你最好准备些灼伤药！{PLAY_BGM 0x56 0x01}$"

CinnabarIsland_Gym_Text_BlaineDefeat::
    .string "被燃烧殆尽的是我！\n"
    .string "烧得连灰烬也不剩！\p"
    .string "深红徽章是你的了！$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
    .string "大字爆炎是一个\n"
    .string "威力极高的火属性招式，\p"
    .string "别把它浪费在水属性宝可梦身上。$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
    .string "哈！\p"
    .string "深红徽章能够将你\n"
    .string "宝可梦的特攻提高一点点\p"
    .string "还有，你还能得到它！$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
    .string "{PLAYER}得到了招式学习器38。$"

CinnabarIsland_Gym_Text_BlainePostBattle::
    .string "招式学习器38是“大字爆炎”！\n"
    .string "把它教给火属性宝可梦。\p"
    .string "比如九尾或者喷火龙\n"
    .string "就是不错的选择。$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
    .string "把包包腾点空间再来，小孩！$"

CinnabarIsland_Gym_Text_ErikIntro::
    .string "你知道宝可梦\n"
    .string "灼热的吐息温度有多高吗？$"

CinnabarIsland_Gym_Text_ErikDefeat::
    .string "哟噢！\n"
    .string "烫，烫，烫！$"

CinnabarIsland_Gym_Text_ErikPostBattle::
    .string "火，专业点说的话，\n"
    .string "燃烧……\p"
    .string "……空气中的氧……\n"
    .string "叽哩呱啦呱啦叽哩…$"

CinnabarIsland_Gym_Text_QuinnIntro::
    .string "过去我是一名小偷，\n"
    .string "但我现在是一名正直的训练家。$"

CinnabarIsland_Gym_Text_QuinnDefeat::
    .string "我输了！$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
    .string "对于其他人的宝可梦，\n"
    .string "我总是难以抑制的想着去偷。$"

CinnabarIsland_Gym_Text_AveryIntro::
    .string "我很努力的学过了宝可梦的知识。\n"
    .string "你赢不了我的！$"

CinnabarIsland_Gym_Text_AveryDefeat::
    .string "哇啊！\n"
    .string "我学的还不够！$"

CinnabarIsland_Gym_Text_AveryPostBattle::
    .string "我的理论很高深，\n"
    .string "和你讲你很难明白。$"

CinnabarIsland_Gym_Text_RamonIntro::
    .string "我喜欢用火属性宝可梦。\n"
    .string "我就是喜欢。$"

CinnabarIsland_Gym_Text_RamonDefeat::
    .string "太热了，搞不定！$"

CinnabarIsland_Gym_Text_RamonPostBattle::
    .string "我希望有一种小偷宝可梦。\n"
    .string "那我就指望着用它了！$"

CinnabarIsland_Gym_Text_DerekIntro::
    .string "我知道夏伯为什么会\n"
    .string "成为一名训练家。$"

CinnabarIsland_Gym_Text_DerekDefeat::
    .string "喔！$"

CinnabarIsland_Gym_Text_DerekPostBattle::
    .string "我们的馆主，夏伯在山里迷路了，\n"
    .string "但幸运的是，\p"
    .string "当夜幕降临的时候，\n"
    .string "一只灼热的鸟宝可梦降临在他面前。\p"
    .string "它发出的光使\n"
    .string "夏伯找到了下山的路。$"

CinnabarIsland_Gym_Text_DustyIntro::
    .string "我去过许多道馆，\n"
    .string "但这个最合我的口味。$"

CinnabarIsland_Gym_Text_DustyDefeat::
    .string "好、好火热的战斗。$"

CinnabarIsland_Gym_Text_DustyPostBattle::
    .string "小火马，九尾…\n"
    .string "都是受欢迎的火属性宝可梦。$"

CinnabarIsland_Gym_Text_ZacIntro::
    .string "火对H2O不利。$"

CinnabarIsland_Gym_Text_ZacDefeat::
    .string "呃！\n"
    .string "火熄灭了！$"

CinnabarIsland_Gym_Text_ZacPostBattle::
    .string "毋庸置疑，水克火。\p"
    .string "但是火能融化冰，\n"
    .string "所以火属性能够打败冰属性宝可梦。$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
    .string "哟！\n"
    .string "未来的冠军！\p"
    .string "热血的夏伯是一位\n"
    .string "火属性宝可梦专家。\p"
    .string "用水来浇灭他的斗志吧！\p"
    .string "你最好带上些\n"
    .string "灼伤药。$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
    .string "{PLAYER}！\n"
    .string "你击败了那个火焰狂人！$"

CinnabarIsland_Gym_Text_GymStatue::
    .string "红莲宝可梦道馆\n"
    .string "馆主：夏伯\p"
    .string "优胜训练家：\n"
    .string "{B_OPPONENT_MON1_NAME}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
    .string "红莲宝可梦道馆\n"
    .string "馆主：夏伯\p"
    .string "优胜训练家：\n"
    .string "{B_OPPONENT_MON1_NAME}，{PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
    .string "宝可梦竞答！\p"
    .string "答对了，\n"
    .string "通向下一个房间的门就会打开。\p"
    .string "答错了，就得面对训练家的挑战！\p"
    .string "你如果想要把你的实力\n"
    .string "保留到最后一刻……\p"
    .string "那就要尽可能的答对！\n"
    .string "三，二，一，开始了！$"

CinnabarIsland_Gym_Text_QuizQuestion1::
    .string "绿毛虫进化成铁甲蛹吗？$"

CinnabarIsland_Gym_Text_QuizQuestion2::
    .string "宝可梦联盟徽章\n"
    .string "一共有九枚？$"

CinnabarIsland_Gym_Text_QuizQuestion3::
    .string "蚊香蝌蚪能进化三次？$"

CinnabarIsland_Gym_Text_QuizQuestion4::
    .string "电属性招式对地面属性\n"
    .string "宝可梦有效果吗？$"

CinnabarIsland_Gym_Text_QuizQuestion5::
    .string "同种宝可梦即使等级相同，\n"
    .string "它们的能力却不一定一样？$"

CinnabarIsland_Gym_Text_QuizQuestion6::
    .string "招式学习器28是挖坟吗？$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
    .string "回答正确！\p"
    .string "请通过！$"

CinnabarIsland_Gym_Text_SorryBadCall::
    .string "糟糕，你答错了……$"

