Route25_SeaCottage_Text_ImBillHelpMeOutPal::
    .string "哈！我是一只宝可梦……\n"
    .string "不对，我才不是！\p"
    .string "我是正辉！\n"
    .string "我是一个货真价实的宝可梦狂！\p"
    .string "嘿！\n"
    .string "为什么要摆出一副怀疑的表情？\p"
    .string "朋友，我没和你开玩笑！\p"
    .string "我试验失败了然后和\n"
    .string "一只宝可梦合体了！\p"
    .string "那么，怎么样？\n"
    .string "帮我恢复原状吧！$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady::
    .string "哈！我是一只宝可梦……\n"
    .string "不对，我才不是！\p"
    .string "我是正辉！\n"
    .string "我是一个货真价实的宝可梦狂！\p"
    .string "嘿！\n"
    .string "为什么要摆出一副怀疑的表情？\p"
    .string "小姐，我没和你开玩笑！\p"
    .string "我试验失败了然后和\n"
    .string "一只宝可梦合体了！\p"
    .string "那么，你觉得怎么样？\n"
    .string "帮我恢复原状吧！$"

Route25_SeaCottage_Text_RunCellSeparationOnPC::
    .string "请先等我进入\n"
    .string "传送装置。\p"
    .string "等我进去了以后，去我的电脑运行\n"
    .string "细胞分离系统。$"

Route25_SeaCottage_Text_NoPleaseChief::
    .string "不！？\n"
    .string "你不能这么冷淡！\p"
    .string "拜托，你一定要帮我这个陷入了\n"
    .string "大——大——大麻烦的人！\p"
    .string "怎样，帅哥？\n"
    .string "好吧？\l"
    .string "行吧？\l"
    .string "太好了！$"

Route25_SeaCottage_Text_NoPleaseBeautiful::
    .string "不！？\n"
    .string "你不能这么冷淡！\p"
    .string "拜托，你一定要帮我这个陷入了\n"
    .string "大——大——大麻烦的人！\p"
    .string "怎样，美女？\n"
    .string "好吧？\l"
    .string "行吧？\l"
    .string "太好了！$"

Route25_SeaCottage_Text_ThanksBudTakeThis::
    .string "正辉：啊呀呀呀！\n"
    .string "谢了，兄弟！我欠你一次！\p"
    .string "嗯，你看过我的\n"
    .string "宝可梦收藏了吗？\p"
    .string "还没有？\n"
    .string "太可惜了。\p"
    .string "我该怎样表达我的谢意……\n"
    .string "啊，这个，这个应该不错的。$"

Route25_SeaCottage_Text_ThanksLadyTakeThis::
    .string "正辉：啊呀呀呀！\n"
    .string "谢了，小姐！我欠你一次！\p"
    .string "嗯，你看过我的\n"
    .string "宝可梦收藏了吗？\p"
    .string "还没有？\n"
    .string "太可惜了。\p"
    .string "我该怎样表达我的谢意……\n"
    .string "啊，这个，这应该不错的。$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill::
    .string "{PLAYER}从正辉手上\n"
    .string "接过船票。$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff::
    .string "你身上的东西太多了！$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead::
    .string "这艘圣特安努号巡航船\n"
    .string "现在停在枯叶市。\p"
    .string "我听说有很多训练家\n"
    .string "都会上船。\p"
    .string "他们邀请过我，\n"
    .string "不过我不习惯这种大场面。\p"
    .string "所以你能代替我去吗？\n"
    .string "去好好享受吧。$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
    .string "正辉：想要在我的电脑上\n"
    .string "看我珍贵的宝可梦？\p"
    .string "那就请看吧。$"

Route25_SeaCottage_Text_TeleporterIsDisplayed::
    .string "传送装置显示在\n"
    .string "电脑的屏幕上。$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
    .string "{PLAYER}启动了传送装置的\n"
    .string "细胞分离器。$"

Route25_SeaCottage_Text_BillsFavoriteMonList::
    .string "正辉的最爱的宝可梦列表！$"

Route25_SeaCottage_Text_SeeWhichMon::
    .string "你想看哪只宝可梦？$"

