@ Male and female text identical, differ (presumably) in JP
Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale::
    .string "我宝可梦的骨灰寄存在\n"
    .string "宝可梦塔。\p"
    .string "把这个招式学习器拿走吧。\n"
    .string "我不再需要它了……$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale::
    .string "我宝可梦的骨灰寄存在\n"
    .string "宝可梦塔。\p"
    .string "把这个招式学习器拿走吧。\n"
    .string "我不再需要它了……$"

Route12_NorthEntrance_2F_Text_ReceivedTM27FromLittleGirl::
    .string "{PLAYER}从小女孩那\n"
    .string "得到了招式学习器27。$"

Route12_NorthEntrance_2F_Text_ExplainTM27::
    .string "招式学习器27记录着报恩……\p"
    .string "如果你把宝可梦照顾得很好，\n"
    .string "它将会在战斗中\l"
    .string "以最大的力量回馈你的爱。$"

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis::
    .string "你包包的空间不足以存放此道具。$"

Route12_NorthEntrance_2F_Text_TheresManFishing::
    .string "有架望远镜……\n"
    .string "我来看看……\p"
    .string "一个正在钓鱼的男人……！$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
    .string "有架望远镜……\n"
    .string "我来看看……\p"
    .string "那是一座宝可梦塔！$"

