CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked::
    .string "我是特地来拜访红莲道馆的，\n"
    .string "但是这里的门却锁得很紧。\p"
    .string "这附近某个地方\n"
    .string "一定有一把能开门的钥匙。\p"
    .string "它该不会在\n"
    .string "那幢被烧毁的房子里吧？\p"
    .string "我听说这岛上的道馆馆主的朋友\n"
    .string "曾经住在那里。$"

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom::
    .string "你有那么一些朋友吗？\p"
    .string "毫无疑问，\n"
    .string "和他们联机是很有趣的。\p"
    .string "既然如此何不去\n"
    .string "联盟交谊厅看看呢？\p"
    .string "谁知道呢，\n"
    .string "你会交到新的朋友也说不定呢。\p"
    .string "我想联盟交谊厅\n"
    .string "一定值得一去。$"

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves::
    .string "宝可梦在取消进化之后\n"
    .string "仍然可以学会新招式。\p"
    .string "可以等新招式学会了\n"
    .string "之后再进化。$"

CinnabarIsland_PokemonCenter_1F_Text_ReadyToSailToOneIsland::
    .string "正辉：嘿，让我好等！\n"
    .string "准备好乘船去一之岛了吗？$"

CinnabarIsland_PokemonCenter_1F_Text_OhNotDoneYet::
    .string "噢，你还是没准备好？$"

CinnabarIsland_PokemonCenter_1F_Text_LetsGo::
    .string "好，就是这样。\n"
    .string "出发了！$"

