PokemonTower_2F_Text_RivalIntro::
    .string "{B_OPPONENT_MON1_NAME}：嘿，{PLAYER}！\n"
    .string "什么风把你吹来的？\l"
    .string "你的宝可梦死了吗？\p"
    .string "嘿！还活着嘛！\p"
    .string "我至少还可以把它们打到晕！\n"
    .string "开战吧！$"

PokemonTower_2F_Text_RivalDefeat::
    .string "什么？\n"
    .string "你这个讨厌鬼！\p"
    .string "我刚才对你手下留情了！$"

@ Unused. Translated below
@ Aw, man! They really kicked the bucket! Weak! Do them a favor and raise them more properly.
PokemonTower_2F_Text_RivalVictory::
    .string "{RIVAL}“あーあ‥！\n"
    .string "ほんとに　くたばっちまったぞ！\l"
    .string "よわいなー！\l"
    .string "もっと　ちゃんと　そだてて　やれよ$"

PokemonTower_2F_Text_RivalPostBattle::
    .string "你的宝可梦图鉴收集得怎么样了？\n"
    .string "我刚抓住了一只卡拉卡拉！\p"
    .string "我找不到进化后的嘎啦嘎啦。\n"
    .string "它们在哪儿呢？\p"
    .string "这里肯定是没有了！\p"
    .string "嗯，我得走了。\n"
    .string "我可不像你，\l"
    .string "我还有很多事情要做。\p"
    .string "再见！$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
    .string "我们无法确认\n"
    .string "幽灵的真面目！\p"
    .string "用西尔佛检视镜的话\n"
    .string "也许就能看清了！$"

