CeruleanCity_Gym_Text_MistyIntro::
    .string "嗨，你是个新人啊！\p"
    .string "只有那些懂战术的训练家\n"
    .string "能在这儿出现。\p"
    .string "你收服和训练宝可梦时\n"
    .string "会讲究战术吗？\p"
    .string "我的战术就是用\n"
    .string "我的水属性宝可梦全力地猛攻！{PLAY_BGM 0x56 0x01}$"

CeruleanCity_Gym_Text_ExplainTM03::
    .string "招式学习器03是水之波动。\p"
    .string "把它用在水属性宝可梦身上吧！$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
    .string "蓝色徽章能让所有的\n"
    .string "30级以下的宝可梦听你的话，\p"
    .string "包括那些从别人那儿交换得到的。\p"
    .string "而且你可以在对战外\n"
    .string "使用居合劈砍断挡路的小树。\p"
    .string "还有这是我最喜欢的\n"
    .string "招式学习器，要好好保管哦！$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .string "{PLAYER}得到了招式学习器03。$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .string "你的包包满了！$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "哇！\n"
    .string "你真厉害！\p"
    .string "很好！\p"
    .string "这个蓝色徽章给你啦，\n"
    .string "作为你打败过我的证明。$"

CeruleanCity_Gym_Text_DianaIntro::
    .string "什么？就你？\n"
    .string "我比你可强多了！\p"
    .string "不能随便去打扰小霞！$"

CeruleanCity_Gym_Text_DianaDefeat::
    .string "你打败了我！$"

CeruleanCity_Gym_Text_DianaPostBattle::
    .string "你必须面对其他的训练家，\n"
    .string "看看你到底有多强大。$"

CeruleanCity_Gym_Text_LuisIntro::
    .string "哈！\p"
    .string "我是第一个！\n"
    .string "我们开战吧！$"

CeruleanCity_Gym_Text_LuisDefeat::
    .string "不可能吧！$"

CeruleanCity_Gym_Text_LuisPostBattle::
    .string "小霞总是不断地提升着自己。\p"
    .string "她是不会输给你这种新手的！$"

CeruleanCity_Gym_Text_GymGuyAdvice::
    .string "哟！\n"
    .string "未来的冠军！\p"
    .string "给你一些建议吧！\p"
    .string "这个馆主小霞，\n"
    .string "使用的是水属性宝可梦。\p"
    .string "你可以用草属性宝可梦\n"
    .string "吸收它们的水份。\p"
    .string "或者你也可以用电属性\n"
    .string "宝可梦电击它们！$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
    .string "你战胜了小霞！\n"
    .string "看吧，我说什么来着？\p"
    .string "你和我，小子，\n"
    .string "我们组成了一个强大之极的队伍！$"

CeruleanCity_Gym_Text_GymStatue::
    .string "华蓝宝可梦道馆\n"
    .string "馆主：小霞\p"
    .string "优胜训练家：\n"
    .string "{B_OPPONENT_MON1_NAME}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "华蓝宝可梦道馆\n"
    .string "馆主：小霞\p"
    .string "优胜训练家：\n"
    .string "{B_OPPONENT_MON1_NAME}，{PLAYER}$"

