FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
    .string "啊……\n"
    .string "哦，没错，我是遗忘爷爷。\p"
    .string "我可以帮宝可梦忘记招式。\p"
    .string "需要让我帮宝可梦忘记招式吗？$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
    .string "哪一只宝可梦想要\n"
    .string "忘记招式？$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
    .string "要忘记哪个招式？$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
    .string "{B_COPY_VAR_1}好像只会\n"
    .string "一个招式……$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
    .string "嗯！{B_COPY_VAR_1}的{B_COPY_VAR_2}吗？\n"
    .string "要忘记这个招式？$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
    .string "完美搞定！\p"
    .string "{B_COPY_VAR_1}已经将\n"
    .string "{B_COPY_VAR_2}忘得一干二净了。$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
    .string "如果你有别的招式想要忘记\n"
    .string "那么欢迎再次光临。$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
    .string "你在想什么？\n"
    .string "蛋怎么可能会学招式。$"

