Text_DreamEaterTeach::
    .string "哈欠！\n"
    .string "在这种阳光下我肯定会打起瞌睡。\p"
    .string "然后我做了一个一只\n"
    .string "催眠貘正在吞食我做的梦的怪梦。\p"
    .string "在那之后……\n"
    .string "我学会了如何食梦……\p"
    .string "噢，真是太恐怖了！\p"
    .string "让我把它教给一只宝可梦吧\n"
    .string "这样我才能赶快忘了它！$"

Text_DreamEaterDeclined::
    .string "……呼……$"

Text_DreamEaterWhichMon::
    .string "哪一只宝可梦想要学会\n"
    .string "食梦呢？$"

Text_DreamEaterTaught::
    .string "…ZZZ…\n"
    .string "我…吃不…下了…$"

PewterCity_Text_ClefairyCameFromMoon::
    .string "有这样一个传说，\n"
    .string "说皮皮来自月亮。\p"
    .string "在那之后月之石\n"
    .string "才出现在了月见山。$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .string "这里没有那种很严肃的\n"
    .string "宝可梦训练家。\p"
    .string "他们都打扮得像个捉虫少年，\n"
    .string "你懂的，就是一种癖好。\p"
    .string "可深灰道馆的小刚并不像这样打扮。\n"
    .string "不像，一点都不像。$"

PewterCity_Text_DidYouCheckOutMuseum::
    .string "你去博物馆看过了吗？$"

PewterCity_Text_WerentThoseFossilsAmazing::
    .string "不觉得这些来自月见山的化石\n"
    .string "很令人吃惊吗？$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "不会吧……？\n"
    .string "那你一定、必须、绝对\l"
    .string "要去参观一下！$"

PewterCity_Text_ThisIsTheMuseum::
    .string "博物馆就在这里了。\p"
    .string "虽然你必须花钱买了票才能进去，\n"
    .string "但是里面非常值得一看。回头见！$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "嘘！\n"
    .string "你知道我正在做什么吗？$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "没错！\n"
    .string "这事做起来可不轻松！$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .string "我正在喷除虫喷雾，好让那些野生的\n"
    .string "宝可梦远离我的花园！$"

PewterCity_Text_BrocksLookingForChallengersFollowMe::
    .string "你是一个训练家，对吗？\p"
    .string "小刚正在寻找新的挑战者\n"
    .string "跟我来！$"

PewterCity_Text_GoTakeOnBrock::
    .string "如果你有了正确的信念，\n"
    .string "就应该去打倒小刚！$"

PewterCity_Text_TrainerTipsEarningEXP::
    .string "……有用的公告牌！\p"
    .string "在战斗中出场过的宝可梦，\n"
    .string "无论登场时间长短都会获得经验值。$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .string "紧急通告！\p"
    .string "近日有些小偷正在对月见山的\n"
    .string "宝可梦化石下手。\p"
    .string "如果你有任何线索，\n"
    .string "请立即联系深灰市警察局。$"

PewterCity_Text_MuseumOfScience::
    .string "深灰科学博物馆$"

PewterCity_Text_GymSign::
    .string "深灰市宝可梦道馆\n"
    .string "馆主：小刚\l"
    .string "有如磐石般坚硬的宝可梦训练家！$"

PewterCity_Text_CitySign::
    .string "深灰市\n"
    .string "灰色的岩石之城$"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
    .string "あッれー！\n"
    .string "その　ジムバッジ‥‥\l"
    .string "すげえな　タケシに　かったのかよ！\p"
    .string "かんどう　したから\n"
    .string "おれの　たからもの　やるよ！$"

PewterCity_Text_BerriesInsideUseCarefully::
    .string "なかには　きのみが　はいってるぜ\p"
    .string "やくに　たつ　きのみも\n"
    .string "はいって　いるから\l"
    .string "だいじに　つかって　くれよ！$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
    .string "ポケモンに　きのみを\n"
    .string "もたせて　おけば\l"
    .string "たたかっている　ときに\l"
    .string "かってに　つかって　くれるんだ\p"
    .string "キズぐすり　とか　どくけし　より\n"
    .string "てがるで　べんり　だろ？$"

PewterCity_Text_OhPlayer::
    .string "噢，{PLAYER}{B_PLAYER_MON1_NAME}！$"

PewterCity_Text_AskedToDeliverThis::
    .string "能够赶上你真高兴。\n"
    .string "我是大木博士的助手。\p"
    .string "给。\n"
    .string "我被叮嘱要把这件东西带给你。$"

PewterCity_Text_ReceivedRunningShoesFromAide::
    .string "{PLAYER}从助手那里\n"
    .string "获得了跑步鞋。$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .string "{PLAYER}换上了\n"
    .string "跑步鞋。$"

PewterCity_Text_ExplainRunningShoes::
    .string "现在开始按B键就可以跑步了。\n"
    .string "但是只能在空旷的地方跑哦！$"

PewterCity_Text_MustBeGoingBackToLab::
    .string "那么，我必须回\n"
    .string "研究所去了。\p"
    .string "再见啦！$"

PewterCity_Text_RunningShoesLetterFromMom::
    .string "是一封信……\p"
    .string "亲爱的{PLAYER}，\p"
    .string "这双跑步鞋\n"
    .string "是给我心爱的挑战者的。\p"
    .string "我一直都会祝福你。\n"
    .string "记住，永远不要中途就放弃了！\p"
    .string "妈妈$"

