PokemonTower_3F_Text_HopeIntro::
    .string "呃……哇……\n"
    .string "呼呼……嘎嘎……$"

PokemonTower_3F_Text_HopeDefeat::
    .string "哗！\n"
    .string "得救了！$"

PokemonTower_3F_Text_HopePostBattle::
    .string "用西尔佛检视镜\n"
    .string "可以看清幽灵的真面目！$"

PokemonTower_3F_Text_CarlyIntro::
    .string "………………\n"
    .string "……咔咔！$"

PokemonTower_3F_Text_CarlyDefeat::
    .string "……啊？\n"
    .string "我在做什么啊？$"

PokemonTower_3F_Text_CarlyPostBattle::
    .string "对不起！我被恶灵附身了，\n"
    .string "所以不受控制地胡闹了起来。$"

PokemonTower_3F_Text_PatriciaIntro::
    .string "滚！\n"
    .string "邪恶的幽灵！$"

PokemonTower_3F_Text_PatriciaDefeat::
    .string "呼……！\n"
    .string "……恶灵逃走了吗？$"

PokemonTower_3F_Text_PatriciaPostBattle::
    .string "上面的人……\n"
    .string "他们一定被鬼迷心窍了。$"

