SilphCo_9F_Text_YouShouldTakeQuickNap::
    .string "你看起来很累。\n"
    .string "你应该快去休息一下。$"

SilphCo_9F_Text_DontGiveUp::
    .string "不要放弃！$"

SilphCo_9F_Text_ThankYouSoMuch::
    .string "太感谢你了。$"

SilphCo_9F_Text_Grunt1Intro::
    .string "你的宝可梦看起来很喜欢你，\n"
    .string "孩子！$"

SilphCo_9F_Text_Grunt1Defeat::
    .string "嘎啊！$"

SilphCo_9F_Text_Grunt1PostBattle::
    .string "如果我在你这个年纪\n"
    .string "就开始当训练家……$"

SilphCo_9F_Text_EdIntro::
    .string "你的宝可梦……有弱点！\n"
    .string "只要攻击弱点，我就能赢！$"

SilphCo_9F_Text_EdDefeat::
    .string "没等我找出弱点……\n"
    .string "我就被打败了。$"

SilphCo_9F_Text_EdPostBattle::
    .string "利用对方的弱点做出对策。\n"
    .string "想想属性优势。$"

SilphCo_9F_Text_Grunt2Intro::
    .string "我是火箭队\n"
    .string "四兄弟之一！$"

SilphCo_9F_Text_Grunt2Defeat::
    .string "哇！\n"
    .string "兄弟们，我输了！$"

SilphCo_9F_Text_Grunt2PostBattle::
    .string "我的兄弟们会为我报仇的！$"

SilphCo_9F_Text_FloorSign::
    .string "西尔佛公司总部\n"
    .string "9F$"

