ThreeIsland_Port_Text_WereKantoRiderFederation::
    .string "我们是关都暴走帮！\n"
    .string "呜！呜！呜！\p"
    .string "我的车子太安静了，所以\n"
    .string "我不得不自己发出排气的声音！$"

ThreeIsland_Port_Text_ForkOverMoney::
    .string "嘿，站住，小姐！\n"
    .string "借点儿钱花花！$"

ThreeIsland_Port_Text_IllCallThePolice::
    .string "哎！\p"
    .string "你，你是谁？！\n"
    .string "我要叫警察了！$"

ThreeIsland_Port_Text_ThankGoodnessBikersGone::
    .string "那些暴走族……\n"
    .string "它们都不见了？\p"
    .string "真是谢天谢地！\n"
    .string "那些家伙都让我烦透了！$"

ThreeIsland_Port_Text_EverythingTurnedOutForBest::
    .string "那些暴走族不见了，\n"
    .string "但小迷很安全。\p"
    .string "一切事情都变好了！$"

