PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{B_OPPONENT_MON1_NAME}：什么，只有{PLAYER}？\n"
    .string "爷爷不在这儿。$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "{B_OPPONENT_MON1_NAME}：爷爷！\n"
    .string "我都等不及了！$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "{B_OPPONENT_MON1_NAME}：嘿！爷爷！这不公平！\n"
    .string "我也要！$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "{B_OPPONENT_MON1_NAME}：哼，我没有像你一样那么急。\n"
    .string "我成熟得很！\p"
    .string "你先去选吧，{PLAYER}！$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "{B_OPPONENT_MON1_NAME}：那我就要这只了！$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "{B_OPPONENT_MON1_NAME}从大木博士那儿\n"
    .string "得到了{B_COPY_VAR_1}！$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "{B_OPPONENT_MON1_NAME}：我的宝可梦看起来\n"
    .string "比你的厉害。$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "{B_OPPONENT_MON1_NAME}：等等，{PLAYER}！\n"
    .string "让我们检验一下各自的宝可梦！\p"
    .string "来吧，我会打败你！$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "什么？\n"
    .string "难以置信！\l"
    .string "我拿错了宝可梦！$"

@ Also used for early Route 22 battle
Text_RivalVictory::
    .string "{B_OPPONENT_MON1_NAME}：耶！\n"
    .string "我很强吧？$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "{B_OPPONENT_MON1_NAME}：我要让我的宝可梦战斗\n"
    .string "来使它变强！\p"
    .string "{PLAYER}！爷爷！\n"
    .string "回见！$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{B_OPPONENT_MON1_NAME}：爷爷！$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{B_OPPONENT_MON1_NAME}：我差点忘了！\n"
    .string "你叫我来干什么？$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{B_OPPONENT_MON1_NAME}：好的，爷爷！\n"
    .string "全部交给我吧！$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "{PLAYER}，我说句不好听的话，\n"
    .string "你没必做这么多努力。\p"
    .string "我要去向我姐姐借张城镇地图！\p"
    .string "我会告诉她别借给你！\n"
    .string "{PLAYER}！哈哈！\p"
    .string "之后不要因为这个\n"
    .string "来我们家了！$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "大木：{B_OPPONENT_MON1_NAME}？\n"
    .string "我想想……\p"
    .string "噢，对了，是我叫你来的！\n"
    .string "等等！\p"
    .string "来这儿，{PLAYER}。\p"
    .string "这儿有三只宝可梦。\p"
    .string "哈哈！\p"
    .string "宝可梦都在这些\n"
    .string "精灵球里面。\p"
    .string "我年轻的时候，\n"
    .string "可是一个厉害的宝可梦训练家。\p"
    .string "但是现在，我老了！\n"
    .string "只剩下了这三只宝可梦了。\p"
    .string "你可以从中挑一个。\n"
    .string "去选吧！$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "大木：耐心点，{B_OPPONENT_MON1_NAME}。\n"
    .string "你也可以选一只的！$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "大木：现在，{PLAYER}。\p"
    .string "在那三个精灵球里面\n"
    .string "都是宝可梦。\p"
    .string "你想要哪一只？$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "大木：嘿！\n"
    .string "别急着走啊！$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "啊！你选择了小火龙。\n"
    .string "你要耐心地培养它。\p"
    .string "好的，{PLAYER}，你确定要和火属性的\n"
    .string "小火龙并肩作战吗？$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "嗯！你选择了杰尼龟。\n"
    .string "它很值得培养。\p"
    .string "好的，{PLAYER}，你确定要与水属性的\n"
    .string "杰尼龟成为搭档吗？$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "嗯！你选择了妙蛙种子。\n"
    .string "它非常好培养。\p"
    .string "好的，{PLAYER}，你确定要同草属性的\n"
    .string "妙蛙种子一起冒险吗？$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "这只宝可梦充满了活力！\n"
    .string "它看起来很开心！$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "{PLAYER}从大木博士那儿\n"
    .string "得到了{B_COPY_VAR_1}！$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "大木：如果有野生的宝可梦出现了，\n"
    .string "你的宝可梦就能和它战斗。\p"
    .string "有宝可梦陪在你身边，\n"
    .string "你就能抵达下一个城镇了。$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "大木：{PLAYER}，想好好培育你的宝可梦\n"
    .string "就多让它战斗吧。\p"
    .string "它得在战斗中成长。$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "大木：{PLAYER}！\n"
    .string "我给你的宝可梦怎么样了？\p"
    .string "嗯，他好像已经\n"
    .string "离不开你了。\p"
    .string "你一定是个天才宝可梦训练家。\p"
    .string "你说什么？\n"
    .string "你有东西要给我？$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER}交出了大木的包裹。$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "啊！\n"
    .string "这是我订制的精灵球！\p"
    .string "是我订的没错。\n"
    .string "谢谢你！$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "大木：噢，对了！\n"
    .string "我对你们两个有个请求。$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "那桌子上的是我的发明，\n"
    .string "宝可梦图鉴！\p"
    .string "它能自动记录你见过或收服的\n"
    .string "宝可梦的资料。\p"
    .string "它是一部高科技的百科全书！$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "大木：{PLAYER}和{B_OPPONENT_MON1_NAME}。\n"
    .string "拿着这个吧。$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "{PLAYER}从大木博士那儿\n"
    .string "得到了宝可梦图鉴。$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "大木：如果你仅仅是发现宝可梦，\n"
    .string "你是无法得到它们的详细资料的。\p"
    .string "你必须抓住它们\n"
    .string "来获取完整的资料。\p"
    .string "那么，给你一些收服\n"
    .string "野生宝可梦的工具吧。$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "{PLAYER}得到了5个精灵球。$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "当野生宝可梦出现时，\n"
    .string "战斗就开始了。\p"
    .string "向它扔出一个精灵球\n"
    .string "就能试去着收服它！\p"
    .string "但是，这不一定会成功。\p"
    .string "精神饱满的宝可梦是能逃走的。\n"
    .string "想要成功需要点运气！$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "收集齐世界上所有宝可梦的资料……\p"
    .string "一直是我的梦想！\p"
    .string "但是，我太老了。\n"
    .string "我不能完成这项任务了。\p"
    .string "所以，我希望你们俩能替我\n"
    .string "实现我的梦想。\p"
    .string "出发吧。\p"
    .string "这是宝可梦史上\n"
    .string "最伟大的事业！$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "这个世界的宝可梦正等着你，{PLAYER}！$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "啊，{PLAYER}！\n"
    .string "你的宝可梦图鉴完成得怎么样了？\p"
    .string "{B_OPPONENT_MON1_NAME}已经收服了一些宝可梦，\n"
    .string "而且添加了一些资料。\p"
    .string "那么，{PLAYER}，\n"
    .string "我来看看你的宝可梦图鉴。\p"
    .string "……怎么回事？\n"
    .string "你还没有添加任何新的数据。\p"
    .string "这个给你好了，\n"
    .string "希望你更努力些。$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "大木：有空了就回来看看我。\p"
    .string "我也想了解下，你的宝可梦图鉴工作\n"
    .string "进展到了什么样的程度。$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "像图鉴一样的东西，\n"
    .string "只是里面是空白的。$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "一些精灵球。\n"
    .string "里面装着宝可梦！$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "这是大木博士最后的宝可梦。$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "按开始键打开菜单！$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "保存选项在菜单里。\n"
    .string "好好利用它吧。$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "所有类型的宝可梦在对战时\n"
    .string "都有它的优势和弱势。$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "这儿有一封电子邮件……\p"
    .string "终于！\n"
    .string "宝可梦联盟最强的训练家\l"
    .string "准备好迎接\l"
    .string "各位的挑战了！\p"
    .string "带上你最好的宝可梦，\n"
    .string "看看你作为一个训练家的表现！\p"
    .string "宝可梦联盟总部\n"
    .string "石英高原\p"
    .string "大木博士，请来挑战我们吧！\n"
    .string "……$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "我是大木博士的助手，\n"
    .string "我在研究宝可梦。$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "嗨，{PLAYER}。我相信\n"
    .string "你和你的宝可梦相处得很好吧。\p"
    .string "对了，你知道奈奈美吗？\p"
    .string "如果你把你的宝可梦给娜娜妹看，\n"
    .string "她会告诉你宝可梦喜欢你的程度，\p"
    .string "有时候，她甚至会帮你的\n"
    .string "宝可梦梳理毛发。\p"
    .string "这是一个秘密喔，\n"
    .string "请不要告诉任何人。$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "大木博士要有他自己的\n"
    .string "广播节目了。\p"
    .string "这个节目被叫做大木博士\n"
    .string "的宝可梦大讲堂。$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "大木博士可能长得不是很帅，\n"
    .string "但他是宝可梦研究的权威。\p"
    .string "宝可梦训练家都非常尊敬他。$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "啊，真是棒极了！\p"
    .string "{PLAYER}，我有另一个重大的\n"
    .string "事情想要请你帮忙。\p"
    .string "你可要认真听好了。$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "最近，出现了很多\n"
    .string "珍贵的宝可梦品种。\p"
    .string "我是在说我们在关都\n"
    .string "从来没见过的宝可梦。\p"
    .string "我想要自己去亲眼见识它们，\n"
    .string "但是我太老了。\p"
    .string "我自己无法干这件事了，{PLAYER}\n"
    .string "我想让你去替我完成。$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{B_OPPONENT_MON1_NAME}：嘿，我听说了！\p"
    .string "爷爷，为什么总是要{PLAYER}帮你\n"
    .string "而不是我？\p"
    .string "我用了更快的速度\n"
    .string "收集了更多的宝可梦，\p"
    .string "你应该让我来完成\n"
    .string "一切事情就行了。$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "大木：我知道，我知道。\n"
    .string "我当然也需要你的帮助。\p"
    .string "现在，我要看看你们俩的宝可梦图鉴。$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "大木博士拿了二人的宝可梦图鉴。$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "…………………………\p"
    .string "…………………………\p"
    .string "……完成了！\p"
    .string "现在这个机器能记录更多\n"
    .string "宝可梦的数据了。$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "{PLAYER}的宝可梦图鉴升级了！$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "现在，{PLAYER}和{B_OPPONENT_MON1_NAME}！\p"
    .string "这次，你们真的要努力\n"
    .string "填满你们的宝可梦图鉴。\p"
    .string "我希望你们能把它们做成\n"
    .string "最好的最完整的图鉴！\p"
    .string "说真的，这在宝可梦的历史上\n"
    .string "是一项伟大的任务！$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{B_OPPONENT_MON1_NAME}：冷静点，爷爷！\n"
    .string "可别太激动了。\p"
    .string "我会完成宝可梦图鉴的，\n"
    .string "你不用担心。\p"
    .string "我想我首先要调查一之岛……\p"
    .string "不管怎么说，我出发了！$"

