Route24_Text_JustEarnedFabulousPrize::
    .string "祝贺你！你战胜了\n"
    .string "我们五个训练家！\p"
    .string "你获得了一份神秘大礼！$"

Route24_Text_ReceivedNuggetFromMysteryTrainer::
    .string "{PLAYER}从谜之训练家那儿\n"
    .string "获得了一个金珠！$"

Route24_Text_YouDontHaveAnyRoom::
    .string "你没有退路了！$"

Route24_Text_JoinTeamRocket::
    .string "顺便问问，\n"
    .string "你想加入火箭队吗？\p"
    .string "我们是以抢夺宝可梦为主的\n"
    .string "专业犯罪组织。\p"
    .string "想加入吗？\p"
    .string "你确定？\p"
    .string "来吧，加入我们吧！\p"
    .string "我是叫你加入我们！\p"
    .string "好吧，看来得给你来点硬的！\p"
    .string "我要让你无法拒绝！$"

Route24_Text_RocketDefeat::
    .string "啊！\n"
    .string "你太强了！$"

Route24_Text_YoudBecomeTopRocketLeader::
    .string "以你的能力，\n"
    .string "你能成为火箭队的高级干部。\p"
    .string "瞧瞧，多么好的机会！\n"
    .string "浪费掉真是太可惜了。$"

Route24_Text_ShaneIntro::
    .string "呵呵……！你的出色表现\n"
    .string "我在草丛里可都看到了。$"

Route24_Text_ShaneDefeat::
    .string "……果然不行么。$"

Route24_Text_ShanePostBattle::
    .string "我藏着是因为\n"
    .string "我害怕桥上的人们。$"

Route24_Text_EthanIntro::
    .string "嗯！我是5号！\n"
    .string "我要把你踏在脚下！$"

Route24_Text_EthanDefeat::
    .string "你可真了不起！$"

Route24_Text_EthanPostBattle::
    .string "我尽力了，无怨无悔！$"

Route24_Text_ReliIntro::
    .string "我是4号！\n"
    .string "感觉累了吗？$"

Route24_Text_ReliDefeat::
    .string "我也输了呢。$"

Route24_Text_ReliPostBattle::
    .string "我尽力了，我不后悔！$"

Route24_Text_TimmyIntro::
    .string "3号在这儿！\n"
    .string "我可没那么容易搞定！$"

Route24_Text_TimmyDefeat::
    .string "哎呀呀，我不行了。$"

Route24_Text_TimmyPostBattle::
    .string "我尽力了，无怨无悔！$"

Route24_Text_AliIntro::
    .string "我是2号！\n"
    .string "现在要认真了！$"

Route24_Text_AliDefeat::
    .string "简直不可置信！$"

Route24_Text_AliPostBattle::
    .string "我尽力了，无怨无悔！$"

Route24_Text_CaleIntro::
    .string "人们把这里称作\n"
    .string "金珠大桥！\p"
    .string "战胜我们五个训练家就可以\n"
    .string "获得一份神秘大礼！\p"
    .string "你能得到它吗？$"

Route24_Text_CaleDefeat::
    .string "呼！\n"
    .string "好家伙！$"

Route24_Text_CalePostBattle::
    .string "我尽力了，无怨无悔！$"
