ThreeIsland_Mart_Text_TrueThatCeldadonDeptStoreBigger::
    .string "真的假的？\p"
    .string "玉虹百货公司\n"
    .string "比这个商店大好几十倍？！$"

ThreeIsland_Mart_Text_PeopleHealWithBerriesFromForest::
    .string "有时我在这儿买药。\p"
    .string "但有很多人用来自树果森林\n"
    .string "的树果治疗宝可梦。\p"
    .string "这是因为树果不要钱\n"
    .string "而且取之不尽，用之不竭！$"

ThreeIsland_Mart_Text_BikersWereAboutToTrashMart::
    .string "这些暴走族会弄脏\n"
    .string "这座宝可梦商店。\p"
    .string "要是他们能离开就好了！$"

