Route11_Text_HugoIntro::
    .string "是输是赢，一决胜负！$"

Route11_Text_HugoDefeat::
    .string "喂！\n"
    .string "别挡了我的路！$"

Route11_Text_HugoPostBattle::
    .string "宝可梦就是我的人生！\n"
    .string "人生就是一场赌博！$"

Route11_Text_JasperIntro::
    .string "竞技！\n"
    .string "这一点还满足不了我！$"

Route11_Text_JasperDefeat::
    .string "我还有的是机会！$"

Route11_Text_JasperPostBattle::
    .string "在宝可梦的世界里\n"
    .string "你不能做胆小鬼！$"

Route11_Text_EddieIntro::
    .string "来吧！但不许耍赖！$"

Route11_Text_EddieDefeat::
    .string "嗯？\n"
    .string "这不科学！$"

Route11_Text_EddiePostBattle::
    .string "我堂堂正正战斗过了！\n"
    .string "所以我不后悔！$"

Route11_Text_BraxtonIntro::
    .string "当心点！\n"
    .string "我正在接电线呢！$"

Route11_Text_BraxtonDefeat::
    .string "电线可是导电的！$"

Route11_Text_BraxtonPostBattle::
    .string "有句话忘记对你说了！\n"
    .string "要注意用电安全！$"

Route11_Text_DillonIntro::
    .string "虽然我成为训练家没多久。\n"
    .string "但是，这一战我坚信我能赢。$"

Route11_Text_DillonDefeat::
    .string "我的宝可梦还战胜不了你……\n"
    .string "它们还没成长到那个水平吗？$"

Route11_Text_DillonPostBattle::
    .string "怎么了？\n"
    .string "让我一个人待一会！$"

Route11_Text_DirkIntro::
    .string "哈哈哈！\n"
    .string "我至今还没有输过！$"

Route11_Text_DirkDefeat::
    .string "哈！\n"
    .string "头一次输了！$"

Route11_Text_DirkPostBattle::
    .string "你只是走运罢了。$"

Route11_Text_DarianIntro::
    .string "我还从来没赢过……$"

Route11_Text_DarianDefeat::
    .string "我早就预料到了……$"

Route11_Text_DarianPostBattle::
    .string "我很不幸，一直如此。$"

Route11_Text_YasuIntro::
    .string "在班里我是最强的。\n"
    .string "每天早上我都要特训。$"

Route11_Text_YasuDefeat::
    .string "讨厌！\n"
    .string "我的宝可梦要变得更强！$"

Route11_Text_YasuPostBattle::
    .string "那里有一只胖乎乎的宝可梦\n"
    .string "是从山上下来的。\p"
    .string "如果你能收服它\n"
    .string "肯定会得到一个强力伙伴的。$"

Route11_Text_BernieIntro::
    .string "当心电线！$"

Route11_Text_BernieDefeat::
    .string "哇哦！\n"
    .string "电火花溅起来了！$"

Route11_Text_BerniePostBattle::
    .string "……好了好了！\n"
    .string "去工作啊去工作！$"

Route11_Text_DaveIntro::
    .string "这是我精心培育的宝可梦。\n"
    .string "是时候派它去战斗看看了！$"

Route11_Text_DaveDefeat::
    .string "拜拜……！\n"
    .string "谢谢你，再见！$"

Route11_Text_DavePostBattle::
    .string "切……\n"
    .string "我最好还是去找只更强的来！$"

Route11_Text_DiglettsCave::
    .string "地鼠洞$"

