CeladonCity_House1_Text_SlotsReelInTheDough::
    .string "呵呵呵！\p"
    .string "老虎机就是个无底洞，\n"
    .string "一个吸钱机器！$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
    .string "队长！\p"
    .string "我们今天刚又运来了2000个宝可梦\n"
    .string "作为老虎机的奖品！$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
    .string "千万别去碰游戏城的海报！\p"
    .string "那后面可没有什么秘密机关！$"

@ Text for the replaced altars in the rocket chiefs house / celadon mansion
@ In English RB, this is westernized as "It's a sculpture of DIGLETT.", and is removed altogether in FRLG
Text_ItsABuddhistAltar::
    .string "ぶつだん　だ‥$"
