Route14_Text_CarterIntro::
    .string "要想让你的宝可梦学到更强\n"
    .string "的招式就要善用招式学习器。$"

Route14_Text_CarterDefeat::
    .string "我觉得我还有待加强。$"

Route14_Text_CarterPostBattle::
    .string "你已经得到秘传学习器了吗？宝可梦不会\n"
    .string "轻易忘记从上面学得的招式。$"

Route14_Text_MitchIntro::
    .string "我的鸟宝可梦已经\n"
    .string "备战完毕。$"

Route14_Text_MitchDefeat::
    .string "还没准备好！$"

Route14_Text_MitchPostBattle::
    .string "我的鸟宝可梦需要\n"
    .string "学习更强的招式。$"

Route14_Text_BeckIntro::
    .string "玉虹百货公司\n"
    .string "出售好几种招式学习器。\p"
    .string "招式学习器并不是什么稀有物品，\n"
    .string "但是拥有它的人也不多。$"

Route14_Text_BeckDefeat::
    .string "真是丢人丢到家了。$"

Route14_Text_BeckPostBattle::
    .string "让宝可梦学习与它自身属性\n"
    .string "相符的招式。\p"
    .string "这样招式的伤害会有显著提升。$"

Route14_Text_MarlonIntro::
    .string "你教过你的鸟宝可梦\n"
    .string "如何飞翔了吗？\p"
    .string "你可以跟它一同在天空中\n"
    .string "翱翔！$"

Route14_Text_MarlonDefeat::
    .string "在火焰中击落它！$"

Route14_Text_MarlonPostBattle::
    .string "飞行属性的宝可梦是我最钟爱的。\n"
    .string "任何其他的宝可梦都让我兴趣索然。$"

Route14_Text_DonaldIntro::
    .string "你听说过传说中\n"
    .string "飞行的幻影吗？$"

Route14_Text_DonaldDefeat::
    .string "为什么？\n"
    .string "我为什么输了？$"

Route14_Text_DonaldPostBattle::
    .string "飞行的幻影指的是\n"
    .string "传说中的鸟宝可梦。\p"
    .string "有三只：急冻鸟，\n"
    .string "闪电鸟和火焰鸟。$"

Route14_Text_BennyIntro::
    .string "我没有进去过，不过没关系。\n"
    .string "我们出发吧！$"

Route14_Text_BennyDefeat::
    .string "啊……果然是这样。$"

Route14_Text_BennyPostBattle::
    .string "输与赢……\n"
    .string "在宽广的天空下皆是浮云。$"

Route14_Text_LukasIntro::
    .string "来吧，开战。\n"
    .string "擂鼓，呐喊，冲锋！$"

Route14_Text_LukasDefeat::
    .string "哎！\n"
    .string "迷路了！走开！$"

Route14_Text_LukasPostBattle::
    .string "啊？什么？怎么了？\n"
    .string "你还想干嘛？$"

Route14_Text_IsaacIntro::
    .string "来得正好！\n"
    .string "别废话，快来对战！$"

Route14_Text_IsaacDefeat::
    .string "什么？\n"
    .string "你！？$"

Route14_Text_IsaacPostBattle::
    .string "总觉得我不擅长\n"
    .string "慢慢培育宝可梦！$"

Route14_Text_GeraldIntro::
    .string "这里地方很宽敞，\n"
    .string "所以我们就骑车过来了。$"

Route14_Text_GeraldDefeat::
    .string "哎呀，被绊倒了！$"

Route14_Text_GeraldPostBattle::
    .string "你把你的宝可梦培育得这么厉害，\n"
    .string "实在太酷了。\p"
    .string "速度即是力量！\n"
    .string "看来你已经领悟到了！$"

Route14_Text_MalikIntro::
    .string "宝可梦对决么！\n"
    .string "有意思！那就陪你玩玩！$"

Route14_Text_MalikDefeat::
    .string "我不接受！$"

Route14_Text_MalikPostBattle::
    .string "你知道谁是胜者，\n"
    .string "不是你就是我！$"

Route14_Text_RouteSign::
    .string "14号道路\n"
    .string "往西到浅红市$"

Route14_Text_KiriIntro::
    .string "阿雾：惠娜，我们一起试试，\n"
    .string "两个人一起胜率会更高点。$"

Route14_Text_KiriDefeat::
    .string "阿雾：呜，呜……\n"
    .string "我们输了么？$"

Route14_Text_KiriPostBattle::
    .string "阿雾：是因为我太弱的关系么？$"

Route14_Text_KiriNotEnoughMons::
    .string "阿雾：如果你有两只宝可梦\n"
    .string "我们就可以战斗啦。$"

Route14_Text_JanIntro::
    .string "惠娜：走吧，阿雾！\n"
    .string "我们得再度投入修炼！$"

Route14_Text_JanDefeat::
    .string "惠娜：不！\n"
    .string "这不公平！$"

Route14_Text_JanPostBattle::
    .string "惠娜：阿雾，别哭了！\n"
    .string "我们下次要更加努力才行。$"

Route14_Text_JanNotEnoughMons::
    .string "惠娜：你想战斗吗？\n"
    .string "你没有足够的宝可梦。$"
