SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner::
    .string "这艘轮船是为全世界训练家\n"
    .string "特设的豪华班轮！\p"
    .string "我们会和受邀的训练家们\n"
    .string "在每个港口开派对。$"

SSAnne_2F_Corridor_Text_RivalIntro::
    .string "{B_OPPONENT_MON1_NAME}：Hello！\n"
    .string "{PLAYER}！\p"
    .string "真没想到能在这里碰见你！\n"
    .string "{PLAYER}，你真的有被邀请吗？\p"
    .string "另外你的宝可梦图鉴\n"
    .string "收集得怎么样了？\p"
    .string "我已经收服40种了。\n"
    .string "不同的地方有不同的宝可梦。\p"
    .string "要匍匐在草地里，\n"
    .string "努力地寻找它们！$"

SSAnne_2F_Corridor_Text_RivalDefeat::
    .string "哼！\p"
    .string "你的宝可梦确实成长了！$"

SSAnne_2F_Corridor_Text_RivalVictory::
    .string "{PLAYER}‥！\n"
    .string "ふなよい　してるのか！\p"
    .string "もっと　からだ\n"
    .string "きたえた　ほうが　いいぜ！$"

SSAnne_2F_Corridor_Text_RivalPostBattle::
    .string "{B_OPPONENT_MON1_NAME}：我听说\n"
    .string "这船上有个居合劈大师。\p"
    .string "可他不过是一个爱晕船的老头！\p"
    .string "不过居合劈本身非常有用。\n"
    .string "没错，学会了它的话会非常方便。\p"
    .string "你也应该去拜访下他。\n"
    .string "我先闪了！$"

