Route10_Text_MarkIntro::
    .string "哇，你历经磨难终于到了我这里？\n"
    .string "也许你也是一个宝可梦狂对吗？\l"
    .string "想要看看我的收藏吗？$"

Route10_Text_MarkDefeat::
    .string "啊哼。\n"
    .string "我不会生气的！$"

Route10_Text_MarkPostBattle::
    .string "我家里还有\n"
    .string "更珍贵的宝可梦。$"

Route10_Text_ClarkIntro::
    .string "哈——哈！$"

Route10_Text_ClarkDefeat::
    .string "哈-啊啊！\n"
    .string "不准笑！\l"
    .string "啊啊-发烧了！啊啊-啊嚏！$"

Route10_Text_ClarkPostBattle::
    .string "啊啊-啊嚏！\n"
    .string "啊嚏！\l"
    .string "抽鼻子，擦鼻涕。$"

Route10_Text_HermanIntro::
    .string "对了、对了！\n"
    .string "你要看看我的宝可梦吗？$"

Route10_Text_HermanDefeat::
    .string "喔，不！\n"
    .string "我的宝可梦！$"

Route10_Text_HermanPostBattle::
    .string "我讨厌你。\n"
    .string "比我强的人我都不喜欢！$"

Route10_Text_HeidiIntro::
    .string "我已经在宝可梦道馆中辗转\n"
    .string "奋战多时。\p"
    .string "…可总是输多赢少。$"

Route10_Text_HeidiDefeat::
    .string "真是的……！\n"
    .string "明明已经特训过了。$"

Route10_Text_HeidiPostBattle::
    .string "我发现一些宝可梦狂\n"
    .string "正在附近徘徊的踪迹。\p"
    .string "你想象得出来吗？\n"
    .string "从这山顶往下俯视的样子？$"

Route10_Text_TrentIntro::
    .string "哈！\n"
    .string "这山里的空气真爽！$"

Route10_Text_TrentDefeat::
    .string "我头脑清醒了！$"

Route10_Text_TrentPostBattle::
    .string "山上的空气吸多后，\n"
    .string "肚子鼓起来了！$"

Route10_Text_CarolIntro::
    .string "我现在有点头晕，\n"
    .string "好久都没有登山了。$"

Route10_Text_CarolDefeat::
    .string "我太累了。\n"
    .string "我还没准备好。$"

Route10_Text_CarolPostBattle::
    .string "这座山里生活的宝可梦\n"
    .string "都是矮矮胖胖的那种……\p"
    .string "我希望能有一种宝可梦，\n"
    .string "它粉色的皮肤上有花瓣花纹！$"

Route10_Text_RockTunnelDetourToLavender::
    .string "岩山隧道\n"
    .string "绕道到紫苑镇$"

Route10_Text_RockTunnel::
    .string "这里是岩山隧道$"

Route10_Text_PowerPlant::
    .string "这里是无人发电厂$"

