RockTunnel_1F_Text_LennyIntro::
    .string "你想穿过这条\n"
    .string "长长的隧道吗？$"

RockTunnel_1F_Text_LennyDefeat::
    .string "我输了。$"

RockTunnel_1F_Text_LennyPostBattle::
    .string "大岩蛇的很少在这出没，\n"
    .string "但要是在寻找的时候，\p"
    .string "遇上了高等级大岩蛇，\n"
    .string "会给你造成重创！$"

RockTunnel_1F_Text_OliverIntro::
    .string "嗯哼。\n"
    .string "我也许在这里迷路了……$"

RockTunnel_1F_Text_OliverDefeat::
    .string "刚才就不应该和你战斗的。\n"
    .string "出口在哪呢？$"

RockTunnel_1F_Text_OliverPostBattle::
    .string "12号道路上那只沉睡的宝可梦\n"
    .string "让我不得不绕道而行。$"

RockTunnel_1F_Text_LucasIntro::
    .string "我住在山里很久了。\n"
    .string "外来者休想在我面前放肆。$"

RockTunnel_1F_Text_LucasDefeat::
    .string "很厉害啊。$"

RockTunnel_1F_Text_LucasPostBattle::
    .string "你已经有足够的能力去登山了！$"

RockTunnel_1F_Text_AshtonIntro::
    .string "宝可梦斗士！\n"
    .string "前来拜访！$"

RockTunnel_1F_Text_AshtonDefeat::
    .string "被打败了么。$"

RockTunnel_1F_Text_AshtonPostBattle::
    .string "好吧，我一会儿就去抓只超音蝠！$"

RockTunnel_1F_Text_LeahIntro::
    .string "喂！\p"
    .string "这里这么黑，\n"
    .string "别想在这里耍小花招！$"

RockTunnel_1F_Text_LeahDefeat::
    .string "太暗了…$"

RockTunnel_1F_Text_LeahPostBattle::
    .string "我在隧道里见过腕力。$"

RockTunnel_1F_Text_DanaIntro::
    .string "我走了这么远\n"
    .string "就是为了寻找宝可梦！$"

RockTunnel_1F_Text_DanaDefeat::
    .string "我的宝可梦全倒下了！$"

RockTunnel_1F_Text_DanaPostBattle::
    .string "你不但长得可爱，\n"
    .string "而且实力强大。$"

RockTunnel_1F_Text_ArianaIntro::
    .string "你带着宝可梦！\n"
    .string "那么战个痛快吧！$"

RockTunnel_1F_Text_ArianaDefeat::
    .string "今后再来……$"

RockTunnel_1F_Text_ArianaPostBattle::
    .string "哇哦！\n"
    .string "我现在汗流浃背。$"

RockTunnel_1F_Text_RouteSign::
    .string "岩山隧道\n"
    .string "华蓝市 - 紫苑镇$"

