CeladonCity_Restaurant_Text_TakingBreakRightNow::
    .string "嗨！\p"
    .string "抱歉，我们正在休息呢。$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore::
    .string "我的宝可梦总受伤，\n"
    .string "所以我不得不经常去药店。$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner::
    .string "嘿！我听说这个\n"
    .string "游戏城下面有个地下室。$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots::
    .string "吧唧吧唧……\p"
    .string "那边桌子上那个人，\n"
    .string "把家当全输在老虎机上了。$"

CeladonCity_Restaurant_Text_TakeThisImBusted::
    .string "见鬼吧！哈哈！\n"
    .string "我破产了！\p"
    .string "没法再玩老虎机了！\n"
    .string "我要走了！\p"
    .string "这个破玩意给你！\n"
    .string "我再也用不着它了！$"

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan::
    .string "{PLAYER}获得了一个代币盒。$"

CeladonCity_Restaurant_Text_MakeRoomForThis::
    .string "把包包腾出点地方来！$"

CeladonCity_Restaurant_Text_ThoughtIdWinItBack::
    .string "我总想着把输的都赢回来，\n"
    .string "结果越输越多……$"

