TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "我是宝可梦招式研究狂。\p"
    .string "我知道宝可梦成长\n"
    .string "所学的每个基本招式。\p"
    .string "同时，我还在收集蘑菇。\p"
    .string "给我小蘑菇。\n"
    .string "或者一个大蘑菇。\p"
    .string "如果你有的话，\n"
    .string "我就教给一只宝可梦一个招式。$"

TwoIsland_House_Text_WantMeToTeachMove::
    .string "嗯……嗯……\n"
    .string "没错！你的身上有蘑菇的香味！\p"
    .string "你想让我教给你宝可梦\n"
    .string "一个招式吗？$"

TwoIsland_House_Text_TutorWhichMon::
    .string "那教给那只宝可梦好呢？$"

TwoIsland_House_Text_TeachWhichMove::
    .string "教给它哪个招式好呢？$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "抱歉……\p"
    .string "我不能把这个招式\n"
    .string "教给这只宝可梦。$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .string "那么，我需要一个或两个的蘑菇。\n"
    .string "你打算给我哪个？$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER}给了\n"
    .string "两个小蘑菇。$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .string "{PLAYER}给了\n"
    .string "一个大蘑菇。$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "如果你想让你的宝可梦学习\n"
    .string "一个招式，就给我一个或两个蘑菇。$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "哼？\n"
    .string "我不能教给一颗蛋什么招式。$"

