SixIsland_DottedHole_SapphireRoom_Text_FoundSapphire::
    .string "{PLAYER}发现了一个蓝宝石！$"

SixIsland_DottedHole_SapphireRoom_Text_IWasRightInTailingYou::
    .string "呋呋……呋呋呋呋……\n"
    .string "我猜对了。\p"
    .string "尾随着你是对的！$"

SixIsland_DottedHole_SapphireRoom_Text_SellToTeamRocketTellPassword::
    .string "我知道这里有蓝宝石，\n"
    .string "因此它是我的了！\p"
    .string "我把它卖给火箭队换钱。\p"
    .string "……不要像那样盯着我！\p"
    .string "如果你想要要回来的话，为什么\n"
    .string "不等到我卖了以后再去要呢？\p"
    .string "我会告诉你火箭队的\n"
    .string "仓库的一条密码的。\p"
    .string "我知道仓库的密码是\n"
    .string "“大大小小 小小大大。”\p"
    .string "就这样吧。\n"
    .string "别把我当成大坏人！$"

