PokemonTower_5F_Text_RestHereInPurifiedSpace::
    .string "过来，孩子！\n"
    .string "我已经净化了这里！\l"
    .string "在这里回复体力吧。$"

PokemonTower_5F_Text_TammyIntro::
    .string "给……我……\n"
    .string "你……所有的……$"

PokemonTower_5F_Text_TammyDefeat::
    .string "呼！$"

PokemonTower_5F_Text_TammyPostBattle::
    .string "我……\n"
    .string "被附身了么。$"

PokemonTower_5F_Text_RuthIntro::
    .string "你……应该……\n"
    .string "加入……我们……$"

PokemonTower_5F_Text_RuthDefeat::
    .string "怎么会这样。$"

PokemonTower_5F_Text_RuthPostBattle::
    .string "我有些失态了。$"

PokemonTower_5F_Text_KarinaIntro::
    .string "僵……僵僵……\n"
    .string "尸……！$"

PokemonTower_5F_Text_KarinaDefeat::
    .string "哈？$"

PokemonTower_5F_Text_KarinaPostBattle::
    .string "唔，我终于清醒了！$"

PokemonTower_5F_Text_JanaeIntro::
    .string "恩……\n"
    .string "啊……$"

PokemonTower_5F_Text_JanaeDefeat::
    .string "好可怕……$"

PokemonTower_5F_Text_JanaePostBattle::
    .string "尽管我在山上不断地修行\n"
    .string "却还是堕入了邪念……$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed::
    .string "进入了净化和被保护的区域。\p"
    .string "{PLAYER}的宝可梦\n"
    .string "全都恢复了体力。$"

