Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad::
    .string "单车路上\n"
    .string "禁止步行。$"

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse::
    .string "在海边附近的单车路\n"
    .string "是一段下坡路，\n"
    .string "在那儿骑车很享受。$"

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp::
    .string "抱歉！\n"
    .string "请等一下！$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort::
    .string "你是怎么进来的？\n"
    .string "干得不赖！$"

