CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow::
    .string "就像我在黑板上写的那样，\n"
    .string "我无所不知。\p"
    .string "我了解在Game Boy Advance中的\n"
    .string "宝可梦世界！\p"
    .string "和你的朋友们一起玩吧，\n"
    .string "祝你们交换宝可梦愉快！$"

CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee::
    .string "{PLAYER}获得了伊布！$"

CeladonCity_Condominiums_RoofRoom_Text_BoxIsFull::
    .string "ポケモンが　いっぱいだ\n"
    .string "ボックスを　かえて　きなさい$"

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture::
    .string "宝可梦讲座\p"
    .string "用无线适配器游戏$"

CeladonCity_Condominiums_RoofRoom_Text_ReadWhichHeading::
    .string "你想了解哪部分？$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainWirelessClub::
    .string "宝可梦无线俱乐部\n"
    .string "在宝可梦中心的上层。\p"
    .string "去那里通过无线适配器\n"
    .string "和你的朋友通讯。$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainDirectCorner::
    .string "和单个朋友通讯，\n"
    .string "就去直连房间。\p"
    .string "宝可梦无线俱乐部右边的柜台就是。\p"
    .string "和你的朋友一起进入\n"
    .string "通信房间或者大竞技场。$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainUnionRoom::
    .string "如果要和任意其他人通讯，\n"
    .string "就去联盟交谊厅。\p"
    .string "宝可梦无线俱乐部左边的柜台就是。\p"
    .string "去联盟交谊厅尽情享受和其他训练家\n"
    .string "通讯的乐趣吧！$"

CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
    .string "是本关于招式学习器的小册子。\p"
    .string "…… ……\p"
    .string "一共有50种招式学习器。\p"
    .string "还有7种能反复使用的秘传学习器。\p"
    .string "西尔佛公司。$"

