CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon::
    .string "我超级超级想要那只多边兽！\n"
    .string "可是这老虎机也太难赢了！$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday::
    .string "哇哈哈！我今天人品大爆发了哇！\n"
    .string "要是每天都像今天一样就好了……$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired::
    .string "你还没有代币盒……$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes::
    .string "你可以用代币和我们兑换奖品。$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize::
    .string "你想要哪个奖品？$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo::
    .string "はい どうぞ$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize::
    .string "嗯，你想要的是{B_COPY_VAR_1}？$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM::
    .string "好的，你想要的是招式学习器{B_COPY_VAR_2}？$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins::
    .string "抱歉，你的代币不够兑换它哦。$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom::
    .string "おきゃくさん もう もてないよ$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen::
    .string "あっ そう$"

