SilphCo_10F_Text_GruntIntro::
    .string "欢迎来到10楼！\n"
    .string "你能来到这里真是很厉害啊！$"

SilphCo_10F_Text_GruntDefeat::
    .string "我震惊了！$"

SilphCo_10F_Text_GruntPostBattle::
    .string "做的不错，但会议室\n"
    .string "在这层楼上。$"

SilphCo_10F_Text_TravisIntro::
    .string "就让我们来……\n"
    .string "结束这场游戏吧！$"

SilphCo_10F_Text_TravisDefeat::
    .string "哎呀。$"

SilphCo_10F_Text_TravisPostBattle::
    .string "打赢我就满足了吗？\n"
    .string "那么你快回家吧。$"

SilphCo_10F_Text_WaaaImScared::
    .string "哇啊啊！\n"
    .string "好可怕！$"

SilphCo_10F_Text_KeepMeCryingASecret::
    .string "至于我哭的原因……\n"
    .string "请为我保密。$"

SilphCo_10F_Text_FloorSign::
    .string "西尔佛公司总部\n"
    .string "10F$"

