SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale::
    .string "{PLAYER}：嗨！\n"
    .string "你喜欢宝可梦吗？\p"
    .string "{PLAYER}：喔，不，我只是问问你罢了。\p"
    .string "{PLAYER}：嗯？\n"
    .string "你确实很厉害！\p"
    .string "模仿少女：嗯？快速模仿？\n"
    .string "对，那是我的爱好！$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale::
    .string "{PLAYER}：嗨。\n"
    .string "你一定热爱着宝可梦.\p"
    .string "{PLAYER}：不，不是问我。\n"
    .string "我是在问你。\p"
    .string "{PLAYER}：再说一遍？\n"
    .string "你真古怪！\l"
    .string " \l"
    .string "模仿少女：嗯？快速模仿？\l"
    .string "那是我的最爱！$"

Text_MimicTeach::
    .string "哇塞！\n"
    .string "皮皮玩偶！\p"
    .string "给我的？\n"
    .string "谢谢你！\p"
    .string "你想要什么？\n"
    .string "我能教给你模仿这个招式。$"

Text_MimicDeclined::
    .string "你不喜欢模仿？$"

Text_MimicWhichMon::
    .string "我真的很喜欢模仿！\n"
    .string "谁想要来学会这个招式？$"

Text_MimicTaughtMale::
    .string "{PLAYER}：嗨！\n"
    .string "首先要谢谢你！\p"
    .string "{PLAYER}：再说一遍？\p"
    .string "{PLAYER}：模仿我的动作\n"
    .string "很有意思吗？\p"
    .string "模仿少女：你敢打赌的吧！\n"
    .string "那真是太有意思了！$"

Text_MimicTaughtFemale::
    .string "{PLAYER}：嗨\n"
    .string "谢谢你为我做的一切！\p"
    .string "{PLAYER}：再说一遍？\p"
    .string "{PLAYER}：学我说话\n"
    .string "很有意思吗？\p"
    .string "模仿达人：你敢打赌吗？\n"
    .string "那真是太有意思了！$"

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag::
    .string "にもつが　いっぱいね！$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP::
    .string "{PLAYER}“やあ！　こんにちは！\n"
    .string "きみ　ポケモン　すきかい？\p"
    .string "{PLAYER}“ぼく　じゃなくって\n"
    .string "きみに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥‥　えー　なんだよ！\n"
    .string "ヘンな　やつ　だなあ！\p"
    .string "モノマネむすめ“‥‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし　\n"
    .string "ものまね　しゅみ　なんだ　もん！”$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP::
    .string "{PLAYER}“こんにちは！\n"
    .string "ポケモン　すきなのね？\p"
    .string "{PLAYER}“わたし　じゃなくって\n"
    .string "あなたに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥　えー　なんなの！\n"
    .string "おかしなこ　ねー！\p"
    .string "モノマネむすめ“‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし\n"
    .string "ものまね　しゅみ　なんだ　もん！$"

SaffronCity_CopycatsHouse_2F_Text_Doduo::
    .string "嘟嘟：嘻嘻！\p"
    .string "魔镜魔镜告诉我，\n"
    .string "谁是这个世界上最漂亮的人？$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll::
    .string "这真是少见的宝可梦啊！\n"
    .string "嗯？这只是个玩偶！$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket::
    .string "游戏里马力欧\n"
    .string "正在用头顶蘑菇！$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets::
    .string "……\p"
    .string "我的秘密！\p"
    .string "我的特长：模仿！\n"
    .string "我的爱好：收集玩偶！\l"
    .string "我最喜欢的宝可梦：皮皮！$"

SaffronCity_CopycatsHouse_2F_Text_HuhCantSee::
    .string "？　みえないぞ‥$"
