PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "妈妈：……好吧。\n"
    .string "电视上说过。\l"
    .string "每一个男孩子都有离开家的那一天。\p"
    .string "对了，隔壁的大木博士\n"
    .string "正在找你呢。$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "妈妈：……好吧。\n"
    .string "电视上说过，\l"
    .string "每一个女孩子都梦想着去旅行。\p"
    .string "对了，隔壁的大木博士\n"
    .string "正在找你呢。$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "妈妈：{PLAYER}！\n"
    .string "你应该稍微休息一下。$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "妈妈：嗯，很好！你和你的\n"
    .string "宝可梦看起来精力十足。\l"
    .string "路上小心！$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "电视上播放着一部电影。\n"
    .string "四个男孩沿着铁轨\l"
    .string "步行着开始了旅行。\p"
    .string "……我也该走了。$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "电视上播放着一部电影。\n"
    .string "一个扎着马尾的女孩\l"
    .string "沿着砖块砌成的路开始了旅行。\p"
    .string "……我也该走了。$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "哎哟，方向错了……$"

