RocketHideout_B3F_Text_Grunt1Intro::
    .string "你给我站住，不许插手\n"
    .string "火箭队的事，不然的话……！$"

RocketHideout_B3F_Text_Grunt1Defeat::
    .string "可恶，被打败了！$"

RocketHideout_B3F_Text_Grunt1PostBattle::
    .string "西尔佛检视镜？\n"
    .string "哦，那个老大偷走的机器啊。\p"
    .string "它应该就在附近。$"

RocketHideout_B3F_Text_Grunt2Intro::
    .string "我们得到了楼上的情报，\n"
    .string "就知道你会来这里！$"

RocketHideout_B3F_Text_Grunt2Defeat::
    .string "我输了……\n"
    .string "怎么会这样。$"

RocketHideout_B3F_Text_Grunt2PostBattle::
    .string "想进去就进去吧！\p"
    .string "但是没有电梯的钥匙的话，\n"
    .string "你就无法操作电梯。$"

