SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies::
    .string "不同的宝可梦成长速度\n"
    .string "不一样。$"

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame::
    .string "西尔佛公司的名声远扬。\p"
    .string "它的名气吸引了\n"
    .string "火箭队。$"

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets::
    .string "唉……\n"
    .string "这样的话不就好了？\p"
    .string "让四天王赶来\n"
    .string "灭了火箭队？$"

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff::
    .string "火箭队离开了！\n"
    .string "我们又可以安全地出行了！\l"
    .string "太棒了！$"

