Route16_House_Text_FoundMySecretRetreat::
    .string "哦，天哪。\n"
    .string "你发现了我的秘密藏身处！\p"
    .string "请不要告诉任何人我在这里！\n"
    .string "如果你答应的话这个就给你！$"

Route16_House_Text_ReceivedHM02FromGirl::
    .string "{PLAYER}从女孩那儿\n"
    .string "获得了秘传学习器HM02。$"

Route16_House_Text_ExplainHM02::
    .string "秘传学习器02是飞翔。\n"
    .string "这是一个极为方便的招式。\p"
    .string "请好好利用它吧。$"

Route16_House_Text_DontHaveAnyRoomForThis::
    .string "你身上没有足够的空间存放它了。$"

Route16_House_Text_Fearow::
    .string "大嘴雀：法露！$"

