Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "将宝可梦的属性\n"
    .string "互相不同搭配起来。\p"
    .string "每一种属性都比其它一些属性强，\n"
    .string "相对的，也比其它一些属性弱。$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "金珠没什么用。\n"
    .string "所以我用¥5000把它卖掉了。$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "我听说那个幽灵经常出没于\n"
    .string "紫苑镇。$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
    .string "哦……{PLAYER}！\n"
    .string "我一直在找你。\p"
    .string "是我，你经常会看到的\n"
    .string "大木博士的助手之一。\p"
    .string "如果你的宝可梦图鉴已经收集了\n"
    .string "20个不同的宝可梦的数据，我就会把\l"
    .string "大木博士的奖励给你。\p"
    .string "他委托我给你这个\n"
    .string "不变之石。\p"
    .string "那么，{PLAYER}，让我问问你吧。\p"
    .string "你的宝可梦图鉴已经收集到\n"
    .string "20个宝可梦的数据吗？$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "太棒了！你已经收集了\n"
    .string "{B_COPY_VAR_3}种宝可梦！\p"
    .string "恭喜！\n"
    .string "奖励，拿去吧！$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
    .string "{PLAYER}从助手那儿\n"
    .string "获得了不变之石。$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
    .string "如果宝可梦进化\n"
    .string "数据一样可以加入宝可梦图鉴。\p"
    .string "但有时，你也许会\n"
    .string "不希望一个宝可梦进化。\p"
    .string "在那种情况下，就把不变之石\n"
    .string "给那只宝可梦吧。\p"
    .string "根据博士的话所说，\n"
    .string "它会阻止宝可梦的进化$"

