CeruleanCity_Text_RivalIntro::
    .string "{B_OPPONENT_MON1_NAME}：哟！是{PLAYER}啊！\p"
    .string "你还在这里\n"
    .string "独自徘徊么？\p"
    .string "我可是做得很好！我收服了一群\n"
    .string "既强壮又聪明的宝可梦！\p"
    .string "来吧，让我看看你收服了什么！\n"
    .string "{PLAYER}！$"

CeruleanCity_Text_RivalDefeat::
    .string "嘿！\n"
    .string "放松点！\l"
    .string "你已经赢了！$"

CeruleanCity_Text_RivalPostBattle::
    .string "{B_OPPONENT_MON1_NAME}：嘿，你猜怎么着？\p"
    .string "我去了趟正辉的家，叫他让我\n"
    .string "看了他稀有的宝可梦。\p"
    .string "这样就使我的宝可梦图鉴\n"
    .string "增加了好多数据！\p"
    .string "毕竟啊，正辉作为一个宝可梦狂\n"
    .string "在全世界都很有名。\p"
    .string "就是他开发了\n"
    .string "宝可梦存储系统。\p"
    .string "既然你正在使用他的系统\n"
    .string "就应该去好好谢谢他。\p"
    .string "好了，我得走了。\n"
    .string "下次再见咯！$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
    .string "噢，对了。\p"
    .string "看到你总是不声不响的跟在我身后。\n"
    .string "我有些不好意思。不，我是真心的。\p"
    .string "所以呐，我要送你一个\n"
    .string "小小的礼物。$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
    .string "虽然这个东西废话很多……\n"
    .string "但是东西本身倒不坏。\p"
    .string "我不需要它是因为\n"
    .string "我才不喜欢和别人唠唠叨叨的。\p"
    .string "现在我可是真的要走了，\n"
    .string "有缘再会了！$"

@ RB translation: "Heh! You're no match for my genius!"
CeruleanCity_Text_RivalVictory::
    .string "なんたって！\n"
    .string "おれは　てんさい　だからよ！$"

CeruleanCity_Text_GruntIntro::
    .string "嘿！给我站住！\n"
    .string "这里可不是你的院子！\p"
    .string "……什么？\n"
    .string "我是干什么的？\p"
    .string "我是路过打酱油的！\n"
    .string "……你不相信我？{PLAY_BGM 0x1B 0x01}$"

CeruleanCity_Text_GruntDefeat::
    .string "手下：别打了！我投降！\n"
    .string "我会马上离开的！$"

CeruleanCity_Text_OkayIllReturnStolenTM::
    .string "…好吧。\n"
    .string "我会把偷来的招式学习器还给你。$"

CeruleanCity_Text_RecoveredTM28FromGrunt::
    .string "{PLAYER}从火箭队手下那里\n"
    .string "获得了招式学习器28。$"

CeruleanCity_Text_BetterGetMovingBye::
    .string "那么……！\n"
    .string "我就先撤了！\l"
    .string "…………拜拜～！$"

CeruleanCity_Text_MakeRoomForThisCantRun::
    .string "赶快把你的包腾出地方！\n"
    .string "给了你这个我才能走！$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
    .string "你也是一个训练家，对不对？\p"
    .string "收集，战斗……\n"
    .string "这是一条艰辛的路啊，可不是吗？$"

CeruleanCity_Text_YouCanCutDownSmallTrees::
    .string "你知道用居合劈能\n"
    .string "砍倒细小的树吗？\p"
    .string "就算是那个商店面前的小树\n"
    .string "也可以用居合劈砍倒。\p"
    .string "我认为有条路在那附近。$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
    .string "如果那只呆壳兽不在这里的话\n"
    .string "你就能用居合劈砍倒那边的小树了。\p"
    .string "这样一来，\n"
    .string "你就可以到另一边去了。\p"
    .string "虽然也有办法绕路过去。$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
    .string "你在做关于宝可梦的百科全书吧？\n"
    .string "听起来真厉害啊。$"

CeruleanCity_Text_PeopleHereWereRobbed::
    .string "这家人被抢了。\p"
    .string "很明显这种十恶不赦的事\n"
    .string "背后又有火箭队在作怪！\p"
    .string "甚至我们的警力集结\n"
    .string "起来都敌不过火箭队！$"

CeruleanCity_Text_SlowbroUseSonicboom::
    .string "好！呆壳兽！\n"
    .string "使用音爆！$"

CeruleanCity_Text_SlowbroPayAttention::
    .string "来吧，呆壳兽，注意了！$"

CeruleanCity_Text_SlowbroPunch::
    .string "呆壳兽，挥拳！$"

CeruleanCity_Text_NoYouBlewItAgain::
    .string "不！\n"
    .string "你又搞砸了！$"

CeruleanCity_Text_SlowbroWithdraw::
    .string "呆壳兽，撤退！$"

CeruleanCity_Text_HardToControlMonsObedience::
    .string "不对！那样不对！\n"
    .string "想要控制好宝可梦是很困难的！\p"
    .string "你的宝可梦对你信赖与否\n"
    .string "取决于你作为一名训练家的能力。$"

CeruleanCity_Text_SlowbroTookSnooze::
    .string "呆壳兽打起了盹……$"

CeruleanCity_Text_SlowbroLoafingAround::
    .string "呆壳兽在四处闲逛……$"

CeruleanCity_Text_SlowbroTurnedAway::
    .string "呆壳兽躲得远远的……$"

CeruleanCity_Text_SlowbroIgnoredOrders::
    .string "被呆壳兽无视了……$"

CeruleanCity_Text_WantBrightRedBicycle::
    .string "我想要一辆红色的自行车。\p"
    .string "有了它我就会把它放在家里，\n"
    .string "这样它就不会被弄脏了。$"

CeruleanCity_Text_ThisIsCeruleanCave::
    .string "从这里进去就是华蓝洞窟了。\p"
    .string "那只强大得恐怖的宝可梦\n"
    .string "就栖息在这里面。\p"
    .string "只有那些特别的训练家\n"
    .string "才能够被允许入内。\p"
    .string "如果你成为了\n"
    .string "宝可梦联盟\l"
    .string "的联盟冠军。\p"
    .string "才有足够的\n"
    .string "实力进去挑战。$"

CeruleanCity_Text_CitySign::
    .string "华蓝市\n"
    .string "被蓝色所环绕着的\l"
    .string "神秘城市$"

CeruleanCity_Text_TrainerTipsHeldItems::
    .string "……有用的公告牌！\p"
    .string "一只宝可梦只可以装备\n"
    .string "一个道具。\p"
    .string "其中一些道具\n"
    .string "甚至能在战斗使用。$"

CeruleanCity_Text_BikeShopSign::
    .string "轻松愉快的在草地和洞窟间驰骋！\n"
    .string "自行车行$"

CeruleanCity_Text_GymSign::
    .string "华蓝市宝可梦道馆\n"
    .string "馆主：小霞\l"
    .string "男孩子气的美人鱼！$"

