FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
    .string "有很多宝可梦被锁在围栏里……$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
    .string "因为围栏的大门没上锁。\n"
    .string "宝可梦逃跑了。$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
    .string "你敢来这里是因为知道\n"
    .string "这里是火箭队的仓库吗？$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
    .string "你清楚自己在做什么吗？！$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
    .string "你说火箭队解散了？\n"
    .string "你来自哪个星球？$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
    .string "哦，你的宝可梦现在看起来很强。\n"
    .string "愿意卖掉它们吗？\p"
    .string "哦？\n"
    .string "想要打一场？$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
    .string "哦，但是……\n"
    .string "太多了！$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
    .string "我们会给你开一个好价钱。\n"
    .string "把宝可梦卖给我们吧！$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
    .string "我从别人那听说过关于你的事情。\p"
    .string "但是像你这样的孩子不可能\n"
    .string "了解我们的坂木老大！$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
    .string "你…不…准…笑…$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
    .string "不要掺和到大人的事情中来，\n"
    .string "你这只上窜下跳的小老鼠！$"

FiveIsland_RocketWarehouse_Text_Admin1Intro::
    .string "我不知道我做的是对还是错……\p"
    .string "我只是信任坂木，\n"
    .string "并且按照命令行事。$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
    .string "我……\n"
    .string "我被击垮了……$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
    .string "你在按照你的信仰和道德行事。\p"
    .string "我现在明白了……$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
    .string "我做到了，因此你能从那回来。\p"
    .string "你休息恢复下之后\n"
    .string "准备继续前进吧。\p"
    .string "干部们成为训练家要比我晚，\n"
    .string "但现在却完全超越了我。\p"
    .string "你最好好好锻炼自己\n"
    .string "来迎接严厉的挑战。$"

FiveIsland_RocketWarehouse_Text_Admin2Intro::
    .string "小朋友，\n"
    .string "扮英雄的游戏结束了。\p"
    .string "散播关于火箭队\n"
    .string "如何解散的谎言……\p"
    .string "这是一个明显的想要\n"
    .string "扰乱我们的队伍的计划。\p"
    .string "幸好，我们不会无知到因为\n"
    .string "一个孩子的谎言而就此沦落！\p"
    .string "而现在，我会让你见识一下\n"
    .string "生气的大人有多可怕！$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
    .string "呃……\n"
    .string "你太强了……\p"
    .string "……\n"
    .string "那-那是坂木的徽章！\p"
    .string "传言是真的吗？\n"
    .string "火箭队真的解散了？$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
    .string "我们将放弃这个仓库……\p"
    .string "但不要认为已经结束了。\n"
    .string "我不会善罢甘休的。\p"
    .string "我会找到坂木。\n"
    .string "并且复活火箭队！\l"
    .string "我要…\p"
    .string "就这样，再会！$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
    .string "电脑屏幕上有\n"
    .string "图表和文字的报告。\p"
    .string "“电波对宝可梦进化的影响”\p"
    .string "…… …… ……\p"
    .string "这太难懂了……$"

FiveIsland_RocketWarehouse_Text_GideonIntro::
    .string "我差一点就能把蓝宝石卖了\n"
    .string "赚到大笔大笔的钱……\p"
    .string "你却过来毁了整个交易！\p"
    .string "呋呋……呋呋呋呋……\n"
    .string "绝不能饶恕你！$"

FiveIsland_RocketWarehouse_Text_GideonDefeat::
    .string "噶！该死！\n"
    .string "混蛋！真气人！$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
    .string "如果我卖不了它，它就没价值了！\n"
    .string "来吧，拿着它吧！$"

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
    .string "你现在想要什么？\n"
    .string "走开，滚远点，让我一个人呆着。$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
    .string "什么，又是你？\p"
    .string "你……你莫非是坂木的孩子？\n"
    .string "我没认错吧？\p"
    .string "不，我认错了。\n"
    .string "坂木的孩子是红头发。\p"
    .string "那你别来烦我了。\n"
    .string "让我单独呆一会儿！$"

