Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30::
    .string "嗨！还记得我吗？\n"
    .string "我是大木博士的助手之一。\p"
    .string "如果你的宝可梦图鉴已经收集了\n"
    .string "{B_COPY_VAR_1}个宝可梦的数据，我就会\l"
    .string "给你一个奖励。\p"
    .string "大木博士委托我把\n"
    .string "{B_COPY_VAR_2}给你。\p"
    .string "那么{PLAYER}，让我问问你。\p"
    .string "你已经得到了至少\n"
    .string "{B_COPY_VAR_1}种宝可梦了吗？$"

Route11_EastEntrance_2F_Text_GreatHereYouGo::
    .string "太棒了！你已经收集了\n"
    .string "{B_COPY_VAR_3}种宝可梦了！\p"
    .string "恭喜！\n"
    .string "这是奖励，拿去吧！$"

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide::
    .string "{PLAYER}从助手那儿\n"
    .string "得到了{B_COPY_VAR_2}。$"

Route11_EastEntrance_2F_Text_ExplainItemfinder::
    .string "地面上有\n"
    .string "隐藏的道具。\p"
    .string "就用探宝器来找出\n"
    .string "在你周围的隐藏道具吧。\p"
    .string "由于这个机器机能有限，\n"
    .string "所以它不能直接探明道具的位置。\p"
    .string "它所做的\n"
    .string "只有指向道具所在的方向。\p"
    .string "找准方向之后，\n"
    .string "侦察一下你认为可疑的地方。$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad::
    .string "一架望远镜……\n"
    .string "我来看看……\p"
    .string "啊，一只体形巨大的宝可梦\n"
    .string "正在路上睡觉！$"

Route11_EastEntrance_2F_Text_WhatABreathtakingView::
    .string "一架望远镜……\n"
    .string "我来看看……\p"
    .string "哇哦，多么壮观的美景！$"

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender::
    .string "一架望远镜……\n"
    .string "我来看看……\p"
    .string "从华蓝市\n"
    .string "再到紫苑镇…\p"
    .string "岩山隧道也许是一个\n"
    .string "不错的路线。$"

