ViridianCity_Text_CanCarryMonsAnywhere::
    .string "你腰上挂着的这些精灵球！\n"
    .string "你有宝可梦，是吧？\p"
    .string "太棒了！无论何时何地，\n"
    .string "你都能携带并使用宝可梦。$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "这个宝可梦道馆总是关闭着。\p"
    .string "我很想到底知道谁是馆主？$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "常青道馆的馆主回来了！$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "你想知道两种\n"
    .string "虫属性宝可梦的区别吗？$"

ViridianCity_Text_OhOkayThen::
    .string "噢，好吧！$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "绿毛虫没有毒，\n"
    .string "但是独角虫有毒。\p"
    .string "当心你的宝可梦别被独角虫的\n"
    .string "毒针给刺中了。$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "噢，爷爷！\n"
    .string "别这么任性啊！\p"
    .string "真的很抱歉。\n"
    .string "他还没喝咖啡。$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "我有时候会去深灰市买东西。\p"
    .string "我每次去的时候，都必须\n"
    .string "在常青森林中走一段蜿蜒的小路。$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "我绝不允许你通过这里！\p"
    .string "这里是私人领地！$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "刚刚我喝过咖啡了。\n"
    .string "喝咖啡可是我每天的必修课！\p"
    .string "嗯？\n"
    .string "你手上拿着的那个红色盒子是什么？\p"
    .string "噢，你在完成你的宝可梦图鉴啊。\p"
    .string "那么让我给你一些建议吧。\p"
    .string "宝可梦图鉴会在\n"
    .string "你收服到宝可梦时\l"
    .string "自动更新数据。\p"
    .string "……你不知道该怎么收服宝可梦？\p"
    .string "那我想我应该教你怎么做！$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "怎么样？\n"
    .string "是不是受益匪浅啊？\p"
    .string "把这个也带上吧。$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "如果有什么你不懂的，\n"
    .string "一定要仔细看它。\p"
    .string "它将教会你如何成为\n"
    .string "一名合格的宝可梦训练家。$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "我已经喝过咖啡了。\n"
    .string "喝咖啡可是我每天的必修课！\p"
    .string "但是我泡得太浓了。\n"
    .string "现在我头有点痛……\p"
    .string "顺便说一下，\n"
    .string "你完成了你的宝可梦图鉴吗？\p"
    .string "首先，要使宝可梦变弱，\n"
    .string "然后才能试图抓住它。$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "我刚刚喝过咖啡了。\n"
    .string "喝咖啡可是我每天的必修课！\p"
    .string "但是我泡得太浓了，\n"
    .string "喝得我头都痛了……\p"
    .string "顺便，我那台旧的教学电视机\n"
    .string "帮到你了吗？$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "哇哈哈！\n"
    .string "电视上的是我孙子！\p"
    .string "既然是他在教的话\n"
    .string "你就得好好学。$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "嗯……你忙得甚至抽不出\n"
    .string "时间来看教学电视机了……\p"
    .string "时间就是金钱，这两者\n"
    .string "都不应当被虚耗……$"

ViridianCity_Text_CitySign::
    .string "常青市\n"
    .string "永远的绿色天堂$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "……有用的公告牌！\p"
    .string "收服宝可梦\n"
    .string "增加你的收集数。\p"
    .string "你拥有得越多，\n"
    .string "战斗就越轻松。$"

ViridianCity_Text_MovesLimitedByPP::
    .string "……有用的公告牌！\p"
    .string "宝可梦的招式受到它们的\n"
    .string "招式点，也就是PP值的限制。\p"
    .string "想要回复PP的话，将你疲惫的\n"
    .string "宝可梦放到宝可梦中心休息吧。$"

ViridianCity_Text_GymSign::
    .string "常青市宝可梦道馆$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "常青道馆的门锁上了……$"

