CeruleanCity_House4_Text_NothingEntertaining::
    .string "唉……\n"
    .string "太多的时间，太少能做的事……\p"
    .string "就没有什么有趣的事情发生吗？$"

CeruleanCity_House4_Text_NewNewsInformativeHaveThis::
    .string "啊！\n"
    .string "一条新的消息！\p"
    .string "嗯……\p"
    .string "我知道了！\n"
    .string "真是长见识了！\p"
    .string "我很欣赏你这么年轻\n"
    .string "能对这条消息感兴趣。\p"
    .string "作为你和我分享这条消息的谢意。\n"
    .string "我要给你这个。$"

CeruleanCity_House4_Text_IncredibleNewsHaveBerries::
    .string "噢，噢！\n"
    .string "这——这条消息！\p"
    .string "嗯……\p"
    .string "令人震惊！\n"
    .string "多么不可思议的消息！\p"
    .string "我好久都没有听到过\n"
    .string "这么难以置信的事情了！\p"
    .string "谢谢你分享这条惊异的消息。\n"
    .string "给你一些树果！$"

CeruleanCity_House4_Text_WishCouldShareNewsWithOthers::
    .string "不跟其他人分享这条消息\n"
    .string "好像很不厚道……\p"
    .string "我希望我能告诉大家……\n"
    .string "让大家知道这个消息……$"

CeruleanCity_House4_Text_ThanksForSpreadingNewsTakeThis::
    .string "啊，你把这条消息告诉了我？\p"
    .string "当各种人分享它时，\n"
    .string "好消息就会变得有价值。\p"
    .string "谢谢你传播这条消息，\n"
    .string "作为谢意，拿着这个吧！$"

CeruleanCity_House4_Text_MagnificentNewsSpreadHaveBerries::
    .string "你又告诉了其他的人？\n"
    .string "好极了！\p"
    .string "那条新闻肯定很高兴\n"
    .string "被这样广泛的传播。\p"
    .string "是的，真的！\p"
    .string "从我和这条消息的角度\n"
    .string "想想这个价值。\p"
    .string "我要给你比平常多的树果。$"

CeruleanCity_House4_Text_EnjoyingMyselfWithAllSortsOfNews::
    .string "沉浸在各种各样的新闻中\n"
    .string "我很享受。\p"
    .string "是的，我很满足！\n"
    .string "我暂时是不会无聊了。$"

CeruleanCity_House4_Text_YourBerryPouchIsFull::
    .string "嗯？你的树果袋满了。\n"
    .string "我的礼物送不出去了。$"

