PokemonLeague_AgathasRoom_Text_Intro::
    .string "我是四天王之一菊子。\p"
    .string "孩子我听说大木\n"
    .string "相当疼爱你。\p"
    .string "那个老傻瓜\n"
    .string "曾经又猛又迷人！\p"
    .string "但是，这只是几十年前的事了。\n"
    .string "现在的他已不复当年之勇了。\p"
    .string "成天玩弄他的破\n"
    .string "宝可梦图鉴。\p"
    .string "他错了。\n"
    .string "宝可梦是用来战斗的！\p"
    .string "{PLAYER}！让我来教你真正的\n"
    .string "训练家是怎样战斗的！{PLAY_BGM 0x56 0x01}$"

PokemonLeague_AgathasRoom_Text_RematchIntro::
    .string "我是四天王之一菊子。\p"
    .string "我听说大木\n"
    .string "相当疼你。\p"
    .string "那个老傻瓜\n"
    .string "曾经又猛又迷人！\p"
    .string "但那是几十年前的事了。\n"
    .string "现在的他活在他过去的影子里。\p"
    .string "成天摆弄他的破\n"
    .string "宝可梦图鉴。\p"
    .string "他错了。\n"
    .string "宝可梦是用来战斗的！\p"
    .string "{PLAYER}！让我来教你真正的\n"
    .string "训练家是怎样战斗的！{PLAY_BGM 0x56 0x01}$"

PokemonLeague_AgathasRoom_Text_Defeat::
    .string "啊，真是了不得啊！\n"
    .string "你确实有些特别，孩子！$"

PokemonLeague_AgathasRoom_Text_PostBattle::
    .string "是你赢了我！\p"
    .string "我想我明白那糟老头在你身上\n"
    .string "看到了什么了。\p"
    .string "我没有别的话可说了。\n"
    .string "到下个房间去吧，孩子！$"

