VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon::
	.string "嗨！\n"
	.string "你有{B_COPY_VAR_1}吗？\p"
	.string "要和我的{B_COPY_VAR_2}交换吗？$"

VermilionCity_House2_Text_ThatsTooBad::
	.string "太糟了。$"

VermilionCity_House2_Text_ThisIsNoMon::
	.string "……这不是{B_COPY_VAR_1}。\p"
	.string "如果你得到了一只，\n"
	.string "请和我交换吧！$"

VermilionCity_House2_Text_ThankYou::
	.string "谢谢你！$"

VermilionCity_House2_Text_HowIsMyOldMon::
	.string "我的{B_COPY_VAR_2}怎么样了？\p"
	.string "我的{B_COPY_VAR_1}现在很好！$"
