ViridianCity_Mart_Text_YouCameFromPallet::
    .string "嘿！\n"
    .string "你来自真新镇？$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "你认识大木博士，对吗？\p"
    .string "他订的包裹到了。\n"
    .string "你能帮我捎给他吗？$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER}从宝可梦商店的店员处\n"
    .string "得到了大木的包裹。$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "谢谢！请替我向\n"
    .string "大木博士问好。$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "我听说这家商店的\n"
    .string "解毒药卖的很好。$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "我要买一些伤药。\p"
    .string "你无法预知你的宝可梦\n"
    .string "什么时候需要快速恢复。$"

