VermilionCity_Gym_Text_LtSurgeIntro::
    .string "嘿，小鬼，\n"
    .string "你在这儿发什么呆呢？\p"
    .string "打起仗来你可活不长的！\n"
    .string "瞧你那可怜的力量！\p"
    .string "我告诉你，小鬼，\n"
    .string "电属性宝可梦在战争中救过我！\p"
    .string "它们把我的敌人电得麻痹了！\p"
    .string "我也要把你电成这样！{PLAY_BGM 0x56 0x01}$"

VermilionCity_Gym_Text_LtSurgePostBattle::
    .string "给你一点忠告，小朋友！\p"
    .string "电是一种很强大的力量！\p"
    .string "但是面对地面属性的宝可梦\n"
    .string "它就毫无用处！$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis::
    .string "橘色徽章能提升你宝可梦的速度！\p"
    .string "能让你的宝可梦行动得\n"
    .string "像闪电一样快！\p"
    .string "你很特别啊，小鬼！\n"
    .string "拿着这个招式学习器吧！$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
    .string "{PLAYER}得到了招式学习器34。$"

VermilionCity_Gym_Text_ExplainTM34::
    .string "招式学习器34记录着电击波！\p"
    .string "把它教给电属性宝可梦吧！$"

VermilionCity_Gym_Text_MakeRoomInYourBag::
    .string "哟，小孩，把你的包包里腾出空间来！$"

VermilionCity_Gym_Text_LtSurgeDefeat::
    .string "真是令人吃惊！\p"
    .string "你有两下子嘛，小孩！\p"
    .string "你赢了，拿好这个橘色徽章！$"

VermilionCity_Gym_Text_TuckerIntro::
    .string "我以前在军队的时候，马志士\n"
    .string "是一个严厉的长官。\p"
    .string "执行任务时他总是冲在最前！$"

VermilionCity_Gym_Text_TuckerDefeat::
    .string "够了！\n"
    .string "你太厉害了！$"

VermilionCity_Gym_Text_TuckerPostBattle::
    .string "想打开这扇门可没那么容易。\p"
    .string "马志士以前在军队里\n"
    .string "可是出了名的谨慎。$"

VermilionCity_Gym_Text_BailyIntro::
    .string "虽然我体重很轻，\n"
    .string "但是我擅长使用电属性宝可梦！\p"
    .string "所以我加入了这个道馆。$"

VermilionCity_Gym_Text_BailyDefeat::
    .string "呀！被电麻了！$"

VermilionCity_Gym_Text_BailyPostBattle::
    .string "好了，我说我说！\p"
    .string "马志士说过他把开关\n"
    .string "藏在什么东西里了。$"

VermilionCity_Gym_Text_DwayneIntro::
    .string "这里不是小孩子该来的地方！\n"
    .string "即使你很厉害也不行！$"

VermilionCity_Gym_Text_DwayneDefeat::
    .string "哦，真是让人吃惊！$"

VermilionCity_Gym_Text_DwaynePostBattle::
    .string "训练馆的机关是马志士亲自安装的。\p"
    .string "他做的机关都是双层的。\n"
    .string "我给你点提示吧。\p"
    .string "如果你找到了打开第一道电锁的开关，\n"
    .string "第二道电锁的开关就在它的附近。$"

VermilionCity_Gym_Text_GymGuyAdvice::
    .string "嗨！\n"
    .string "未来的冠军！\p"
    .string "马志士有一个外号。\p"
    .string "人们把他称作“闪电般的美国人”！\p"
    .string "他是电属性宝可梦的专家。\p"
    .string "飞行属性和水属性的宝可梦\n"
    .string "遇着电属性的会很不利。\p"
    .string "你也要提防别被麻痹了。\p"
    .string "马志士是非常谨慎小心的。\p"
    .string "他把自己锁在了里面，\n"
    .string "所以你想要跟他对战可不容易。$"

VermilionCity_Gym_Text_GymGuyPostVictory::
    .string "唔！\n"
    .string "这场对战真带劲！$"

VermilionCity_Gym_Text_GymStatue::
    .string "枯叶宝可梦道馆\n"
    .string "馆主：马志士\p"
    .string "获胜训练家：\n"
    .string "{B_OPPONENT_MON1_NAME}$"

VermilionCity_Gym_Text_GymStatuePlayerWon::
    .string "枯叶宝可梦道馆\n"
    .string "馆主：马志士\p"
    .string "获胜训练家：\n"
    .string "{B_OPPONENT_MON1_NAME}、{PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere::
    .string "什么也没有！\n"
    .string "里面只有一些垃圾。$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
    .string "嘿！垃圾下面有个开关！\n"
    .string "打开它！\p"
    .string "第一道电锁打开了！$"

VermilionCity_Gym_Text_AnotherSwitchInTrash::
    .string "ガサゴソ‥！\n"
    .string "おっと！　ゴミばこの　そこに\l"
    .string "また　スイッチが　あった！\l"
    .string "おして　みよう！　‥　ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened::
    .string "第二道电锁打开了！\n"
    .string "门开了！$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
    .string "什么也没有！\n"
    .string "里边只是一些垃圾。\p"
    .string "嘿！\n"
    .string "电锁重置了！$"

