FuchsiaCity_SafariZone_Entrance_Text_WelcomeToSafariZone::
    .string "欢迎来到狩猎地带！$"

FuchsiaCity_SafariZone_Entrance_Text_PlaySafariGameFor500::
    .string "只要¥500，\n"
    .string "你就能参加狩猎地带游戏。\p"
    .string "你可以在开阔的狩猎地带里\n"
    .string "任意收服你想要的宝可梦。\p"
    .string "想试试吗？$"

FuchsiaCity_SafariZone_Entrance_Text_ThatllBe500WeOnlyUseSpecialBalls::
    .string "收您¥500！\p"
    .string "在我们这里只能使用\n"
    .string "一种特殊的精灵球。$"

FuchsiaCity_SafariZone_Entrance_Text_PlayerReceived30SafariBalls::
    .string "{PLAYER}从服务员那里\n"
    .string "获得了30个狩猎球。$"

FuchsiaCity_SafariZone_Entrance_Text_CallYouOnPAWhenYouRunOut::
    .string "如果时间到了或者你的狩猎球用完了，\n"
    .string "我们会通过广播告诉你。\p"
    .string "好了，祝你好运啦！$"

FuchsiaCity_SafariZone_Entrance_Text_OkayPleaseComeAgain::
    .string "好的。\n"
    .string "欢迎下次再来！$"

FuchsiaCity_SafariZone_Entrance_Text_OopsNotEnoughMoney::
    .string "哎哟！\n"
    .string "您的钱不够！$"

FuchsiaCity_SafariZone_Entrance_Text_GoingToLeaveSafariZoneEarly::
    .string "您想提前离开狩猎地带吗？$"

FuchsiaCity_SafariZone_Entrance_Text_PleaseReturnSafariBalls::
    .string "请交还您剩余的狩猎球。$"

FuchsiaCity_SafariZone_Entrance_Text_GoodLuck::
    .string "加油哦！$"

FuchsiaCity_SafariZone_Entrance_Text_CatchFairShareComeAgain::
    .string "您收服的够回本了吗？\n"
    .string "欢迎下次再来！$"

FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone::
    .string "嗨！这是你\n"
    .string "第一次来狩猎地带吗？$"

FuchsiaCity_SafariZone_Entrance_Text_ExplainSafariZone::
    .string "狩猎地带里实际上分为四块区域。\p"
    .string "每个区域都有不同的宝可梦，\n"
    .string "很稀有的宝可梦也藏匿其中。\p"
    .string "用给你的狩猎球去收服它们吧。\p"
    .string "除了向它们扔狩猎球，\n"
    .string "你也可以投掷饵料或者石头。\p"
    .string "如果你投掷饵料，\n"
    .string "宝可梦不易逃走，\l"
    .string "不过会更难收服。\p"
    .string "如果你投掷石头，\n"
    .string "宝可梦更易逃走，\l"
    .string "但是会更好收服。\p"
    .string "如果时间到了或者狩猎球用完了，\n"
    .string "狩猎游戏也就结束了！$"

FuchsiaCity_SafariZone_Entrance_Text_SorryYoureARegularHere::
    .string "对不起，在这儿你得好好守规矩！$"

