Route8_Text_AidanIntro::
    .string "你看起来对宝可梦很擅长，\n"
    .string "但是你的化学成绩怎么样？$"

Route8_Text_AidanDefeat::
    .string "啊！我输了！$"

Route8_Text_AidanPostBattle::
    .string "果然还是学习比较适合我。$"

Route8_Text_StanIntro::
    .string "很好！\n"
    .string "我们来玩个游戏吧！$"

Route8_Text_StanDefeat::
    .string "……今天我的胜负运很差！$"

Route8_Text_StanPostBattle::
    .string "今天也没有事情可做。$"

Route8_Text_GlennIntro::
    .string "那个，在战斗中，\n"
    .string "战术是必不可少的。$"

Route8_Text_GlennDefeat::
    .string "这不可能！$"

Route8_Text_GlennPostBattle::
    .string "先跟臭泥一起……\n"
    .string "……然后……$"

Route8_Text_PaigeIntro::
    .string "我喜欢尼多家族，所以我在收集它们！$"

Route8_Text_PaigeDefeat::
    .string "为什么？\n"
    .string "为什么？？$"

Route8_Text_PaigePostBattle::
    .string "宝可梦一进化，就完全不可爱了！\n"
    .string "所以还是不要进化的好。$"

Route8_Text_LeslieIntro::
    .string "我很喜欢学习……\n"
    .string "也很喜欢宝可梦。$"

Route8_Text_LeslieDefeat::
    .string "你让我清楚地明白\n"
    .string "我应该继续坚持学习。$"

Route8_Text_LesliePostBattle::
    .string "我曾准备以一个新的面貌做出\n"
    .string "一些改变，但是……\p"
    .string "我们被卡在金黄的门口了。$"

Route8_Text_AndreaIntro::
    .string "喵喵太可爱了，\n"
    .string "喵，喵，喵！$"

Route8_Text_AndreaDefeat::
    .string "不会吧喵～！$"

Route8_Text_AndreaPostBattle::
    .string "我认为波波和小拉达也很可爱！$"

Route8_Text_MeganIntro::
    .string "我们像这样傻站在这儿\n"
    .string "一定显得很可笑。$"

Route8_Text_MeganDefeat::
    .string "看你对我的可怜的，娇小的\n"
    .string "宝可梦做了什么！$"

Route8_Text_MeganPostBattle::
    .string "金黄的门卫\n"
    .string "不让我们通过。\p"
    .string "虽然我知道这是他的职责，\n"
    .string "不过这也太小气了。$"

Route8_Text_RichIntro::
    .string "我是一个混乱又顽劣的家伙！$"

Route8_Text_RichDefeat::
    .string "……！\n"
    .string "我竟然会算漏这么重要的一步！$"

Route8_Text_RichPostBattle::
    .string "一边赌博一边喂宝可梦吃东西！\n"
    .string "生活真是太美好了！$"

Route8_Text_JuliaIntro::
    .string "小小的，圆圆的，毛绒绒的\n"
    .string "是哪种宝可梦？$"

Route8_Text_JuliaDefeat::
    .string "停下！\p"
    .string "不要对我的皮皮这么无情！$"

Route8_Text_JuliaPostBattle::
    .string "我在宝可梦特刊上读到，\p"
    .string "皮皮是靠月之石进化的。\n"
    .string "这是真的吗？$"

Route8_Text_UndergroundPathSign::
    .string "地下通道\n"
    .string "玉虹市-紫苑镇$"

Route8_Text_EliIntro::
    .string "莉娜：双胞胎的力量是很强大的，\n"
    .string "你知道吗？$"

Route8_Text_EliDefeat::
    .string "莉娜：但是……\n"
    .string "这种力量已经用过了……$"

Route8_Text_EliPostBattle::
    .string "莉娜：我和卡娜一起抓住了我的宝可梦！$"

Route8_Text_EliNotEnoughMons::
    .string "莉娜：如果你没有两只宝可梦，\n"
    .string "就不能和我们战斗。$"

Route8_Text_AnneIntro::
    .string "卡娜：我们要用两个人的力量把你击垮！$"

Route8_Text_AnneDefeat::
    .string "卡娜：我们两个人的力量……$"

Route8_Text_AnnePostBattle::
    .string "卡娜：我和莉娜一起培育宝可梦。$"

Route8_Text_AnneNotEnoughMons::
    .string "卡娜：嗨！和我们战斗吧！\n"
    .string "但是要带两只宝可梦喔。$"

Route8_Text_RicardoIntro::
    .string "老兄，我的自行车出毛病了。$"

Route8_Text_RicardoDefeat::
    .string "啊。\n"
    .string "我进不去这里面。$"

Route8_Text_RicardoPostBattle::
    .string "草卷入我自行车的辐条里面了。$"

Route8_Text_JarenIntro::
    .string "给我让道，\n"
    .string "否则我把你压扁！$"

Route8_Text_JarenDefeat::
    .string "你是来真的吗，小子？$"

Route8_Text_JarenPostBattle::
    .string "不要认为你有多么特殊，\n"
    .string "没什么了不起的。$"
