SilphCo_3F_Text_WhatAmIToDo::
    .string "我……我是……\n"
    .string "我是西尔佛公司的员工……$"

SilphCo_3F_Text_YouAndYourMonsSavedUs::
    .string "{PLAYER}！\n"
    .string "你和你的宝可梦救了我们！$"

SilphCo_3F_Text_GruntIntro::
    .string "不要给我们添乱了，小孩！$"

SilphCo_3F_Text_GruntDefeat::
    .string "我、我输了！$"

SilphCo_3F_Text_GruntPostBattle::
    .string "一个提示？你可以用一个钥匙卡\n"
    .string "来打开门！$"

SilphCo_3F_Text_JoseIntro::
    .string "比起火箭队我\n"
    .string "更支持西尔佛公司！$"

SilphCo_3F_Text_JoseDefeat::
    .string "有两下子啊！$"

SilphCo_3F_Text_JosePostBattle::
    .string "哼……\p"
    .string "火箭队说，如果我帮助\n"
    .string "他们，他们就会让我研究宝可梦。$"

SilphCo_3F_Text_FloorSign::
    .string "西尔佛公司总部\n"
    .string "3F$"

