PalletTown_Text_OakDontGoOut::
    .string "大木：嘿，等等！\n"
    .string "别急着出去！$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "大木：太危险了！\n"
    .string "有野生的宝可梦生活在草丛里！\p"
    .string "你需要拥有自己的宝可梦\n"
    .string "来保护你自己。\p"
    .string "我知道了！\n"
    .string "这边走，跟我来一下吧！$"

PalletTown_Text_RaisingMonsToo::
    .string "我也在培育宝可梦。\p"
    .string "等当它们变得强大了，\n"
    .string "它们就能保护我了。$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "我本来应该说，\n"
    .string "科学力量真厉害！\p"
    .string "但是，\n"
    .string "有人修改了我的台词！\p"
    .string "这是基于Switch移植版\n"
.ifdef FIRERED
    .string "制作的《宝可梦 火红》汉化版。$"
.else
.ifdef LEAFGREEN
    .string "制作的《宝可梦 叶绿》汉化版。$"
.endif
.endif
    @ .string "通过电脑你可以像管理数据一样\n"
    @ .string "存取物品和宝可梦。$"

PalletTown_Text_OakPokemonResearchLab::
    .string "这里是大木博士的\n"
    .string "宝可梦研究所。$"

PalletTown_Text_PlayersHouse::
    .string "{PLAYER}的家$"

PalletTown_Text_RivalsHouse::
    .string "{B_OPPONENT_MON1_NAME}的家$"

PalletTown_Text_TownSign::
    .string "真新镇\n"
    .string "在此揭开你的旅程！$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "大木：啊，{PLAYER}！\n"
    .string "你回来啦？\p"
    .string "宝可梦图鉴完成得怎么样了？\p"
    .string "能让我看看吗？\p"
    .string "那我瞧瞧……$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "你已经抓到了{B_COPY_VAR_2}种……\p"
    .string "嗯，看得出来，\n"
    .string "你的确付出了你的努力。\p"
    .string "等你完成得多一些的时候，\n"
    .string "再拿来给我看看吧。$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "你抓到了……{B_COPY_VAR_2}种！？\n"
    .string "真是难以置信！\p"
    .string "我有个请求，{PLAYER}。\p"
    .string "跟我来。$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "大木：啊，{PLAYER}！\n"
    .string "你好像很喜欢旅行啊。\p"
    .string "{PLAYER}，\n"
    .string "我猜想你一定会到\l"
    .string "更奇异地地方去冒险。\p"
    .string "好极了，好极了。\n"
    .string "呵呵呵。$"

