ThreeIsland_BerryForest_Text_HelpScaryPokemon::
    .string "小迷：呜……呜呜……\n"
    .string "哦！请救救我！\p"
    .string "就在刚才，\n"
    .string "一只可怕的宝可梦出现了。\p"
    .string "它一直吓唬人。\n"
    .string "小迷被它吓坏了了。\p"
    .string "小迷害怕得动不了了！\n"
    .string "但是我想回家……$"

ThreeIsland_BerryForest_Text_HereItComesAgain::
    .string "哦！它又来了！\n"
    .string "不！走开！太吓人了！\p"
    .string "哇！\n"
    .string "我要爸爸！$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
    .string "哦！刚才真是太吓人了！\n"
    .string "谢谢！\p"
    .string "小迷捡了一些\n"
    .string "树果。\p"
    .string "这些送给你！$"

ThreeIsland_BerryForest_Text_LetsGoHome::
    .string "你叫什么名字？\p"
    .string "小迷很害怕，所以能让你\n"
    .string "送我回我爸爸的屋里吗？\p"
    .string "好！\n"
    .string "我们一起回家吧！$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
    .string "你的树果袋满了。\n"
    .string "看来你不想要这个了吧。$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
    .string "欢迎来到树果森林\p"
    .string "请友好地和其他人与\n"
    .string "宝可梦分享树果。$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
    .string "当心野生的，喜爱树果\n"
    .string "的宝可梦！$"

