FourIsland_Text_IslandSign::
    .string "四之岛\n"
    .string "温暖的蓝色浮冰之岛$"

FourIsland_Text_LoreleiHasReturned::
    .string "科拿回来了。\p"
    .string "莫非是因为\n"
    .string "都市生活的压力太大了吗？$"

FourIsland_Text_LoreleiMetLaprasAsChild::
    .string "科拿已经回来了。\p"
    .string "我猜她的拉普拉斯就是那只\n"
    .string "她在很小时候就遇到的宝可梦。\p"
    .string "我想她是在冻瀑洞窟\n"
    .string "收服到拉普拉斯的。\p"
    .string "可能从那时起那只宝可梦\n"
    .string "就一直陪伴着她。$"

FourIsland_Text_RivalAlreadyGotEggBeSmellingYa::
    .string "{B_OPPONENT_MON1_NAME}：嗨！\n"
    .string "{PLAYER}！\p"
    .string "你到七岛上来干什么？\p"
    .string "你不该老学我，\n"
    .string "知道吗？\p"
    .string "反正我已经拿到宝可梦的蛋了，\n"
    .string "在这岛上已经没什么事可做了。\p"
    .string "嘿，我打赌你都不知道\n"
    .string "什么是宝可梦的蛋。\p"
    .string "那你就永远别想\n"
    .string "完成全国宝可梦图鉴了。\p"
    .string "对了，我在这岛上遇到了\n"
    .string "一个我们都认识的人。\p"
    .string "如果你好奇的话，\n"
    .string "可以到处找找哦！\p"
    .string "我呢，没时间浪费在这里了。\p"
    .string "先闪啦！$"

FourIsland_Text_LoreleiHasLotsOfStuffedDolls::
    .string "啊，你发现我了！\n"
    .string "请别告诉科拿。\p"
    .string "你知道科拿有许多许多\n"
    .string "的毛绒娃娃吗？\p"
    .string "每次她回四之岛，\n"
    .string "她的收藏都会增加！$"

FourIsland_Text_MadeSlushieUsingIcefallCaveIce::
    .string "哇，好冰！\p"
    .string "我用冻瀑洞窟里采集到的冰\n"
    .string "又做了一杯冰沙。\p"
    .string "冰爽又美味哦！$"

FourIsland_Text_LoreleisHouse::
    .string "科拿的家$"

